### ISSUE TITLE
Resume cron job for fixity check (all environments)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1012]
Re-enables the job - see #858

Job notes
- [ ] all files attached to a set have their sha1 values checked through the service
- [ ] the service only checks fixity for files that have not received a check in the last 90 days
- [ ] the interval at which we will run this task will be *quarterly*
- [ ] the start date will be the 3rd of the month (UTC time)

**Comment by SolomonHD** [comment]
I would prefer that this cron job we handled by the deploy user and the whenever gem that was used for a similar ticket.

**Comment by libdgg** [comment]
@rotated8 and @eporter23 It looks like no one has responded to Solomon's comment yet and having software engineering take this ticket. Can you all review and respond?

**Comment by eporter23** [comment]
@libdgg I'm adding this to the Scrum meeting agenda tomorrow. We talked about this ticket briefly in sprint planning earlier, but there seem to be open questions around this ticket.

**Comment by eporter23** [comment]
Hi @devanshu-m , it may be good to discuss in standup tomorrow as well as compare notes with what Solomon has learned. I can also split this ticket into investigating the gem separately from reactivating the job.

**Comment by lovinscari** [comment]
Could turn this on in the test environment to run monthly to see when it finishes. Need to confirm what it is checking as part of the test (Devanshu reviewing code). This is only checking the first S3 bucket. Need to review the logic in the text about the 90-day timeframe.

**Comment by eporter23** [comment]
To confirm - are all files being checked?
To confirm - the 90 day timeframe

**Comment by eporter23** [comment]
After discussing with @devanshu-m in slack, we think it will be more efficient to wait until the source collection work and testing is complete before re-enabling this job in test. We will also have to coordinate carefully how to move it into production. I'm removing this from the sprint 41 milestone for now.

**Comment by eporter23** [comment]
@devanshu-m I spoke with @kmichaelis yesterday and we discussed pros and cons of how often to run this task and we feel that it would be best to run it every 3 months (quarterly). If possible, can we start it tomorrow 10/2?

**Comment by devanshu-m** [comment]
@eporter23 I can set it up to run every three months. I am getting ready with a PR now, however, it might be difficult to get this deployed to prod by tomorrow, because of the other tickets that might be in the release that will require testing. I can set it up for the 3rd or 4th with the hope we are able to deploy to prod tomorrow by end of day.

**Comment by eporter23** [comment]
That makes sense @devanshu-m.

**Comment by lovinscari** [comment]
Emily, Devanshu, Collin trying to meet this afternoon to discuss errors generated over the weekend. Agreement to stop the job with running.

**Comment by eporter23** [comment]
Closing - we will look into the actual fixity check errors in #1527. Thanks @devanshu-m
