### ISSUE TITLE
Create production db backups - Fedora, application databases

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1020]
While we are confirming our long term solution for MySQL backups, please go ahead and make a backup of our production databases using available tools.

We won't need to try a restoration, but want to make sure we have some type of backup of production now that we have loaded a significant amount of data.

**Comment by SolomonHD** [comment]
Mysql (via mydumper) backups of curates and fedora have been completed.
S3 backup of prod to another bucket (42,000 objects)
Solr backups of all curates and luxes
EFS Backup of all mounts
