### ISSUE TITLE
Populate Notifications section of Preservation Status info block

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1027]
See [wireframe sections 6-8](https://docs.google.com/drawings/d/13zcaIugKDGV0G_y6lHsnXu9ztiu_HmtBptz71go_08w/edit)

Note: we don't anticipate many errors on work-level Events.

If there is a failure, record the information shown in the mockup.

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-01 at 2.43.56 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f4c6918f-c163-43f3-ab0f-ec1cb71ff81a)

PR made: https://github.com/emory-libraries/dlp-curate/pull/1205
