### ISSUE TITLE
Routing a new page to contain Event Details for works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1028]
We need to establish a new page type to show Event Details for works. See mockups in epic #746 and #747.

- [x] Has a new route
- [x] Route unique to each work
- [x] Route resolves

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-26 at 2.25.29 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ae62f18c-1ffe-4310-9d03-5f6a0ffcdb74)![Screen Shot 2020-06-26 at 2.24.19 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/51b87cc0-4f9e-464c-890a-91122c917886)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1297
