### ISSUE TITLE
Adjusts File Details and Characterization display layout

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1034]
See [sections 4 and 5 on wireframe](https://docs.google.com/drawings/d/1A--1khkQlaDndQVu22cOKQjZTWRyC-tfFBbzaqlrM7k/edit)

- [x] Remove two-column/floated output of technical data values
- [x] Add/change the heading for this section to "Preservation Master File Details"
- [ ] Confirm placement/sequence in page display after Files section is moved (#1032)

**Comment by bwatson78** [comment]
![83556762-17f35100-a4d6-11ea-903b-9411149aaf21.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ca53b111-102d-4ad7-9b0b-cd492f456149)

PR made: https://github.com/emory-libraries/dlp-curate/pull/1210
