### ISSUE TITLE
Generate new Preservation Events listing on View FileSet page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1037]
See mockup - [section 7](https://docs.google.com/drawings/d/1A--1khkQlaDndQVu22cOKQjZTWRyC-tfFBbzaqlrM7k/edit)

- [ ] Create new section and heading to the page output
- [ ] Loop and pull data from Fedora; populate table

To do: revise mockup with alternate layouts as needed to get table contents to fit

Discussion: pull all of this from Fedora for now; if performance is a problem, look into indexing it

**Comment by devanshu-m** [comment]
@bwatson78 moved it by mistake

**Comment by bwatson78** [comment]
@eporter23 Unfortunately, I cannot successfully save files on my local environment, so I cannot generate a screenshot of this working. Rspec tests are passing though, so I expect it to work in test/arch.

**Comment by bwatson78** [comment]
@eporter23 A reindex is needed for all filesets after this is deployed.

**Comment by eporter23** [comment]
@bwatson78 I created a couple of new FileSets in arch and test so I could test your work before the reindex. Looks great! Can you please ensure that the table rows break properly so that there is one event per row?

[arch object](https://curate-arch.library.emory.edu/concern/parent/6214mw6mc9-cor/file_sets/003cz8w9j9-cor)
[test object](https://curate-test.library.emory.edu/concern/parent/4300zpc8g1-cor/file_sets/262s4mw6x0-cor)

![Screen Shot 2020-06-05 at 12.35.32 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/63b27811-bcfa-4d64-beb1-7f2fae8f970e)

**Comment by bwatson78** [comment]
@eporter23 Oops, will fix that today.

**Comment by bwatson78** [comment]
PR made for fix: https://github.com/emory-libraries/dlp-curate/pull/1237

![Screen Shot 2020-06-05 at 1.12.11 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b40f153b-d739-4611-b089-87d665e3e8ea)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-05 at 1.12.21 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/aa41aca8-9f65-4dd5-83d9-50319c4b8c69)

**Comment by eporter23** [comment]
@bwatson78 now that the reindex is done I'm doing more in-depth testing. I am seeing that there should be more events per FileSet which aren't all showing up; as I get more info with specific details I'll write up a separate revision ticket.

**Comment by eporter23** [comment]
Closing but noting revision ticket 1246 - we also need to reindex production FileSets to have events display in production, but we will do this at a later time.
