### ISSUE TITLE
Protect the Delete method on Works, Collections controllers

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1039]
- [x] Ensure that a signed in user with Admin credentials is submitting the request

**Comment by eporter23** [comment]
@wulman16 I'm not sure if/how to test this - is there a URL pattern for the method?

**Comment by wulman16** [comment]
@eporter23 When I delete a work in my browser, the logs give me the following:
```
timestamp='2020-06-01 13:14:09 -0400' level=INFO message='Started DELETE "/concern/curate_generic_works/948sbcc2gc-cor?locale=en" for ::1 at 2020-06-01 13:14:09 -0400'
timestamp='2020-06-01 13:14:09 -0400' level=INFO message='Processing by Hyrax::CurateGenericWorksController#destroy as HTML'
timestamp='2020-06-01 13:14:09 -0400' level=INFO message='  Parameters: {"authenticity_token"=>"Ol12PaRho/+BkHWqAsGcHYnlDSCx5eBtKEEOcz3v3NAIOXoxUNuka73szSyX093YJhThaDzXLEZhTQ4RzIjjlQ==", "locale"=>"en", "id"=>"948sbcc2gc-cor"}'
```
I assume the URL pattern would be `/concern/curate_generic_works/948sbcc2gc-cor?locale=en` for works, though I haven't been able to get the right response in my browser console.

**Comment by eporter23** [comment]
Discussed in standup briefly: the technical expertise required for our non-Admin users to execute this in order to test is more complex than is probably worth the effort, so we will close this and reopen if there are issues later.
