### ISSUE TITLE
Cantaloupe Configuration Change

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-curate#1051]
In order to limit file sizes for Low Resolution images in Lux ("Public low view" and "Emory low view"), we should configure Cantaloupe not to deliver images larger than those in the info.json.

```
cantaloupe.properties
. . . 
# If true, requests for sizes other than those contained in an information
# response will be denied.
endpoint.iiif.2.restrict_to_sizes = true
```

example info.json to see for context on sizes:
https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/d4d69aabc76fedf018ab4b9d2717a1171e0c7d20/info.json

**Comment by bess** [comment]
We tried this and it didn't appear to make a difference. We're working on a different solution.
