### ISSUE TITLE
Configure ability to supply an abbreviated Collection Title for Lux

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1055]
Relates to Lux ticket https://app.zenhub.com/workspaces/dlp-lux-5c75900b135e053ed882c4d0/issues/emory-libraries/dlp-lux/378

Lux breadcrumbs navigation includes a link to the Collection title. These titles can be very long, however, and may exceed the available space. 

To confirm: should we provide an Alternate Title metadata field for Collections which Collection Managers can use to supply their own shorter version of a title?

**Comment by tmiles2** [comment]
Note: Curate team suggests truncating display + hover text
