### ISSUE TITLE
Add Cantaloupe responses to Cloudwatch 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1059]
Follows on prior work (#970) to see what we can identify from Cantaloupe/ImageMagick responses; can we get these into our CloudWatch logs for easier review?

The least-work option that logs the incoming url of the request, and the total time to complete that request would close this ticket. Something in Cloudwatch would be preferred, as the team already has access to it, and it is where we are currently putting logs.

**Comment by SolomonHD** [comment]
Currently in cloudwatch we are capturing the following logs:

wrapper.log
access.log
error.log
cantaloupe.log

@rotated8 Is there another log this ticket needs?

**Comment by tmiles2** [comment]
Pending the results from Collin/Doug's conversation

**Comment by mightycollins** [comment]
After having several conversations and looking at what is provided in the logs, we cannot identify the information needed for this story.  Initial attempts to enhance and modify what is captured in the logs has not proven to provide the necessary information.  Mark and Solomon will reach out to the community (Samvera, IIIF, etc) to see what options are available.

**Comment by tmiles2** [comment]
Mark P/Solomon/Steve C/Collin met on 3/24 after further discussion they identified the following next steps for investigating Cantaloupe performance 

• Join and post questions to the IIIF Slack channel – Mark
• Join and post questions about IIIF/Cantaloupe to Samvera Slack channel – Mark
• Attempt to query Code For Lib person John Rothline for possible solutions – Collin
• Add Java performance tools, investigate session tracking, and other Tomcat tools to capture needed information – Mark
