### ISSUE TITLE
Authentication for AWX

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1060]
Use Shibboleth to authenticate to AWX. This will require a new request for Shibboleth attributes filed.

The attributes we will need are:
- NetID
- First Name
- Last Name
- IsMemberOf

Additionally we will a new LDAP group created for dlp's developers, that will govern who will have access to awx. There's already a Web management group that will be given admin access. LDAP groups require a list administrator who can add or remove other people.
 
- [x] Submit new shibboleth Attribute request
- [x] Submit request for new LDAP group
  1. LDAP group should be called DLP_DEVELOPERS
  2. Admins of the list should be Solomon, Collin and Emily

**Comment by tmiles2** [comment]
I've submitted the request form for Shibboleth (servicenow INC03343039)

**Comment by SolomonHD** [comment]
The LDAP group has been created, it's called RGR_DLP_DEVELOPERS

**Comment by tmiles2** [comment]
Shibboleth form is pending attributes being approved by Anne Marie.
