### ISSUE TITLE
Adapt Ansible Roles to AWX

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1061]
Preliminary testing with AWX has shown that certain roles will need to be modified to work in AWX rather than Ansible core. My intention is to retain Ansible Core functionality, so the scripts will need to work on both.

- [x] Identify which roles and plays do not work in AWX
- [ ] Adjust roles for AWX
- [ ] Test out roles in AWX
- [ ] Setup templates for AWX

**Comment by SolomonHD** [comment]
I'm closing this ticket because I think there's a larger discussion about using ansible to provision vs using an actual provisioning tool like Terraform, CloudFormation. All of the non provisioning ansible roles work in AWX and don't need any adaptions.
