### ISSUE TITLE
Generate and cache IIIF manifests for production

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1076]
- [ ] Update rake task with new manifest generation
- [ ]  Move processing in a job
- [ ]  Write/update tests

Please also see ticket #1127 in which we may need to refine how files provided for users to download should not attempt to render in the UV

**Comment by devanshu-m** [comment]
- [ ] Update rake task with new manifest generation
- [ ] Move processing in a job
- [ ] Write/update tests
