### ISSUE TITLE
Load preservation workflow metadata for Kobe

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1082]
- [ ] Add `preservation_workflows.csv` to `config/preservation_workflow_metadata/preservation_workflows.csv` on the server
- [ ] Run rake task: RAILS_ENV=production bundle exec rails curate:works:import_preservation_workflows

CSV file: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/asian-artifacts/Kobe-processed-pwfmd.csv

**Comment by bwatson78** [comment]
@eporter23 CSV has been loaded.

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-20 at 8.24.21 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/98447a0f-054c-45d2-bcf4-24f30887378a)

**Comment by bwatson78** [comment]
![Screen Shot 2020-05-20 at 8.24.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/45146f2f-2d32-4253-9575-f179f7d288c6)

**Comment by eporter23** [comment]
@bwatson78 I spot checked the collection and can see the metadata, thanks!
