### ISSUE TITLE
AWX: Create users and roles

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#1085]
Create roles based on isMemberOf attribute. Main roles will be admin and user.

**Comment by SolomonHD** [comment]
After some further experimenting with this; I believe I will need an additional attributes from shibboleth.

I need the email attribute and also serial number. @tmiles2 Can you update the forms and resubmit them to Identity Management?

**Comment by SolomonHD** [comment]
Update: I've created the login users and roles on AWX. I would still like the additional attributes I mentioned in the previous post. All of the developers should be able to login to awx.library.emory.edu, hit the S button to get to shibboleth

**Comment by tmiles2** [comment]
Pending testing SE logging with Shibboleth

**Comment by SolomonHD** [comment]
To Test: 
Go to awx.library.emory.edu and login through the saml (S button at bottom)
