### ISSUE TITLE
Grant Isilon access for lsdi lsdi2 and dmfiles

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1087]
Please add eporter and Kathryn Michaelis to the Isilon shares that we've been transferring files from to get them to AWS, so that we can go in and spot check file naming problems before transferring to AWS.

Based on my notes, I think these are the locations needed:

nfs://nasn2ac-nfs.cc.emory.edu:/ifs/emoryndb2/n2nfs/library/repl/lsdi

nfs://nasn2ac-nfs.cc.emory.edu:/ifs/emoryndb2/n2nfs/library/repl/lsdi2

I'm not sure the full path to the DAMS files, but I know the directory name is dmfiles

**Comment by mprefer** [comment]
user 'eporter' already existed. Added 'kmicha3'.

Use NetID password as password for logging in.

Paths:
/opt/lsdi
/opt/lsdi2
/opt/dmfiles
