### ISSUE TITLE
Replicate Universal Viewer configuration from Lux within Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1088]
In order to preview access control behaviors, it would be helpful to have the same Universal Viewer configurations available in Curate that are used in Lux. Curate currently uses a basic/default UV configuration. 

For Curate, we should enable:

- [x] Contents (Thumbnail) sidebar at left
- [x] Pagination/navigation at top
- [x] Gallery button at top right
- [x] Settings options at top right
- [x] More information pane at right
- [x] Download and share buttons at bottom left (depending on access control setting)
- [x] Full screen option at lower left (depending on access controls)
- [x] Zoom/pan buttons when hovering over image

To confirm:
- [x] Access controls behavior including delivery of low-resolution when applicable (e.g. Emory Low Download)
- [x] Access controls behavior including disabling download buttons when applicable (e.g. Public Low View)

**Example of Lux UV - Fully Public Item**
![Screen Shot 2020-06-22 at 12.46.28 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a3448c34-9fc0-44c4-a1c7-ff0082006bb6)

**Example of same item in current Curate UV**
![Screen Shot 2020-06-22 at 12.47.29 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/cf5cdd09-1b66-4a22-83df-07712565702a)

**Comment by tmiles2** [comment]
@bwatson78 we are removing this ticket from the sprint, further discussion is needed

**Comment by bwatson78** [comment]
Each image is displaying its visibility. PR made: https://github.com/emory-libraries/dlp-curate/pull/1339

![Screen Shot 2020-07-15 at 1.26.28 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/36b08f7a-ca32-467f-a287-940eba4b99cc)

![Screen Shot 2020-07-15 at 1.26.51 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2b5eb727-fb92-456a-a4de-694e34fa91cd)

![Screen Shot 2020-07-15 at 1.38.05 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/7233fb72-770c-45ad-b46b-d5f0fc7a4084)

**Comment by eporter23** [comment]
Looks great @bwatson78! This should be good for prod.
