### ISSUE TITLE
Add Java performance tools for Cantaloupe 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#1110]
- [x] Investigate session tracking
- [x] Look into other Tomcat tools 
- [x] Add Ansible scripts (Solomon) 
- [ ] Write the steps involved and place in the existing role 

Data points:

**Comment by tmiles2** [comment]
Please estimate this ticket @mprefer

**Comment by mprefer** [comment]
Added admin user to tomcat-users.xml file.
Added psi-probe Java monitoring tool to the Cantaloupe Tomcat server. Placing the 'probe.war' file into the Tomcat webapps directory allows Tomcat to unarchive the WAR file and register the application.

Ansible script to perform above in progress.

**Comment by tmiles2** [comment]
@mprefer Can I get an update on this?

**Comment by mprefer** [comment]
[https://app.zenhub.com/files/158455630/236acc84-a067-4163-87f0-f2cf5d24ade5/download](https://app.zenhub.com/files/158455630/236acc84-a067-4163-87f0-f2cf5d24ade5/download)

**Comment by mprefer** [comment]
Ansible scripts to install 'psi-probe' available in tar.gz file, link in last comment.

Or from Box:
ttps://emory.box.com/s/iyek220mv6peyktcoe8luyl90ob07p9w
