### ISSUE TITLE
Spike: Query and search IIIF community for advice on performance

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#1118]
- [x] Join and post questions to the IIIF Slack channel

**Comment by tmiles2** [comment]
- [ ]  How are others gathering metrics for Cantaloupe performance?

**Comment by mprefer** [comment]
Actual text of Slack query:
For those using Cantaloupe as their IIIF server, how are others gathering metrics for Cantaloupe performance?

**Comment by mprefer** [comment]
Received this message in the IIIF Slack:

"We ran Locust tests against it and looked at load metrics in graph form in CloudWatch."

Will look at Locust soon.
