### ISSUE TITLE
Implement production logging solution

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#112]
Scrum team has decided on using CloudWatch for monitoring purposes.

Create ansible role that manages cloudwatch on ec2s

**Comment by eporter23** [comment]
Relates to ticket 49 - depending on budget decision.

**Comment by SolomonHD** [comment]
I found a really detailed ansible role at https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent
I'm going to experiment with using this.

**Comment by rotated8** [comment]
@SolomonHD I'd like to add sidekiq to this as well. Otherwise, looks good!

**Comment by SolomonHD** [comment]
The logs are in CloudWatch:

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/b78d4341-795f-4551-9fc8-25a22c0d017a)

**Comment by SolomonHD** [comment]
@rotated8 @alexBLR @bess @devanshu-m 

I've updated the wiki with an entry about view logs with CloudWatch.

https://wiki.service.emory.edu/display/DLPP/DLP+CloudWatch+Logging
