### ISSUE TITLE
Environment variable for the base URL for Persistent URL display

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1124]
Relates to ticket #983

We need a new env variable set to the base url for lux servers. Env variable: ENV['LUX_BASE_URL']

Example: ENV['LUX_BASE_URL'] = "digital-test.library.emory.edu" for lux test and so on for arch and prod.

**Comment by mprefer** [comment]
With Solomon's assistance, added the LUX_BASE_URL ENV variable to Ansible so deploys will include it in the .env files.

**Comment by mprefer** [comment]
Added LUX_BASE_URL=digital-test.library.emory.edu to <DLP_BASE>/shared/.env.production on 'curate-test.library.emory.edu' and reloaded Apache to reload the .env file

**Comment by mprefer** [comment]
Changed he URL by adding "https://", so the setting is now:
LUX_BASE_URL=https://digital-test.library.emory.edu
And an Apache reload.

**Comment by mprefer** [comment]
Added the variable to arch and prod and performed a restart of Apache.
