### ISSUE TITLE
AWX: Request additional attributes from Identity Managment

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#1129]
AWX needs some additional attributes from shibboleth. The attributes are serialNumber and email.

- [x] Modify and resubmit AWX identity management request.

**Comment by tmiles2** [comment]
Request has been sent through servicenow: INC03360077

**Comment by tmiles2** [comment]
Response from Anne Marie, @SolomonHD please provide an answer: 
Security has asked us to add Duo 2-factor for all Shibboleth implementations retroactive to 3/1/2020.
Would it be OK with you if we add Duo?

**Comment by tmiles2** [comment]
This ticket is blocked until the attributes are approved. As of today no updates have been provided by Identity Mgt team.

**Comment by tmiles2** [comment]
Attributes approved and an email has been sent to Solomon.
