### ISSUE TITLE
Add new users to Curate 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1130]
The following people need accounts for Curate and should be added to the groups/roles noted below:

**Rose Viewer, Oxford Viewer, Health Sciences Viewer**
- [x] Jody Bailey - jebail5
- [x] Melanie Kowalski - mtkowal

**Administrator**
- [x] Lisa Hamlett - lhamlet
- [x] Clare Barton - cbarto8
- [x] Ann Hulton - libah
- [x] Rosalyn Metz

**Comment by tmiles2** [comment]
@devanshu-m I have added the netids for the users.

**Comment by devanshu-m** [comment]
PR ready for review and merge: https://github.com/emory-libraries/cor-cm/pull/11

**Comment by devanshu-m** [comment]
PR ready for review and merge: https://github.com/emory-libraries/cor-cm/pull/12

**Comment by SolomonHD** [comment]
Merged the PR and added the users to the curate's manually. Please have them test.
