### ISSUE TITLE
Restore rendering option selections (PDF, OCR, and other files) in our new manifest construction method 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1132]
We previously enabled the rendering options section of the Hyrax form so that users can supply additional files for downloads in the UV. #936

We have some cached manifests that included PDF, OCR files as part of the download options shown to users. Now that our manifest generation process has changed, we need to make sure this still functions before we regenerate all the manifests for beta.

Example of desired behavior - [There is no death](https://digital-test.library.emory.edu/catalog/515bcc2fs2-cor)

This ticket also relates to #1127

**Comment by devanshu-m** [comment]
Before:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/6a768bc0-6976-46bc-976c-8631b717ba55)

After:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/0f827d2f-f382-4ca9-84f7-1c93eb90a940)

**Comment by eporter23** [comment]
@devanshu-m @alexBLR tested on two books in production - looks good!
