### ISSUE TITLE
Disable SOLRSuggest for better indexing and ingest performance 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1138]
See PR #1137

* SolrSuggest may be responsible for slowdown in ingest pace. Disabling SolrSuggest might help to decrease time taken to create and add a work to a collection. Refer:
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_0
and
https://docs.google.com/presentation/d/1Jj0aC8LhfbcWxe0g8bBhTj1wxKMbkU6v11iJRBKNV3E/edit?copiedFromTrash#slide=id.g44d37b2273_2_7
and
https://github.com/samvera/active_fedora/pull/1311/files

**Comment by tmiles2** [comment]
@devanshu-m Can you update this ticket, with any details?

**Comment by devanshu-m** [comment]
New solrconfig is up on curate-arch. @SolomonHD  suggested we test it a little bit before making changes to other environments.

**Comment by devanshu-m** [comment]
We are unable to test this on curate-arch due to an unrelated error:
`Ldp::HttpError: STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool at org.modes...`

**Comment by eporter23** [comment]
We tested this change in test and production, but it has not affected our ingest speed. As next steps we will try 

- [ ] importing Langmuir objects in a brand new collection
- [ ] investigate Fedora specifically while running an import
