### ISSUE TITLE
Create Rake task to reindex specific IDs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1139]
Done when we have:
- [x] a new rake task that
- [x] reads a list of IDs from a file, and
- [x] enqueues a background job for each ID that
- [x] reindexes that ID.

Currently, the Resolrize job will attempt to reindex every Collection, Work, and FileSet in the repository. We need a way to only reindex certain objects from a list of IDs.

How that list of IDs is generated is outside the scope of this ticket.

**Comment by devanshu-m** [comment]
This is running on prod right now
