### ISSUE TITLE
Add Java performance tools to Fedora

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1141]
- [ ] Tools should be installed and setup the same as for the IIIF server

**Comment by mprefer** [comment]
All three Fedora instances have been configured and 'probe.war' deployed. Each Fedora has been restarted.
URL:
http://fedora-cor.library.emory.edu/probe
http://fedora-cor-test.library.emory.edu/probe
http://fedora-cor-arch.library.emory.edu/probe

On all:
User: admin
PWD: shutup

**Comment by tmiles2** [comment]
Need to complete the work for SOLR
