### ISSUE TITLE
href attribute for Persistent URL display contains http://https://

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1144]
Relates to work in #983:

The links do not function properly on the Curate view pages because the href attribute has an extra prefix:

`<a href="http://https://digital-test.library.emory.edu/purl/153jwstqk1-cor" target="_blank">https://digital-test.library.emory.edu/purl/153jwstqk1-cor</a>`

Please revise to output 

`<a href="https://digital-test.library.emory.edu/purl/153jwstqk1-cor" target="_blank">https://digital-test.library.emory.edu/purl/153jwstqk1-cor</a>`

**Comment by eporter23** [comment]
@devanshu-m this is now fixed for works, but I'm still encountering the issue with the href value being incorrect on Collection pages.

**Comment by devanshu-m** [comment]
@eporter23 Aah, looks like I missed the collections show page. I will put in a new PR for this.

**Comment by eporter23** [comment]
Tested in production.
