### ISSUE TITLE
Investigate private internal DNS instead of /etc/hosts for SOLR

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1160]
Outcome of postmortem 4/17/20.

[Additional notes here.](https://emory.box.com/s/6uys742tkudd5xlzp7tkdeoyjsyz5e95)

**Comment by SolomonHD** [comment]
Route53 private hosted zone is working in aws@emory. I've created a new hosted zone called .internal.emory.edu
