### ISSUE TITLE
PDF, OCR downloads not found - localhost address

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1165]
Since the manifest regeneration in production over the weekend, book objects' additional download files are not able to be downloaded because they point to a localhost address. These items were functioning last Friday.

To reproduce, select a book from the Yellowbacks collection (e.g. Gerard..., https://digital.library.emory.edu/catalog/4881jwstwx-cor)

Select either the PDF or OCR to download from the UV:

![Screen Shot 2020-04-20 at 5.15.55 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/17bc18b4-6ad9-4349-b659-52957d6a4c35)

The following error results:

![Screen Shot 2020-04-20 at 5.15.17 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/2ddae3c0-6e33-46b1-8ba4-e4a6d0dc8242)

**Comment by eporter23** [comment]
@devanshu-m @alexBLR can you guys take a look at this? Nik and I just found this bug after the manifests were regenerated.

**Comment by devanshu-m** [comment]
Sidekiq picks up env variables from `.env.production`, however, the `HOSTNAME` env variable is missing in that file. `HOSTNAME` right now might be a linux server variable.

**Comment by SolomonHD** [comment]
The HOSTNAME variable has been added to all curate environments

**Comment by nikdragovic** [comment]
Great work, @devanshu-m! This works for me in Lux, PDF and OCR, logged in and not.
