### ISSUE TITLE
Persistent URL href attribute incorrect in curate-arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1170]
Curate-arch is generating nonfunctional links for the persistent URL in the href attribute:

Collection example:
https://curate-arch.library.emory.edu/collections/digital-arch.library.emory.edu/purl/24947d7wm8-cor

Work example:
https://curate-arch.library.emory.edu/concern/curate_generic_works/digital-arch.library.emory.edu/purl/054kkwh724-cor

**Comment by devanshu-m** [comment]
env variable seems to be incorrect:

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/2be75474-931d-42f8-9c91-a4ef238b4987)

**Comment by rotated8** [comment]
The issue is: on an object (like https://curate-arch.library.emory.edu/concern/curate_generic_works/959189321n-cor), the persistent url does includes the curate domain in the url (https://curate-arch.library.emory.edu/concern/curate_generic_works/digital-arch.library.emory.edu/purl/959189321n-cor) when it should only have the lux domain.

**Comment by devanshu-m** [comment]
The env variable is set to `digital-arch.library.emory.edu` it is missing the `https://` in the beginning which is causing this bug. Other envs have it set to with `https://` in its variable.

**Comment by eporter23** [comment]
@devanshu-m should this be a Middleware ticket?

**Comment by devanshu-m** [comment]
I think so. Can we discuss this in standup tomorrow? @eporter23

**Comment by SolomonHD** [comment]
The variable has been changed.
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/a5bc4d7f-e014-4e36-a8d0-d2eef46a8232)

**Comment by eporter23** [comment]
Tested in arch - urls now working.
