### ISSUE TITLE
Investigate how to move works from Deposit Collection to permanent Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1182]
As part of our ongoing investigations to fix the slowdown in ingest rate, we tested a load of Langmuir works into an empty, private Deposit Collection. We also discussed this strategy with DCE.

The works were imported at Private visibility because of their temporary collection affiliation.

As a next step, we need to test how to move these 10 works from the Deposit Collection to Langmuir.

- [ ] Ensure that the move process adds the works to the Langmuir collection and also deletes them from the Deposit collection (so that the works do not show two collection memberships) 
- [ ] Determine most efficient method to move works
- [ ] Document how long this process takes

If successful, we will need to come up with a process for how to address the problem of the desired visibility not being assigned at the time of ingest. This is mainly a problem because of the Policy Assignment preservation event, which will show Private (restricted) for ingest.

Options:
1. Refresh the metadata so that the correct visibility is assigned
2. Add a second preservation event at the work level to indicate the correct visibility assignment after ingest
3. Update the preservation workflow metadata in the CSV so that the original (correct) visibility is indicated as part of the Ingest workflow notes, and will eventually be visible on the View Work page

**Comment by devanshu-m** [comment]
Snippet to run from console (draft 1):

```
c.member_works.each do |w|
  w.member_of_collections.delete(c)
  w.member_of_collections << c1
  w.save!
end
where c is `Deposit Collection` and c1 is `Langmuir`
```

**Comment by devanshu-m** [comment]
Draft 2:

```
import_col.member_works.each do |work|
  work.member_of_collections << true_col unless true_col.member_work_ids.include?(work.id)
  work.member_of_collections.delete(import_col)
  work.save!
end
```

**Comment by devanshu-m** [comment]
Update: Discussed a profiling strategy with Collin which will help us create a call-stack profile along with graphs to monitor how our code runs step by step and the time it takes to run. Working on a writing a job for that now. Using stackprof for profiling: https://github.com/tmm1/stackprof

**Comment by devanshu-m** [comment]
Deployed to prod and started job to transfer works from deposit col to langmuir with profiler. Results for profiler live here: `tmp/stackprof-curate.dump`

**Comment by devanshu-m** [comment]
Update: Stackprof dump file produced is very large and takes a long time to open. We might have to look at a different profiler or maybe try ignoring garbage collection when creating a profile for our code.

**Comment by eporter23** [comment]
Update: the most recent transfer works attempt on 2 works took 3 hours.

**Comment by devanshu-m** [comment]
Report from stackprof dump file:
* More than 180k sample frames were generated. This is what I found out from combing through it:
  * The following methods have a considerable amount of samples collected -- we try to transfer a work to langmuir (calling the `member_of_collections` method on a work and adding langmuir to it):
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/819a4d3e-37a6-4157-8b86-0a0acee2d54b)
  * Updating of indexes and solr also has a lot of samples:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/f86c57c5-be19-4486-a4a3-aca3210213ce)
  * Next is callbacks. These are commands that are run when the work gets saved as well as when both collections are updated:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/fca9beaf-7d0d-431d-950f-b87533224f64)
  * The job itself along with sidekiq:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/8686443a-fa44-42fa-9143-e3d2917fdcf5)
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/dfb6997d-1719-4ab4-9775-0ba426740398)
  * Find methods (finds collections to deposit from and to):
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/e895b27b-8cbb-405e-86d6-9f0ae4090752)
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/936df685-8b48-4827-98c9-a01edd852428)
  * Following method is for finding each work within the deposit collection and then running operations on that work until it reach `end` of the block:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/efed58c6-7dff-4ed8-b169-a8bed87e7236)
  * Collecting child works present in a collection:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/aa471d83-3caf-4321-ba14-2b51e5aba058)
 
* The methods that we would be interested in are in the `ActiveFedora::Associations` module. The following are methods we can look into/try to change (I still have to research these in detail in the ActiveFedora gem we are using):
  * `ActiveFedora::Associations::IndirectlyContainsAssociation#insert_record`: This method might be responsible for associating and inserting a work to a collection.
  * `ActiveFedora::Associations::CollectionAssociation#concat_records`: Probably for concatenating/appending a work to collection's child works.
  *  `ActiveFedora::Associations::CollectionAssociation#add_to_target`: This method is called in the `concat_records` method above.
