### ISSUE TITLE
Backup and restoration testing - prod to test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1184]
This ticket follows work in ticket Curate #1007, which contains additional details about steps to implement.

- [x] Copy the production environment totally (application databases, SOLR, Fedora, S3 files)
- [x] Restore the prod backup to the test environment

Confirmation checks
- [x] Users and groups recreated
- [x] Collection Types recreated
- [x] Other/misc application settings recreated (colors)
- [x] Number of Collections 
- [x] Number of Works
- [x] Number of FileSets
- [x] Identifiers persist
- [x] Collection banners and thumbnails
- [x] Count of files in S3 matches
- [x] Environment-specific variables persist
- [x] Preservation Events persist (dates, etc.)
- [ ] User activity data/versioning on FileSets persists
- [x] Lux/Curate SOLR remain in sync

**Comment by eporter23** [comment]
@SolomonHD I was able to confirm most of the stats in the restored test environment except for the S3 file quantity. One thing I also noticed is the digital-test seems to be a little out of sync with digital (prod) in terms of facet counts, etc. I'll check on it again tomorrow in case this is a solr sync timing issue.

**Comment by eporter23** [comment]
The count of S3 files is slightly different but there were active processes running in prod at the time we restored to test, so that may account for it. We should see a 1:1 of works to files in Fedora, however. There were ~300 files more in prod than in test after the clone and restore.

![Screen Shot 2020-06-04 at 11.02.10 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/3806f5a2-8a48-48f5-8cdb-bd573414ff60)

**Comment by eporter23** [comment]
@SolomonHD I reopened this for the documentation step. I added a new page on the wiki if you want to add your steps there: https://wiki.service.emory.edu/display/DLPP/Backup+and+Restoration+Process

**Comment by SolomonHD** [comment]
I'm going to move the documentation to it's own ticket, since that may take me a few additional days

**Comment by eporter23** [comment]
@SolomonHD yes, I'll close this one. FYI, please see #1223 for something I just noticed but we can investigate that outside of this ticket. Thanks!
