### ISSUE TITLE
Re-transfer Yellowback volume files (ocm02175853-1919/ocm02175853)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1185]
The following volume is missing most of its page files in our EFS mount space. I tried to upload the files via scp but received permission denied errors. 

Source location:
libetdappprod1.library.emory.edu:/opt/lsdi/diesel/lts_new/ocm02175853-1919/ocm02175853/Output

Destination:
libetdappprod1.library.emory.edu:/mnt/efs/Collections/lsdi/diesel/lts_new/ocm02175853-1919/ocm02175853/Output

**Comment by mprefer** [comment]
Copied 'lsdi/diesel/lts_new/ocm02175853-1919' to 'Collections/lsdi/diesel/lts_new/ocm02175853-1919'.
Changed ownership of all files to 'root:root'.
Changed mod of files to 644.
Moving to test for Emily's approval

**Comment by eporter23** [comment]
Thanks @mprefer I ran the CSV import pre-check and no file missing errors. I still seem to be unable to upload files into this directory using scp, but I'll check with you later about the best method to do this.
