### ISSUE TITLE
Additional human readable EDTF dates for Lux

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1186]
This ticket replaces dlp-lux 531 and includes two aspects: 1) confirming consistent behavior across the human readable display dates for Lux and 2) configuring/revising additional EDTF date types that may be entered in Curate. See the following test objects for examples: 
[Curate-test](https://curate-test.library.emory.edu/concern/curate_generic_works/3418kprr6m-cor?locale=en)
[Lux-test](https://digital-test.library.emory.edu/catalog/3418kprr6m-cor)
 
1 - All date fields that use human readable display dates in Lux should follow the same display behavior. To confirm: all these all configured for human readable translations already?

- date_created
- date_issued
- data_collection_dates
- conference_dates
- copyright_date

2 - The following EDTF date formats should have human readable dates formatted as noted below.

1. Unspecified decade
```
Curate entry: 20XX
Current Lux display:  200s0s
Desired Lux display: 2000s
```

```
Curate entry: 19XX
Current Lux display: 190s0s
Desired Lux display: 1900s
```

2. Known month with unspecified year
```
Curate entry: XXXX-10
Current Lux display: XXXX-10
Desired Lux display: October (year unknown)
```

3. Date range/duration with two known decades but unspecified exact years
```
Curate entry: 193X/194X
Current Lux display: 193X/194X
Desired Lux display: 1930s to 1940s
```

4. Approximate, complete year
```
Curate entry: 1976~
Current Lux display: 1976~
Desired Lux display: 1976 approx.
```

**Comment by kmichaelis** [comment]
The format of dates input in the style of #3 is slightly different from the example given:
https://digital-test.library.emory.edu/catalog/873pvmcvps-cor

**Comment by wulman16** [comment]
@kmichaelis There was a previous ticket that had those date ranges formatted differently: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-lux/126 @nikdragovic Do you know whether the human-readable version of 193X/194X should be "within the 1930s or 1940s" or "1930s to 1940s"?

**Comment by eporter23** [comment]
@wulman16 looks good, ready for prod! I've been testing on this object: https://digital-test.library.emory.edu/catalog/989r2280r9-cor
