### ISSUE TITLE
Edit display of Rights Status in UV

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-curate#1191]
As an end user, I would like to view a clickable link with human-readable text in the Rights Status field, so that it is easy to ascertain the rights status from the embedded viewer and easy to click for more information about that status.

## Acceptance Criteria
- [x] Instead of static text in the Rights Status Field, add linked text that replicates what displays in the Rights Status field in the Access and Copyright section.
- [x] Clicking the link should open the target in a new tab, as it does for PURL.

![Screen Shot 2020-05-20 at 8.56.49 AM.png](https://images.zenhubusercontent.com/5ba135cf945aef49576d50f2/ccd9d126-555c-4504-b301-559b642ffa36)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1351

**Comment by bwatson78** [comment]
![Screen Shot 2020-07-20 at 12.30.44 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/ab45a68a-8b6b-42cd-868b-84e527d2ad17)

**Comment by bwatson78** [comment]
For my local environment, I had to modify my object before the Manifest Builder service would recreate the metadata since the builder only creates a new one if the date modified differs the manifest file key.

**Comment by bwatson78** [comment]
Since this delivers the same UV to both Lux and Curate, there shouldn't be any alterations necessary for the Lux side.

**Comment by eporter23** [comment]
Looks good! Tested by manually regenerating the manifests on these objects:
https://curate-test.library.emory.edu/concern/curate_generic_works/163stqjqb4-cor?locale=en
https://curate-test.library.emory.edu/concern/curate_generic_works/7440rxwdnt-cor?locale=en

We'll plan to do a large-scale regeneration of manifests in production sometime soon to pick up this change environment-wide.

**Comment by eporter23** [comment]
Update: the manifest regeneration process is still running, but some works are now showing the updated rights status display.
