### ISSUE TITLE
Resolve SOLR Bad Gateway 502 errors

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1192]
After we adjusted our Sidekiq automatic retries behavior and ran an import of Yellowbacks, we observed that the AttachFilesToWork job was periodically failing with a SOLR error.

If the error did not resolve after 1 retry, the job then moved to Dead and no new filesets were being added to the work, which caused the import to run more slowly than prior loads.

**Comment by SolomonHD** [comment]
I created a solr-cor.internal.emory.edu DNS entry that has all 3 solr-cor environments as ARecords. Using this will bypass the ALBs in machine to machine communication. Curate prod's SOLR_URL environment variable has been switched to this new address.

**Comment by eporter23** [comment]
We haven't seen this in error in the last two imports in prod.
