### ISSUE TITLE
Document F5 Settings

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1196]
At Rosalyn's request, we should document as much as we know about recent F5 changes made in consultation with Sheldon in order to assess if these adjustments are successful.

Update, for 6/10 - will do screenshots and post to wiki

**Comment by eporter23** [comment]
From Solomon on slack, 5/22 after working with Sheldon: 

> our setup now exactly mirrors the setup Steve Wheat is using for TKI/Rhedcloud

**Comment by SolomonHD** [comment]
Settings document has been published:

https://wiki.service.emory.edu/display/DLPP/F5+Settings+Documentation
