### ISSUE TITLE
Investigate easier file system access options for pre-ingest files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1198]
For non-developers, accessing files on Isilon and our AWS EFS mount is only currently available via ssh and command line options.

- [x] For routine file management tasks, is there a more GUI/local filesystem friendly way to browse and transfer files (e.g. SFTP or mounted volumes)?
- [x] What is the recommended method and syntax for _uploading_ files/directories to the EFS mount? Product managers encounter permission errors when attempting to use scp in the current method of connection.

Frequent activities include:

- Reviewing entire directories for file naming patterns
- Identifying file sizes for individual files or directories
- Downloading one or more files from a remote directory on Isilon or EFS 
- Uploading one or more files to an EFS directory (adding/replacing files)

**Comment by kmichaelis** [comment]
As we perform more frequent ingests and prepare more collections for upload, Emily and I need to access the files on Isilon and AWS more frequently for various purposes. I currently have to ask either Emily or Kyle to retrieve files or file information for me, which creates a significant bottleneck.

**Comment by eporter23** [comment]
Team has reviewed and cross-trained on how to do uploads to EFS.
