### ISSUE TITLE
Dashboard counts vary in different parts of the Curate UI

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1211]
To investigate - why are the counts of works in the repository different in different views?

[Top level dashboard](https://curate.library.emory.edu/dashboard?locale=en):
Total works in Default Admin Set = **12079**
![Screen Shot 2020-06-02 at 2.46.57 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/34c27a86-ac1b-4b26-9594-56ee29c94feb)

[Dashboard > Collections](https://curate.library.emory.edu/dashboard/collections?locale=en) counts:
Total works in Default Admin Set = **12064**
Total works in Langmuir Collection = **11879**
![Screen Shot 2020-06-02 at 2.47.32 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b3a63813-be4f-47a5-9c21-5bb591ebc5f0)

[Individual Collection View](https://curate.library.emory.edu/dashboard/collections/914nk98sfv-cor?locale=en) count:
Total works in Langmuir Collection = **11889**
![Screen Shot 2020-06-02 at 2.48.48 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a0924859-8b51-4489-b921-23540f0c748a)

**Comment by alexBLR** [comment]
In Admin dashboard Collection the item count is fetched directly from Solr by
CollectionPresentter

The correct count is presented directly from if you click on a specific collection or the AdminSet

Total items are fetched by Solr and it counts ids that are a member of the collection
https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/presenters/hyrax/collection_presenter.rb#L79-L81


"Total viewable items" is the count of the items within the collections table
https://github.com/samvera/hyrax/blob/aff34c3f2953232cc4ffea237a8d5b82bacfc338/app/views/hyrax/dashboard/collections/_list_collections.html.erb#L64

https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/presenters/hyrax/collection_presenter.rb#L83-L85


"Count works" within the collection
https://github.com/samvera/hyrax/blob/130c4e600318a9194725b35dd0fd6e19e5108dd9/app/controllers/concerns/hyrax/collections_controller_behavior.rb#L81

https://github.com/samvera/hyrax/blob/aff34c3f2953232cc4ffea237a8d5b82bacfc338/app/views/hyrax/dashboard/collections/show.html.erb#L82


Based on this investigation the count difference depends on how we pull data with total_viewable_count vs total_items from Solr.

**Comment by eporter23** [comment]
@zo does "total viewable items" have anything to do with visibility?
