### ISSUE TITLE
Curate, Lux -arch out of sync after restoration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1218]
While the copy and restore of test to arch is successful for Curate, the solr index seems out of sync for lux. Does this require a reindex?

Examples:

Curate
https://curate-arch.library.emory.edu/concern/curate_generic_works/856n02v6zr-cor

Lux
https://digital-arch.library.emory.edu/purl/856n02v6zr-cor

**Comment by eporter23** [comment]
@Solomon I already had a this ticket for the Curate/Lux sync in arch if you want to revise this one.

**Comment by Solomon** [comment]
Wrong Solomon...
