### ISSUE TITLE
Allow more retries on AttachFilesToWork, Zizia import jobs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1220]
We changed our Sidekiq behavior (Curate #1183) so that it only allows for one automatic retry per job. 

When a job fails after its second attempt it goes into the Dead queue. 

If this happens with the AttachFilesToWork job, this can cause an import to largely cease operating, as FileSets do not continue to be created for a work. This job also seems to be a trigger for additional jobs. Unless the person running the bulk import is constantly monitoring and manually retrying this failure the ingest will cease to continue for its respective work.

The same impact occurs if the Zizia import job fails, because no new works are created. If this happens overnight while depositors are not monitoring sidekiq, we lose progress on the import.

Recommendation: allow at least 2 retries, or unlimited retries, on AttachFilesToWork job and Zizia:CreateCSVImport jobs

Additional info:
The majority of errors we see during imports that show up in the Dead queue (failing retries) are:

- IngestJob (failing on zero byte files)
- CreateDerivativesJob (failing with MiniMagick error)
- AttachFilesToWork job (failing on minter state lockout; infrequent, but has serious impact on the import's completion time)

**Comment by rotated8** [comment]
Of the three jobs above, we have copied only the AttachFilesToWorkJob into our application. Therefore, instead of copying the other two in (with the maintenance overhead that would add), I have updated the maximum retries for all jobs from 1 to 3. If this does not mitigate the issue, we can still copy the jobs in and try new options.

PR: #1323

**Comment by eporter23** [comment]
Tested this with a book import, ran smoothly with a lot less dead jobs. This should be ready for prod.

**Comment by eporter23** [comment]
@rotated8 @SolomonHD FYI, there have been some 502 and other errors in the import that is still running. These have had multiple retries and failed. I've restarted them, but here is a screenshot of some of them: 

[Uploading... Sidekiq errors 2020-07-23.png ]

**Comment by eporter23** [comment]
Closing, please see bug ticket #1364
