### ISSUE TITLE
Enable creation of deduplication_key in the Curate work form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1221]
If a user creates a work manually using the Create Work form, they cannot assign a deduplication key, because this is not available in the form. If a user then needs to update the object's metadata along with other items in the collection, they cannot use the CSV bulk method, because the work has no deduplication key.

Additionally, users cannot currently populate Preservation Workflow Metadata using Curate work forms. This metadata must be loaded via a CSV process, which also requires the presence of the deduplication_key field.

**Comment by eporter23** [comment]
@devanshu-m this is great! Sorry that I didn't specify this before, but would it be possible to move this field into the Admin metadata section as the very last field on the form?

**Comment by devanshu-m** [comment]
@eporter23 new PR with changes:
https://github.com/emory-libraries/dlp-curate/pull/1316

Output:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/a1339b86-ab86-4e6e-9e97-40a9f343dd83)

**Comment by eporter23** [comment]
Looks great, thank you @devanshu-m!
