### ISSUE TITLE
Access to files in Isilon, EFS Mount

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1226]
SSH access setup in curate #1087 - Kathryn is unable to connect.

![Capture.JPG](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9e3290f1-e16f-4385-a28d-b339b4d23c0b)

**Comment by SolomonHD** [comment]
User had an account on the server but did not have access to the proper VPN core to reach the server. She is now able to connect.
