### ISSUE TITLE
Upgrade Indexers to beta3

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1227]
Moving from beta1 to beta3 requires reviewing [~700 commits](https://github.com/samvera/hyrax/compare/v3.0.0.pre.beta1...v3.0.0.pre.beta3).

- [x] Review all the commits between beta1 and beta3
- [x] Identify any files in`app/indexers` that we have overridden.
- [x] Update affected files to the new Hyrax version OR remove our overwrites.

**Comment by bwatson78** [comment]
@rotated8 All of the indexers are necessary and only using methods that still exist or were created by Software Engineering.
