### ISSUE TITLE
Upgrade Presenters to beta3

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1228]
Moving from beta1 to beta3 requires reviewing [~700 commits](https://github.com/samvera/hyrax/compare/v3.0.0.pre.beta1...v3.0.0.pre.beta3).

- [x] Review all the commits between beta1 and beta3
- [x] Identify any files in`app/presenters` that we have overridden.
- [x] Update affected files to the new Hyrax version OR remove our overwrites.

**Comment by wulman16** [comment]
We have limited overwrites in our presenters directory that don't appear to be affected by the beta3 upgrade. Because there are no necessary changes to our code, I'm closing this ticket.
