### ISSUE TITLE
Document Backup and Restore procedure in DLP Wiki

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#1231]
- [x] Document Backup and Restore procedure in DLP Wiki

[Starter page added to wiki](https://wiki.service.emory.edu/display/DLPP/Backup+and+Restoration+Process)

**Comment by SolomonHD** [comment]
First published draft:

https://wiki.service.emory.edu/display/DLPP/Backup+and+Restore+Strategy

**Comment by eporter23** [comment]
@SolomonHD thanks for these docs! As discussed in standup, if you can add some more detail around the frequency of our ongoing backups (which backups occur when), that would be really helpful.

**Comment by SolomonHD** [comment]
I've added a table with the backup times and frequency.

**Comment by eporter23** [comment]
Thanks @SolomonHD - very helpful info.
