### ISSUE TITLE
Regenerate IIIF manifests in arch, test after restoration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1236]
After the restoration of prod data to the test environment, we realized that the manifest URLs still point to production which is causing some anomalies related to access controlled files.

When we do a restoration of data to a different environment, we will need to regenerate the manifests.

- [x] Regenerate test manifests
- [ ] Regenerate arch manifests

**Comment by eporter23** [comment]
@devanshu-m did you run this already in arch and test?

**Comment by devanshu-m** [comment]
@eporter23 this is running in test now. Last 1000 to go. Haven't run it in arch yet.

**Comment by devanshu-m** [comment]
This has finished in test and is running in arch right now.
