### ISSUE TITLE
Upgrade Views to beta3

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1238]
Moving from beta1 to beta3 requires reviewing [~700 commits](https://github.com/samvera/hyrax/compare/v3.0.0.pre.beta1...v3.0.0.pre.beta3).

- [x] Review all the commits between beta1 and beta3
- [ ] Identify any files in`app/views` that we have overridden.
- [x] Update affected files to the new Hyrax version OR remove our overwrites.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1257
