### ISSUE TITLE
Some Events from Fedora missing from FileSet page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1246]
Update: this ticket has been split into two parts - this one focuses on how to re-associate our existing nested objects in Fedora. The other ticket focuses on how to ensure they are associated correctly moving forward (curate #1262).

After we reindexed FileSets on curate-test, preservation events are displaying on FileSet pages, but not all the events attached in Fedora are showing up. Initial patterns noted for missing events: there should be a File Submission event for each file attached (most FileSets have more than one file). There should also be a Message Digest calculation event for each FileSet.

For FileSets, there should be:

- File Submission event (one for each file attached)
- Message Digest Calculation (one for the FileSet)
- Characterization (one for the fileset)
- Virus check (one for the fileset)
- Fixity check (one for each time this is run; not always populated right now) 

Examples - Langmuir object

Curate record: shows 3 events (missing one File Submission event and one Message Digest event)
https://curate-test.library.emory.edu/concern/parent/409j3tx9d4-cor/file_sets/170msbcc82-cor

Fedora record: 5 events
https://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/17/0m/sb/cc/170msbcc82-cor

Examples - Yellowback object

Curate record - 3 events (missing Message Digest Calculation and 2 File Submission events)
https://curate-test.library.emory.edu/concern/parent/784zgmsbmj-cor/file_sets/784zgmsbmk-cor

Fedora record - 6 events
https://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/78/4z/gm/sb/784zgmsbmk-cor

**Comment by eporter23** [comment]
Discussed via slack with @devanshu-m : the most important goal right now is to ensure we can display all the nested event objects in the Curate UI (vs. moving them around in Fedora).

**Comment by tmiles2** [comment]
@devanshu-m Can you provide details as to why this ticket is blocked?

**Comment by kmichaelis** [comment]
Showing on some (Langmuir, some yearbooks) but not others

**Comment by eporter23** [comment]
Spot checked on recently ingested samples in prod and reindexed samples in test. The missing events now appear as expected. We have a separate ticket for reindexing all filesets which will be needed in all environments.
