### ISSUE TITLE
FileSet attached User Activity data always shows depositor name

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1249]
When a user makes file-related edits to an object such as adding a new fileset, the User Activity shows the action with the original depositor's name even if a different person adds the FileSet.

Example - Kathryn deposited this work via bulk ingest.
I later added a fileset to the work.
The user Activity trail shows Kathryn having added the new fileset.

![Screen Shot 2020-06-09 at 4.26.35 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a8a051c8-5ca7-477b-a888-8c45ff3d4077) 

Note: making metadata edits to a FileSet _does_ show the initiating user (when different from the depositor).

https://curate-test.library.emory.edu/concern/file_sets/948sbcc2s6-cor/

![Screen Shot 2020-09-28 at 11.48.54 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9fc75caf-6db7-42c5-ad38-cb0a51a7bc85)

**Comment by eporter23** [comment]
This appears to have been fixed in another ticket, so this is probably a duplicate.

**Comment by eporter23** [comment]
I thought this had been resolved, but I am seeing it again as of 9/15/20. 
I manually added this PDF fileset to a work, but it shows up as Kathryn having attached it:

https://curate.library.emory.edu/concern/file_sets/0171vhhmtf-cor?locale=en

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1517

@eporter23 The other two events we discussed on Slack (`:after_destroy` and `:after_revert_content`) are only called from a controller and strictly utilize the `current_user` object, so no change is required to them.

**Comment by devanshu-m** [comment]
@eporter23 this ticket method definitions for attaching files to work on the backend. It would be a good idea to test ingests both manually and via the importer.

**Comment by eporter23** [comment]
@bwatson78 @devanshu-m I've done some testing to attach filesets both in the form and through an import. I am seeing the correct username now being assigned in the User Activity area, but I am seeing that when I use the form, all of the filesets I create attach without being characterized. 

I also ran a small book import and 2/5 of the filesets were attached without characterization. 

While this does occasionally happen particularly with large bulk ingest, I'm concerned about the behavior with the form, because that is unusual behavior.

**Comment by bwatson78** [comment]
@eporter23 I'll tinker with this more.

**Comment by bwatson78** [comment]
New PR made to reduce Characterization issues.

**Comment by eporter23** [comment]
@bwatson78 I tested this again with 1.2.1 but still seeing characterization issues:

4/8 filesets created by the importer were missing characterization
2/4 manually added filesets were missing characterization

**Comment by bwatson78** [comment]
@eporter23 If you don't object, I have two things in mind to try, step by step. Mind if we deploy them one by one?

**Comment by bwatson78** [comment]
After separate discussions with @eporter23 and @rotated8, they have agreed that the changes I've tried have a possible cascading effect for future errors. I will be pushing a reversion PR, resetting the files back.

**Comment by eporter23** [comment]
Additional comments: we now know for documentation that the FileSet attach will always show the depositing user in the User Activity trail, but other types of FileSet edits will show the initiating username.
