### ISSUE TITLE
Provide a count of files ingested per Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1252]
As part of migration acceptance criteria, we need a way to count the number of _all individual files_ (not just FileSets) ingested for each Collection. This is not currently available in the Hyrax UI, which provides an overall count of FileSets only, and also does not report FileSet counts at the Collection level.

In SOLR, file-level information is also not indexed. From SOLR, is possible to get a count of files per fileset, and a list of the filesets attached to each work, and a list of the works assigned to each Collection but this data would have to collated. 

Ideas discussed:

1. Create a background job to count all works in a collection, then find its filesets, then count files per fileset

- User supplies a collection ID
- Job outputs a CSV or JSON file that contains:
- Total count of filesets in collection
- Total count of all files in collection

**Comment by eporter23** [comment]
Possible approach: background job to count all works in a collection, then find its filesets, then count files per fileset

**Comment by bwatson78** [comment]
Blocked: awaiting instructions from @devanshu-m on how to deliver the file to an AWS bucket.

**Comment by bwatson78** [comment]
@eporter23 After speaking with Devanshu, who, earlier, discussed with Collin about setting up a connection to AWS for delivery, he let me know that we should put off that delivery system setup until we create the UI pages for the rake tasks. The only interaction that we have currently with aws buckets is the checking of binaries against our sha1 values--nothing pushing to a separate bucket.

So, for the time being, this would be processed the same way that we do preprocessing tickets.

With that in mind, once we get this into test/arch, please send me a ticket to request the resulting json for this process.

**Comment by eporter23** [comment]
@bwatson78 that makes sense, thanks for the update.

**Comment by bwatson78** [comment]
No screenshot to display. Will need to be tested once deployed to a production environment.

**Comment by bwatson78** [comment]
Produced error on test run. Will debug.

**Comment by bwatson78** [comment]
Pr for fix: https://github.com/emory-libraries/dlp-curate/pull/1363

**Comment by eporter23** [comment]
@bwatson78 when you're back in the office, can we coordinate on running this in prod?

**Comment by bwatson78** [comment]
@eporter23 New Job d414229f60675facac8ec2e5 kicked off at 2020-08-11T15:25:50Z

**Comment by bwatson78** [comment]
File delivered to @eporter23 via slack.

**Comment by eporter23** [comment]
Looks good, thanks!
