### ISSUE TITLE
ImageMagick unable to open image error

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1253]
[Honeybadger Example](https://app.honeybadger.io/projects/66999/faults/59689878)

Proposal:
- [ ] Log the time the job starts, and the filename in tmp
- [ ] Use rescue to log when the error occurs and the filename (again)

Use this data to get a better idea of when this error happens

**Comment by eporter23** [comment]
@devanshu-m I ran a single book import in curate-test and there were no dead jobs create derivatives jobs in sidekiq which is good news! This should be good to go for prod.

**Comment by eporter23** [comment]
@devanshu-m I ran a reimport of a single book volume and there were no create derivative job failures noted. I do see some missing thumbnails, however. I can fix these using the regenerate derivatives button, but wanted to note this as an FYI. Here's the work with some of the missing thumbnails on fillets: https://curate.library.emory.edu/concern/curate_generic_works/4881jwsv22-cor?locale=en&page=36
