### ISSUE TITLE
Upgrade Testing

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1260]
- [x] Review work from all the previous upgrade tickets
- [x] Discuss test failures as needed with the group
- [x] Fix application code rather than tests as much as possible, assuming the underlying behavior hasn't changed
- [x] Get tests passing again

**Comment by rotated8** [comment]
Please check that titles work as expected. New behavior came in with the upgrade that allows multiple titles to be added to a work or collection, and the titles after the first one are supposed to become "alt_title"s. Having multiple titles should not affect other parts of the application.

**Comment by eporter23** [comment]
@rotated8 I've tested creating and editing Collections and Works. The forms do not permit adding a second Title, which is what we originally established. Is there any further testing to be done? Everything appears to be as expected.

**Comment by rotated8** [comment]
Sounds like it's working as intended.
