### ISSUE TITLE
Enable remaining generic work fields for CSV importer

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1265]
When we worked with DCE to implement the CSV bulk import tool, they prioritized enabling fields for which we had representative data populated for testing.

As we move into preparing for new collections, there are still 29 fields in our Curate Generic Work model that are not yet supported for bulk import via CSV that need to be mapped for import.

[List of fields not yet implemented](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=282953260)

To confirm: if some fields require a URI input in the CSV (this is the case for any locally defined vocabularies for which the form displays a text value, but the URI value is stored in Fedora and SOLR).

Already implemented examples:

- rights_status
- content_type

Not yet implemented, which may follow this pattern:
- re_use_license

Other URI fields do not utilize a locally configured vocabulary:
- related_publications
- related_datasets
- final_published_versions
- rights_documentation

**Comment by bwatson78** [comment]
@eporter23 `grant_information_notes` is already established within the CurateGenericWork model as `grant_information`. Please use `grant_information` as the header in the csv.

**Comment by bwatson78** [comment]
There is no UI example I can display.

https://github.com/emory-libraries/dlp-curate/pull/1320

**Comment by eporter23** [comment]
@bwatson78, impressive work here! I started testing and ran into an error when I input a Creative Commons license value (from our locally defined vocabulary) in URL form into the CSV, using the _re_use_license_ header:  
http://creativecommons.org/licenses/by/3.0/us/ 

This URL was copied directly [from our term list here](https://github.com/emory-libraries/dlp-curate/blob/main/config/authorities/licenses.yml). Should I be using the string value instead?

See the error below. Note that I had the following also:
http://rightsstatements.org/vocab/NoC-US/1.0/ assigned to _rights_statement_ so I assume that error message was actually referring to the re_use_license entry.

![Screen Shot 2020-07-14 at 4.22.04 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/eada1128-c4b2-43bb-babb-ca907a607e92)

**Comment by bwatson78** [comment]
@eporter23 You’re right, it’s on the list, but the mapper method is using the same logic as rights_statement, which is only focused on licenses marked active. I do have to change the error statement to reflect the right verbiage. Below are the licenses I have:

‘’’
terms:
    - id: http://creativecommons.org/licenses/by/3.0/us/
      term: Attribution 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-sa/3.0/us/
      term: Attribution-ShareAlike 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc/3.0/us/
      term: Attribution-NonCommercial 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nd/3.0/us/
      term: Attribution-NoDerivs 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
      term: Attribution-NonCommercial-NoDerivs 3.0 United States
      active: false
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
      term: Attribution-NonCommercial-ShareAlike 3.0 United States
      active: false
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All rights reserved
      active: false
    - id: https://creativecommons.org/licenses/by/4.0/
      term: Creative Commons BY Attribution 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-sa/4.0/
      term: Creative Commons BY-SA Attribution-ShareAlike 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nd/4.0/
      term: Creative Commons BY-ND Attribution-NoDerivatives 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc/4.0/
      term: Creative Commons BY-NC Attribution-NonCommercial 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
      term: Creative Commons BY-NC-ND Attribution-NonCommercial-NoDerivs 4.0 International
      active: true
    - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
      term: Creative Commons BY-NC-SA Attribution-NonCommercial-ShareAlike 4.0 International
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: Creative Commons CC0 1.0 Universal
      active: true
    - id: http://creativecommons.org/publicdomain/mark/1.0/
      term: Creative Commons Public Domain Mark 1.0
      active: true
‘’’ 

If they should all be active, or the logic not care about that clause, let me know.

**Comment by eporter23** [comment]
Ah, thanks for pointing that out! I'll test one that is active:true. I'll also look into why some of these are false vs. true.

**Comment by bwatson78** [comment]
No, I'll take care of the wrong error message and this field tomorrow in the same PR.

**Comment by bwatson78** [comment]
New PR made for revisions: https://github.com/emory-libraries/dlp-curate/pull/1342

**Comment by eporter23** [comment]
Ready for prod, thanks!
