### ISSUE TITLE
Transfer additional Oxford yearbook volumes to EFS

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1266]
Additional volumes were discovered that were not in our original set of yearbooks.

Please transfer the following volumes' files from Isilon to /mnt/efs/Collections, retaining their relative directory structure after that point.

lsdi2/ftp/050000097150
lsdi2/ftp/000011973129
lsdi2/ftp/050000084030
lsdi2/ftp/050000084031
lsdi2/ftp/050000084032
lsdi2/ftp/050000087503
lsdi2/ftp/oxfordyearbooks/050000087521

**Comment by mprefer** [comment]
File transfer begun using 'rclone'.

**Comment by mprefer** [comment]
File copy completed @ 4:15PM 06/24/2020. Moving to "To Test"

**Comment by eporter23** [comment]
Confirmed the file counts, looks good.
