### ISSUE TITLE
Make Collection View pages metadata easier to read

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1267]
Collection View pages' metadata display uses default Hyrax styles, which are not optimal for reading. 

[Mockup for layout revisions](https://docs.google.com/document/d/19aduQc_g6drxWDtf3szQnUTSK_XA5EG4MynOVZhmKYU/edit#)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1375
![Screen Shot 2020-08-03 at 9.54.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c8542da3-cb13-457a-a35b-39211956b7af)
![Screen Shot 2020-08-03 at 9.53.59 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/e6ea7120-77a8-46fb-a8fd-84acfb6b1d8b)

**Comment by eporter23** [comment]
Looks great @bwatson78!

**Comment by eporter23** [comment]
Such a huge improvement - thanks!
