### ISSUE TITLE
Run preprocessor on additional Oxford yearbooks

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1271]
We need to run the preprocessor on an additional set of volumes found after we ran this the first time.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/Yearbooks-Oxford-Curate-LIMB-extravols-only.csv)
[Alma XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have 1-based filename sequences.
Filepaths start with _/Volumes_ as the prefix (should not need a _repl_ parameter)

`bundle exec rake curate:books csv=../cor-data-transfer/curate-ingests/2019/in_development/yearbooks/Yearbooks-Oxford-Curate-LIMB-extravols-only.csv xml=../cor-data-transfer/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml repl="" map="limb" 
`

**Comment by bwatson78** [comment]
Processed file placed in https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/2019/processed/yearbooks .

**Comment by eporter23** [comment]
@bwatson78 thanks for this! For some reason it has output very few filesets and I'm trying to track down what the problem in the input file is. I may ping you to retry this later.

**Comment by eporter23** [comment]
@bwatson78 when you have a moment, can you please re-run this on the same files linked above?

**Comment by bwatson78** [comment]
@eporter23 Absolutely.

**Comment by bwatson78** [comment]
@eporter23 New one located here: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/yearbooks/Yearbooks-Oxford-Curate-LIMB-extravols-only-merged-redo.csv

**Comment by eporter23** [comment]
@bwatson78 Looks perfect now! There was some unexpected whitespace in one of the source data columns that had interfered with the count of files rows.

Do you want to add an estimate to this ticket and then close it?
