### ISSUE TITLE
Confirm which fields are searchable in Curate search boxes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1272]
Before adjusting any search behavior, can we confirm which fields are searchable in two search options:

- [x] Main search box
- [ ] Dashboard search box

Main searchbox
![Screen Shot 2020-06-22 at 9.43.53 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5107282e-1e1a-4e46-8fcd-14d5be19c531)

Dashboard search box
![Screen Shot 2020-06-22 at 9.44.28 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/155b9b12-91ac-4a4a-bad6-87b8389b5cc0)

**Comment by wulman16** [comment]
@eporter23 The main search box searches virtually every metadata field:

- access_control_id_tesim
- representative_id_tesim
- thumbnail_id_tesim
- rendering_ids_tesim
- admin_set_id_tesim
- embargo_id_tesim
- lease_id_tesim
- head_tesim
- tail_tesim
- depositor_tesim
- title_tesim
- date_uploaded_tesim
- date_modified_tesim
- state_tesim
- proxy_depositor_tesim
- on_behalf_of_tesim
- arkivo_checksum_tesim
- owner_tesim
- abstract_tesim
- access_restriction_notes_tesim
- administrative_unit_tesim
- alt_title_tesim
- author_notes_tesim
- conference_dates_tesim
- conference_name_tesim
- contact_information_tesim
- content_genres_tesim
- content_type_tesim
- contributors_tesim
- copyright_date_tesim
- creator_tesim
- data_classifications_tesim
- data_collection_dates_tesim
- data_producers_tesim
- data_source_notes_tesim
- date_created_tesim
- date_digitized_tesim
- date_issued_tesim
- edition_tesim
- emory_ark_tesim
- emory_rights_statements_tesim
- extent_tesim
- final_published_versions_tesim
- geographic_unit_tesim
- grant_agencies_tesim
- grant_information_tesim
- holding_repository_tesim
- institution_tesim
- internal_rights_note_tesim
- isbn_tesim
- issn_tesim
- issue_tesim
- keywords_tesim
- legacy_rights_tesim
- local_call_number_tesim
- notes_tesim
- other_identifiers_tesim
- page_range_end_tesim
- page_range_start_tesim
- parent_title_tesim
- place_of_production_tesim
- preservation_event_tesim
- preservation_workflow_tesim
- preservation_workflow_terms_tesim
- primary_language_tesim
- primary_repository_ID_tesim
- publisher_tesim
- publisher_version_tesim
- re_use_license_tesim
- related_datasets_tesim
- related_material_notes_tesim
- related_publications_tesim
- rights_documentation_tesim
- rights_holders_tesim
- rights_statement_tesim
- scheduled_rights_review_tesim
- scheduled_rights_review_note_tesim
- sensitive_material_tesim
- sensitive_material_note_tesim
- series_title_tesim
- sponsor_tesim
- staff_notes_tesim
- subject_geo_tesim
- subject_names_tesim
- subject_time_periods_tesim
- subject_topics_tesim
- sublocation_tesim
- system_of_record_ID_tesim
- table_of_contents_tesim
- technical_note_tesim
- transfer_engineer_tesim
- uniform_title_tesim
- volume_tesim
- deduplication_key_tesim
- identifier_tesim
- file_format_tesim
- all_text_timv
- id

After some digging, I haven't yet found the place where the dashboard search fields are initially defined (I can only tell from manual testing that it searches at least title and creator but not ID, for example). I did, however, figure out how to add search fields to the dashboard search form. It would be very straightforward to just copy over the main search fields to be used in the dashboard search.

**Comment by eporter23** [comment]
@wulman16 great findings! A couple of followups:

1) Do you know if it's possible to target a specific field in the main search box via some type of input syntax? like "id:12345678910-cor" etc

2) For the dashboard search box, I have some requested ID fields to add in ticket #1273, if you are now able to estimate that ticket.

**Comment by wulman16** [comment]
@eporter23 

1) Not that I can tell. You could probably construct a query in the url to search on a specific field, but it would be a decent chunk of work to get the search bar to parse specific fields.

2) I put that ticket at a 2. I'll get started on that one shortly.

**Comment by eporter23** [comment]
Many thanks, this will be so helpful!
