### ISSUE TITLE
Re-characterize a FileSet using the UI

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1283]
This functionality would enable a user to regenerate technical metadata for a specific FileSet on demand using the UI.

This would involve cloning the characterization job, emptying the prior technical metadata, and then kicking off the job for that specific fileset.

To confirm:
Can we also add another Characterization Preservation Event entry when this occurs? This should record the name of the user that submitted the job from the UI.

**Comment by eporter23** [comment]
Hey @bwatson78 I saw that you had picked this one up. I had recently moved it out of the Backlog into New Issues because it isn't a high priority. But if you want to take a look at it, should be fine.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1417
![Screen Shot 2020-08-17 at 12.13.56 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/999514ab-158f-4739-85c4-bd6e51ec4176)

**Comment by devanshu-m** [comment]
@eporter23 is this something we are doing? Re-characterization will append data in some metadata fields instead of overwriting.

**Comment by eporter23** [comment]
@devanshu-m thanks for commenting on this and reminding me of that concern. The ticket description as we wrote it notes that it would delete the existing technical metadata and recreate it. But if that isn't possible (@bwatson78) we should hold off on doing this, because we would not want to append new/different technical metadata on top of existing metadata for files.

**Comment by bwatson78** [comment]
@eporter23 and @devanshu-m: Bringing this back into "In Progress" to dig deeper into how to address that requirement.

**Comment by bwatson78** [comment]
@eporter23 The UI and basic controller action has been fleshed out, but Devanshu feels that Software Engineering needs to meet to discuss the best way to perform the re-characterization in the back end. Placing this back in New Issues.

**Comment by eporter23** [comment]
@bwatson78 looks good! One item from the ticket description above regarding the Preservation Event - can it record the username who initiated the recharacterize event? I just recharacterized a fileset that Kathryn created, but it shows her name as running the re-characterization:

![Screen Shot 2020-09-10 at 9.05.14 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/00efa561-defd-4dbc-aeb0-3968d1735283)

**Comment by bwatson78** [comment]
@eporter23 Hmm, that's interesting. Bringing it back into progress to debug this.

**Comment by bwatson78** [comment]
New PR made to address the name not passing to the preservation event: https://github.com/emory-libraries/dlp-curate/pull/1489

![Screen Shot 2020-09-15 at 8.39.12 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/03cb1f4d-857d-492e-a35d-1d91a212c3b4)

**Comment by eporter23** [comment]
@bwatson78 I just tested recharacterizing this fileset: https://curate-test.library.emory.edu/concern/file_sets/412z34tn05-cor?locale=en

I notice that it created a new characterization event as well as a message digest calculation event: one is in my name and the other is in Kathryn's name (she was the original depositor):

![Screen Shot 2020-09-17 at 10.30.53 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f6367b1a-903a-4a70-bf83-cff3a586e921)

**Comment by bwatson78** [comment]
@eporter23 Digging into that event processing now.

**Comment by bwatson78** [comment]
@eporter23 I just examined our override that includes that preservation event. In order for us to pass along the initiating user, I'd have to alter the `initialization` and `run` methods of the `Hydra::Works::CharacterizationService`. To do that, with testing, I'm guessing I'd have a PR by tomorrow morning. Would you like me to move forward with that?

**Comment by eporter23** [comment]
@bwatson78 yes, let's move forward on that. I guess this is an unusual situation where one event is kicked off due to another, but it would be very good to have the correct user name associated with both.

**Comment by bwatson78** [comment]
New PR made fore revisions: https://github.com/emory-libraries/dlp-curate/pull/1495

![Screen Shot 2020-09-17 at 4.14.45 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6303522e-a80c-466e-8508-b034599bd499)

**Comment by eporter23** [comment]
Tested this on multiple filesets, seems to be working as expected and the usernames are now registering correctly.

**Comment by eporter23** [comment]
I happened upon a FileSet that had not been characterized and ran this, and it worked well! https://curate.library.emory.edu/concern/file_sets/668x95x6qj-cor?locale=en
