### ISSUE TITLE
Transfer missing Yearbook directories

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1298]
The following volumes are missing their TIFF subdirectories and files. Please transfer from Isilon to EFS:

From Isilon: lsdi2/ftp/000011743497/TIFF/*
To: mnt/efs/Collections/Yearbooks/Emory/lsdi2/ftp/000011743497/TIFF

From Isilon: lsdi2/ocm25899106-4402/ocm25899106/Output/TIFF/*
To: mnt/efs/Collections/Yearbooks/Emory/lsdi2/ocm25899106-4402/ocm25899106/Output/TIFF

**Comment by mprefer** [comment]
Missing file have been transferred to the EFS volume at AWS. Moving to "To Test" for verification.

**Comment by tmiles2** [comment]
Pending Emily's return.

**Comment by eporter23** [comment]
Got 'em, thanks! @mprefer
