### ISSUE TITLE
UI for Fileset Cleanup

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1318]
- [ ] Add a page to the dashboard for admins to kick off jobs from.
- [ ] Curate administrators can initiate fileset cleanup task through a UI

[Wireframe for UI](https://docs.google.com/drawings/d/1I7pLwQFjB9Wlcc2-grcS0Ug04IymOqPXEySrxftoJqI/edit), except using separate forms for each of the jobs, rather than one form for all of them.

**Comment by eporter23** [comment]
This work is being completed in ticket #1319.
