### ISSUE TITLE
UI for bulk-loading preservation workflow metadata

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1319]
- [x] Curate administrators can load preservation workflow metadata by submitting a CSV in the UI
- [x] the work should happen in a background job

[Wireframe](https://docs.google.com/drawings/d/1I7pLwQFjB9Wlcc2-grcS0Ug04IymOqPXEySrxftoJqI/edit), see also #1318

[[needs details: what info is in the csv?]]

[Sample CSV that is run in the current rake task](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/medical-artifacts/medical-artifacts-curate-processed-pwf.csv)

**Comment by eporter23** [comment]
@alexBLR I added a link to a sample CSV that we have run in the past which includes the necessary fields.

**Comment by alexBLR** [comment]
![Screen Shot 2020-08-04 at 8.33.50 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/1f3caf91-c294-4606-bf70-36b2d9c29111)

**Comment by eporter23** [comment]
@alexBLR I just tried testing a preservation workflow MD update in the new UI in Curate-test. Sidekiq is showing an error here:
https://curate-test.library.emory.edu/sidekiq/retries

[Uploading... Screen Shot 2020-08-18 at 2.15.08 PM.png ]

Here is the file I tried to load, which is based on prior usage. https://emory.box.com/s/tsp9ooogzmrwy79r6uymrqkzrxvl6v7g

**Comment by alexBLR** [comment]
@eporter23 I'll take a look at some point tomorrow. Thank you for testing

**Comment by eporter23** [comment]
@alexBLR I don't exactly where this is in code - but here are some examples of working file uploads in Curate:

CSV importer
https://curate-test.library.emory.edu/csv_imports/new

Assigning branding images to Collections
https://curate-test.library.emory.edu/dashboard/collections/945cc2fr5s-cor/edit?locale=en#branding

**Comment by eporter23** [comment]
@alexBLR when I upload [the following test file ](https://emory.box.com/s/tsp9ooogzmrwy79r6uymrqkzrxvl6v7g)which has been used in the past, I am immediately getting a generic application error, and nothing appears in sidekiq.


![Screen Shot 2020-08-27 at 9.47.20 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/54c6d200-487b-48c4-8000-91788139c793)

![Screen Shot 2020-08-27 at 9.47.27 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8dbcdcf7-4368-44d3-b559-2cef9b6c368b)

**Comment by eporter23** [comment]
@alexBLR I was able to run the reindex job successfully and the fileset cleanup job. The only remaining issue is running the preservation workflow metadata.

**Comment by eporter23** [comment]
@alexBLR @devanshu-m I created ticket #1462 for the preservation workflow error. I think we can go ahead and deploy this to prod however and address that later.

**Comment by lovinscari** [comment]
Zo believes issue/error reported above has been resolved since last test over week ago. Emily will test again. Last prod deployment was 8/27.

**Comment by eporter23** [comment]
Closing this - fix for preservation workflow MD csv uploads will occur in a separate ticket.
