### ISSUE TITLE
Use Shibboleth on curate-test

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#132]
- [x] Change env variable to use Shibboleth.
- [x] Test that login works
- [x] Ensure the admin setup rake task is run.
- [x] Revert changes that were made in order to disable database_auth on curate-test

**Comment by tmiles2** [comment]
@devanshu-m what part of this work has been completed? I don't see any tasks checked off but there is a PR.

**Comment by devanshu-m** [comment]
@tmiles2 I will add a task to this list now.
