### ISSUE TITLE
Problems running fixity checks in curate-prod

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1326]
When I click on the Run Fixity Check button on a fileset in the Curate production environment, I get an error (screenshot attached). I am able to successfully run the fixity check by either refreshing the error page or going back to the fileset and clicking the Run Fixity Check button again.

**Comment by kmichaelis** [comment]
![fixity_check_error.JPG](https://images.zenhubusercontent.com/5d924e9841d63100014d5334/ff3399e2-a0ec-40ec-b5f7-350d5e4242a5)

**Comment by eporter23** [comment]
@alexBLR - I did some more testing on this in prod with @kmichaelis and we're not seeing this today.
