### ISSUE TITLE
Prevent new users from getting an account

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#133]
Users that are not already registered with the system (done on the backend) should not be able to create an account, or log in.

- [x] Remove route to signup page.
- [x] Update User model to reject users unless already in db (or on the list)

**Comment by eporter23** [comment]
@alexBLR is this ready to be tested again?

**Comment by eporter23** [comment]
@alexBLR re-opening this. @tmiles2 is still able to login to Curate, but she is not on the list of users who is supposed to have an account. She should not be able to log in.
