### ISSUE TITLE
Encrypt EBS root volumes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1330]
Related to R02 and other security recommendations, we should encrypt root volumes for all application servers, currently estimated at 10 total.

**Comment by mprefer** [comment]
There are 2 methods to remediation:
1) Rebuild the server(s) from scratch with Ansible deploys.
2) Use snapshot to create an encrypted volume that can be attached to instance.

Steps to perform #2 above:
1. Stop your EC2 instance.
2. Create an EBS snapshot of the volume you want to encrypt.
3. Create a new EBS volume from your new EBS snapshot, making certain to set the encrypted option. The new EBS volume will then be encrypted.
4. Detach the original EBS volume and attach your new encrypted EBS volume, making sure to match the device name (/dev/xvda1, etc.)
5. Start the EC2 instance.

If there are issues, you can always stop the instance, detach the encrypted volume, attach the original unencrypted volume, start the instance. The instance's state will be as it was before.

@rotated8 @SolomonHD

**Comment by mprefer** [comment]
Systems with unencrypted root EBS volumes:

1)  awx.library.emory.edu
2)  curate.library.emory.edu
3)  curate-arch.library.emory.edu
4)  curate-test.library.emory.edu
5)  fedora-cor.library.emory.edu
6)  fedora-cor-arch.library.emory.edu
7)  fedora-cor-test.library.emory.edu
8)  digital.library.emory.edu
9)  digital-arch.library.emory.edu
10) digital-test.library.emory.edu

**Comment by rotated8** [comment]
@mprefer Is there any automatic cleanup for unattached EBS volumes? Would we want to keep the old unencrypted volume around for a couple days to ensure the new volume is working well before we delete it, or do you think having the snapshot is enough?

It sounds like this would work in reverse, too, if we wanted to move from an encrypted volume to unencrypted. Is that true?

**Comment by mprefer** [comment]
@rotated8 To my knowledge there is no auto cleanup of unattached volumes, unless a scripted solution has been written.
I'm in total agreement that we keep the original unencrypted volume around for several days after the procedure. I would be more comfortable keeping the volume, and maybe the snap. Can always create more snaps from the volume, since it will be unattached and unmodified.

Never tried reversing the process. Would have to experiment to see if that works.

**Comment by eporter23** [comment]
@mprefer I just tested curate-arch (edited an existing work, created a new one, modified some application layout settings) - all good.

**Comment by mprefer** [comment]
Onwards an upwards......

**Comment by eporter23** [comment]
@mprefer I did more testing on curate-arch by running a bulk import. I also connected to fedora-cor-arch, and browsed around in digital-arch. Everything looks as usual.

**Comment by libdgg** [comment]
Mark will work on this for test environment first (it's not being held up by 1335 that way).

**Comment by eporter23** [comment]
Update from slack by @mprefer: Only thing left is to keep the old ESBs and snaps for a month, then release those resources.
