### ISSUE TITLE
Suppress "Add Subcollection" options for non-admin users

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1336]
When a Curate user has access to view/manage a Collection, they can options to "Add to Collection" and "Add a Subcollection" and "create a new collection as sub collection" within a collection.

Because this functionality has not been fully tested, we should restrict this feature for non-admin users until we know what performance impact it may have on large collections, indexing, etc.

Suppress for non-Admins:
- [ ] Add to Collection
- [ ] Add a subcollection
- [ ] Create new collection as subcollection

![Screen Shot 2020-07-15 at 8.22.42 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ce159379-4bfd-45f1-9e6f-5d684a9b7b62)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1370

![Screen Shot 2020-07-30 at 6.35.34 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2fd3fa43-f6fe-4120-9fa3-58c4418526d3)
![Screen Shot 2020-07-30 at 6.35.59 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/849bd1a1-f743-4bdf-8cbf-a02352ca5604)
![Screen Shot 2020-07-30 at 6.36.08 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/eaa7b031-068f-4155-bd3d-099f2bd9f2b5)

**Comment by eporter23** [comment]
Tested with @tmiles2 - looks good for prod.

**Comment by eporter23** [comment]
Tested again in prod, looks good.

![Screen Shot 2020-08-11 at 1.06.17 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f8c9c1fd-396b-444f-85f0-b9749ed1caac)

![Screen Shot 2020-08-11 at 1.06.24 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/01103a63-a2ab-49b4-b280-17d2258eb2ae)
