### ISSUE TITLE
Configure the form to use our properties

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#134]
Using the metadata spreadsheet Emily gave us, the form should display fields for the properties that are editable in Curate.

- [ ] Form has the appropriate fields.
- [ ] System test can get to the form, and find some of the fields.

**Comment by eporter23** [comment]
@devanshu-m noting some testing issues here:

Re-use License: field is missing:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.y5fn5i8yw0ib

Primary Repository ID - this should not actually be editable by users in the form:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.64828yl5xd8e
