### ISSUE TITLE
Configure or hide Contact form in Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1345]
The Curate main navigation shows a link to a Contact page, which contains a form that is not configured.

https://curate-test.library.emory.edu/contact?locale=en

Options:

1. Remove the link to this form
2. Configure the form so that it emails to a valid address: dlpfeedback@listserv.cc.emory.edu
3. **Redirect the Contact link so that it redirects to https://emory.libwizard.com/f/dlp-feedback**

**Comment by eporter23** [comment]
Discussed: overwrite the route to the Contact page so that it redirects to our DLP Feedback form. This could then be updated to redirect to service now (or final support url).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1374
![Screen Shot 2020-07-30 at 8.06.56 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6f2f9070-0120-497f-8e52-bcac9b0ce2aa)
![Screen Shot 2020-07-30 at 8.06.47 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/70914e8a-3ad9-4357-8df2-d8284ec79ae6)

**Comment by eporter23** [comment]
Looks good!

**Comment by eporter23** [comment]
Verified in prod.
