### ISSUE TITLE
Disable button set for batch actions in dashboard UI

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1348]
When a user is in the Dashboard view, they have the ability to select multiple items through checkboxes. Once a checkbox is selected, a set of buttons appears allowing users to Edit, Delete, or Add to Collection. 

Edit does not appear to function, and we don't want non-Admins Deleting or Adding to Collection.

![Screen Shot 2020-07-17 at 1.11.51 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c883741a-ed00-4d3d-a977-567ae6f00a28)

Tested:

The edit button returns a generic application error

The delete button works, however (tested with Tiffany as a manager-level user)

![Screen Shot 2020-07-17 at 12.45.33 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/2ff182cb-5a4c-488c-a4dc-9f38f2acd167)

**Comment by eporter23** [comment]
@devanshu-m Tiffany and I tested this in curate-test, she does not have Admin level access. For Works, she is still able to see these buttons:

![Screen Shot 2020-07-29 at 1.02.12 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c310f1fa-a36f-4d6f-a037-7e34f02fd6d7)


For Collections she does not:

![Screen Shot 2020-07-29 at 1.03.59 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/24fff40f-944b-476c-b6b8-28bcf4f7542e)

**Comment by devanshu-m** [comment]
https://github.com/emory-libraries/dlp-curate/blob/302f1a6fc9b7ca03f192a5a6a7a8b0b80817b615/app/views/hyrax/my/works/_bactch_actions.html.erb

I have a misspelled filename here. I will correct the name and put in a PR.

**Comment by eporter23** [comment]
This has been retested successfully:

![image.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/dddf3f31-bd57-4460-86d4-e668fc74aa8c)

**Comment by eporter23** [comment]
Tested again in prod.
