### ISSUE TITLE
Ensure repeating entries repeat in the form

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#135]
- [x] Add to the form system test to try adding multiple of a repeating entry.

This is something that should happen automatically.

**Comment by eporter23** [comment]
@alexBLR @devanshu-m adding some form testing notes here:

Title - should not repeat
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.rrh3fp7199ud

Grant/Funding Agency should be repeatable:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.is973n4kmqxm

Subject - Geographic should be repeatable:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.k1ert41acjvh

Rights Statement Free Text should be repeatable
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.z9a79moa2qdi

**Comment by eporter23** [comment]
Test issues above are all resolved except that Title still repeats.
