### ISSUE TITLE
Configure required fields for the form

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#136]
Using the metadata spreadsheet Emily gave us, the form should require fields for the properties that are required in Curate.

- [ ] Configure the required fields
- [ ] Add the required fields to the form's system test.

**Comment by eporter23** [comment]
@devanshu-m adding test notes here:

Date Created - should be presented as required in the form:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.nq1e9krbwm5z

Data Classification - should be required:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.78se67w32j9d

**Comment by eporter23** [comment]
@devanshu-m thanks for the revisions - closing this ticket because they now show as required, though I am running into some issues with both fields which I'll report on separately.
