### ISSUE TITLE
Run collection count task in curate-test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1362]
To test ticket #1252, please run the rake task in the curate-test environment. If possible, please run it on all collections. Or, please target the following:

320sqv9s4v-cor
914nk98sfv-cor
5053ffbg7n-cor
815p8cz8wv-cor
706g1jwsv6-cor

**Comment by bwatson78** [comment]
Process started at 11:41AM EDT 7/24/2020.

For reference, command used:
`RAILS_ENV=production bundle exec rails curate:collection_files_ingested:process`

To process only certain collections, use this command:
`RAILS_ENV=production bundle exec rails curate:collection_files_ingested:process collections="320sqv9s4v-cor 914nk98sfv-cor 5053ffbg7n-cor 815p8cz8wv-cor 706g1jwsv6-cor`

**Comment by bwatson78** [comment]
@eporter23 It produced an error, pulling the original ticket back into progress.

**Comment by bwatson78** [comment]
@eporter23 New rake process started in Test at 442p EDT.

**Comment by bwatson78** [comment]
Process completed roughly 15 minutes after. File produced by rake task delivered to @eporter23 7/27/20 via slack DM.

**Comment by eporter23** [comment]
The report looks great. 

testing notes for posterity: I ran into some count discrepancies on the "Deposit Collection"'s counts, but this seems to be due to 1) one of the works in that collection had a child work which was in a different collection 2) one of the filesets didn't have both of its files included in the sha1 value which appears to be an indexing issue. The Asian Artifacts and Medical Artifacts collection counts were exactly as expected. There are 8 files fewer than expected for Langmuir, but it will be hard to know exactly which ones and/or if this is due to an indexing issue. Curate-test filesets haven't been fully reindexed recently. I have not attempted to verify the file and fileset counts for the book collections at this time.
