### ISSUE TITLE
Hundreds of errors at import: 400, 502 (SOLR and Fedora)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1364]
The ingest that is currently running since Friday 7/27 has logged over 750 errors which has caused hundreds of files to not be ingested. These include 400 Bad Request errors for SOLR, and 502 Bad Gateway errors for Fedora. A typical book ingest job may generate perhaps 50 or less errors; these current errors are unusual.

Also of concern - I have not seen any email alerts about SOLR or Fedora experiencing issues.

```
17 hours ago	default	AttachFilesToWorkJob	
{"_aj_globalid"=>"gid://dlp-curate/CurateGenericWork/4407wm3813-cor"}

RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request Error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>400 Bad Request</title> </head><body> <h1>Bad Request</h1> <p>Your...
```

```
IngestJob	
{"_aj_globalid"=>"gid://dlp-curate/JobIoWrapper/172748"}
Ldp::HttpError: STATUS: 502 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>502 Bad Gateway</title> </head><body> <h1>Bad Gateway</h1> <p>The proxy server received an invalid re...

```

**Comment by SolomonHD** [comment]
I'm not sure what's causing this. We probably need to restart fedora/solr for the prod instances at the very  least.

**Comment by eporter23** [comment]
@SolomonHD @rotated8 here is a screenshot of the most recent instances errors occurring since about 6pm last night. There is also a new faraday connection error in the list. 

![Screen Shot 2020-07-28 at 8.33.26 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f5da4f1d-d8cf-4c3c-a5df-50fc3c448b6a)

**Comment by SolomonHD** [comment]
I've reviewed the logs for fedora and solr, I don't see any smoking gun that coincides with the timestamps in honeybadger. I do think reworking the DNS/load balancing for solr will help. I'll give details in standup.

**Comment by SolomonHD** [comment]
I've made changes to all the solr's DNS. They now use multivalue instead of simple routing, this should balance the traffic among all three solrs evenly. 

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/64807cb4-d772-4adc-88b9-ed0b3d7a0839)

With this done I am unsure if I have any further role in this ticket.

**Comment by eporter23** [comment]
@SolomonHD thanks! do we still have no insights about the Fedora 502 errors? FWIW, the last instance of that error occurred 2020-07-29T10:05:59Z according to sidekiq.

**Comment by eporter23** [comment]
@SolomonHD @rotated8 this may be unrelated, but on the import that had all these errors and failures I am often seeing numerous Virus Scan events showing up during those affected timeframes. Here's one example, but there are many more: https://curate.library.emory.edu/concern/parent/576rxwdc4h-cor/file_sets/723hx3ffpm-cor

**Comment by rotated8** [comment]
I think that makes sense. I believe the IngestJob triggers the virus check, so when the job retries, I would not be surprised to get another virus check. The number of checks on the first link is interesting, though, as it is larger than the number of retries.

**Comment by eporter23** [comment]
I re-ran an import of a book that had missing filesets and kept an eye on the jobs - there were no recurrences of these errors in the last 24 hours.
