### ISSUE TITLE
Configure non-local controlled vocabs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#137]
Using the metadata spreadsheet Emily gave us, the form should use  non-local controlled vocabs for the properties that are have them in Curate.

- [ ] Add the vocabs to the Questioning Authority configuration.
- [ ] Set up any necessary services for the vocabs
- [ ] Enable the vocabs for the appropriate properties in the form.
- [ ] Add or update some of these properties to the form's system test.

**Comment by devanshu-m** [comment]
@eporter23 @rotated8 

Most of the External (non-local) controlled vocabs are available through the Questioning Authority gem, but there are some exceptions:

1. Content Genre (D6) (LOC Marc genre/terms) - not available through `qa` gem
2. Subject - Names (D31) (VIAF) - not available through `qa` gem
3. Role - Creator (D45) (VIAF)
4. Role - Contributor (D46) (VIAF)
5. Rights Holder (D58) (ORCID; VIAF) 

Some properties have a controlled vocab that came with Hyrax:
1. Content type (D5) (LOC Resource types): https://github.com/emory-libraries/dlp-curate/blob/master/config/authorities/resource_types.yml
2. Rights statement (D57): https://github.com/emory-libraries/dlp-curate/blob/master/config/authorities/rights_statements.yml
3. Re-use license (D60): https://github.com/emory-libraries/dlp-curate/blob/master/config/authorities/licenses.yml

**Comment by eporter23** [comment]
@devanshu-m I tried to respond to your questions and notes from above, but it was a little long for a comment box so I've noted them here: https://docs.google.com/document/d/1nrm6D3_VhroZDCno2Lqybvpeqg7bseCvYHtXusOnAgU/edit

**Comment by eporter23** [comment]
Tested 5/10. All external vocabs function except that GeoNames is not fully configured because of the account setup needed.

**Comment by eporter23** [comment]
@devanshu-m tested again - GeoNames is working great!
