### ISSUE TITLE
Configure local controlled vocabs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#138]
Using the metadata spreadsheet Emily gave us, the form should use  local controlled vocabs for the properties that are have them in Curate.

- [x] Create the vocabs with local terms.
- [x] Add the vocabs to the Questioning Authority configuration.
- [x] Set up any necessary services for the vocabs
- [x] Enable the vocabs for the appropriate properties in the form.
- [x] Add or update some of these properties to the form's system test.

**Comment by eporter23** [comment]
Tested 5/10. Some issues noted in the test log.

Re-Use license field is missing: https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.y5fn5i8yw0ib

extraneous term in the Content Type vocab:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.2hyegbg3h3t3

Grant/Funding Agency should not be a local vocab:
https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.is973n4kmqxm
