### ISSUE TITLE
Basic display of source collection and deposit collections on View Work pages for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1383]
This refers to [wireframe section 4](https://docs.google.com/drawings/d/1QlhvkVxhXByBJYoWr587wx10YLbv0HYXP7W9bhx6AC0/edit).

Should also accommodate existing collections if both a deposit and a source id have not yet been populated

**Comment by kmichaelis** [comment]
![Capture.JPG](https://images.zenhubusercontent.com/5d924e9841d63100014d5334/2d3d21e7-374a-4a50-9f24-6a612a72ea0a)

@devanshu-m Is this labeling ok? It looks different from above where each collection title gets its own header.

**Comment by devanshu-m** [comment]
Does the work in the example above have different source and deposit collections? @kmichaelis

**Comment by kmichaelis** [comment]
@devanshu-m yes it's this item: https://curate.library.emory.edu/concern/curate_generic_works/436tx95xd2-cor?locale=en

Hopefully I associated the item with the deposit collection correctly.

**Comment by eporter23** [comment]
@devanshu-m @kmichaelis I'm going to set up some new (Private) works and Collections in prod to test things out further, but I will need to wait until we can assign the source_collection_id via the edit form. I want to make sure we don't use real production objects just yet.

**Comment by eporter23** [comment]
@devanshu-m @kmichaelis I was able to test this on some additional (hidden) objects in production. The distinct source and deposit collections are showing up on the work pages as expected:

![Screen Shot 2020-09-08 at 1.40.48 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1595c63b-a7e5-42dc-b05b-f531ef50e456)
