### ISSUE TITLE
Add new setting to Collection Type to differentiate between Source, Deposit Collection views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1385]
Because all Hyrax collections seem to share a common display template, the collection type model would need a new option added. This should look similar to existing Collection Type options available when you [create a new Collection Type](https://curate-test.library.emory.edu/admin/collection_types?locale=en).

Example:

Deposit-only Collection: (checkbox) 

We can delete and recreate the existing Deposit Collection type in test, so that it would utilize the new property/setting.

Mockup:

![Screen Shot 2020-08-12 at 8.34.26 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1540ded5-6d1c-4bd5-b368-0b6f8cd6fd6a)

**Comment by bwatson78** [comment]
@eporter23 Just confirming that this is only the addition of a boolean attribute to the `CollectionType` model and that what it's affecting in the system is not in this ticket's scope.

**Comment by eporter23** [comment]
@bwatson78 that is my understanding. Once this is established, I will go recreate the Deposit Collection type. After that, I'll test depositing some works in there and hopefully we'll have the necessary hooks to differentiate between a Source Collection and a deposit-only collection for display purposes as outlined in other tickets.

**Comment by bwatson78** [comment]
@eporter23 Should it default to false/true?

**Comment by eporter23** [comment]
@bwatson78 I think it should default to false (unchecked).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1424

**Comment by bwatson78** [comment]
![Screen Shot 2020-08-25 at 10.59.02 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/0c2b72d7-422d-4f29-b48d-b352cc186dd6)

**Comment by bwatson78** [comment]
![Screen Shot 2020-08-25 at 11.02.56 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/f5cbac07-8900-4a53-80ae-09f86b572e09)

**Comment by eporter23** [comment]
I created a new Collection Type instance in curate-test and applied the new settings. https://curate-test.library.emory.edu/admin/collection_types/5/edit?locale=en#settings
