### ISSUE TITLE
Update Collection form to add/edit relationships between source and deposit collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1388]
See [wireframe](https://docs.google.com/drawings/d/1w8W1lAFsUV7kKWkJdnzCR1xsJjyYtel4_XP6SPMRlmU/edit) for assigning collection ids at the collection level.

Discussion: it may be best to make these form fields admin-only. It may also be beneficial to detect the type of collection being edited, and only show source OR deposit collection fields as applicable.

**Comment by eporter23** [comment]
Discussed by slack with @bwatson78 - we can use a drop-down select menu instead of the collection lookup feature shown in the wireframe.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1449
![Screen Shot 2020-08-26 at 11.32.28 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3b2d7c1d-ef81-4dae-9fbc-653dd3334102)

**Comment by eporter23** [comment]
@bwatson78 I successfully assigned a relationship via UI between a Deposit Collection back to its Source Collection. In testing I also see that the Source Collection displays in one of the collection views but not the "Public" view. Should I create another ticket for this? This also is probably more about ticket #1390.

Deposit Collection - Dashboard View
https://curate-test.library.emory.edu/dashboard/collections/235gb5mkx3-cor?locale=en

Deposit Collection - Hyrax "Public View"
https://curate-test.library.emory.edu/collections/235gb5mkx3-cor?locale=en

**Comment by eporter23** [comment]
@bwatson78 I added the above comments to ticket #1390. The assignment via UI is working as expected between the two collections as shown below:

Deposit Collection
![Screen Shot 2020-08-26 at 7.50.53 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/db3d993a-6321-4d2e-9b29-1f654a717f63)

Source Collection
![Screen Shot 2020-08-26 at 7.51.35 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b4b3f5df-e251-41c5-ac72-82956ba12742)

**Comment by bwatson78** [comment]
@eporter23 This only reflects on #1390 in the sense that, when the source id is assigned, it would populate if both view pages had the source collection link html. If the form successfully persists the id, then I think the scope of this ticket is complete.

**Comment by eporter23** [comment]
@bwatson78 this is looking great. The form persists single and multiple ID values. Please also see new ticket #1456 about storing the Title values, as I'm not sure if that relates to the form or the collection fields ticket that Zo worked on.

**Comment by eporter23** [comment]
Tested in Curate prod using a new Library Collection type instance called Regression Test Collection, and creating 2 new Deposit Collection type instances and assigning them to the Regression Test Collection. @bwatson78 can you confirm if the new fields are visible to admins only, or can all users see them?

**Comment by bwatson78** [comment]
@eporter23 I have inserted logic for both that replaces the input field with an "Admin only" message when anybody other than an admin starts to edit/create a Collection. That seemed to be the least invasive way to block access, since the easiest way to customize the fields allows access only to the input tag, not it's label.

**Comment by eporter23** [comment]
Thanks @bwatson78 just wanted to confirm for future testing/documentation!
