### ISSUE TITLE
Adjust view collection page output for Deposit Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1390]
See wireframe for [Deposit Collection view](https://docs.google.com/drawings/d/18zAPiFxsVH12Oq5mXhNb_Bz6i025fjhvdHXriAANJvA/edit)
- section 5

The rest of this page's behavior is standard Hyrax collection display.

**Comment by eporter23** [comment]
@bwatson78 I successfully assigned a relationship via UI between a Deposit Collection back to its Source Collection. In testing I also see that the Source Collection displays in one of the collection views but not the "Public" view. Should I create another ticket for this? 

Deposit Collection - Dashboard View
https://curate-test.library.emory.edu/dashboard/collections/235gb5mkx3-cor?locale=en

Deposit Collection - Hyrax "Public View"
https://curate-test.library.emory.edu/collections/235gb5mkx3-cor?locale=en

**Comment by bwatson78** [comment]
New PR made: https://github.com/emory-libraries/dlp-curate/pull/1455
![Screen Shot 2020-08-27 at 5.59.28 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/a271a38a-f560-4273-872a-787527d9147e)
![Screen Shot 2020-08-27 at 5.59.59 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/3c135ee0-2308-4723-880e-061a2af842d5)

**Comment by eporter23** [comment]
Looks great, thank you @bwatson78!

**Comment by eporter23** [comment]
Tested in Curate prod using a new Library Collection type instance called Regression Test Collection, and creating 2 new Deposit Collection type instances and assigning them to the Regression Test Collection.
