### ISSUE TITLE
Adjust manifest regeneration process when saving changes to works in Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1394]
We have identified a pattern of Curate application performance degradation and disruption of image delivery to Lux when too many manifest regeneration requests occur in a short period of time. See Lux ticket 679.

The manifest regeneration process is currently triggered whenever a work is first created or later modified, whether a user opens a work and edits it, or during a bulk-update of metadata. In many cases, metadata changes do not necessitate a new manifest.

The state changes that would necessitate a new manifest actually being needed are:

1. Changing or adding filesets used by the manifest
2. Changing/assigning the representative media for a work
3. Changing/assigning the rendering options (aka download files) assigned to a work
4. Changing the work's Title
5. Changing the work's Rights Status
6. Changing the work's Holding Repository
7. Changing the work's Visibility
8. Changing a Fileset's Visibility

 

To discuss: can we make the regenerate manifest process optional when a user saves a work?
OR, should we revise the Curate manifest regeneration process to be sent to a background job/sidekiq instead of through the application server.
This could also be combined with proposed work in #1402 (moving background workers to a separate server).

**Comment by lovinscari** [comment]
Follow up meeting needed - cannot estimate at this time.

**Comment by eporter23** [comment]
Discussion: when a user in Curate saves a work, this triggers the manifest regeneration process but goes directly through the Curate application server and is not queued as a background job in sidekiq.

**Comment by eporter23** [comment]
Additional updates from slack discussion with Devanshu: when we run a metadata refresh on works, this will trigger the manifest regeneration process. We will need to do this carefully with books.

**Comment by devanshu-m** [comment]
Pushing this to a bg job might be complicated and will require some research. This is because the uv looks for the manifest for a work by going here `/work_id/manifest`, which renders a json that the uv works with to display images: https://github.com/emory-libraries/dlp-curate/blob/main/app/controllers/hyrax/curate_generic_works_controller.rb#L40
and here (for lux): https://github.com/emory-libraries/dlp-curate/blob/main/app/controllers/iiif_controller.rb#L260

If we change this to go to a background job, the uv will be confused and will not receive a json to map images from. One solution to this would be moving the checking of manifest existence to the controller and if it exists then we render the json for feeding it to uv else we queue up the bg job. If a bg job is queued up, the uv will be blank until a manifest is generated and then uv can render it. This will be similar to what we are already doing when checking if a manifest exists in the manifest builder service here: https://github.com/emory-libraries/dlp-curate/blob/main/app/services/manifest_builder_service.rb#L45

This requires more discussion with Emily.

**Comment by eporter23** [comment]
Discussion - @rotated8 please clarify these if possible:

- Only some fields/states changes to works would impact the manifest changing - can we target those only?
- can we create a hash/cache key (id.hash) and put this in Solr. Also establish a fallback manifest with a "content is being assembled - please return soon" etc message.
- On save in tosolr, a new thing creates a hash/cache key - before save callback that compares key to previous key...

**Comment by devanshu-m** [comment]
Fields that go in a manifest:

- work.title
- manifest metadata
  - holding_repository
  - rights_statement
  - work.id
  - purl
- rendering options (rendering_ids in solr_doc)
- file_sets details
  - file_set.id
  - file_set title
  - file_set.height
  - file_set.width
  - iiif_url for preferred file in file_set
  - info_url for preferred file in file_set
- canvas uri which is basically `root_url/canvas/file_set_id`

I don't expect any IDs to change, so we can skip those when creating manifest cache key. Tricky parts here could be getting the file_set details in the work indexer to construct manifest cache key. Thinking of work arounds for checking if files are being added.

**Comment by devanshu-m** [comment]
Update: Creating a cache key for manifest is possible however, getting a placeholder manifest is difficult to do. Thinking of some work arounds, for instance, adding text in the banner after updates.

**Comment by devanshu-m** [comment]
Update: Just putting this here as a reminder. We will need to first reindex all works before we regen manifests so that the new manifest cache key can be indexed for works.

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/dlp-curate/pull/1429

A new manifest will only be generated if the following values change:
`object.title or object.file_sets.count or object.holding_repository or object.rights_statement or object.rendering_ids`
object here is a work

**Comment by eporter23** [comment]
@devanshu-m will the new process get triggered if a work's Visibility has changed? That will be very important related to access controls.

**Comment by devanshu-m** [comment]
@eporter23 currently it will not. But it will be easy to add that constraint.

**Comment by eporter23** [comment]
@devanshu-m if it is possible to add that, that would be great. I had noted it in the ticket description above after we met last week.

**Comment by devanshu-m** [comment]
@eporter23 I do apologize, I might have missed that point. I was only looking at what work related things went into the manifest.

**Comment by eporter23** [comment]
Great work, @devanshu-m! I tested this on multiple works by editing the various fields manually, and I also ran a small CSV import to update the Title of a work which also triggered the manifest regeneration.

**Comment by eporter23** [comment]
Tested minimally in production, looks good. I am sure this was also tested quite a bit while metadata updates were run in production last week too.
