### ISSUE TITLE
Review AWS storage locations and usage reporting

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1396]
To understand current, active storage buckets and usage, and to project storage growth over time we need to document our current utilization.

- [x] Review existing S3 buckets - which are used actively?
- [x] Update Cloudwatch widgets/metrics to include all applicable storage 
- [x] Review existing EFS storage
- [x] Document other applicable AWS storage
- [x] Identify a retention period for backups

**Notes**

1. [Estimating/projections worksheet](https://docs.google.com/spreadsheets/d/152ucLfr85Qfzl-VBsThuCPwDcTzNFaq1OX_he6xFvr0/edit?usp=sharing)
2. [Draft retention policy for storage and files](https://emory.box.com/s/8aul64gv99vvc2ni527vvd8z5anw08p2)

**S3 buckets on our account:**

See additional notes in the links above.

![S3 buckets 2020-08-10 at 1.14.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6a1fb945-b9db-4a15-ab11-704ada7cf187)

**Comment by eporter23** [comment]
I met with Solomon today and we walked through most of the open questions I had, and where to locate different storage metrics in Cloudwatch and other locations. We also identified an issue where versioning is enabled in our second copy S3 buckets, which is causing a very large amount of storage to be used which we didn't know about. This has been written up as a separate ticket.

**Comment by libdgg** [comment]
@eporter23 can you provide the retention period that you will need for backups?

**Comment by eporter23** [comment]
@libdgg I can't really do that without input from the Scrum team - the retention period may vary per different types of backups. It would also be helpful if others could provide input on best practices in this area.

**Comment by lovinscari** [comment]
Emily had created a document with a Box task but it does not appear everyone has reviewed/approved. Comment from 8/21.

**Comment by libdgg** [comment]
Mark, Solomon, Collin and Doug reviewed the doucment, added comments and are ok with the document.
