### ISSUE TITLE
Update AWS architecture diagrams/documentation

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1397]
The AWS architecture diagram we provided for the ART review is out of date, as we transition to operational support, we need to make sure it is updated:

https://app.lucidchart.com/documents/edit/21a529d5-aa77-44fb-ad78-397c9bd8b082/0_0

**Comment by lovinscari** [comment]
Need Solomon to review with Collin to determine the accuracy of the existing Lucidchart.

**Comment by libdgg** [comment]
Mark did not have access to edit the lucid chart. Collin has provided edit access to both Mark and Solomon.

**Comment by mprefer** [comment]
Still have a few lines need to be moved, but here is the current WIP.

https://app.lucidchart.com/invitations/accept/e9ef5492-ef3b-4ce2-8e79-f6811f3b713c

**Comment by lovinscari** [comment]
@libdgg, @rotated8, @SolomonHD - please review the Lucidchart from Mark's comment on 8/24.

**Comment by libdgg** [comment]
Mark, Solomon, Collin and Doug reviewed and approved the updated architecture diagram.
