### ISSUE TITLE
Validate date entries

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#140]
Using the [date validation notes](https://docs.google.com/document/d/1A9hMl1ZNDbN2J4q77_6ixvq_wVW4gFJtxK-nnZKo5Tc/edit#heading=h.brpnvg8zad3u), ensure the date fields conform to our requirements

- [ ] Add form validation to date fields.
- [ ] Extend or update the form's system test to fill in date fields.

**Comment by rotated8** [comment]
We found a EDTF javascript library to help with this: https://github.com/inukshuk/edtf.js

**Comment by eporter23** [comment]
@alexBLR I saw this was closed but I haven't tested yet - so I'll move it into To Test.

**Comment by eporter23** [comment]
@alexBLR I started some testing on the dates validation but ran into errors on what should be valid dates, as well as unknown dates entered as "XXXX"

![Screen Shot 2019-05-22 at 2.13.37 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d57a08a0-d524-4504-ba02-ac45480f00dd)

![Screen Shot 2019-05-22 at 2.14.19 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c32a0de5-2804-4a76-92d8-33952a1865b0)

**Comment by alexBLR** [comment]
@eporter23
![Screen Shot 2019-05-23 at 9.38.15 AM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/54bd734b-5d96-4012-8935-f7078f89f042)

**Comment by alexBLR** [comment]
@rotated8 do we need to do anything specific for the test server to precompile assets for webpacker. I assume this might be the issue here.

**Comment by rotated8** [comment]
@alexBLR Is that what you see when you submit the form? Capistrano does precompile the assets for us.

**Comment by rotated8** [comment]
Closing in favor of #257
