### ISSUE TITLE
Run preprocessor to test date digitized outputs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1401]
Please run the book preprocessor in the following mode:

`map` = kirtas
`repl` = blank

CSV
https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/Yearbooks-Oxford-Curate-LIMB.csv

XML
https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml

**Comment by bwatson78** [comment]
@eporter23 The email notification I receive from Github says to run this in `:limb` mode, but the description states `:kirtas`. I ran into errors, first trying kirtas, but switched to limb when I saw the CSV filename. Processed file has been sent to your slack.

**Comment by eporter23** [comment]
Sorry @bwatson78 for my copy and paste error from another ticket. Output looks great.
