### ISSUE TITLE
Adjust pre-processors so that they output a source_collection_id column in generated CSVs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1407]
The preprocessors developed by DCE output take an input CSV which includes column headers for required fields and other additional/optional fields. We need to add support for source_collection_id which is a new required field.

Adjustments needed:

- [x] If the input file **does not** contain a column for source_collection_id, it should be added to the output (there will be no values assigned at this point, it is just an empty column)
- [x] If the input file **does** contain a column for source_collection_id, it should be included in the generated output. 

To update:

- [x] Langmuir preprocessor
- [x] Book preprocessor
- [ ] Other CSV importer validations?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1469

**Comment by bwatson78** [comment]
No screenshots necessary.

**Comment by eporter23** [comment]
@bwatson78 when you have a chance, can you please run these for testing?

Test file for Langmuir/DAMS preprocessor: 

- https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/langmuir/langmuir_batch_raketest.csv

Test files for book preprocessor - LIMB mode

- https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/Yearbooks-Oxford-Curate-LIMB-extravols-only.csv
- https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml

**Comment by eporter23** [comment]
Tested with output files provided by @bwatson78 in slack, looks good!

**Comment by eporter23** [comment]
@bwatson78 I don't think there is a need to re-test this for production specifically, so I'll close this. Thanks!
