### ISSUE TITLE
Add source_collection_id to Work form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1408]
**To confirm: would this be easier through the Relationships tab, or as a field on the Descriptions section of the form?**

See [early wireframe concept](https://docs.google.com/drawings/d/16KWbOhooGWYj0-C92Jp1oq_0ptjHELTCtZwysfAlpNg/edit).

If a work is manually created (not created through the CSV import process), we need a way to assign it to a Source Collection.

- [ ] The field should be single valued (multiples not allowed).

Preferred option:

- [ ] Expand the Relationships tab to specify Deposit and Source collection relationships (see wireframe). 
- [ ] Use a lookup field to search by Collection title, returning matches on Source Collections only.
- [ ] The existing Hyrax collection relationship becomes the Deposit Collection.

Alternate option:

- [x] Provide a simple text input field that receives the ID of a Source Collection. 
- [x] Update the Edit/Create Work form to add Source Collection (source_collection_id) as a form field, at the very end of the Admin Metadata section. 
- [x] The field is required.

**Comment by eporter23** [comment]
@wulman16 the field is working on the form, but it is supposed to be a required field. Can you please make that adjustment, or let me know if there is an issue with making it required?

**Comment by wulman16** [comment]
@eporter23 Apologies, I meant to reach out to you about this earlier. There are two complications with making source_collection_id required:

1. When collections and works have shared a metadata field, the new/edit form uses the same partial to display that input field. Making source_collection_id required on works also makes it required on collections, which would then prevent users from creating new source collections using the form, since that collection's id wouldn't exist yet.

2. Because source_collection_id is in the admin metadata section, non-admin users would be unable to create new works using the form. I wasn't sure if that was intended behavior or not.

**Comment by eporter23** [comment]
@wulman16 thanks for these details. I didn't realize about your point 1 above. For the "Admin" metadata section, that heading is short for "Administrative" but aren't actually restricted to admin users only: all fields in the Descriptions tab are currently visible to users who can create and edit works. (I may write a ticket to change that "Admin" heading though, as it may be confusing.) At any rate, I think it's okay for the source_collection_id field to not be required at this point and we can revisit this in the future if not requiring it causes problems with users who might be manually creating works in the form.

**Comment by eporter23** [comment]
@wulman16 sorry, to clarify, is the source_collection_id field on the work form visible to all users? That will be needed.

**Comment by wulman16** [comment]
@eporter23 I figured out a way to make this field required only for works and for it to show up to all users in the work form. I have a PR for it now, so I'll move this ticket back to To Merge.

**Comment by eporter23** [comment]
Now enforces this as a required field - thanks @wulman16 !

**Comment by eporter23** [comment]
Testing this to add source collection ID to books one by one in production and it is working well.
