### ISSUE TITLE
Group fields into sections based on metadata type

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#141]
The metadata type is part of the metadata spreadsheet Emily gave us.

- [ ] Group descriptive metadata in a section at the top of the form.
- [ ] Group rights metadata in a section in the middle.
- [ ] Group admin metadata in a section at the bottom.

**Comment by eporter23** [comment]
Tested on 5/10. Metadata is grouped into 3 sections but not all of the other criteria in the epic #40 were included related to which fields are initially visible and the overall field ordering. See test log:

https://docs.google.com/document/d/1X9uU55NRGg3Jb3e2iLXpVAG9ObuvGbR49Ml3Vm2IvWM/edit#heading=h.giibep2g87tq
