### ISSUE TITLE
Fedora 502 Proxy Errors causing AttachFilestoWork jobs to fail

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1420]
Updates, 9/11/20:

Changes to implement for better Curate performance include:

- Changing the type of events worker used
- Limiting maximum number of requests to Passenger (300 across the board) 

Original ticket details:

We are seeing recurring Fedora 502 errors on the import that's been running in prod since 8/14. On a batch of 10 works, 7 of them have currently failed at the AttachFilesToWork stage. We've been retrying them, but they continue to fail. We have not seen any other unusual errors during this import.

Error in sidekiq:
`Ldp::HttpError: STATUS: 502 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>502 Proxy Error</title> </head><body> <h1>Proxy Error</h1> <p>The proxy server received an invalid re...`

Screenshot of current errors in the dead queue:

![Screen Shot 2020-08-19 at 8.43.16 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ea7ad3a0-4571-433a-af56-4e912804a3e3)

**Comment by SolomonHD** [comment]
So I've dug through the logs again and I see the errors occurring on the apache side of fedora.

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/fc34a654-15f5-43f0-8d19-00c3a01eee59)

This appears to be another proxy timeout issue. I'll need to experiment with the settings again

**Comment by eporter23** [comment]
@SolomonHD the book object ingested into test successfully (~14 hours). Can you add notes to this ticket about what changes you applied to the test environment and then we can discuss options about putting this into production?

**Comment by eporter23** [comment]
Standup notes: after documenting the changes to the test environment in this ticket we'll coordinate how to add it to production.

**Comment by lovinscari** [comment]
Solomon was supposed to update this ticket with the changes he made but this does not appear to have been completed as of yet.

**Comment by eporter23** [comment]
This was implemented in production on 9/11 and several large jobs have been run including a book ingest - no Fedora 502 errors occurred, and performance has been improved.

**Comment by lovinscari** [comment]
Event worker changed - Apache worker type changed to events
