### ISSUE TITLE
Document changes implemented for Source and Deposit Collections 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1421]
Document a summary of changes implemented for the epic for reference purposes.

The changes in behavior should also be incorporated into Curate training material.

**Comment by bwatson78** [comment]
@eporter23 Is it safe to say, at this moment, that all fundamental changes to Curate pertaining to the Source/Deposit Collection epic are in the status of "To Deploy - Arch/Test" or deeper? I ask this to make a determination of whether this document is "done" or not.

**Comment by eporter23** [comment]
@bwatson78 I think there is still one open ticket regarding updating the Curate Collection facet, but yes, it looks like everything else is well underway or complete.

**Comment by lovinscari** [comment]
@bwatson78 is waiting on the last ticket to complete to incorporate all changes into the document. @rotated8 needs to provide feedback on if this should be a Confluence page.

**Comment by lovinscari** [comment]
Waiting on work to be completed by ticket referenced in blocked.

**Comment by lovinscari** [comment]
Should be able to complete the work today but monitor review, merge, etc.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1500

**Comment by eporter23** [comment]
Great docs, thanks!
