### ISSUE TITLE
Update all works in Curate-test to add source_collection_id

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1422]
- [x] Langmuir
- - [x] batch 5
- - [x] batch 1 (segment which was already loaded prior to Sept)
- - [x] batch 4 (missing segment)
- [x] Asian Artifacts
- [x] Medical Artifacts
- [ ] Yearbooks
- [ ] Yellowbacks

**Comment by lovinscari** [comment]
Move to next sprint.
