### ISSUE TITLE
Update all works in production to add source_collection_id

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1423]
- [x] Langmuir
- - [x] Batch 1
- - [x] Batch 2
- - [x] Batch 3
- - [x] Batch 4
- - [x] Batch 5
- [x] Asian Artifacts
- [x] Medical Artifacts
- [x] Yellowbacks
- - [x] lsdi
- [x] Yearbooks
- - [x] Kirtas batches
- - [x] LIMB batches

**Comment by lovinscari** [comment]
Move to next sprint.
