### ISSUE TITLE
Curate-test: Errno::ENOSPC: No space left on device - sendfile

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1430]
When trying to run a metadata update in curate-test last night, the job failed with the following error:

`Errno::ENOSPC: No space left on device - sendfile`

![Screen Shot 2020-08-21 at 8.17.58 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d29b2fde-ffa5-4656-8219-fe634821370f)

**Comment by SolomonHD** [comment]
/opt/curate/cache/hyrax/uploaded_file/{preservation_master_file,intermediate_file}
