### ISSUE TITLE
Update rake task documentation for recent changes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1435]
- [ ] Manifest regeneration
- [ ] Counts by Collection report
- [ ] Others?

**Comment by bwatson78** [comment]
@devanshu-m I was just checking the changes for manifest generation and, as far as I can tell, removing all of the manifests from the command line is still a necessity when processing all Works' manifests. Am I assuming correctly? If so, the process described in the tutorial is the same.

**Comment by bwatson78** [comment]
@eporter23 Pending @devanshu-m response to the question above, nothing about the tasks themselves have changed. I have changed some descriptions because they are misleading or needed to be expounded upon. A new PR will be available soon.

**Comment by bwatson78** [comment]
New PR made: https://github.com/emory-libraries/dlp-curate/pull/1491

**Comment by eporter23** [comment]
@bwatson78 sounds good, thanks for the updates.

**Comment by devanshu-m** [comment]
@bwatson78 yes, deleting manifests when regenerating for all works is still a necessity.

**Comment by bwatson78** [comment]
That PR was merged and deployed into test/arch.
