### ISSUE TITLE
Update collection counts rake task to use source_collection_id

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1436]

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1467
No screenshots necessary.

**Comment by eporter23** [comment]
@bwatson78 after the two runs of this today I think it looks solid. There are still some discrepancies with the Yearbook file counts in test for some reason, but that may just be an indexing lag. Should be good to go for prod.

**Comment by eporter23** [comment]
Report looks good - we've added all the source collection IDs to works in production now, and I compared the latest run of the report against a prior one and the counts are highly consistent for collections that we haven't been adding new works to. Thanks @bwatson78 !
