### ISSUE TITLE
Add new user accounts to Curate for testing and monitoring

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1443]
**1. Add the LTDS Core Systems test user account to Curate (Viewer-level):**
Contact Emily or Alex C for credentials. 
This user will not be at the Admin level.
Please assign the user to the following groups:

- [x] rose_viewer
- [x] oxford_viewer
- [x] health_sciences_viewer

**2. Add Thousand Eyes User (Admin level)**
Collin can provide the user credential
- [ ] Add an account for Thousand Eyes  for monitoring
- [x] Thousand Eyes user should be granted Admin group access

**Comment by devanshu-m** [comment]
PR: https://github.com/emory-libraries/cor-cm/pull/23

**Comment by eporter23** [comment]
@rotated8 can you test the user credential you requested?
