### ISSUE TITLE
Add deduplication_key and Curate ID to search results snippet

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1444]
When previewing search results, it would be helpful to add the following fields to the results snippet for works:

- [x] deduplication_key
- Display label: Deduplication Key

- [x] id
- Display label: ID

Desired output:

![Screen Shot 2020-09-18 at 11.40.28 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/67df3410-6674-4275-8e36-28e112b4bc3d)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1541

![Screen Shot 2020-10-15 at 2.21.26 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/09069a85-629b-4639-941f-e0c60d762c15)

**Comment by eporter23** [comment]
looks good!
