### ISSUE TITLE
Revisions to manifest regeneration triggers

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1452]
Following changes to the manifest regeneration process in ticket #1394, there are a few scenarios that still need to trigger the regeneration process:

- [ ] Changes to a work's visibility
-- If a user manually edits a work and changes the Visibility, especially for a work being set to Private (or vice versa), the manifest needs to be regenerated
-- If a bulk update to works changes their Visibility, this should also regenerate affected manifests

**Comment by eporter23** [comment]
@devanshu-m I'm not sure if we discussed already how bulk-updates to metadata from the CSV process impact the new manifest generation? If that is not already accounted for, should I create another ticket for that?

**Comment by devanshu-m** [comment]
@eporter23 each work save triggers manifest cache key generation and indexes in solr.

**Comment by devanshu-m** [comment]
@eporter23 is this ready to be brought in progress?

**Comment by eporter23** [comment]
@devanshu-m looks good! I successfully tested this a few times by changing the visibility on a couple of works from public to private and then back to public again and the manifest updated accordingly.
