### ISSUE TITLE
Ensure that multiple Deposit Collection ids and titles can be assigned to a Source Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1456]
In testing the collection-level relationships between a Source and its Deposit Collection(s), I am able to assign multiple Deposit Collections to a Source collection in the UI, but it appears that the title is only stored for the first one.

I assigned two Deposit Collections to the Langmuir source collection curate-test using the Edit Collection form:

![Screen Shot 2020-08-27 at 8.12.02 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d3fdd3f5-d40c-4a6d-be01-dcba6852792c)

In SOLR, I see 2 ids assigned:

![Screen Shot 2020-08-27 at 8.07.40 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/769bdbfb-cf0b-4ddf-91bb-fe4ded21ac3f)

Only one title has been stored:

![Screen Shot 2020-08-27 at 8.07.45 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f2ada3d3-f197-4d33-857c-21d7f048f842)

**Comment by eporter23** [comment]
@bwatson78 @alexBLR FYI, I wrote up this as a new ticket after testing so as not to hold up any deploys, etc.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1463
![Screen Shot 2020-08-27 at 1.22.43 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/8c978158-2515-4f3b-95b2-0a80930999bf)
![Screen Shot 2020-08-27 at 1.23.28 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/312b6ef6-3cd2-44fc-a067-ef333ab02d37)

**Comment by eporter23** [comment]
I tested this again and can see multiple deposit ids and their titles now in SOLR. Thanks! 

![Screen Shot 2020-08-27 at 4.09.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/101ccbff-cc83-4e4c-a98b-fd22512d21d2)

**Comment by eporter23** [comment]
Tested in Curate prod using a new Library Collection type instance called Regression Test Collection, and creating 2 new Deposit Collection type instances and assigning them to the Regression Test Collection.
