### ISSUE TITLE
Library Collection Type shows twice in Collection Type filter

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1458]
In Curate, when viewing the Collections > Dashboard > All Collections tab, there is a filter for Collection Type.

In Curate test we have Library Collection and Deposit Collection types defined. The filter shows two different instances and counts for Library Collection, however:

![Screen Shot 2020-08-27 at 8.40.03 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9b62e441-3f0a-4d9c-9c78-13d95aa4fc0e)

The same behavior occurs in Curate production:

![Screen Shot 2020-08-27 at 8.42.54 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0317d1ed-d240-4484-9783-63f6018d5c0b)

**Comment by bwatson78** [comment]
@eporter23 Is this a new behavior? Did this pop up after a deploy?

**Comment by eporter23** [comment]
@bwatson78 unfortunately, I'm not sure when this occurred. I noticed it recently while testing various Source + Deposit collections work. It's not a filter I use very often.

**Comment by bwatson78** [comment]
@eporter23 I've been searching for a while for what's creating this behavior and so far I haven't found any code we've touched that makes this happen. This may be Hyrax-specific processing that, for some reason, doesn't combine together the `current_user`'s Collections with all Collections when on All Collections view. I'm still on the hunt and will confirm that.

**Comment by bwatson78** [comment]
@eporter23 I've confirmed that this is the out-of-the-box Hyrax behavior. It pulls its facets from the Solr Response with a search clause that slices away any of the current user's Collections into separate facets grouped by type. It seems that altering the way it does this would affect the "My"/"All" Tabs functionality. In other words, every time that page is loaded, the Solr Response would deliver the facet objects in the same way, no matter if the page requested just the user's Collections or All Collections. 

With that in hand, is it worth it to go forward with changing this behavior?

**Comment by eporter23** [comment]
@bwatson78 If this is a Hyrax behavior (bug IMO!) then I don't think it's worth us trying to fix it locally. Thanks for digging into this! I may make a note of it to report back to Hyrax later.
