### ISSUE TITLE
Display source and deposit collections in Dashboard > Works listing

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1479]
See [wireframe item 3](https://docs.google.com/drawings/d/16I0cKv7kwZ7OeDWW6KW_xlnx2-3MYBJ3D1vrAccD0gU/edit).

When browsing works in the dashboard, the item listing should show a source collection and a deposit collection if they are distinct for a given work.

**Comment by eporter23** [comment]
Discussed an alternative layout with @bwatson78 which is simpler to output:

![Screen Shot 2020-09-15 at 1.55.20 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f3ac1461-71c5-4f2a-9447-68acbd1f439b)

**Comment by lovinscari** [comment]
Devanshu will look at this after sprint review.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1500

**Comment by eporter23** [comment]
Looks good in test!

![Screen Shot 2020-10-02 at 9.46.22 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/4de3eae5-4e7b-4b20-86cf-c88cb3aa26fd)

**Comment by eporter23** [comment]
Works in prod as well, thanks.
