### ISSUE TITLE
Dashboard > Works display bug when applying filters

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1480]
As of v1.0.7, when applying any dashboard filter from View Works (All Works and My Works), the layout becomes distorted and/or some filter options move or disappear. This does not appear to be due to the browser width, it occurs even when maximized on a very large screen. The layout resets correctly when a filter is applied.

![Screen Shot 2020-09-10 at 10.13.16 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e391c8f4-ef42-4b6a-a2f5-c8c8242a2635)

![Screen Shot 2020-09-10 at 10.16.12 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/62b8d2e3-dea8-4b99-96b3-f4f74fa08908)

**Comment by bwatson78** [comment]
@eporter23 Cannot reproduce this behavior in a Chromium-based browser (using Brave, currently). Trying out Safari now.

**Comment by bwatson78** [comment]
@eporter23 Safari not exhibiting the behavior, either. Can you try to reproduce the formatting issues from your side again?

**Comment by eporter23** [comment]
@bwatson78 I'm no longer seeing this either, in Safari, Chrome, or Firefox. I'll go ahead and close this.
