### ISSUE TITLE
Automate deletion of selected files from AWS

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1492]
This ticket follows documentation work completed in #1396, which is also documented in [OneDrive](https://emory-my.sharepoint.com/:w:/g/personal/rmetz_emory_edu/EWxht5TvsyxImvFMHbWVEj4BtqyMv9i2P7171RBNOkR1rA?email=eporter%40emory.edu&e=dFqlXe).

The goal of this ticket is to automate periodic deletion of selected files from our AWS environments. This does not include S3 content storage which is always retained.

- [x] **Curate application temporary upload spaces**
Locations:` /opt/curate/upload/hyrax/uploaded_file/{preservation_master_file,intermediate_file} `
`/opt/dlp-curate/current/tmp/csv_uploads_cache `
Delete: monthly
Note: delete only files that are _older_ than one month

- [ ] **AWS/Cor backup files** (files needed for preservation backup and restoration: databases, Fedora, SOLR, Redis)
Delete: every 6 months
Note: retain most recent 6 months worth of backups

- [x] **Log files**
Delete: every 6 months
Note: retain most recent 6 months worth of backups

**Comment by SolomonHD** [comment]
- I've created a new role that will clean the old temporary files and I've set the age to 30 days as this ticket specifies. New role is [here](https://github.com/emory-libraries/emorylib_clean_subdirectories)

- Adjusted the retention period of all Cloudwatch Logs to 6 months, from indefinite
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/101ad5c5-0309-4584-b826-8b472b193b06).

I wasn't able to control the vpc flow logs group, I'll email PP about it, it's large, 120GBs.

**Comment by eporter23** [comment]
@SolomonHD I appreciate you finding time to work on this! For the temporary files, I understand what you're saying about a week vs. 30 days, but it's also possible that we may need access to those temp files longer than a week. @rotated8 or @devanshu-m do you happen to know, if we need to regenerate a thumbnail using the fileset cleanup task, if that is occurring through fetching the file from S3 or from the file in the temp upload space? If it's from the temp space, we don't always have time to fix broken thumbnails within a week of an ingest.
