### ISSUE TITLE
Omit Preservation event and workflow arrays from the main metadata display on work pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1501]
Since we are now displaying this information elsewhere on the View Work and View Work Events pages, we can remove these from display in the regular metadata section.

Current output

![Screen Shot 2020-09-18 at 11.47.07 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e6de0c66-a119-4978-9816-d0743e95c88b)

Desired output
![Screen Shot 2020-09-18 at 11.48.55 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7fd6b293-7cac-463b-9763-1679e8fca628)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1552

![Screen Shot 2020-10-28 at 8.41.20 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/70b94bd1-d9b5-4a5d-96c8-0fad2cdcf047)

**Comment by kmichaelis** [comment]
@bwatson78 looks good!

**Comment by eporter23** [comment]
Looks great.
