### ISSUE TITLE
Show actual visibility value in badges for works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1502]
In 2019 while working with DCE, some Curate display behavior around visibility badges was changed to show the Private badge for non-Public works as a level of protection before we had access controls implemented. The end result was that the majority of works in Curate show the red Private badge in most areas of the UI, and this is not consistent with the actual Visibility settings assigned to the work; this is confusing to users.

Example of an object with Emory Low Download visibility assigned - displays with Private badge:

![Screen Shot 2020-09-18 at 1.35.26 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b3777513-bf5e-4b70-a51f-c15f104163b9)

Same object: metadata display of Visibility

![Screen Shot 2020-09-18 at 1.28.37 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/78333dae-32c2-48f5-9fd5-c637630f7dd4)

Visibility filter - shows actual values and colors used in Work form

![Screen Shot 2020-09-18 at 1.26.24 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/46a00581-9d4d-4f8d-9518-b02882ed5bf4)

The desired display would be to show the actual Visibility value in the colored badge (as shown in the Edit work sidebar and in the Visibility filter shown above):

![Screen Shot 2020-09-18 at 1.40.27 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/badcb548-317c-412a-86f9-4f59ec9280ec)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1543

![Screen Shot 2020-10-16 at 3.18.43 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1d56e346-0e59-4563-aa01-64a02c0aa562)

**Comment by eporter23** [comment]
@bwatson78 this is great.
