### ISSUE TITLE
Suppress Add to Collection button on view work pages for non-Admin users

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1504]
The Add to Collection button is prominent on View Work pages and can be accessed by those who have edit permission to a work and can be triggered while simply viewing a work (outside the Edit form). We should suppress this from display to reduce accidental moving of works between collections and to reduce collections membership changes on large collections. 

![Screen Shot 2020-09-21 at 8.51.44 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1d96034d-bb20-49ea-bd18-b2c0fbd2b333)

**Comment by bwatson78** [comment]
@eporter23 requested that this be commented out so that it could be added back in easily.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1514

![Screen Shot 2020-09-24 at 11.11.34 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/263d3706-85f5-4474-94ab-a2a65875c364)

**Comment by eporter23** [comment]
Tested successfully with

- Viewer-level user
- Manager-level user

**Comment by eporter23** [comment]
Tested with a viewer-only and manager permissions in prod. Looks good!
