### ISSUE TITLE
Document/confirm documentation of fields that are searchable in Curate and in Lux

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1506]
The original Curate metadata implementation sheet includes the original indexing implemented for Curate, where "Indexed" was intended to indicate that a field was searchable ([see column Q](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&range=Q:Q)). We have since expanded that to index other fields for display purposes.

To confirm:
- Which fields are currently searchable in Curate's main searchbox?
- Which fields are currently searchable in Lux?
- Were changes made to which fields were searchable when Lux was developed? If so, we need to update the original metadata implementation documentation to reflect this in order to include this in training materials.
- Does Curate's main search support any operators [such as noted for Lux](https://wiki.service.emory.edu/display/DLPP/Emory+Digital+Collections+User+Guide)?

To populate:

- [x] Column [AN - Curate](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&range=AN:AN) 

- [x] Column [AO - Lux](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&range=AO:AO)

**Comment by bwatson78** [comment]
@eporter23 The fields have been confirmed and updated for both environments in the document you linked.

Search Operators:
What I've learned (after direction from @rotated8) is that Blacklight passes the query string entered into the search bar directly to Solr, so any Solr query convention should work. I have confirmed by a cursory google search that the full battery of Solr search operators are in effect. Below are the sites reinforcing this:

https://support.blackbagtech.com/hc/en-us/articles/360026483651-Query-Tips-for-BlackLight-s-Index
https://digitalforensiccommunity.com/searching-tips-and-tricks-in-blacklight/

Both of these sites are using nearly the same vernacular, which leads me to believe that they are taking Solr query documentation and pasting it in. Also, searching on how to customize Blacklight search operators has returned no fruit.

**Comment by eporter23** [comment]
@bwatson78 those links are a goldmine, thanks. Before we close this out, are Collection-level fields following the same pattern as their work-level equivalents? I assume so but wanted to check, and I noted you'd added finding_aid_link which is at the Collection level only.

**Comment by bwatson78** [comment]
Yes, they are.
