### ISSUE TITLE
Suppress the "Feature" button on View Work page (breaks the homepage view)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1515]
The _Feature_ button shown appears on the View Work page for works whose Visibility is set to Public. This button should be suppressed for all users. 

When this button is clicked a work becomes activated as a featured work, which triggers a related bug (#605) where the homepage view breaks with a generic application error. 

![Feature Work button 2020-09-26 at 11.50.55 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/39efea2d-d05e-4af7-aa7f-36393840e857)

**Comment by eporter23** [comment]
@wulman16 with the recent ticket @bwatson78 worked on (#1504) on suppressing the Add to Collection button on View Work pages it looks like the adjacent Feature button isn't displaying in test anymore for viewer-level and manager-level users, so might be worth checking to see if this work is still needed?

**Comment by eporter23** [comment]
^ on second thought, that Feature button might only show up to the depositing user "owner" of the work, so that may be why I am not seeing it while logged in as the test user (which hasn't actually deposited anything yet). So, this ticket is probably still needed.

**Comment by wulman16** [comment]
@eporter23 It looks like the code for the feature button is still there, so I will go ahead and remove it.

**Comment by eporter23** [comment]
@wulman16 works, great, thanks - I tested this logged in as admin and also as a manager level user.

**Comment by eporter23** [comment]
looks good! thanks @wulman16
