### ISSUE TITLE
AWS impact analysis testing 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#152]

**Comment by tmiles2** [comment]
Once we are ready to start this process, I'll look at scheduling our ART review. I'm going to close out the initiate ART issue #47

**Comment by eporter23** [comment]
@tmiles2 do you remember what this ticket was for?

**Comment by tmiles2** [comment]
@eporter23 I think this issue was drafted back when we first met with the AWS@Emory team. They suggested testing, I don't think this issues is no longer needed but we can confirm with Solomon.
