### ISSUE TITLE
High rate of filesets displaying as "not characterized"/not indexed

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1526]
In testing 

We are recently seeing at least 50% of filesets showing up as "Not characterized", which is unusually high, especially for manually uploaded filesets. Writing this up as a separate bug ticket in case this is an unrelated issue.

Additional info: a SOLR query of filesets without sha1_tesim populated returned ~3000 filesets, most of which appear to have been created in the past month or so. These were reindexed on 10/6/20.

Book pages import: 4/8
https://curate-test.library.emory.edu/concern/curate_generic_works/402q573ngz-cor?locale=en

Manually uploaded filesets: 3/3
https://curate-test.library.emory.edu/concern/curate_generic_works/8708w9gj84-cor?locale=en

I reviewed most of them in Fedora and they do show characterization data there, so it appears to be a matter of indexing.

While these can be corrected manually one by one, it is time consuming on large batches and the rate of this occurring has increased significantly.  

![Screen Shot 2020-10-02 at 4.17.29 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/40999087-01ed-41fe-b61b-0cdcce52d01c)

**Comment by devanshu-m** [comment]
@eporter23 I don't think this issue is related to recent changes in 1.2.0. Also, lately we haven't changed anything about how files are attached. We did change the way characterization happens via the re-characterize button, but I am not sure if these things are related. The way I understand that button process is that it clears all characterization data and rewrites it. Could this be related? @bwatson78  

I did go through a few filesets that have this issue, but I am also seeing a successful characterization event for the same. Can we confirm if characterization data is present in fedora or not?

**Comment by devanshu-m** [comment]
After looking at the changes for the characterization button, I can confirm that the clearing of data only happens when the button is clicked, and not otherwise.

Also, did we test this after we upgraded hyrax3 to rc1?

**Comment by eporter23** [comment]
@devanshu-m I spot checked about 5 of the filesets I created today via form and via import. They all **do** show characterization in Fedora.

**Comment by devanshu-m** [comment]
@eporter23 oh, ok. Sorry I looked at 2 examples and didn't see characterization data in fedora so I assumed it doesn't show for all. If the data shows in fedora, then we should check how we are displaying this data on the fileset show page, is it using solr or directly pulling in from fedora?

**Comment by eporter23** [comment]
Another comment: we frequently see high rates of thumbnails missing, but usually filesets show their characterization data right after ingest. I've been fixing a lot of missing filesets from the Langmuir final batch, but most of those show their characterization data on the view fileset page.

**Comment by eporter23** [comment]
@devanshu-m can you let me know which ones you saw that didn't have characterization in Fedora?

**Comment by devanshu-m** [comment]
@eporter23 Understood. Do we want to continue ingesting in prod and see if the issue still persists?

I was looking at the following example which is open in my window right now: http://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/76/12/ng/f2/7612ngf254-cor/files/a4a98aa4-4beb-4598-a43b-0546941d2d6a/fcr:metadata

PMF for fileset `7612ngf254-cor`

**Comment by eporter23** [comment]
Update on this: after manually creating a number of filesets today which had missing files, 100% of the ones I uploaded did not show a thumbnail or characterization, and I have had to run the regenerate derivative process on each Fileset multiple times.

**Comment by eporter23** [comment]
This issue may have some improvements in Hyrax 3.3. 50/50 filesets checked have characterization and only 1/50 is missing a thumbnail.

**Comment by eporter23** [comment]
Closing this since bulk imports are showing great improvement. This problem still recurs frequently on manually uploaded filesets, however which I will write up as a separate issue.
