### ISSUE TITLE
Many files failing fixity check during scheduled automated checking

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1527]
We began running the scheduled fixity checking on 10/3 (UTC). It has been running over for several days and there are at least 9,999 dead jobs in sidekiq (is this the maximum count it will display)?

Kathryn has received over 4,000 notification failures in Curate and I have received ~300.

To confirm:
Re-check selected files once the sidekiq process is finished - did we set a check on how soon a fixity check can be run in the UI after the last check?
what is the difference between the dead jobs in sidekiq and the counts we are seeing in Curate?

Breakout meeting notes (Emily, Collin, Devanshu, Kathryn)

- We think the failures are due to some kind of transaction threshold with S3; the errors SE are seeing are very generic
- EP has been manually checking files using Fedora's UI (fixity check button) and downloading and running a shasum check
- We will reduce the Curate UI button timeframe down from 7 days to 24 hours between checks to assist with testing
- We will try adding a delay between requests while the job is running, so that it does not overload any S3 request threshold
- We will try running increasing sizes of checks in curate-test (100, 500, etc)
- We will try adding environment-specific checks in the rake task so that we can run the cron job at different intervals for test vs. prod

**Comment by eporter23** [comment]
@devanshu-m @kmichaelis @rotated8 I posted some discussion notes to the ticket description above, please edit/refine as needed.

**Comment by rotated8** [comment]
Adding delay into the job did not stop the errors. Our next step with this ticket is to limit the number of workers available to work on Fixity jobs, so that only one job runs at a time. In service of that, Sidekiq provides this documentation: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues

**Comment by eporter23** [comment]
We now completed running a large-scale fixity check in production (took ~5-6 days to complete). There were 29 sidekiq failures and 4 Curate notifications of failures, all suspected to be due to incomplete file ingests. Thanks @devanshu-m !
