### ISSUE TITLE
Langmuir source collection count anomalies

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1529]
In Curate production, the test user, when assigned to the rose_viewer group only sees 12,648 out of 12,664 works.
The viewer permission level should permit seeing all works assigned to a given collection, and the same group permissions are assigned to both the source and deposit collections in production.

I also added the test user to repository_manager, rose_manager groups but the test user still can't see all the Langmuir works. 

![Screen Shot 2020-10-05 at 3.05.07 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0e9c3c49-2ea5-470e-bbfd-1e379abd48bb)

Admin user sees 12,663 (1 work missing)
![Screen Shot 2020-10-05 at 3.05.01 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/876651d0-a858-4af1-a032-f55e53dcd9ea)

Admin user sees 12,664 works in the Works filter drop down
![Screen Shot 2020-10-06 at 8.59.38 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7b1e88bf-a6fb-4cd6-ae94-49d52048fd2f)

Admin user facet count: 12,664
![Screen Shot 2020-10-06 at 9.00.09 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b5066968-fda6-4652-84da-366956b55da7)

Test user facet count: 12,648

![Screen Shot 2020-10-06 at 9.00.54 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/285d5683-9a6e-47f1-a195-d9492ee9f7b8)

**Comment by bwatson78** [comment]
@eporter23 Would you happen to know which 16 Works are not being shown? Just one would help me out

**Comment by eporter23** [comment]
@bwatson78 unfortunately that is part of the challenge, but I'll see if I can find a couple - will be a manual/random process.

**Comment by bwatson78** [comment]
@eporter23 I'm in the middle of it--just wondering if you had verified what works were missing. Since I'm already sifting, please don't worry about tracking one down.

**Comment by eporter23** [comment]
@bwatson78 I think I found one: https://curate.library.emory.edu/concern/curate_generic_works/723hx3ffqn-cor?locale=en (shows up as an Admin, but not when I'm a non-Admin).

My method for doing this was running a facet search on Langmuir, sorting by date uploaded descending, and then looking at the works in sets of 10. If the first/last didn't match up between both users it was easier to pin down where a gap was.

**Comment by bwatson78** [comment]
Perfect, thank you.

**Comment by eporter23** [comment]
from @bwatson78  works_without_viewer_groups = [
    "423612jmds-cor",
    "689d51c5j3-cor",
    "740ksn032g-cor",
    "576rxwdc02-cor",
    "26663xsjb6-cor",
    "211kh189dj-cor",
    "433dz08m0v-cor",
    "692t4b8h14-cor",
    "0859cnp5qw-cor",
    "392g79cnvq-cor",
    "460qrfj6vw-cor",
    "808v9s4n2r-cor",
    "064tht76q8-cor",
    "7203xsj41m-cor",
    "723hx3ffqn-cor",
    "709w0vt4jz-cor"
]

**Comment by bwatson78** [comment]
@eporter23 I have assigned:
`["repository_manager", "rose_manager", "admin"]` 
to all of the works listed above for `edit_groups`.

I just checked the counts and they match. 

Just to note here, I asked you on Slack whether you wanted me to update the FileSets associated to the works listed above and you stated that you would go back in to edit works and that would, most likely, tie the permissions to the associated file sets as well. 

If any of that is incorrect, please comment here and I will update. Otherwise, is there anything else I need to do to fulfill the ticket requirements?

**Comment by eporter23** [comment]
Thanks @bwatson78 : to confirm, I will go update the works manually in Curate to check the fileset permissions.
