### ISSUE TITLE
Run collection counts rake task in production

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1532]
After loading the Langmuir collection final batch, the 10/2 run of the collection count rake task revealed that about 500 files were missing from the count.

As a next step, I reindexed recent filesets in hopes that this may bring the count up.

In order to test again, I need to get an updated run of the collection counts rake task for all collections.

**Comment by bwatson78** [comment]
@eporter23 New file delivered via Slack.
