### ISSUE TITLE
Show exact Visibility in badges displayed in dashboard lists of works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1545]
Following work done in #1502, adjust the current Public/Private-only badge behaviors to show the exact visibility assigned to a work.

My works page
All Works (or Managed Works for non-admins)
Dashboard > Collection view page list of works

![Screen Shot 2020-10-16 at 4.36.19 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/da35a7af-fa57-4dfd-a802-253e11aa9175)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1549

No screenshot necessary.

**Comment by kmichaelis** [comment]
@bwatson78 looks good, thanks!

**Comment by eporter23** [comment]
Excellent, thank you!
