### ISSUE TITLE
Don't hard-code software versions in preservation events

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1548]
Goal: detect and use the currently installed version so that we aren't recorded an older version of the software that performed the action.

For example, if our version of FITS is upgraded, we should record the version in use at Emory when creating a Characterization event.  

Update 11/7/23: we are getting ready to patch our Fedora instances from 4.7.5 to 4.7.6 to address a CVE. I have already run several fixity checks as part of the testing process, but these are being recorded as 4.7.5.

**Comment by bwatson78** [comment]
I have found evidence that querying a Fedora instance for its version is a brand new feature for v6.4 (see [here](https://fedora-repository.atlassian.net/browse/FCREPO-3890)). I have gone through the EC2 container for the Fedora Test instance and have found no reference to the current version in just the file names. I have a meeting tentatively scheduled with Beth at 4pm EST to discuss if she found any obvious ways to see the current Fedora version during the recent upgrade.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/2229
