### ISSUE TITLE
Works missing group permissions

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1550]
While investigating a work n Langmuir that was not showing up in the total count, I checked SOLR for works that had no edit access or read access groups assigned. The following two works were deposited into collections, but for some reason have no read_access_group_ssim or read_access_group_ssim assignments:

- [x] 969866t1pr-cor
deduplication_key:OXKOBE_025
Should have the following:

- oxford_viewer
- oxford_depositor
- oxford_manager
- admin
- repository_manager

- [x] 4881jwsv22-cor
deduplication_key:11743500
should have the following:

- rose_viewer
- rose_depositor
- rose_manager
- admin
- repository_manager

**Comment by bwatson78** [comment]
969866t1pr-cor's read groups contained "public", so I maintained that.![Screen Shot 2020-10-26 at 6.42.05 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/15ae5b41-43e6-43a3-84ad-7907433a25a0)

**Comment by bwatson78** [comment]
4881jwsv22-cor's read groups were empty (visibility restricted) so the following groups were applied:
<img width="452" alt="Screen Shot 2020-10-26 at 6 52 02 AM" src="https://user-images.githubusercontent.com/18330149/97164048-f1210a00-1757-11eb-8b06-fe1ebecb6940.png">

**Comment by eporter23** [comment]
Looks good, thanks!
