### ISSUE TITLE
Curate user accounts - additions and removals

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1551]
There have been some staffing transitions and the Curate user accounts and groups need to be updated.

For the groups mentioned here, I am listing the entirety of the group membership instead of add to and remove from, etc.

**Create new user accounts** (group assignments noted below):
- [x] kfish26
- [x] bwason
- [x] amcshan
- [x] bamicha
- [x] Anicka Austin (aaust29)
- [x] Tierra Thomas (tthom70)
- [x] Nick Twemlow (ntwemlo)
- [x] Vivek Patel (vpate68)

**Delete user accounts** (no longer at Emory/DCE/etc.)
- [x] BEDWA24
- [x] DWAUGH
- [x] AVANNUC
- [x] pmcdani
- [x] jlittl6
- [x] wulman

**Create new Pitts Theology Library groups:**
- [x] pitts_manager
- [x] pitts_depositor
- [x] pitts_viewer

**pitts_manager** group members should be:
- [x] bwason
- [x] amcshan
- [x] bamicha

**pitts_depositor** and **pitts_viewer** group members should be:
- [x] tezprox

**Update rose_manager group** - members should be:
- [x] Elizabeth Roke (ERUSSEY)
- [x] kfish26

**Update rose_viewer group** - members should be:
- [x] John Bence (JBENCE)
- [x] Sarah Quigley (SQUIGLE)
- [x] Carrie Hintz (CHINTZ2)
- [x] Laura Starratt (LSTARRA)
- [x] Beth Shoemaker (ESHOEM2)
- [x] Courtney Chartier (CCHARTI)
- [x] Kyle Fenton (JFENTON)
- [x] Gabrielle Dudley (GDUDLEY)
- [x] Lolita Rowe (LROWE8)
- [x] Jackie Reed (JREED30)
- [x] Kathy Shoemaker (LIBEKK)
- [x] Randy Gue (WGUE)
- [x] Jennifer Gunter King (JGKING3)
- [x] Karen Chason (KCHASON)
- [x] Jody Bailey
- [x] Melanie Kowalski
- [x] Anicka Austin (aaust29)
- [x] Tierra Thomas (tthom70)
- [x] Nick Twemlow (ntwemlo)
- [x] Vivek Patel (vpate68)

**Update rose_depositor group** - members should be:
- [x] Nina Rao (NRAOGRA)
- [x] Kyle Fenton (JFENTON)
- [x] Brian Methot (BMETHOT)
- [x] Paige Knight (PRKNIGH)

**Comment by eporter23** [comment]
Moving this to blocked because additional changes have since been requested, and the list needs to be updated.

**Comment by eporter23** [comment]
Updated list provided by Rose on 12/18/20.

**Comment by SolomonHD** [comment]
The updated lists should be on all of the curates now.
