### ISSUE TITLE
File transfer: Atlanta Real Estate Maps (DAMS/Isilon) to EFS mount

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1554]
Please transfer the following files from Isilon to our AWS EFS mount, using Rclone with either MD5 or SHA1 to perform fixity checking during transfer.

**Base path where files are located (Libraries Isilon "dmfiles" directory root):**

- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP1/F019
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP2/F005
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP5
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/XOP1

**Specific list of files or directories to be copied**

- All TIFF files in the above folders

**Desired destination directory structure in EFS**

- /mnt/efs/Collections/dmfiles/ + relative directory structure from original Isilon location, e.g.:
/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP1/F019
/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP2/F005
/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/OP5
/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0572_Atlanta_Misc/XOP1

**Estimated count of files to transfer**

- 128 + (TIFF files)
- Note: there may be more files in the folders we are transferring, but there should be at least 128 (identified for ingest) 

**Estimated size of files to transfer**

- Approximately 34.5 GB

**Comment by mprefer** [comment]
32.315 Gig of file data transferred.

**Comment by eporter23** [comment]
Folders and files look good in EFS, thanks!
