### ISSUE TITLE
Transfer files for Gregory and Avant collections (Rose Instructional Materials)

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1559]
Please transfer the following files from Isilon to our AWS EFS mount, using Rclone with either MD5 or SHA1 to perform fixity checking during transfer.

**Base path where files are located (Libraries Isilon "dmfiles" directory root):**

- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0624_GregoryFamily/B044/F009
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0624_GregoryFamily/B044/F010
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0887_Avant/B001/F001
- nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0887_Avant/B001/F010

**Specific list of files or directories to be copied**

- All TIFF files in the above folders

**Desired destination directory structure in EFS**

/mnt/efs/Collections/dmfiles/ + relative directory structure from original Isilon location, e.g.:

- /mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0624_GregoryFamily/B044/F009
- /mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0624_GregoryFamily/B044/F010
- /mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0887_Avant/B001/F001
- /mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0887_Avant/B001/F010

**Estimated count of files to transfer**

- 120 + (TIFF files)
- Note: there may be more files in the folders we are transferring, but there should be at least 120 (identified for ingest)

**Estimated size of files to transfer**

- Approximately 11.5 GB

**Comment by mprefer** [comment]
Confirmed there are 120 files at ~ 11.5 Gig.
Copying to commence shortly.

**Comment by mprefer** [comment]
All files copied/updated from directory lists above.

**Comment by eporter23** [comment]
Thanks @mprefer! I spot checked them on the EFS mount. Will move this into To Accept in case @kmichaelis wants to review.

**Comment by kmichaelis** [comment]
Thanks @mprefer ! Closing this.
