### ISSUE TITLE
DAMS preprocessor outputs "creators" column heading instead of "creator" 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1560]
There was an error in my [DAMS to Curate mapping worksheet](https://docs.google.com/spreadsheets/d/1Mv78t-1HJNPFgBgN6eGt_sM0iumuBkFAFkRP7YhD1Dk/edit#gid=811514181) that showed "creators" as the Curate field name, which I have just corrected based [on this reference](https://curate.library.emory.edu/importer_documentation/guide); this causes the creator information to get missed by the importer because of the "s" on the end. 

https://github.com/emory-libraries/dlp-curate/blob/main/app/importers/dams_preprocessor.rb

**Comment by bwatson78** [comment]
This should be fixed in PR #2004.
