### ISSUE TITLE
Transfer files for Lucille Clifton Papers (Rose Instructional Materials)

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1563]
Please transfer the following files from Isilon to our AWS EFS mount, using Rclone with either MD5 or SHA1 to perform fixity checking during transfer.

Base path where files are located (Libraries Isilon "dmfiles" directory root):

nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_1054_Clifton/B029/F012

Specific list of files or directories to be copied:

All TIFF files in the above folders

Desired destination directory structure in EFS:

/mnt/efs/Collections/dmfiles/ + relative directory structure from original Isilon location, e.g.:

/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_1054_Clifton/B029/F012

Estimated count of files to transfer

222 + (TIFF files)
Note: there may be more files in the folders we are transferring, but there should be at least 120 (identified for ingest)
Estimated size of files to transfer

Approximately 31.4 GB

**Comment by mprefer** [comment]
File copy underway.

**Comment by mprefer** [comment]
445 files copied of total size 29.25G

**Comment by kmichaelis** [comment]
Looks good!
