### ISSUE TITLE
Run preprocessor on Lucille Clifton files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1564]
Please run the preprocessor on files in the Lucille Clifton papers.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/LucilleClifton_editedUnprocessed.csv)

This is a DAMS collection, so it can be run in the DAMS/Langmuir mode.

See the Langmuir notes in the [Rake Tasks Tutorial](https://github.com/emory-libraries/dlp-curate/blob/f12f497da2175b084e7785467fef140f7e169b1d/lib/tasks/README.md#langmuir-preprocessor).

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis I have run into errors processing the file linked above. Two of them, I've been able to resolve on my end ("Filename" written as "File name" in headers and had to remove non-text characters from complete file.)

There is one repeating error that occurs after line 196 in the file that I'm having trouble pin-pointing. Can you please review the lines following 196 on the edited file I shared with you via slack and see if you can find any issues that would cause these errors?
