### ISSUE TITLE
[SPIKE] Automate preprocessor

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#1567]
Use CI to automate processing data via the preprocessor rake task.

Notes from Emily: 
If feasible, consider a UI option similar to what we have in Curate for running CSV-based tasks like reindexing and loading preservation workflow metadata. 

https://curate-test.library.emory.edu/background_jobs/new

We also have a this repo where we store files for the preprocessor, if that may offer a simpler approach to automate:
https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1653

[Uploading... Screen Shot 2021-09-14 at 9.25.00 AM.png]
