### ISSUE TITLE
Run preprocessor on H.T. Burleigh files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1568]
Please run the preprocessor on files in the H.T. Burleigh papers.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/HTBurleigh_EditedUnprocessed.csv)

This is a DAMS collection, so it can be run in the DAMS/Langmuir mode.

See the Langmuir notes in the [Rake Tasks Tutorial](https://github.com/emory-libraries/dlp-curate/blob/f12f497da2175b084e7785467fef140f7e169b1d/lib/tasks/README.md#langmuir-preprocessor).

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis Processed file in desired folder.
