### ISSUE TITLE
Transfer files for multiple collections

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1569]
Please transfer the following files from Isilon to our AWS EFS mount, using Rclone with either MD5 or SHA1 to perform fixity checking during transfer.

Base path where files are located (Libraries Isilon "dmfiles" directory root), number of files, and approximate size of files per collection:
*Note: there may be more files in the folders we are transferring, but there should be at least the numbers specified below (identified for ingest).

**Collection 1 (H.T. Burleigh Papers):** nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_1195_Burleigh/B001/F005
184 files
~47.8 GB

**Collection 2 (Joan Browning Papers):** nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0821_Browning/B001
44 files
~3.7 GB

**Collection 3 (Calvin Fred Craig Papers):**
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F002 
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F003
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F004
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F005
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F006
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F007
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F008
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F009
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F010
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0612_Craig/B002/F011
156 files
~7.1 GB

**Collection 4 (Richard H. Rich Papers):**
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0575_Rich/B037/F001
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0575_Rich/B037/F002
nasn2dmz.cc.emory.edu/dmfiles/MARBL/Manuscripts/MSS_0575_Rich/B037/F003
128 files
~9.2 GB
 
Specific list of files or directories to be copied:

All TIFF files in the above folders

Desired destination directory structure in EFS:

/mnt/efs/Collections/dmfiles/ + relative directory structure from original Isilon location, e.g.:

/mnt/efs/Collections/dmfiles/MARBL/Manuscripts/MSS_0575_Rich/B037/F003

Estimated count of files to transfer

512+ (TIFF files)

Estimated size of files to transfer

Approximately 68 GB

**Comment by mprefer** [comment]
1083 files transferred, 65.059 Gig transferred.

**Comment by kmichaelis** [comment]
Thanks @mprefer !
