### ISSUE TITLE
Update homepage hero images (add new FY21 collection images)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1577]
Please remove the following images from the hero images on the digital collections homepage ( https://digital.library.emory.edu/ ) :

https://digital.library.emory.edu/catalog/006sxksn5r-cor
https://digital.library.emory.edu/catalog/931qfttf4h-cor
https://digital.library.emory.edu/catalog/706g1jwsv6-cor
https://digital.library.emory.edu/catalog/218dfn2z9j-cor

Please replace those images with the following images. They should link to the works indicated below.

Work: https://digital.library.emory.edu/catalog/28380gb616-cor 
(alt text: Handwritten spells and charms)
image: 

Work: https://digital.library.emory.edu/catalog/709w0vt4s5-cor 
(alt text: Undated spirit writing fragments)
image:

Work: https://digital.library.emory.edu/catalog/962f7m0d16-cor 
(alt text: Dietrich Dietz Notar family seal)
image:

Work: https://digital.library.emory.edu/catalog/245q83bkj4-cor 
(alt text: Bubba D. Licious bobblehead doll)
image:

**Comment by kmichaelis** [comment]
Please remove the following images from the hero images on the digital collections homepage ( [https://digital.library.emory.edu/](https://digital.library.emory.edu/) ) :

https://digital.library.emory.edu/catalog/006sxksn5r-cor
https://digital.library.emory.edu/catalog/931qfttf4h-cor
https://digital.library.emory.edu/catalog/706g1jwsv6-cor
https://digital.library.emory.edu/catalog/218dfn2z9j-cor

Please replace those images with the following images:

https://digital.library.emory.edu/catalog/28380gb616-cor (alt text: Handwritten spells and charms)
https://digital.library.emory.edu/catalog/709w0vt4s5-cor (alt text: Undated spirit writing fragments) 
https://digital.library.emory.edu/catalog/962f7m0d16-cor (alt text: Dietrich Dietz Notar family seal)
https://digital.library.emory.edu/catalog/245q83bkj4-cor (alt text: Bubba D. Licious bobblehead doll)

**Comment by kmichaelis** [comment]
@eporter23 can you take a look at this whenever you have a minute? Thanks!

**Comment by eporter23** [comment]
I am closing this as a stale ticket.
