### ISSUE TITLE
Run preprocessor on spring instruction books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1579]
Please run the preprocessor on a small set of books to be used for spring instruction:

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Spring_instruction_books.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Spring_instruction_books.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have zero-based filename sequences.

One of the works does not have a METS file. 
Two of the works share an Alma record--they are a two-volume set with just one catalog record between them. I manually copied the single record that was generated for this work and added it to the end of the XML file.

**Comment by bwatson78** [comment]
File delivered to @kmichaelis via slack and github folder for processed ingestion material.
