### ISSUE TITLE
Transfer missing file from LGBTQ Collection

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1580]
One file was missing from the LGBTQ Collection transfer: MSS1249_BV1_P008_I001_P000_ARCH.tif

Please transfer it from the library Isilon directory dmfiles/MARBL/MSS_1249_LGBT/BV1 to our AWS EFS mount.

**Comment by mprefer** [comment]
Files copied.

Reason they missed first time around if the Manuscripts was missing from path

**Comment by kmichaelis** [comment]
I'm still getting the "file not found" error when I pre-flight the CSV, and I don't see it in the folder where it should be on EFS.

**Comment by kmichaelis** [comment]
I'm downloading this file from the DAMS and attaching it manually.
