### ISSUE TITLE
SCLC/W.O.M.E.N., Inc. collection - link to items returns no matches

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1581]
Collection link: https://digital.library.emory.edu/catalog/501pg4f56v-cor

The _View items in this digital collection_ link returns no matches, but all the works (4 total) have the correct Source Collection ID, and the Source Collection shows up in the Collection facet with works assigned. 

https://digital.library.emory.edu/?f%5Bsource_collection_title_ssim%5D%5B%5D=SCLC%2FW.O.M.E.N.%2C+Inc.+Records+1965-2013&per_page=10

As troubleshooting steps, we have reindexed the Collection itself.

SOLR record for a work in the collection includes:
"source_collection_id_tesim":["501pg4f56v-cor"],
"source_collection_title_ssim":["SCLC/W.O.M.E.N., Inc. records 1965-2013"],

SOLR record for the Collection includes:
"member_works_count_isi":4, 

![Screen Shot 2021-01-29 at 9.23.15 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f533d6f7-2e7a-420e-922c-029380bc763e)

**Comment by kmichaelis** [comment]
@eporter23 this appears to be working now, not sure why.
