### ISSUE TITLE
PDF downloads are corrupted from Curate, but successful from Fedora

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1584]
These PDF files, when downloaded from Curate, cannot be opened because they are corrupted. The same files are fine, however, when downloaded directly from Fedora. Others may also be impacted.

This is similar to prior bug tickets including #755 and https://github.com/emory-libraries/dlp-curate/issues/940

Curate:
https://curate.library.emory.edu/concern//file_sets/515bcc2g6g-cor

https://curate.library.emory.edu/concern/file_sets/136h1893jg-cor

https://curate.library.emory.edu/concern/file_sets/972p5hqcfp-cor

Fedora:

http://fedora-cor.library.emory.edu/fcrepo/rest/prod/51/5b/cc/2g/515bcc2g6g-cor/files/8e5de7bd-fe33-4e00-aace-2a16cf916eae/fcr:metadata

http://fedora-cor.library.emory.edu/fcrepo/rest/prod/13/6h/18/93/136h1893jg-cor/files/fe1f13fd-0f8d-49da-8ec2-3f523f0b671e/fcr:metadata

http://fedora-cor.library.emory.edu/fcrepo/rest/prod/97/2p/5h/qc/972p5hqcfp-cor/files/8bc5c5c3-a75f-448c-9df6-ab45269705cd/fcr:metadata

**Comment by eporter23** [comment]
Updates: met with @SolomonHD @libdgg @kmichaelis @rotated8 to brainstorm. The prior bug tickets may not be applicable because we are no longer behind load balancing for Curate. Solomon suspects issues with large PDF files specifically. Team confirmed that all could download a 300 MB TIFF, but some of us could not download a 300 MB PDF.  Team also noted that Fedora downloads are slower, and include the full file size in the download information, where Curate does not.

- [ ] Emily will look at compressing 5 PDFs
- [ ] Kathryn will try attaching them manually to see if smaller size resolves the issue
- [ ] Collin will look at whether or not multi-part downloads are enabled on Hyrax (vs. Fedora)

**Comment by eporter23** [comment]
Screenshot showing file size detail in Curate (top: unknown) and Fedora (bottom: known)

![Screen Shot 2021-02-12 at 3.54.40 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/44557e66-7f22-4807-8294-f9e8dd457c44)

**Comment by kmichaelis** [comment]
Replaced the PDFs with the smaller versions and the problem appears to have been resolved.

**Comment by rotated8** [comment]
@eporter23 @kmichaelis Is there a 400 MB TIFF in curate-test for me to compare with?

**Comment by eporter23** [comment]
@rotated8 here's one: https://curate-test.library.emory.edu/concern/parent/098z8w9gtz-cor/file_sets/552w3r22k6-cor

**Comment by eporter23** [comment]
[Additional investigation notes](https://emory-my.sharepoint.com/:w:/r/personal/rmetz_emory_edu/Documents/LTDS%20Division/LTDS%20Shared%20Documentation/Projects/Project%20Documentation/DLP_%20Curation%20and%20Discovery/Scrum%20Team/Curate%20+%20Lux%20Scrum%20Team/Artifacts/2021-02-15%20Content%20Delivery%20Details.docx?d=wb8b235ecfb704915a07889d3f122de96&csf=1&web=1&e=yt9jhU) from @rotated8

**Comment by eporter23** [comment]
We resolved this for the short term by compressing the PDF files, but when we have the opportunity we should look at Collin's notes to see what else we may do.

**Comment by eporter23** [comment]
This Samvera-tech thread also has interesting information: https://groups.google.com/g/samvera-tech/c/StO0onrSk9I
