### ISSUE TITLE
Enable encryption on EC2 hosting Fedora

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#159]
To support performance testing for uploading files in an encrypted environment
- [ ] Setup encryption
- [ ] Deploy to curate-test

**Comment by eporter23** [comment]
Need to confirm encryption setup details from Circe

**Comment by tmiles2** [comment]
@rotated8 @mprefer Is this issue still valid now that we are moving forward with setting up an AWS at Emory account?

**Comment by rotated8** [comment]
Nope. Thanks!
