### ISSUE TITLE
Manifests not updating when FileSet permissions are changed

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1591]
Note: we have manually remediated the example below because we had to re-ingest the filesets from this batch, but we can try to reproduce the bug again if needed. 

Example: https://curate.library.emory.edu/concern/curate_generic_works/675r7sqvtx-cor?locale=en

For some works in this collection, the Back image was not supposed to be included in the manifest. The FileSet was manually set to Private in order to exclude it. After regenerating the manifest (twice), the manifest still included the Back image.

Note: the manifest regeneration did not start automatically started when the fileset was updated.
It also did not start automatically after I made an edit to the work's Title.
I had to run the regenerate manifest twice manually, but it still has not updated.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1604

No screenshots necessary.

**Comment by eporter23** [comment]
I successfully tested setting filesets to private and regenerating the manifests for those works. The Private filesets are now excluded as expected. 

https://curate-test.library.emory.edu/concern/curate_generic_works/453wstqk05-cor?locale=en

https://curate-test.library.emory.edu/concern/curate_generic_works/235gb5mkxb-cor?locale=en
