### ISSUE TITLE
Run preprocessor on Oxford catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1593]
Please run the preprocessor on a batch of Oxford College catalogs:

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Oxford_catalogs.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Oxford_catalogs_Emory_catalogs.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have zero-based filename sequences.

There will be several batches of catalogs within this one that share an Alma record.

The XML file also contains entries for some Emory catalogs; I have submitted that CSV in a separate ticket.

Please add processed CSV to [this folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
The processed file has been delivered to the github folder above.

**Comment by kmichaelis** [comment]
Thanks, @bwatson78 !

**Comment by bwatson78** [comment]
You're welcome, @kmichaelis! MP.
