### ISSUE TITLE
Run preprocessor on Office of Alumni Publications boxes 1 and 2 csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1599]
Please run the preprocessor on files in boxes 1 and 2 of the Office of Alumni Publications Photographs.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Office_of_Alumni_Pubs_box1_and2.csv)

This is a DAMS collection, so it can be run in the DAMS/Langmuir mode.

See the Langmuir notes in the [Rake Tasks Tutorial](https://github.com/emory-libraries/dlp-curate/blob/f12f497da2175b084e7785467fef140f7e169b1d/lib/tasks/README.md#langmuir-preprocessor).

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
File has been delivered to folder above.

**Comment by bwatson78** [comment]
@kmichaelis The only thing I can think of that has changed about the way we process these files is that we have two ways to run it: DAMS or Langmuir. I'm going to run it both ways and denote which way it was run in the filename--provide both to you.

**Comment by bwatson78** [comment]
@kmichaelis Two new files are in the folder above. The will end with either `_langmuir-processed.csv` or `_dams-processed.csv`. When you see which one is right, can you make sure to call out either Langmuir or Dams (not both) on future tickets.
