### ISSUE TITLE
Bulk-imported works missing edit group assignments

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1605]
This follows [a prior ticket](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1550) in which we found a couple of works that had no Curate permissions assigned. While investigating another work count discrepancy between Lux and Curate, we ran a SOLR check and found the following have no values in _edit_access_group_ssim_ and also have no _member of collection_ value. We are adding the collection assignment via UI.

Please add the following permissions to these works since we are not able to add all of our local groups via the UI. These are all Rose Library collections so will get the following groups assigned.

rose_manager, rose_depositor, rose_viewer, admin

 {
        "id":"221tdz0911-cor",
        "deduplication_key_tesim":["MSS0624_B044_F010_I007"]},
{
        "id":"286nzs7hgw-cor",
        "deduplication_key_tesim":["MSS0624_B044_F010_I006"]},
{
        "id":"836547d8cb-cor",
        "deduplication_key_tesim":["MSS0653_B001_F010_I012"]},
 {
        "id":"317crjdg55-cor",
        "deduplication_key_tesim":["MSS1313_B002_F020_I001"]},
{
        "id":"590dv41p91-cor",
        "deduplication_key_tesim":["MSS1313_B004_F020_I002"]},
{
        "id":"030prr4z0r-cor",
        "deduplication_key_tesim":["MSS1313_B001_F012_I002"]}, 
 {
        "id":"00000000h6-cor",
        "deduplication_key_tesim":["MSS1313_B001_F049_I003"]},
{
        "id":"706g1jwtc9-cor",
        "deduplication_key_tesim":["MSS1313_B004_F015_I001"]},
{
       "id":"508hdr7t7d-cor",
        "deduplication_key_tesim":["EUA0179_B001_F006_I007"]}]
{
        "id":"122v41nsgg-cor",
        "deduplication_key_tesim":["MSS0653_B001_F010_I010"]},
  },

For the last item in this list, this is what we saw in the UI in the Sharing Tab (no groups assigned). I was able to assign two of our standard groups only in this UI.

![Screen Shot 2021-05-12 at 4.03.16 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/35900bc2-a1e2-4341-8ded-390b7197f2ca)

**Comment by devanshu-m** [comment]
@eporter23 all IDs in above list have been updated. Please let me know if I missed any.

**Comment by eporter23** [comment]
@kmichaelis FYI, I checked all of these. I forgot to note the repository_manager group in the ticket and added it to all of the above works. For the first two works I didn't do the "apply to children" option and their filesets may not have the right edit permissions still for all the Rose groups. I added a Staff Note entry to note what happened and we can fix this in the future if needed.
