### ISSUE TITLE
Upgrade Active Fedora/LDP enhancements from May 2021

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1608]
https://samvera.slack.com/archives/C0F9JQJDQ/p1621021795320300

Is this part of Hyrax 3.0?

**Comment by eporter23** [comment]
Discussed with team in Slack, Sept 2021. We will look into updating this independently before a full Hyrax upgrade.

**Comment by bwatson78** [comment]
@eporter23 Preliminary findings show that 2 gems treat LDP.rb as a dependency. The first is valkyrie (1.7.1), which doesn't require a certain  range of versions, and the second is active-fedora (13.0.0), which does have a range, but the version in question (1.0.2) is definitely within that range (>= 0.7.0, < 2). To be honest, it looks like the developers of this gem intend to have every 1.* version to be compatible with this current version of active-fedora. I recommend trying to jump to the latest version there is (1.0.3) to see if we can keep up with their improvements.

**Comment by bwatson78** [comment]
The dependencies for 3.0.0 are the same as our current version, meaning that the same gems that `bundle install` would do the same for the new version. I have upgraded LDP to v1.0.3 locally, and it has passed all tests. What's unclear is whether the significant boosts mentioned in the Slack message above comes in concert with active-fedora 13.1.2/3, which hyrax v3.0.0 does use.

**Comment by eporter23** [comment]
Sprint planning discussion: we are going to run a medium sized book ingest in arch to get an initial baseline. next, we will deploy a branch to arch with the LDP gem upgrade only. We will then do some comparison tests with profiling on the same book in arch and test.

**Comment by bwatson78** [comment]
An ingest of an identical book was kicked off in both Arch and Test. Arch is currently using a branch that is using the updated version of LDP (v1.0.3) along with a profiler, while Test is operating with a branch just adding the profiler.
