### ISSUE TITLE
FileSets support reordering 

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#161]
- [ ] Research drag-and-drop options for reordering.
- [ ] Provide a dropdown (or drag-and-drop) for each fileset that allows the user to select an order
- [ ] If using a dropdown, ensure an order cannot be selected more than once.
- [ ] Create/update a system test to reorder filesets.

**Comment by eporter23** [comment]
Relates to #119 and #127 - these epics aren't showing up as assignable.

**Comment by eporter23** [comment]
De-scoping this from 0.3 as of 6/5 because it is overcomplicating the file upload process.

**Comment by tmiles2** [comment]
@eporter23 we de-scoped this issue but it is the one remaining issue for the epic to "Create compound/multi-part objects through deposit form". How do want to handle the epic?

**Comment by eporter23** [comment]
@tmiles2 I removed the assignment of this issue from epic #127.

**Comment by tmiles2** [comment]
@eporter23 I removed this issue from epic #119

**Comment by eporter23** [comment]
Do we want to rewrite this ticket?

**Comment by eporter23** [comment]
To confirm: is there a Hyrax 3 bug that is impacting this? File Manager ordering does not save.

**Comment by eporter23** [comment]
To investigate: are there non-UI options to correct FileSet order within a work if needed?

**Comment by eporter23** [comment]
@devanshu-m should I close this ticket as a duplicate?

**Comment by devanshu-m** [comment]
@eporter23 Sorry, I didn't realize the implementation ticket already existed and created a new one #886. We can close either as a duplicate.
