### ISSUE TITLE
Run preprocessor on Office of Alumni Pubs photos boxes 3-5 csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1610]
Please run the preprocessor on the csv for files in boxes 3, 4, and 5 of the Office of Alumni Publications Photographs.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Office_of_Alumni_Pubs_box3_4_5.csv)

This can be run in the Langmuir mode.

See the Langmuir notes in the Rake Tasks Tutorial.

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis The preprocessor produces an empty file (only headers).

**Comment by kmichaelis** [comment]
@bwatson78 I replaced the file, it should be fixed now.

**Comment by bwatson78** [comment]
@kmichaelis Still only header

**Comment by kmichaelis** [comment]
Ok @bwatson78 I tried one more thing. Give it another go and let me know what happens.

**Comment by kmichaelis** [comment]
@bwatson78 I think the processor didn't like that there was a P0002 with no P0001. I removed that work and reuploaded the csv to GitHub. Ready to try again when you can.
