### ISSUE TITLE
Run preprocessor on School of Nursing and Summer School catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1611]
Please run the preprocessor on a batch of Emory catalogs (Sch of Nursing/Summer Sch Bulletin):

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/NursingAndSummerSchCatalogs_for_processing.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Emory_generic_catalogs.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have zero-based filename sequences.

Please add processed CSV to [this folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis Processed file is in the folder requested.

**Comment by kmichaelis** [comment]
Looks good, thanks @bwatson78 !
