### ISSUE TITLE
Run preprocessor on Office of Alumni Pubs photos boxes 6 and 7 csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1612]
Please run the preprocessor on the csv for files in boxes 6 and 7 of the Office of Alumni Publications Photographs.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Office_of_Alumni_Pubs_box6_and7.csv)

This can be run in the Langmuir mode.

See the Langmuir notes in the [Rake Tasks Tutorial](https://github.com/emory-libraries/dlp-curate/blob/f12f497da2175b084e7785467fef140f7e169b1d/lib/tasks/README.md#langmuir-preprocessor).

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis The preprocessor erred out when expecting metadata here:
```
{:metadata=>nil, :filesets=>{2=>#<CSV::Row "source_row":38 "deduplication_key":"EUA0179_B006_F001_I010" "type":"fileset" "fileset_label":nil "preservation_master_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B006/F001/ARCH/EUA0179_B006_F001_I010_P002_ARCH.tif" "intermediate_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B006/F001/PROD/EUA0179_B006_F001_I010_P002_PROD.tif" "other_identifiers":nil "abstract":nil "administrative_unit":nil "local_call_number":nil "creator":nil "date_created":nil "Desc - Date Created - Date Precision":nil "date_issued":nil "content_genres":nil "holding_repository":nil "institution":nil "publisher":nil "emory_rights_statements":nil "rights_statement":nil "subject_names":nil "subject_geo":nil "subject_topics":nil "title":nil "content_type":nil "data_classifications":nil "Ingest.workflow_notes":nil "Digital Object - Parent Identifier":nil "visibility":nil "Directory Path":nil "File Size":nil "Filename":nil "Path":nil "Ingest.workflow_rights_basis":nil "Ingest.workflow_rights_basis_date":nil "Ingest.workflow_rights_basis_note":nil "Accession.workflow_rights_basis":nil "Accession.workflow_rights_basis_date":nil "Accession.workflow_rights_basis_reviewer":nil "Accession.workflow_rights_basis_note":nil "sensitive_material":nil "extent":nil "sublocation":nil "source_collection_id":nil>}}
```

**Comment by kmichaelis** [comment]
@bwatson78 looks like the same issue as the other csv, a part 2 with no part 1. I removed that work and replaced the csv in GitHub.

**Comment by bwatson78** [comment]
@kmichaelis Another error, same issue:
```
{:metadata=>nil, :filesets=>{2=>#<CSV::Row "source_row":3346 "deduplication_key":"EUA0179_B007_F004_I0082" "type":"fileset" "fileset_label":nil "preservation_master_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B007/F004/ARCH/EUA0179_B007_F004_I0082_P002_ARCH.tif" "intermediate_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B007/F004/PROD/EUA0179_B007_F004_I0082_P002_PROD.tif" "other_identifiers":nil "abstract":nil "administrative_unit":nil "local_call_number":nil "creator":nil "date_created":nil "Desc - Date Created - Date Precision":nil "date_issued":nil "content_genres":nil "holding_repository":nil "institution":nil "publisher":nil "emory_rights_statements":nil "rights_statement":nil "subject_names":nil "subject_geo":nil "subject_topics":nil "title":nil "content_type":nil "data_classifications":nil "Ingest.workflow_notes":nil "Digital Object - Parent Identifier":nil "visibility":nil "Directory Path":nil "File Size":nil "Filename":nil "Path":nil "Ingest.workflow_rights_basis":nil "Ingest.workflow_rights_basis_date":nil "Ingest.workflow_rights_basis_note":nil "Accession.workflow_rights_basis":nil "Accession.workflow_rights_basis_date":nil "Accession.workflow_rights_basis_reviewer":nil "Accession.workflow_rights_basis_note":nil "sensitive_material":nil "extent":nil "sublocation":nil "source_collection_id":nil>}}
```

**Comment by kmichaelis** [comment]
@bwatson78 work removed, new file uploaded to GitHub.

**Comment by bwatson78** [comment]
@kmichaelis Same thing:
```{:metadata=>nil, :filesets=>{2=>#<CSV::Row "source_row":3650 "deduplication_key":"EUA0179_B007_F006_I0020" "type":"fileset" "fileset_label":nil "preservation_master_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B007/F006/ARCH/EUA0179_B007_F006_I0020_P002_ARCH.tif" "intermediate_file":"dmfiles/MARBL/Archives/EUA_0179_AlumniPubs/B007/F006/PROD/EUA0179_B007_F006_I0020_P002_PROD.tif" "other_identifiers":nil "abstract":nil "administrative_unit":nil "local_call_number":nil "creator":nil "date_created":nil "Desc - Date Created - Date Precision":nil "date_issued":nil "content_genres":nil "holding_repository":nil "institution":nil "publisher":nil "emory_rights_statements":nil "rights_statement":nil "subject_names":nil "subject_geo":nil "subject_topics":nil "title":nil "content_type":nil "data_classifications":nil "Ingest.workflow_notes":nil "Digital Object - Parent Identifier":nil "visibility":nil "Directory Path":nil "File Size":nil "Filename":nil "Path":nil "Ingest.workflow_rights_basis":nil "Ingest.workflow_rights_basis_date":nil "Ingest.workflow_rights_basis_note":nil "Accession.workflow_rights_basis":nil "Accession.workflow_rights_basis_date":nil "Accession.workflow_rights_basis_reviewer":nil "Accession.workflow_rights_basis_note":nil "sensitive_material":nil "extent":nil "sublocation":nil "source_collection_id":nil>}}```

**Comment by kmichaelis** [comment]
@bwatson78 removed work and replaced file. I checked the remainder of the csv and didn't see any other occurrences of this so hopefully this will be the last edit.

**Comment by bwatson78** [comment]
@kmichaelis Processed file is in that Github folder.

**Comment by kmichaelis** [comment]
Thanks @bwatson78 !
