### ISSUE TITLE
Create new users and user groups in Curate; delete selected users

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1625]
We are preparing to ingest material from the Woodruff general collection and the Law Library collections, and we need to assign users to manage it. We also have a number of users no longer at Emory who should be deleted.

Please **create accounts** for the following users:

- [x] gmreddy
- [x] cpalazz
- [x] eegrime
- [x] adeese2

Please **delete** the following user accounts:

- [x] jlittl6
- [x] dwaugh
- [x] pmcdani
- [x] jduvern
- [x] avannuc
- [x] ccharti
- [x] esadle2
- [x] mprefer
- [x] ndragov
- [x] rkadel2
- [x] sande06
- [x] shilli2
- [x] wulman

Please **create** the following new Library groups:

- [x] woodruff_manager
- [x] woodruff_depositor
- [x] woodruff_viewer
- [x] law_manager
- [x] law_depositor
- [x] law_viewer

**woodruff_manager** group members should be:

- [x] gmreddy
- [x] cpalazz

**woodruff_depositor** and **woodruff_viewer** group members should be:

- [x] tezprox

**law_manager** group members should be:

- [x] eegrime
- [x] adeese2

**law_depositor** and **law_viewer** group members should be:

- [x] tezprox

**Comment by kmichaelis** [comment]
@eporter23 add users to delete

**Comment by devanshu-m** [comment]
@kmichaelis users have been updated

**Comment by kmichaelis** [comment]
@devanshu-m I can still see users mprefer, ccharti, ndragov, rkadel2, and shilli2, are these able to be deleted?

**Comment by devanshu-m** [comment]
@kmichaelis Apologies, I did not remove them from their respective groups, which is why they weren't deleted. I have corrected that and these users should be deleted now.

**Comment by kmichaelis** [comment]
Looks good, thanks @devanshu-m
