### ISSUE TITLE
Run preprocessor on African American Imprints - HathiTrust csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1626]
Please run the preprocessor on the volumes in the African American Imprints collection, HathiTrust batch:

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/AfricanAmericanImprints_HathiTrust_for_processing.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/DLP_Publishing_AAI_HT.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have one-based filename sequences.

Please add processed CSV to [this folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis The processed file has been delivered to the folder indicated above.

**Comment by kmichaelis** [comment]
@bwatson78 this is a book collection but it looks like it was run with the Langmuir preprocessor.

**Comment by bwatson78** [comment]
@kmichaelis The Langmuir Preprocessor only accepts a CSV. This is the command used to process these files:
`bundle exec rails curate:books csv="/Users/bwatso9/Downloads/AfricanAmericanImprints_HathiTrust_for_processing.csv" xml="/Users/bwatso9/Downloads/DLP_Publishing_AAI_HT.xml" repl="" map="limb" base=1`

**Comment by kmichaelis** [comment]
@bwatson78 I think I see what the problem was--I didn't add the values in the Disp_Path and Disp_Cnt columns. They have been added and the csv reuploaded.

**Comment by bwatson78** [comment]
@kmichaelis I had to share this via Slack with you, since it seems that github folder has a 25mb limit.

**Comment by kmichaelis** [comment]
Looks good, thanks @bwatson78 !
