### ISSUE TITLE
Run preprocessor on African American Imprints - Internet Archive csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1627]
Please run the preprocessor on the volumes in the African American Imprints collection, Internet Archive batch:

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/AfricanAmericanImprints_InternetArchive_for_processing.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/DLP_Publishing_AAI_IA.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have zero-based filename sequences.

Please add processed CSV to [this folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis The preprocessor was expecting to have values in `ALTO_Path`, but it seems none of the rows have any.

**Comment by kmichaelis** [comment]
@bwatson78 I added values for ALTO_Path and reuploaded the csv.

**Comment by bwatson78** [comment]
@kmichaelis There is no matching record in the XML for the first item in the CSV `990003480230302000`.

**Comment by kmichaelis** [comment]
@bwatson78 This looks like the same problem I had with a batch of catalogs a while back, where the MMSIDs got converted to a different number after they were exported from the Google sheet. I think I fixed it.

**Comment by bwatson78** [comment]
@kmichaelis If you fix item id 1280, I think this will process.

**Comment by kmichaelis** [comment]
@bwatson78 done!

**Comment by bwatson78** [comment]
@kmichaelis We got further--990002010050302486 is missing from the XML, too, though.

**Comment by kmichaelis** [comment]
@bwatson78 I'll have to put in another request to Core Services to get the export for that one. I'll check back in with you about this tomorrow.

**Comment by kmichaelis** [comment]
@bwatson78 okay, I got the export for this record and added it to the XML file. It should work now *fingers crossed*

**Comment by bwatson78** [comment]
@kmichaelis Processed file in the desired folder.

**Comment by kmichaelis** [comment]
@bwatson78 thanks!
