### ISSUE TITLE
Configure Fedora for MYSQL and S3

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#163]
Fedora has an example [repository.json file](https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-configs/src/main/resources/config/jdbc-mysql-s3/repository.json)

- [x] Adapt the example for use as a template
- [x] Adjust Ansible to set up the RDS and S3 services the template needs
- [x] Add the template to Ansible
- [x] Add or update any variables needed by the template.
- [x] Deploy and test

**Comment by tmiles2** [comment]
@SolomonHD Can we close out this issue?
