### ISSUE TITLE
Run preprocessor on Civil War box 8 csv

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1640]
Please run the preprocessor on the csv for files in box 8 of the Civil War Collection.

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/CivilWar_box8_for_processing.csv)

This can be run in the DAMS mode (**not** Langmuir)

When finished, please save the CSV in the [FY21 processed folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
@kmichaelis There seems to be missing metadata for source row 262, causing errors.

**Comment by kmichaelis** [comment]
@bwatson78 the work that starts on that line apparently does not have a part 1, which is likely the issue. I inserted some dummy part 1 rows and reuploaded the csv, hopefully this will work.

**Comment by bwatson78** [comment]
@kmichaelis Now 640, same issue.

**Comment by kmichaelis** [comment]
@bwatson78 fixed

**Comment by bwatson78** [comment]
@kmichaelis Processed file in desired folder.

**Comment by kmichaelis** [comment]
Thanks @bwatson78 !
