### ISSUE TITLE
Transfer files for Medical Heritage Imprints collection

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1642]
@jcrompton42 here are the books I mentioned in my email yesterday. No deadline for transferring these. Let me know if you have any questions. Thanks!

Please transfer the following files from Isilon "library" volume to our AWS EFS mount.

There are 154 volumes that need to be transferred for this collection. I have created a [Google sheet](https://docs.google.com/spreadsheets/d/1q6p881ix8AO__Iu_x8zDj_gR3WS7cMALSb18WxxV97I/edit?usp=sharing) with info on the base paths where the files are located, as well as the number of files of each type that are included with each volume.

Desired destination directory structure in EFS:
/mnt/efs/Collections/ + relative directory structure from original Isilon location, e.g.:

/mnt/efs/Collections/lsdi2/ocm05514904-5844

**Comment by jcrompton42** [comment]
Got them all transferred.
