### ISSUE TITLE
Low % of thumbnails being generated during bulk ingests

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1645]
During bulk ingests for the last year or more, we have noticed that we see very few thumbnails getting generated for filesets attached to a work. This also seems to correlate with another bug where many filesets in a batch import do not show characterization information after being attached to a work (#1526).

Manually regenerating thumbnails has become a standard part of our post ingest process. Given that most of our batch imports include hundreds of filesets, this can take many hours to manually remediate. We often have to reindex filesets first, and then manually regenerate each missing thumbnail. Sometimes this also does not work on the first try and multiple retries are needed.

_This issue can be reproduced on demand by running a new ingest in either test or production. Production ingests run almost daily._

See also DCE's recommendations about [FITS as a servlet](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/801).

**Comment by kmichaelis** [comment]
For the two most recently ingested books ([this book](https://curate.library.emory.edu/concern/curate_generic_works/313zs7h4v1-cor?locale=en) and [this book](https://curate.library.emory.edu/concern/curate_generic_works/965v6wwqnk-cor?locale=en)), I checked the first 20 filesets and none of them had thumbnails after ingest. Some appear to when viewed in the items list, but once they're opened no thumbnail is present. The attached screenshots show what they look like in the items list as well as opened. ![thumbnails.JPG](https://images.zenhubusercontent.com/5d924e9841d63100014d5334/36ef6ecc-1d9f-48d3-875a-763dce57305d) 
![page9.JPG](https://images.zenhubusercontent.com/5d924e9841d63100014d5334/354a5c04-b4e3-4b1b-a864-21bfd1ef6c92)

This is typical for ingested books. Usually after every few books that are ingested, we retrieve a list of those books' filesets in Solr and reindex them in Curate, which improves the thumbnail generation somewhat.

**Comment by eporter23** [comment]
A recent ingest of 33 image-based works resulted in 21/33 having no thumbnails generated (during Hyrax 3.3 testing in test). A book object, however, had a much higher rate of thumbnails generated.

**Comment by rotated8** [comment]
This may be fix in our move to Bulkrax. Moving this ticket to To Accept for verification.

**Comment by eporter23** [comment]
After running ingests with Bulkrax for several days in production, we are seeing definite improvements in thumbnail generation.
