### ISSUE TITLE
Increase speed of ingest for book objects with many filesets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1646]
## Story
Story: _As a Preservation Curator, I want to increase the overall rate of complex book objects, so that I can keep pace with the demand for preservation and long term access of high value materials needed by researchers_

This work may overlap with our proposed upgrade to the current Hyrax 3.x series (#1644).

**Overview:**
The majority of material queued for ingest in the next few months includes book objects. We also have not yet finished to ingest the Yellowbacks collection which was targeted for Phase 1 of DLP ingests. Additionally, we have some extremely large book objects in the longer-term queue for ingest that we fear may not be feasible to ingest (over 2,000 filesets) with our current system capability.

Similar to the problem we had with the rate of ingest declining as the number of works in a collection grows, we also experience this slowdown on works with many filesets such as books. The initial rate of ingest is speedy, but exponentially slows down as more filesets are added. See the graph and statistics below for more details. This behavior primarily affects digitized books because image objects tend to have only a few filesets.

Over the last 6 months we have applied a number of workarounds to try to ingest books most efficiently, including:

- Only ingesting one book at a time. When we run multiple book ingests, we encounter greater numbers of failed jobs which require retries. Each book can take anywhere from half a day to several days, depending on its size. In Yellowbacks alone, we have over 1100 books remaining which would take years at our current speed.
- Frequently restarting Curate and Fedora. We see a short-term increase in ingest speed immediately after a restart, and after ingests have been running for a few days, the rate begins to decline again.

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Additional Information

- [Chart showing rate of ingest declining](https://docs.google.com/spreadsheets/d/1TVCBGJ1xfXY3tU0rBvrs7Yc-ZpXEmFL0ZRMAjuWMd10/edit#gid=623900542) relative to overall number of filesets per work
- Average number of filesets per book: 134 (approx 4 hours to ingest)
- Largest book object ingested so far: 672 filesets (67 hours)
- Largest book object pending ingest in the short term: 844 pages (part of the South Asian Open Archives, a collection currently in process); 1,368 pages (Medical Heritage Imprints, queued to begin ingest soon. This collection contains 5-10 books that are over 1,000 pages.)
- Largest book object in long-term queue: 2,000+ pages

#### Checklist
- [ ] Research and identify additional strategies to speed up the rate of ingest for books
- [ ] Develop implementation tickets 

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)

**Comment by kmichaelis** [comment]
Sample book csv files:
-[Book with 168 filesets](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/processed/St_Johns_Gospel_Tamil_168_FS.csv)
-[Book with 206 filesets](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/processed/Sangita_darpana_206_FS.csv)
-[Book with 250 filesets](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/processed/Bajirava_Ballala_250_FS.csv)
