### ISSUE TITLE
Transfer batch of course catalog files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1647]
Please transfer the following files from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/Allied_Health_1990-1991
lsdi2/ftp/Allied_Health_1991-1992
lsdi2/ftp/Allied_Health_1992-1993
lsdi2/ftp/Allied_Health_1993-1994
lsdi2/ftp/Allied_Health_1994-1995
lsdi2/ftp/Allied_Health_1996-1997
lsdi2/ftp/Allied_Health_1997-1999
lsdi2/ftp/AlliedHealth_1982-1983
lsdi2/ftp/AlliedHealth_1983-1984
lsdi2/ftp/AlliedHealth_1984-1985
lsdi2/ftp/AlliedHealth_1985-1986
lsdi2/ftp/AlliedHealth_1986-1987
lsdi2/ftp/Business_1993-1995
lsdi2/ftp/Business_BBA_1982-1983
lsdi2/ftp/Business_BBA_1983-1984
lsdi2/ftp/Business_BBA_1984-1985
lsdi2/ftp/Business_BBA_1985-1986
lsdi2/ftp/Business_BBA_1986-1987
lsdi2/ftp/Business_BBA_1989-1990
lsdi2/ftp/Business_BBA_1990-1992
lsdi2/ftp/Business_BBA_1995-1997
lsdi2/ftp/Business_MBA_1982-1983
lsdi2/ftp/Business_MBA_1983-1984
lsdi2/ftp/Business_MBA_1984-1985
lsdi2/ftp/Business_MBA_1985-1986
lsdi2/ftp/Business_MBA_1990-1991
lsdi2/ftp/Business_MBA_1991-1992
lsdi2/ftp/Business_MBA_1993-1995
lsdi2/ftp/Business_MBA_1995-1997
lsdi2/ftp/College_1982-1983
lsdi2/ftp/College_1983-1984
lsdi2/ftp/College_1984-1985
lsdi2/ftp/College_1985-1986
lsdi2/ftp/College_1990-1992
lsdi2/ftp/College_1992-1994
lsdi2/ftp/College_1994-1996
lsdi2/ftp/College_1994-1996
lsdi2/ftp/College_1997-1999
lsdi2/ftp/College_2003-2005
lsdi2/ftp/College_2005-2007
lsdi2/ftp/College_2007-2009
lsdi2/tesseract/EUACatalogs/College/College_2011-2012
lsdi2/ftp/Dentistry_1982-1983
lsdi2/ftp/Dentistry_1983-1984
lsdi2/ftp/Dentistry_1984-1985
lsdi2/tesseract/EUACatalogs/College/College_1999-2000
lsdi2/tesseract/EUACatalogs/College/College_2001-2002
lsdi2/tesseract/EUACatalogs/GBS/BBA_2012-2013
lsdi2/tesseract/EUACatalogs/GBS/BBA_2013-2014
lsdi2/tesseract/EUACatalogs/GBS/BBA_2004-2006
lsdi2/tesseract/EUACatalogs/GBS/BBA_2010-2012
lsdi2/tesseract/EUACatalogs/GBS/EveningMBA_2004-2007
lsdi2/tesseract/EUACatalogs/GBS/EveningMBA_2005-2006
lsdi2/tesseract/EUACatalogs/GBS/EveningMBA_2009-2010
lsdi2/tesseract/EUACatalogs/GBS/ExecMBA_2009-2011
lsdi2/tesseract/EUACatalogs/GBS/MBA_2002-2003
lsdi2/tesseract/EUACatalogs/GBS/MBA_2003-2005
lsdi2/tesseract/EUACatalogs/GBS/MBA_2005-2006
lsdi2/tesseract/EUACatalogs/GBS/MBA_2009-2010
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2006-2007
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2011-2012
lsdi2/tesseract/EUACatalogs/GBS/WkendExecMBA_2012-2013
lsdi2/ftp/GSAS_1982-1983
lsdi2/ftp/GSAS_1983-1984
lsdi2/ftp/GSAS_1984-1985
lsdi2/ftp/GSAS_1985-1986
lsdi2/ftp/GSAS_1990
lsdi2/ftp/GSAS_1990-1991
lsdi2/ftp/GSAS_1991-1993
lsdi2/ftp/GSAS_1993-1995
lsdi2/ftp/GSAS_1995-1997
lsdi2/ftp/GSAS_2002-2003
lsdi2/ftp/GSAS_2003-2004
lsdi2/ftp/GSAS_2005-2006
lsdi2/ftp/GSAS_2006-2007
lsdi2/ftp/GSAS_2008-2010
lsdi2/ftp/Law_1983-1984
lsdi2/ftp/Law_1984-1985
lsdi2/ftp/Law_1990-1992
lsdi2/ftp/Law_1990-1992
lsdi2/ftp/Law_1990-1992
lsdi2/ftp/Law_1992-1994
lsdi2/ftp/Law_1994-1996
lsdi2/ftp/Law_1994-1996
lsdi2/tesseract/EUACatalogs/LGS/LGS_2012-2013
lsdi2/ftp/Library_1983-1984
lsdi2/ftp/Library_1984-1985
lsdi2/ftp/Medicine_1983-1984
lsdi2/ftp/Medicine_1984-1985
lsdi2/ftp/Medicine_1990-1991
lsdi2/ftp/Medicine_1991-1992
lsdi2/ftp/Medicine_1992-1993
lsdi2/ftp/Medicine_1993-1994
lsdi2/ftp/Medicine_1994-1995
lsdi2/ftp/Medicine_1995-1996
lsdi2/ftp/Medicine_1996-1998
lsdi2/ftp/Medicine_1998-1999
lsdi2/ftp/Nursing_1983-1984
lsdi2/ftp/Nursing_1984-1985
lsdi2/ftp/Nursing_1990-1991
lsdi2/ftp/Nursing_1991-1992
lsdi2/ftp/Nursing_1992-1993
lsdi2/ftp/Nursing_1993-1994
lsdi2/ftp/Nursing_1994-1995
lsdi2/ftp/Oxford_1982-1983
lsdi2/ftp/Oxford_1983-1984
lsdi2/ftp/Oxford_1984-1985
lsdi2/ftp/Oxford_1990-1991
lsdi2/ftp/Oxford_1991-1992
lsdi2/ftp/Oxford_1992-1994
lsdi2/ftp/Oxford_1994-1995
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2008-2009
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2009-2010
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2010-2011
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2011-2012
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2012-2013
lsdi2/tesseract/EUACatalogs/Oxford/Oxford_2013-2014
lsdi2/ftp/Public_Health_1990
lsdi2/ftp/Public_Health_1991-1992
lsdi2/ftp/Public_Health_1992-1993
lsdi2/ftp/Public_Health_1993-1994
lsdi2/ftp/Public_Health_1994-1995
lsdi2/ftp/catalogs/Public_Health_1998-1999
lsdi2/ftp/Public_Health_2001-2002
lsdi2/ftp/Public_Health_2002-2003
lsdi2/ftp/Public_Health_2003-2004
lsdi2/ftp/Public_Health_2004-2005
lsdi2/ftp/Public_Health_2006-2007
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2000-2001
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2007-2008
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2008-2009
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2009-2010
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2011-2012
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2012-2013
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2013-2014
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2014-2015
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2015-2016
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2000-2001
lsdi2/ftp/Summer_School_Bulletin_1983
lsdi2/ftp/Summer_School_Bulletin_1984
lsdi2/ftp/Summer_School_Bulletin_1990
lsdi2/ftp/Summer_School_Bulletin_1991
lsdi2/ftp/Summer_School_Bulletin_1992
lsdi2/ftp/Summer_School_Bulletin_1993
lsdi2/ftp/Summer_School_Bulletin_1994
lsdi2/ftp/Summer_School_Bulletin_1995
lsdi2/ftp/Summer_School_Bulletin_1996
lsdi2/ftp/Summer_School_Bulletin_1997
lsdi2/ftp/Summer_School_Bulletin_1998
lsdi2/ftp/Summer_School_Bulletin_1999
lsdi2/ftp/Theology_1983-1984
lsdi2/ftp/Theology_1984-1985
lsdi2/ftp/Theology_1990-1991
lsdi2/ftp/Theology_1991-1992
lsdi2/ftp/Theology_1992-1993
lsdi2/ftp/Theology_1993-1994
lsdi2/ftp/Theology_1994-1995
lsdi2/ftp/Theology_1995-1996
lsdi2/ftp/Theology_1996-1997
lsdi2/ftp/Theology_1997-1998
lsdi2/ftp/Theology_1998-1999
lsdi2/ftp/Theology_1999-2000
lsdi2/ftp/Theology_2001-2002
lsdi2/ftp/Theology_2003-2004
lsdi2/ftp/Theology_2004-2005
lsdi2/ftp/Theology_2005-2006
lsdi2/ftp/Theology_2008-2009
lsdi2/ftp/Theology_2009-2010
lsdi2/ftp/Theology_2010-2011
lsdi2/ftp/Theology_2011-2012
lsdi2/ftp/Theology_2012-2013
lsdi2/ftp/Theology_2013-2014

**Comment by kmichaelis** [comment]
@jcrompton42 let me know if you need info on file counts and sizes to complete this. The info I have is messy and some file counts are missing; I am working on tracking them down but it might take a minute. Thanks!

**Comment by jcrompton42** [comment]
transferred. .
