### ISSUE TITLE
Run preprocessor on batch of assorted catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1648]
Please run the preprocessor on a batch of Emory catalogs (assorted schools/programs):

[CSV file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Catalogs20210831.csv)
[XML file](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/FY21/in-development/Emory_generic_catalogs.xml)

Preprocessor parameters:
These are all LIMB outputs.
These all have zero-based filename sequences.

Please add processed CSV to [this folder](https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/FY21/processed).

**Comment by bwatson78** [comment]
Processed file in desired folder.

**Comment by kmichaelis** [comment]
Awesome, thank you @bwatson78
