### ISSUE TITLE
See about automating restarts

### ISSUE THREAD

**Issue by AGCooper** [emory-libraries/dlp-curate#1650]

**Comment by AGCooper** [comment]
Katheryn documented these steps a little while ago:

1) Open Ubuntu window
2) Generate AWX token by typing "awx_get_token". That will generate the word "export" and a token.
3) Copy the output from the word "export" through the end of the token
4) Enter it in the Ubuntu window.
5) Test it by typing "awx me -f human". That should return my NetID.
6) Set the target environment by typing "export ENV=prod" (or arch or test)
7) Test that by typing "echo $ENV". That should return "prod".
8) Copy this and enter in Ubuntu window to restart Curate and Fedora:
awx workflow_job_templates launch refresh-curate-fedora --monitor -f human --extra_vars "host: $ENV"

**Comment by jcrompton42** [comment]
Is this something we want on a specific schedule or just as a command that can be run whenever without all the steps above?

**Comment by kmichaelis** [comment]
It's something we want to run on demand. Having it run on a regular schedule could potentially disrupt ingests.

**Comment by jcrompton42** [comment]
@kmichaelis please let me know when next you need this restarted so I can test my script. Thanks!

**Comment by jcrompton42** [comment]
CD into home directory and download the restart-curate-fedora.sh  script (install curl if needed)

cd ~

curl https://raw.githubusercontent.com/jcrompton42/utils/main/restart-curate-fedora.sh -o ./restart-curate-fedora.sh

Make the script executable
chmod 0755 restart-curate-fedora.sh

Move the scripts into PATH --Linux / Windows Subsystem for Linux (WSL) --
sudo mv restart-curate-fedora.sh /usr/local/bin/

Everytime after the above steps, you can run with
restart-curate-fedora.sh

**Comment by jcrompton42** [comment]
closng out because current method works fine.
