### ISSUE TITLE
Update regression test plan for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1651]
Update regression test plan ([template](https://docs.google.com/spreadsheets/d/1BTjC_8_mHr49ktUJiOFLYixCNOa3Rdv5nuhdDiOx6_w/edit#gid=2120660950)) for Curate/Lux to include Source Collection features; UI for running bulk tasks

[New test sheet draft](https://docs.google.com/spreadsheets/d/15a2JXuCKh0192UInMNYncar3bIjvU0ocfjJwgYpzi0c/edit#gid=2120660950) - Sept 2021

**Comment by eporter23** [comment]
@kmichaelis I know this is a lot to look at, but if you have a chance could you review it? I added quite a number of things from our last release in 2020. (link in ticket above)

**Comment by kmichaelis** [comment]
@eporter23 it looks good to me!
