### ISSUE TITLE
Profile book ingest performance for bottlenecks

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1652]
See prior tickets for profiling tools we have used to track performance bottlenecks in the past, especially related to adding works to a very large collection (#1182).

**Comment by bwatson78** [comment]
This is the most recent ingest from Arch:
==================================
  Mode: cpu(1000)
  Samples: 23402 (1.14% miss rate)
  GC: 5110 (21.84%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      3598  (15.4%)        3598  (15.4%)     (sweeping)
      2412  (10.3%)        1668   (7.1%)     RDF::Util::Logger#logger_common
      1512   (6.5%)        1512   (6.5%)     (marking)
      2150   (9.2%)        1123   (4.8%)     EBNF::LL1::Lexer#match_token
       696   (3.0%)         696   (3.0%)     RDF::URI#parse
      1695   (7.2%)         653   (2.8%)     RDF::Util::Logger#log_recover
       613   (2.6%)         606   (2.6%)     RDF::Util::Logger#logger
       533   (2.3%)         533   (2.3%)     EBNF::LL1::Lexer::Token#initialize
       385   (1.6%)         384   (1.6%)     FileUtils::Entry_#copy_file
       635   (2.7%)         320   (1.4%)     RDF::Statement#initialize
       314   (1.3%)         309   (1.3%)     RDF::URI#hash
       294   (1.3%)         294   (1.3%)     EBNF::LL1::Lexer#skip_whitespace
       282   (1.2%)         282   (1.2%)     EBNF::LL1::Lexer.unescape_codepoints
      2722  (11.6%)         278   (1.2%)     EBNF::LL1::Lexer#first
       332   (1.4%)         259   (1.1%)     Net::HTTP#connect
       241   (1.0%)         225   (1.0%)     RDF::URI#initialize
       383   (1.6%)         214   (0.9%)     Hamster::Trie#index_for
       193   (0.8%)         193   (0.8%)     Hamster::Trie#initialize
       232   (1.0%)         169   (0.7%)     RDF::Statement#initialize!
       164   (0.7%)         164   (0.7%)     FileUtils::Entry_#remove_file
      2126   (9.1%)         151   (0.6%)     Hamster::Trie#each
       216   (0.9%)         149   (0.6%)     RDF::Mutable#respond_to_missing?
       145   (0.6%)         145   (0.6%)     RDF::Util::Cache::ObjectSpaceCache#[]
       160   (0.7%)         144   (0.6%)     RDF::Reader#prefix
       143   (0.6%)         142   (0.6%)     RDF::URI#value
       462   (2.0%)         139   (0.6%)     EBNF::LL1::Lexer::Terminal#unescape
       136   (0.6%)         135   (0.6%)     URI::RFC3986_Parser#split
       231   (1.0%)         129   (0.6%)     RDF::URI#==
       404   (1.7%)         121   (0.5%)     #<Module:0x0000000004166a80>.URI
       373   (1.6%)         114   (0.5%)     #<Module:0x0000000002646868>.timeout

**Comment by bwatson78** [comment]
Most recent from Test:
==================================
  Mode: cpu(1000)
  Samples: 16892 (1.92% miss rate)
  GC: 4223 (25.00%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
      2608  (15.4%)        2608  (15.4%)     (sweeping)
      1615   (9.6%)        1615   (9.6%)     (marking)
      1818  (10.8%)        1259   (7.5%)     RDF::Util::Logger#logger_common
      1516   (9.0%)         759   (4.5%)     EBNF::LL1::Lexer#match_token
       501   (3.0%)         501   (3.0%)     RDF::URI#parse
       498   (2.9%)         496   (2.9%)     RDF::Util::Logger#logger
      1315   (7.8%)         469   (2.8%)     RDF::Util::Logger#log_recover
       436   (2.6%)         436   (2.6%)     EBNF::LL1::Lexer::Token#initialize
       312   (1.8%)         312   (1.8%)     FileUtils::Entry_#copy_file
       254   (1.5%)         254   (1.5%)     BasicSocket#read_nonblock
       230   (1.4%)         229   (1.4%)     RDF::URI#hash
       223   (1.3%)         223   (1.3%)     EBNF::LL1::Lexer#skip_whitespace
       206   (1.2%)         206   (1.2%)     EBNF::LL1::Lexer.unescape_codepoints
      1926  (11.4%)         187   (1.1%)     EBNF::LL1::Lexer#first
       357   (2.1%)         175   (1.0%)     RDF::Statement#initialize
       154   (0.9%)         152   (0.9%)     FileUtils::Entry_#remove_file
       149   (0.9%)         144   (0.9%)     RDF::URI#initialize
       189   (1.1%)         138   (0.8%)     Net::HTTP#connect
       221   (1.3%)         129   (0.8%)     RDF::URI#==
       246   (1.5%)         129   (0.8%)     Hamster::Trie#index_for
       119   (0.7%)         119   (0.7%)     Hamster::Trie#initialize
       249   (1.5%)         111   (0.7%)     #<Module:0x0000000002afdf50>.timeout
       108   (0.6%)         106   (0.6%)     RDF::URI#value
       106   (0.6%)         101   (0.6%)     RDF::Reader#prefix
        99   (0.6%)          99   (0.6%)     RDF::Util::Cache::ObjectSpaceCache#[]
       100   (0.6%)          98   (0.6%)     URI::RFC3986_Parser#split
      1398   (8.3%)          90   (0.5%)     Hamster::Trie#each
       265   (1.6%)          90   (0.5%)     #<Module:0x0000000005658768>.URI
        83   (0.5%)          83   (0.5%)     EBNF::LL1::Lexer::Token#===
       138   (0.8%)          83   (0.5%)     RDF::Mutable#respond_to_missing?

**Comment by bwatson78** [comment]
Test Flamegraph:
![Screen Shot 2021-09-11 at 9.40.10 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/2d8f5a98-f807-41a0-b2da-d5000820c406)

**Comment by bwatson78** [comment]
Flamegraph Arch:
![Screen Shot 2021-09-11 at 9.41.21 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/73fb5a35-f4dc-4b1c-a1de-07d57d9a13f1)

**Comment by eporter23** [comment]
@bwatson78 and I looked at this but would like more team review on what is reported. Ideally, I am also interesting in seeing a time-based report to understand which processes are running slowly and where that occurs. We are not sure if the profiling shown above is really giving us that.

**Comment by eporter23** [comment]
I'm going to close this because work was done on it and we've also made great progress without having more data.
