### ISSUE TITLE
Spike: Loading fixity check events from AWS into Curate, SOLR, Fedora as Preservation Event metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1658]
_As a Preservation Curator, I want to store the fixity check outcomes generated by AWS in our preservation event metadata for filesets, so that curators and collection stewards can see the event data in Curate along with other preservation events_

After testing a new AWS lambda-based method to check fixity on S3 buckets directly, the method produces a CSV files with a log of outcomes, one row per sha1 checksum. Since we are not using Fedora or Curate to run these fixity checks, we need a way to get the preservation events generated and attached to the parent filesets.

- [x] Populate a Fixity Check preservation event for each row on the CSV, based on our current fixity check event metadata. See the following [mapping from AWS-generated CSV columns to our Event model.](https://docs.google.com/document/d/1w7dgyREHw4WCAx3XHxFo4GQms20XZjTCET3QTQ85iYw/edit#) - this was completed by Beth as part of the fixity report.
- [x] Find a way to associate a given sha1 checksum back to its parent FileSet, so that the event can be attached to the parent FileSet
- [x] Provide a UI (like our existing UI to load Preservation Workflow metadata from a CSV file) or other bulk method to periodically load this data into Fedora and SOLR

Here is a [sample fixity outcomes CSV](https://drive.google.com/file/d/1sUqXgQ6BZ11aOWM5yDcvUb8b7Jk9XMve/view?usp=sharing) generated by the AWS tool for a recent run on a small set of production IDs.

**Comment by eporter23** [comment]
Discussed with @bwatson78 that some modifications to the CSV will be helpful. These have been added to the [CSV mockup](https://docs.google.com/spreadsheets/d/1LwcmZOslYJOj6i1RpAGv3JkWzoOMFpcva5XUmgx06WQ/edit#gid=1880756537) and we will work with @jcrompton42 to implement as her time permits.

**Comment by eporter23** [comment]
@bwatson78 here is a small sample using real data from arch formatted in the new CSV template: https://docs.google.com/spreadsheets/d/1LC_Vat_2FNcoAfDB-eJckVQQG9eedwBnzaaniYOhx8Y/edit#gid=221225981

**Comment by eporter23** [comment]
This is looking great @bwatson78. I loaded the set of 20 sha1s in arch and it ran successfully: I can see the events in Curate, SOLR, and Fedora. One minor formatting revision requested: please remove the space after the "sha1: " prefix and before the value so it is consistent with the older style Fedora events. Example:  https://curate-arch.library.emory.edu/concern/file_sets/863fxpnvz6-cor?locale=en ![Screen Shot 2022-03-16 at 1.10.53 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/647f1895-b99c-4be7-bfdd-119f93450c32)

**Comment by bwatson78** [comment]
@eporter23 On it.
