### ISSUE TITLE
After All Files Updated: Debug Hyrax v3.1.0

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-curate#1680]
Address all errors after we have merged all updates to our v3.1.0 branch.

**Comment by bwatson78** [comment]
PRs so far:
- https://github.com/emory-libraries/dlp-curate/pull/1689
- https://github.com/emory-libraries/dlp-curate/pull/1690

**Comment by eporter23** [comment]
Closing because we reverted to 3.0.2.
