### ISSUE TITLE
Universal Viewer does not load in Work Show Page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1704]
When viewing works in Curate test for which manifests should be available, the Universal Viewer is not loading.

Examples:
https://curate-test.library.emory.edu/concern/curate_generic_works/552w3r22k7-cor?locale=en

https://curate-test.library.emory.edu/concern/curate_generic_works/453wstqk05-cor?locale=en

![Screen Shot 2021-10-04 at 2.14.17 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0049f773-952c-49c2-894b-8e52d6dd5d2d)

**Comment by eporter23** [comment]
@bwatson78 the first example noted above fails with a login error,  but the second example is okay.

**Comment by eporter23** [comment]
See prior work in https://github.com/emory-libraries/dlp-curate/issues/674 about this error which seemed to be Cantaloupe related?

**Comment by bwatson78** [comment]
@rotated8 I've hit a wall because this seems to be an issue revolving around Cantaloupe and problems occurring with regeneration of manifests. I'd really appreciate pairing with you to get a better understanding of how to fix something like this.

**Comment by eporter23** [comment]
After the re-upgrade to 3.1 and the PMF fix was applied, regenerated this one and it loads files now: https://curate-test.library.emory.edu/concern/curate_generic_works/552w3r22k7-cor?locale=en . The second example is also resolved: https://curate-test.library.emory.edu/concern/curate_generic_works/453wstqk05-cor?locale=en

**Comment by eporter23** [comment]
@bwatson78 @rotated8 closing this one because it's resolved related to other fixes.
