### ISSUE TITLE
Transfer Oxford Spokesman files to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1723]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Oxford_Spokesman/Spokesman_2000Spring
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19681024
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19681213
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19690604
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19700327
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19700925
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19701009
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19701113
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710115
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710226
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710412
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710423
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710518
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19710600
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19711100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19720100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19720200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19720300
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19720400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19721000
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19730200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19730400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19730600
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19731026
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19740125
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19740308
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19740430
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19740524
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19741004
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19741115
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19750206
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19750404
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19751100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19761103
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19770131
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19770307
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19770402
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19770603
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19770729
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19771008
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19771117
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19780208
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19780314
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19780408
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19780607
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19790302
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19791022
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19800211
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19800313
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19800412
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19800530
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19801030
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19801121
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19810306
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19810411
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19810609
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19810909
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19811015
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19811029
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19811119
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19820128
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19820218
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19820316
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19820417
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19820603
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19821014
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19821202
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19830308
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19830419
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19830908
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19830929
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19831101
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19831213
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19840210
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19840407
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19841022
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19841211
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19870305
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19870404
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19871200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19880200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19880400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19891000
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20000922
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20001027

**Comment by jcrompton42** [comment]
All files transferred.
