### ISSUE TITLE
Transfer second batch of Kessler Reformation books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1725]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/000015281537
lsdi2/tesseract/Kessler/000015281539
lsdi2/tesseract/Kessler/300000346689-1
lsdi2/tesseract/Kessler/300000346689-2
lsdi2/tesseract/Kessler/000015281591
lsdi2/tesseract/Kessler/000015281597
lsdi2/tesseract/Kessler/000015281607

**Comment by jcrompton42** [comment]
transferred.
