### ISSUE TITLE
Transfer African American Imprints batch 1

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1726]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/010001066805
lsdi2/ftp/010002418432
lsdi2/ftp/010001066580
lsdi2/ftp/010002643711
lsdi2/ftp/010001341300
lsdi2/ftp/010001066830
lsdi2/ftp/10002331269
lsdi2/ftp/africanamerican/010002643665
lsdi2/ftp/010000576508
lsdi2/ftp/010000427089
lsdi2/ftp/africanamerican/010002588964
lsdi2/ftp/africanamerican/010002643954
lsdi2/ftp/010002426554
lsdi2/ftp/010002406241
lsdi2/ftp/africanamerican/010002588806
lsdi2/ftp/010000894133
lsdi2/ftp/010002632251
lsdi2/ftp/010000878647
lsdi2/ftp/010002632366
lsdi2/ftp/010000882610
lsdi2/ftp/africanamerican/010002588886
lsdi2/ftp/africanamerican/010002483582
lsdi2/ftp/africanamerican/010002588453
lsdi2/ftp/africanamerican/010002588428
lsdi2/ftp/010002406236
lsdi2/ftp/000011115833
lsdi2/ftp/africanamerican/010002588861
lsdi2/ftp/africanamerican/010002588603
lsdi2/ftp/africanamerican/010002588725
lsdi2/ftp/010002701006
lsdi2/ftp/africanamerican/010002426551
lsdi2/ftp/010002406384
lsdi2/ftp/10002361042
lsdi2/ftp/010001066550
lsdi2/ftp/010002585821
lsdi2/ftp/10002335905
lsdi2/ftp/010002406243
lsdi2/ftp/010000894935
lsdi2/ftp/africanamerican/010001353431
lsdi2/ftp/africanamerican/000011909690
lsdi2/ftp/africanamerican/010002585879
lsdi2/ftp/010000154223
lsdi2/ftp/010000667804
lsdi2/ftp/010000666239
lsdi2/ftp/010001217020
lsdi2/ftp/010000709792
lsdi2/ftp/africanamerican/010002585909
lsdi2/ftp/africanamerican/010000427856
lsdi2/ftp/010000427817
lsdi2/ftp/010002405952
lsdi2/ftp/africanamerican/010002588441
lsdi2/ftp/010002702790
lsdi2/ftp/africanamerican/010001353136
lsdi2/ftp/010000894696
lsdi2/ftp/010002718070
lsdi2/ftp/africanamerican/010002585910
lsdi2/ftp/010000667892
lsdi2/ftp/africanamerican/010002588150
lsdi2/ftp/10002354672

**Comment by jcrompton42** [comment]
transferred
