### ISSUE TITLE
Transfer handful of South Asian Open Archives volumes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1729]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/010001182833
lsdi2/ftp/300000345425
lsdi2/ftp/000015180462
lsdi2/ftp/300000337656
lsdi2/ftp/010002563986
lsdi2/ftp/010002649610
lsdi2/ftp/010002649492
lsdi2/ftp/010002488577
lsdi2/ftp/010002621269
lsdi2/ftp/300000426242
lsdi2/ftp/300000433992
lsdi2/ftp/300000433996
lsdi2/ftp/300000433963
lsdi2/ftp/300000457522
lsdi2/ftp/300000434000
lsdi2/ftp/300000457861
lsdi2/ftp/300000457878
lsdi2/ftp/300000457812
lsdi2/ftp/300000457892

**Comment by jcrompton42** [comment]
transferred.
