### ISSUE TITLE
Transfer Kessler Reformation Books batch 3

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1730]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/300000098798
lsdi2/tesseract/Kessler/300000120650
lsdi2/tesseract/Kessler/300000120669
lsdi2/tesseract/Kessler/300000120670
lsdi2/tesseract/Kessler/300000197791
lsdi2/tesseract/Kessler/300000173903
lsdi2/tesseract/Kessler/300000223701
lsdi2/tesseract/Kessler/300000221015
lsdi2/tesseract/Kessler/300000272142
lsdi2/tesseract/Kessler/300000346318
lsdi2/tesseract/Kessler/300000488903
lsdi2/tesseract/Kessler/585443-10

**Comment by jcrompton42** [comment]
transferred
