### ISSUE TITLE
Develop a workflow for moving files from EFS into Glacier

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1731]
The [EFS and Glacier proposal](https://docs.google.com/document/d/1qarINqfGFSnLa6B8PMWiWvXyyvhILamcL3jE5uTfWpA/edit#heading=h.98wpffpufxts) was approved by Rosalyn in April, 2022.

DataSync is now available in AWS@Emory, so we can begin moving selected files from EFS into Glacier.

Workflow components needed:

- [x] Criteria for which files should move to Glacier
- [ ] Mechanism to identify specific objects (files and folders) that should move to Glacier 
- [x] File transfer interface
- [x] How to replicate directory structures within Glacier for human-readable access
- [ ] How to move files from Glacier back to EFS if needed (re-ingests, etc.)

Setup tasks

- [x] Create a new S3 Glacier Deep Archive bucket
- [x] Create a test DataSync task using arch 
- [x] Confirm options to delete after moving
- [ ] Confirm ability to reverse the transfer from Glacier back to EFS
- [x] Document how to run a task manually

**Comment by eporter23** [comment]
We assume this will be a manual process to identify which folders/files can be moved into Glacier. We also confirmed we will keep the same directory structure in EFS and Glacier for easier reference later (ingest CSV paths).

**Comment by jcrompton42** [comment]
Documented process of moving here https://wiki.emory.edu/pages/viewpage.action?spaceKey=DLPP&title=Datasync
