### ISSUE TITLE
Transfer new batch of catalogs, 2021-12-09

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1732]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/Aerospace_1973-1974
lsdi2/ftp/AlliedHealth_1973-1974
lsdi2/ftp/AlliedHealth_1974-1975
lsdi2/ftp/AlliedHealth_1975-1976
lsdi2/ftp/AlliedHealth_1976-1977
lsdi2/ftp/AlliedHealth_1977-1978
lsdi2/ftp/AlliedHealth_1978-1979
lsdi2/ftp/AlliedHealth_1979-1980
lsdi2/ftp/AlliedHealth_1980-1981
lsdi2/ftp/AlliedHealth_1981-1982
lsdi2/ftp/AlliedHealth_1987-1988
lsdi2/ftp/AlliedHealth_1988-1989
lsdi2/ftp/AlliedHealth_1989-1990
lsdi2/ftp/Bulletin_Tuition_Raise_1964
lsdi2/ftp/Business_1980-1981
lsdi2/ftp/Business_BBA_1960-1961
lsdi2/ftp/Business_BBA_1961-1963
lsdi2/ftp/Business_BBA_1963-1965
lsdi2/ftp/Business_BBA_1965-1967
lsdi2/ftp/Business_BBA_1966-1968
lsdi2/ftp/Business_BBA_1968-1970
lsdi2/ftp/Business_BBA_1970-1972
lsdi2/ftp/Business_BBA_1973-1975
lsdi2/ftp/Business_BBA_1975-1977
lsdi2/ftp/Business_BBA_1977-1979
lsdi2/ftp/Business_BBA_1979-1980
lsdi2/ftp/Business_BBA_1987-1988
lsdi2/ftp/Business_BBA_1988-1989
lsdi2/ftp/Business_BBA_1989-1990
lsdi2/ftp/Business_BBA_1990-1992
lsdi2/ftp/Business_MBA_1960-1961
lsdi2/ftp/Business_MBA_1965-1967
lsdi2/ftp/Business_MBA_1967-1969
lsdi2/ftp/Business_MBA_1973-1975
lsdi2/ftp/Business_MBA_1975-1977
lsdi2/ftp/Business_MBA_1981-1982
lsdi2/ftp/Business_MBA_1983-1984
lsdi2/ftp/Business_MBA_1984-1985
lsdi2/ftp/Business_MBA_1985-1986
lsdi2/ftp/Business_MBA_1986-1987
lsdi2/ftp/Business_MBA_1987-1988
lsdi2/ftp/Business_MBA_1988-1989
lsdi2/ftp/Business_MBA_1989-1990
lsdi2/ftp/Business_MBA_1990-1991
lsdi2/ftp/Business_MBA_1991-1992
lsdi2/ftp/Business_MBA_1993-1995
lsdi2/ftp/Business_MBA_1995-1997
lsdi2/ftp/College_1960-1961
lsdi2/ftp/College_1961-1962
lsdi2/ftp/College_1962-1963
lsdi2/ftp/College_1963-1964
lsdi2/ftp/College_1964-1965
lsdi2/ftp/College_1965-1966
lsdi2/ftp/College_1966-1967
lsdi2/ftp/College_1967-1968
lsdi2/ftp/College_1973-1974
lsdi2/ftp/College_1974-1975
lsdi2/ftp/College_1975-1976
lsdi2/ftp/College_1977-1978
lsdi2/ftp/College_1978-1979
lsdi2/ftp/College_1979-1980
lsdi2/ftp/College_1980-1981
lsdi2/ftp/College_1981-1982
lsdi2/ftp/College_1982-1983
lsdi2/ftp/College_1983-1984
lsdi2/ftp/College_1984-1985
lsdi2/ftp/College_1985-1986
lsdi2/ftp/College_1986-1988
lsdi2/ftp/College_1988-1990
lsdi2/ftp/College_1990-1992
lsdi2/ftp/College_1992-1994
lsdi2/ftp/College_1994-1996
lsdi2/ftp/catalogs/College_1997-1999
lsdi2/ftp/College_2003-2005
lsdi2/ftp/College_2005-2007
lsdi2/ftp/College_2007-2009
lsdi2/tesseract/EUACatalogs/College/College_2011-2012
lsdi2/ftp/Dentistry_1961-1963
lsdi2/ftp/Dentistry_1963-1965
lsdi2/ftp/Dentistry_1965-1966
lsdi2/ftp/Dentistry_1973-1974
lsdi2/ftp/Dentistry_1974-1975
lsdi2/ftp/Dentistry_1975-1976
lsdi2/ftp/Dentistry_1977-1978
lsdi2/ftp/Dentistry_1978-1979
lsdi2/ftp/Dentistry_1979-1980
lsdi2/ftp/Dentistry_1980-1981
lsdi2/ftp/Dentistry_1981-1982
lsdi2/tesseract/EUACatalogs/College/College_1999-2000
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2006-2007
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2011-2012
lsdi2/ftp/GSAS_1960-1961
lsdi2/ftp/GSAS_1961-1962
lsdi2/ftp/GSAS_1962-1963
lsdi2/ftp/GSAS_1962-1963
lsdi2/ftp/GSAS_1963-1964
lsdi2/ftp/GSAS_1964-1965
lsdi2/ftp/GSAS_1965-1966
lsdi2/ftp/GSAS_1970-1971
lsdi2/ftp/GSAS_1971-1972
lsdi2/ftp/GSAS_1972-1973
lsdi2/ftp/GSAS_1973-1974
lsdi2/ftp/GSAS_1974-1975
lsdi2/ftp/GSAS_1975-1976
lsdi2/ftp/GSAS_1976-1977
lsdi2/ftp/GSAS_1977-1978
lsdi2/ftp/GSAS_1978-1979
lsdi2/ftp/GSAS_1979-1980
lsdi2/ftp/GSAS_1980-1981
lsdi2/ftp/GSAS_1981-1982
lsdi2/ftp/GSAS_1986-1987
lsdi2/ftp/GSAS_1987-1988
lsdi2/ftp/GSAS_1988-1989
lsdi2/ftp/GSAS_1989-1990
lsdi2/ftp/GSAS_2002-2003
lsdi2/ftp/GSAS_2005-2006
lsdi2/ftp/GSAS_2006-2007
lsdi2/ftp/ILA_1961-1962
lsdi2/ftp/ILA_1962-1963
lsdi2/ftp/ILA_1963-1964
lsdi2/ftp/ILA_1964-1965
lsdi2/ftp/ILA_1965-1966
lsdi2/ftp/ILA_1970-1971
lsdi2/ftp/ILA_1971-1972
lsdi2/ftp/ILA_1973-1974
lsdi2/ftp/ILA_1974-1975
lsdi2/ftp/Law_1960-1961
lsdi2/ftp/Law_1961-1962
lsdi2/ftp/Law_1962-1963
lsdi2/ftp/Law_1962-1963
lsdi2/ftp/Law_1963-1964
lsdi2/ftp/Law_1964-1965
lsdi2/ftp/Law_1965-1966
lsdi2/ftp/Law_1970-1971
lsdi2/ftp/Law_1971-1972
lsdi2/ftp/Law_1972-1973
lsdi2/ftp/Law_1973-1974
lsdi2/ftp/Law_1974-1975
lsdi2/ftp/Law_1975-1976
lsdi2/ftp/Law_1976
lsdi2/ftp/Law_1977
lsdi2/ftp/Law_1977-1978
lsdi2/ftp/Law_1978-1979
lsdi2/ftp/Law_1979-1980
lsdi2/ftp/Law_1980-1981
lsdi2/ftp/Law_1981-1982
lsdi2/ftp/Law_1982-1983
lsdi2/ftp/Law_1985-1986
lsdi2/ftp/Law_1986-1987
lsdi2/ftp/Law_1986-1988
lsdi2/ftp/Law_1988-1989
lsdi2/ftp/Law_1989-1990
lsdi2/ftp/Librarianship_1970-1971
lsdi2/ftp/Librarianship_1971-1972
lsdi2/ftp/Librarianship_1972-1973
lsdi2/ftp/Librarianship_1973-1974
lsdi2/ftp/Librarianship_1974-1975
lsdi2/ftp/Librarianship_1977-1978
lsdi2/ftp/Librarianship_1978-1979
lsdi2/ftp/Librarianship_1979-1980
lsdi2/ftp/Library_1981-1982
lsdi2/ftp/Library_1985-1986
lsdi2/ftp/Library_1986-1987
lsdi2/ftp/Medicine_1970-1971
lsdi2/ftp/Medicine_1971-1972
lsdi2/ftp/Medicine_1972-1973
lsdi2/ftp/Medicine_1973-1974
lsdi2/ftp/Medicine_1974-1975
lsdi2/ftp/Medicine_1975-1976
lsdi2/ftp/Medicine_1976-1977
lsdi2/ftp/Medicine_1977-1978
lsdi2/ftp/Medicine_1978-1979
lsdi2/ftp/Medicine_1979-1980
lsdi2/ftp/Medicine_1980-1981
lsdi2/ftp/Medicine_1981-1982
lsdi2/ftp/Medicine_1982-1983
lsdi2/ftp/Medicine_1985-1986
lsdi2/ftp/Medicine_1987-1988
lsdi2/ftp/Medicine_1988-1989
lsdi2/ftp/Medicine_1989-1990
lsdi2/ftp/Medicine_1995-1996
lsdi2/ftp/Nursing_1970-1971
lsdi2/ftp/Nursing_1971-1972
lsdi2/ftp/Nursing_1972-1973
lsdi2/ftp/Nursing_1973-1974
lsdi2/ftp/Nursing_1974-1975
lsdi2/ftp/Nursing_1975-1976
lsdi2/ftp/Nursing_1976-1977
lsdi2/ftp/Nursing_1977-1978
lsdi2/ftp/Nursing_1978-1979
lsdi2/ftp/Nursing_1979-1980
lsdi2/ftp/Nursing_1980-1981
lsdi2/ftp/Nursing_1981-1982
lsdi2/ftp/Nursing_1982-1983
lsdi2/ftp/Nursing_1985-1986
lsdi2/ftp/Nursing_1986-1987
lsdi2/ftp/Nursing_1987-1988
lsdi2/ftp/Nursing_1988-1989
lsdi2/ftp/Nursing_1989-1990
lsdi2/ftp/Nursing_1995-1996
lsdi2/ftp/Nursing_1996-1997
lsdi2/ftp/Nursing_1997-1998
lsdi2/ftp/Oxford_1970-1971
lsdi2/ftp/Oxford_1971-1972
lsdi2/ftp/Oxford_1972-1973
lsdi2/ftp/Oxford_1973-1974
lsdi2/ftp/Oxford_1974-1975
lsdi2/ftp/Oxford_1976-1978
lsdi2/ftp/Oxford_1977-1979
lsdi2/ftp/Oxford_1977-1979
lsdi2/ftp/Oxford_1992-1994
lsdi2/ftp/Oxford_1998-1999
lsdi2/ftp/Public_Health_1987-1988
lsdi2/ftp/Public_Health_1988-1989
lsdi2/ftp/Public_Health_1989-1990
lsdi2/ftp/Public_Health_1995-1996
lsdi2/ftp/Public_Health_1996-1997
lsdi2/ftp/Public_Health_1997-1998
lsdi2/ftp/Public_Health_1999-2000
lsdi2/ftp/Public_Health_2003-2004
lsdi2/ftp/Public_Health_2004-2005
lsdi2/ftp/Public_Health_2006-2007
lsdi2/ftp/Register_1961-1962
lsdi2/ftp/Register_1963-1964
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2000-2001
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2007-2008
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2008-2009
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2009-2010
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2011-2012
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2012-2013
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2013-2014
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2014-2015
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2015-2016
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2000-2001
lsdi2/tesseract/EUACatalogs/Summer/Summer_2001
lsdi2/tesseract/EUACatalogs/Summer/Summer_2002
lsdi2/tesseract/EUACatalogs/Summer/Summer_2003
lsdi2/tesseract/EUACatalogs/Summer/Summer_2004
lsdi2/tesseract/EUACatalogs/Summer/Summer_2005
lsdi2/tesseract/EUACatalogs/Summer/Summer_2006
lsdi2/tesseract/EUACatalogs/Summer/Summer_2007
lsdi2/tesseract/EUACatalogs/Summer/Summer_2008
lsdi2/tesseract/EUACatalogs/Summer/Summer_2009
lsdi2/tesseract/EUACatalogs/Summer/Summer_2011
lsdi2/tesseract/EUACatalogs/Summer/Summer_2012
lsdi2/tesseract/EUACatalogs/Summer/Summer_2013
lsdi2/ftp/Summer_1960
lsdi2/ftp/Summer_1961
lsdi2/ftp/Summer_1962
lsdi2/ftp/Summer_1963
lsdi2/ftp/Summer_1964
lsdi2/ftp/Summer_1965-1966
lsdi2/ftp/Summer_1970
lsdi2/ftp/Summer_1971
lsdi2/ftp/Summer_1972
lsdi2/ftp/Summer_1973
lsdi2/ftp/Summer_1974
lsdi2/ftp/Summer_1977
lsdi2/ftp/Summer_1979
lsdi2/ftp/Summer_School_Bulletin_1980
lsdi2/ftp/Summer_School_Bulletin_1985
lsdi2/ftp/Summer_School_Bulletin_1986
lsdi2/ftp/Summer_School_Bulletin_1988
lsdi2/ftp/Summer_School_Bulletin_1989
lsdi2/ftp/Summer_School_Bulletin_1990
lsdi2/ftp/Summer_School_Bulletin_1998
lsdi2/ftp/Summer_School_Bulletin_1999
lsdi2/ftp/Theology_1960-1961
lsdi2/ftp/Theology_1961-1963
lsdi2/ftp/Theology_1963-1964
lsdi2/ftp/Theology_1964-1965
lsdi2/ftp/Theology_1965-1966
lsdi2/ftp/Theology_1970-1971
lsdi2/ftp/Theology_1971-1972
lsdi2/ftp/Theology_1972-1973
lsdi2/ftp/Theology_1973-1974
lsdi2/ftp/Theology_1974-1975
lsdi2/ftp/Theology_1976-1977
lsdi2/ftp/Theology_1977-1978
lsdi2/ftp/Theology_1979-1980
lsdi2/ftp/Theology_1980-1981
lsdi2/ftp/Theology_1981-1982
lsdi2/ftp/Theology_1982-1983
lsdi2/ftp/Theology_1983-1984
lsdi2/ftp/Theology_1984-1985
lsdi2/ftp/Theology_1985-1986
lsdi2/ftp/Theology_1986-1987
lsdi2/ftp/Theology_1987-1988
lsdi2/ftp/Theology_1988-1989
lsdi2/ftp/Theology_1989-1990
lsdi2/ftp/Theology_1990-1991
lsdi2/ftp/Theology_1991-1992
lsdi2/ftp/Theology_1992-1993
lsdi2/ftp/Theology_1993-1994
lsdi2/ftp/Theology_1994-1995
lsdi2/ftp/Theology_1995-1996
lsdi2/ftp/Theology_1996-1997
lsdi2/ftp/Theology_1997-1998
lsdi2/ftp/Theology_1998-1999
lsdi2/ftp/Theology_2008-2009
lsdi2/ftp/Theology_2010-2011
lsdi2/ftp/Theology_2011-2012
lsdi2/ftp/Theology_2012-2013
lsdi2/ftp/Theology_2013-2014

**Comment by jcrompton42** [comment]
transferred

**Comment by jcrompton42** [comment]
oops, missed some error messages, rerunning transfer script

**Comment by kmichaelis** [comment]
@jcrompton42 are these still transferring?

**Comment by jcrompton42** [comment]
@kmichaelis yes they are, sorry for the inconvenience

**Comment by kmichaelis** [comment]
@jcrompton42 not a problem, just checking!

**Comment by jcrompton42** [comment]
Now these are transferred.
