### ISSUE TITLE
Transfer folders 1-5 of the Barbara Chase-Riboud Papers

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1737]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F001
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F002
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F003
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F004
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F005

**Comment by jcrompton42** [comment]
transferred
