### ISSUE TITLE
Transfer folders 6-11, 13 of the Barbara Chase-Riboud Papers

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1743]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F006
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F007
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F008
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F009
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F010
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F011
dmfiles/MARBL/Manuscripts/MSS_1292_Chase-Riboud/B001/F013

**Comment by jcrompton42** [comment]
transferred
