### ISSUE TITLE
Transfer a batch of Emory course catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1747]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/Adult_Program_1944
lsdi2/ftp/Bulletin_1940
lsdi2/ftp/Bulletin_1940_Vol.26_No.9
lsdi2/ftp/Bulletin_1944
lsdi2/ftp/Bulletin_1946
lsdi2/ftp/Business_1940
lsdi2/ftp/Business_1941
lsdi2/ftp/Business_1942
lsdi2/ftp/Business_1945
lsdi2/ftp/Business_1946
lsdi2/ftp/Business_1947
lsdi2/ftp/Business_1948
lsdi2/ftp/Business_1949
lsdi2/ftp/Business_1980-1981
lsdi2/ftp/Business_MBA_1970-1972
lsdi2/ftp/Business_MBA_1977-1979
lsdi2/ftp/Business_MBA_1979-1971
lsdi2/ftp/Calendar_1947
lsdi2/ftp/College_1945
lsdi2/ftp/College_1948
lsdi2/ftp/College_1949
lsdi2/ftp/College_1968-1969
lsdi2/ftp/College_1969-1970
lsdi2/ftp/Courage_1946
lsdi2/ftp/Dentistry_1945
lsdi2/ftp/Dentistry_1946
lsdi2/ftp/Dentistry_1947
lsdi2/ftp/Dentistry_1948
lsdi2/ftp/Dentistry_1949
lsdi2/ftp/Dentistry_1966-1967
lsdi2/ftp/Dentistry_1967-1968
lsdi2/ftp/Dentistry_1968-1969
lsdi2/ftp/Dentistry_1969-1970
lsdi2/ftp/Dentistry_MSD_1966-1968
lsdi2/ftp/Dentistry_MSD_1969-1970
lsdi2/ftp/Dentistry_Study_1946
lsdi2/ftp/Emory_Library_1948
lsdi2/ftp/Emory-at-Oxford_1945
lsdi2/ftp/Emory-at-Oxford_1946
lsdi2/ftp/Emory-at-Oxford_1947
lsdi2/ftp/Emory-at-Oxford_1948
lsdi2/ftp/Emory-at-Valdosta_1947
lsdi2/ftp/Faculty_Publications_1948
lsdi2/ftp/General_Catalogue_1940
lsdi2/ftp/General_Catalogue_1941
lsdi2/ftp/General_Catalogue_1942
lsdi2/ftp/General_Catalogue_1943
lsdi2/ftp/General_Catalogue_1944
lsdi2/ftp/General_Catalogue_1945
lsdi2/ftp/General_Catalogue_1947
lsdi2/ftp/Govt_Service_1941
lsdi2/ftp/Greatness_1947
lsdi2/ftp/GSAS_1941
lsdi2/ftp/GSAS_1947
lsdi2/ftp/GSAS_1948
lsdi2/ftp/GSAS_1966-1967
lsdi2/ftp/GSAS_1967-1968
lsdi2/ftp/GSAS_1967-1969
lsdi2/ftp/GSAS_1968-1969
lsdi2/ftp/GSAS_1969-1970
lsdi2/borndigital/EU_Catalogs/GSAS_2010-2011
lsdi2/borndigital/EU_Catalogs/GSAS_2014-2015
lsdi2/ftp/Homecoming_1947
lsdi2/ftp/Homecoming_1948
lsdi2/ftp/ILA_1966-1967
lsdi2/ftp/ILA_1967-1968
lsdi2/ftp/ILA_1968-1969
lsdi2/ftp/ILA_1969-1970
lsdi2/ftp/ILA_1972-1973
lsdi2/ftp/Journalism_1947
lsdi2/ftp/Law_1940
lsdi2/ftp/Law_1941
lsdi2/ftp/Law_1942
lsdi2/ftp/Law_1943
lsdi2/ftp/Law_1944
lsdi2/ftp/Law_1945
lsdi2/ftp/Law_1946
lsdi2/ftp/Law_1947
lsdi2/ftp/Law_1948
lsdi2/ftp/Law_1949
lsdi2/ftp/Law_1966-1967
lsdi2/ftp/Law_1967-1968
lsdi2/ftp/Law_1968-1969
lsdi2/ftp/Law_1969-1970
lsdi2/borndigital/EU_Catalogs/Law_2014-2015
lsdi2/ftp/Law_Alumni_1948
lsdi2/ftp/Lectures_1947
lsdi2/ftp/Librarianship_1945
lsdi2/ftp/Librarianship_1948
lsdi2/ftp/Librarianship_1949
lsdi2/ftp/Librarianship_1960-1961/OCR
lsdi2/ftp/Librarianship_1961-1962/OCR
lsdi2/ftp/Librarianship_1962-1963/OCR
lsdi2/ftp/Librarianship_1963-1964/OCR
lsdi2/ftp/Librarianship_1964-1965/OCR
lsdi2/ftp/Librarianship_1965-1966/OCR
lsdi2/ftp/Librarianship_1966-1967
lsdi2/ftp/Librarianship_1967-1968
lsdi2/ftp/Librarianship_1968-1969
lsdi2/ftp/Librarianship_1969-1970
lsdi2/ftp/Library_1940
lsdi2/ftp/Library_1941
lsdi2/ftp/Library_1942
lsdi2/ftp/Library_1943
lsdi2/ftp/Library_1944
lsdi2/ftp/Library_1946
lsdi2/ftp/Library_1947
lsdi2/ftp/Medical_Alumni_1949
lsdi2/ftp/Medical_Education_1945
lsdi2/ftp/Medicine_1940
lsdi2/ftp/Medicine_1941
lsdi2/ftp/Medicine_1942
lsdi2/ftp/Medicine_1943
lsdi2/ftp/Medicine_1944
lsdi2/ftp/Medicine_1945
lsdi2/ftp/Medicine_1945
lsdi2/ftp/Medicine_1947
lsdi2/ftp/Medicine_1948
lsdi2/ftp/Medicine_1949
lsdi2/ftp/Medicine_1960-1961/OCR
lsdi2/ftp/Medicine_1961-1962/OCR
lsdi2/ftp/Medicine_1962-1963/OCR
lsdi2/ftp/Medicine_1963-1964/OCR
lsdi2/ftp/Medicine_1964-1965/OCR
lsdi2/ftp/Medicine_1965-1966/OCR
lsdi2/ftp/Medicine_1966-1967
lsdi2/ftp/Medicine_1967-1968
lsdi2/ftp/Medicine_1968-1969
lsdi2/ftp/Medicine_1969-1970
lsdi2/borndigital/EU_Catalogs/Medicine_2009-2010
lsdi2/ftp/Medicine_Faculty_Pubs_1948
lsdi2/ftp/Medicine_Publications_1942
lsdi2/ftp/Medicine_Publications_1943
lsdi2/ftp/Medicine_Publications_1944
lsdi2/ftp/Medicine_Publications_1946
lsdi2/ftp/Medicine_Publications_1947
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2006-2007
lsdi2/tesseract/EUACatalogs/GBS/ModExecMBA_2011-2012
lsdi2/ftp/Nursing_1941
lsdi2/ftp/Nursing_1945
lsdi2/ftp/Nursing_1946
lsdi2/ftp/Nursing_1947
lsdi2/ftp/Nursing_1949
lsdi2/ftp/Nursing_1960-1961/OCR
lsdi2/ftp/Nursing_1961-1962/OCR
lsdi2/ftp/Nursing_1962-1963/OCR
lsdi2/ftp/Nursing_1963-1964/OCR
lsdi2/ftp/Nursing_1964-1965/OCR
lsdi2/ftp/Nursing_1965-1966/OCR
lsdi2/ftp/Nursing_1966-1967
lsdi2/ftp/Nursing_1967-1968
lsdi2/ftp/Nursing_1968-1969
lsdi2/ftp/Nursing_1969-1970
lsdi2/ftp/Old_Oxford_1948
lsdi2/ftp/Oxford_1960-1961/OCR
lsdi2/ftp/Oxford_1961-1962/OCR
lsdi2/ftp/Oxford_1962-1963/OCR
lsdi2/ftp/Oxford_1963-1965/OCR
lsdi2/ftp/Oxford_1965-1967/OCR
lsdi2/ftp/Oxford_1966-1967
lsdi2/ftp/Oxford_1967-1968
lsdi2/ftp/Oxford_1968-1969
lsdi2/ftp/Oxford_1969-1970
lsdi2/ftp/Oxford_1977-1979
lsdi2/ftp/Partnership_1946
lsdi2/ftp/Prep_for_College_1946
lsdi2/ftp/Register_1948
lsdi2/ftp/Register_1949
lsdi2/ftp/Register_1963-1964
lsdi2/ftp/Report_1944
lsdi2/ftp/Report_1945
lsdi2/ftp/Shrine_1941
lsdi2/ftp/Special_Announcements_1944
lsdi2/ftp/Special_Issue_1946
lsdi2/ftp/Statement_1946
lsdi2/ftp/Student_Theses_1949
lsdi2/ftp/Summer_1940
lsdi2/ftp/Summer_1941
lsdi2/ftp/Summer_1942
lsdi2/ftp/Summer_1945
lsdi2/ftp/Summer_1947
lsdi2/ftp/Summer_1948
lsdi2/ftp/Summer_1949
lsdi2/ftp/Summer_1966
lsdi2/ftp/Summer_1967
lsdi2/ftp/Summer_1968
lsdi2/ftp/Summer_1969-1970
lsdi2/ftp/Summer_Program_Teachers_1945
lsdi2/ftp/Summer_Teachers_1944
lsdi2/ftp/Summer_Teachers_1947
lsdi2/ftp/Supplement_3_1941
lsdi2/ftp/Supplement_5_1941
lsdi2/ftp/Supplement_1942
lsdi2/ftp/Supplement_1945
lsdi2/ftp/Theology_1940
lsdi2/ftp/Theology_1941
lsdi2/ftp/Theology_1942
lsdi2/ftp/Theology_1943
lsdi2/ftp/Theology_1944
lsdi2/ftp/Theology_1946
lsdi2/ftp/Theology_1946_no14
lsdi2/ftp/Theology_1947
lsdi2/ftp/Theology_1948
lsdi2/ftp/Theology_1949
lsdi2/ftp/Theology_1967-1968
lsdi2/ftp/Theology_1968-1969
lsdi2/ftp/Theology_1969-1970
lsdi2/ftp/Theology_1988-1989
lsdi2/ftp/Theology_News_2_1944
lsdi2/ftp/Theology_News_17_1941
lsdi2/ftp/Theology_News_1941
lsdi2/ftp/Theology_News_1941
lsdi2/ftp/Theology_News_1945-1(v31no.2)
lsdi2/ftp/Theology_News_v.31_no.14_1945
lsdi2/ftp/Theology_Summer_1941
lsdi2/ftp/Theology_Summer_1942
lsdi2/ftp/Theology_Training_1946
lsdi2/ftp/Three_Summer_Series_1947
lsdi2/ftp/Valdosta_1940
lsdi2/ftp/Valdosta_1941

**Comment by jcrompton42** [comment]
transferred
