### ISSUE TITLE
Create Role(s) for Installing Java through S3

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#176]
Oracle Java changing the way you can download from their servers on 4/16/2019.
As a consequence the UCLA role that installs Java is no longer working.
This is a good opportunity to create a role that install Java from a bucket in s3.

- [x] Create role to manage s3 bucket
- [x] Create role to manage IAM role and give it permissions to access the s3 bucket
- [x] Rebuild EC2s with new IAM role
- [x] Test out java install with binaries being in s3

**Comment by tmiles2** [comment]
@SolomonHD Can we close this ticket?
