### ISSUE TITLE
Transfer Early Emory Class Photographs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1765]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Oxford_eecp
dmfiles/Libraries/Oxford_SpecColl/OX-S020

**Comment by jcrompton42** [comment]
transferred
