### ISSUE TITLE
Transfer remaining Oxford Spokesman files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1767]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Oxford_Spokesman/Spokesman_1966Fall-1
lsdi2/tesseract/Oxford_Spokesman/Spokesman_1966Fall-2
lsdi2/tesseract/Oxford_Spokesman/Spokesman_1966Spring
lsdi2/tesseract/Oxford_Spokesman/Spokesman_2015-2016
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19660600
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19661200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670300
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670500
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19670600
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19840913
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19880900
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19881100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19881200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19890400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950206
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950228
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950401
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950401_Special
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950426
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19950911
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19951012
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19951109
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19960308
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19960419
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19960920
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19961018
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19961206
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19970214
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19970905
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19971201
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19980305
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19980417
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19991101
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20001117
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20001213
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20010213
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20010401
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20010430
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20010928
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20011031
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20011126
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20011214
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20020214
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20020317
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20020415
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20021000
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20021100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20030400-1
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20030400-2
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20040929
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20041025
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20041119
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20050200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20050300
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20050400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20051000
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20051200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20060200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20060300
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20060400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20061000
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20070200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20070400
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20100200-6
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20100200-7
lsdi2/tesseract/Oxford_Spokesman/Spokesman_20110400

**Comment by jcrompton42** [comment]
transferred
