### ISSUE TITLE
Support custom terms in external vocabs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#177]
- [ ] Allow a user to type in their own terms in select2 for certain fields:
* Institution (D1)
* Subject – Time Periods (D33)
* Role – Creator (D45)
* Role – Contributor (D46)
* Role Sponsor (D50)
* Role - Grant/Funding Agency (D53)
* Rights Holder (D58)
- [ ] Ensure those terms save correctly.
- [ ] Create/Update a feature test to show this works.

**Comment by rotated8** [comment]
See: https://select2.org/tagging

**Comment by eporter23** [comment]
I tested the list above. D53 Grant/Funding Agency is not configured properly but other fields are successful.

**Comment by eporter23** [comment]
@devanshu-m tested and confirmed
