### ISSUE TITLE
CSV imports running overnight stop without sidekiq errors

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1770]
**Describe the bug**
CSV imports in test and production have been failing to complete. This appears to happen when they are running between 8pm and 10pm. The latest instance occurred in test, where an ingest stopped attaching new filesets at about 9:15 PM.

**To Reproduce**
1. Run a book ingest in late afternoon
2. Monitor book ingest progress
3. See book ingest stopping without attaching all filesets
4. Check sidekiq and see no dead jobs related to AttachFilesToWork. There are sometimes IngestJob failures due to empty files which are common, but these do not result in imports failing. ` Unable to find binary value with key "da39a3ee5e6b4b0d3255bfef95601...`

Most recent example: https://curate-test.library.emory.edu/concern/curate_generic_works/846d2547r6-cor?locale=en

**Expected behavior**
The ingest should attach all filesets in the job, or show errors indicating why the import has not completed.

**Screenshots**
For the most recent incomplete ingest in test, there are no relevant dead jobs in the queue to indicate why the ingest stopped running.
![Screen Shot 2022-02-11 at 8.34.35 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9395e322-04d1-45f8-8df2-50189be5d8c2)

Stack trace from production 2/8/22:
[https://app.zenhub.com/files/158455630/54a08734-692b-41c5-b848-1027144aca38/download](https://app.zenhub.com/files/158455630/54a08734-692b-41c5-b848-1027144aca38/download)

**Additional context**
Kathryn and Beth have been seeing this occur in production and it is also occurring in test with 3.1.

**Comment by eporter23** [comment]
Additional notes from @kmichaelis for recent production occurrences: Ingest started at:
1/31, 8:53 PM. Attached 23 out of 118 pages.
Same work, 2/1, 8:42 PM. Attached 29 pages.
2/7, 9:09 PM. Attached 99 out of 132 pages.
2/8, 9:58 PM. Same work. Attached 90 pages.

**Comment by bwatson78** [comment]
Checking the LDP gem's procedure it fails on...

**Comment by eporter23** [comment]
Per slack discussions, it appears sidekiq has been restarting. This causes jobs to disappear with no option to resume them later.
