### ISSUE TITLE
Semi-controlled properties

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#178]
The system of record id field is semi-controlled. It consists of a controlled prefix, and an uncontrolled id. The stored value for the property should be the concatenation of the prefix, a colon, and the uncontrolled id.

- [ ] Research if Select2 support these requirements
- [ ] If it can, implement them using Select2
- [ ] If it cannot, validate using regex and the prefixes from the attached epic.
- [ ] The form field should show an example.
- [ ] Create/Update a feature test for this.

**Comment by eporter23** [comment]
6/10: discussed pushing this to 0.5. The goal is to enforce some type of standard prefix convention for legacy/other system IDs, but this doesn't have to be done in 0.3.

**Comment by eporter23** [comment]
Relate this to epic #203 Metadata Form Enhancements (can't assign through UI for some reason)

**Comment by eporter23** [comment]
Closing because we have been entering the prefixes manually for several years now.
