### ISSUE TITLE
Editing collections in 3.3 returns "the change you wanted was rejected (422)"

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1780]
**Describe the bug**
Original bug noticed: While trying to assign the Langmuir banner image, which was deleted as part of a previous bug fix, Curate returns an error message after the save is submitted
Update: trying to make any edits to a collection seems to return this error, whether it is metadata only or assigning images, etc.

**To Reproduce**
1. Go to Dashboard > Collections > Langmuir > Edit collection (https://curate-test.library.emory.edu/dashboard/collections/914nk98sfv-cor?locale=en)
2. Click on Branding
3. Go to the Banner section, and upload an image
4. See the assigned filename after the upload finishes and click save
5. See error: "the change you wanted was rejected (422)"

**Expected behavior**
The collection banner should be uploaded and previewable on the Edit Collection screen, and the banner should be visible on the Public View of Collection page

**Screenshots**
![Screen Shot 2022-02-23 at 10.49.18 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/106ca982-4954-4823-acc6-f4b0c2872a19)

**Additional context**
This occurs on 2/2 collections I've tried to assign a banner to. The same error occurs when trying to set the collection's thumbnail image.

**Comment by eporter23** [comment]
@bwatson78 I'm still getting a mix of "We're sorry..." errors plus the "rejected" error when trying to edit either collection metadata or branding images when using the workaround we talked about. Maybe we can pair up again to walk through it?

**Comment by bwatson78** [comment]
Hyrax has seen the same issue in their environments. [This ticket ](https://github.com/samvera/hyrax/issues/5470) was created at the request of Chris Colvard.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1795

**Comment by eporter23** [comment]
Closing because this doesn't seem to apply in newer 3.4.2.
