### ISSUE TITLE
Non-admin users should not see Add to Collection button on works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1783]
**Describe the bug**
When a user is assigned to a Viewer-level group permission, they should not see the Add to Collection button when viewing a work

See original work ticket: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/1504

**To Reproduce**
1. Login as a user (e.g. tezprox) assigned to a viewer group (e.g. Rose Viewers)
2. Click on any work
3. See the Add to Collection button above the Universal Viewer

**Expected behavior**
This button should not appear to users who are not in the admin level group.

**Screenshots**
Curate test:
![Screen Shot 2022-02-25 at 10.03.04 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e1689650-67c8-42fb-aad1-34e449890ab1)

Curate prod behavior:
![Screen Shot 2022-02-25 at 10.04.47 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/bf1f58bd-a5e0-4584-a25c-af328702104d)

**Additional context**
There are other admin-only options on the View Work page that are suppressed such as regenerate manifest, and these are behaving as expected.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1786

**Comment by eporter23** [comment]
Looks good, thanks!
