### ISSUE TITLE
Editing some collections' metadata returns "We're sorry..." error on save 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1796]
**Describe the bug**
For some collections we cannot save changes when editing metadata.

**To Reproduce**
1. Go to Dashboard > Collections
2. [Select the Robert Langmuir... collection and click Edit](https://curate-test.library.emory.edu/dashboard/collections/914nk98sfv-cor/edit?locale=en) from the actions dropdown. 
3. Make a minor edit to the metadata for the Description field
4. Save your change
5. See the generic application error.

This occurs on [Robert Langmuir...](https://curate-test.library.emory.edu/dashboard/collections/914nk98sfv-cor/edit?locale=en), [Yellowbacks](https://curate-test.library.emory.edu/dashboard/collections/706g1jwsv6-cor/edit?locale=en), and [Health Sciences artifacts](https://curate-test.library.emory.edu/dashboard/collections/5053ffbg7n-cor/edit?locale=en#description) collections when trying to edit.

**Expected behavior**
A user should be able to edit metadata and save the changes, then see a green banner saying the collection was successfully updated.

**Screenshots**
Unsuccessful attempt:
![Screen Shot 2022-03-03 at 4.55.44 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/306361a8-74b6-4cdc-b352-ee359f5656d4)

Successful edit on a different collection
![Screen Shot 2022-03-04 at 9.04.51 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a6e22438-7fe5-427f-8ecb-740669eacd91)

**Additional context**
Seems similar to what we saw in #1757 which was resolved in 3.1. Without testing all the collections, I can't confirm, but 3/3 that show this error already had banner images assigned through our new method. I do seem to be able to edit metadata for collections that don't have banner images assigned e.g. [Health Sciences Test Collection](https://curate-test.library.emory.edu/dashboard/collections/3720cfxpzv-cor/edit?locale=en).

**Comment by bwatson78** [comment]
I have created a ticket with Samvera for this issue. It appears in their Nurax instance, as well. https://github.com/samvera/hyrax/issues/5501

**Comment by bwatson78** [comment]
I have closed the ticket referenced above because the most recent commit of Hyrax (`1467a570cd2daf8fb063037c0858690452ad0a58`) seems to correct the issue.

**Comment by eporter23** [comment]
Seems to be okay in 3.4.2 upgrade testing so I'll close this.
