### ISSUE TITLE
Transfer Civil War Collection box 2 and 3 files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1805]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/B002
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/B003

**Comment by jcrompton42** [comment]
transferred
