### ISSUE TITLE
Re-transfer small batch of catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1806]
Some catalogs apparently did not transfer successfully to EFS in their previous batches--I discovered upon trying to ingest these that only the OCR subfolders had been successfully copied.

Please re-transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/Nursing_1965-1966
lsdi2/ftp/Nursing_1964-1965
lsdi2/ftp/Nursing_1963-1964
lsdi2/ftp/Nursing_1962-1963
lsdi2/ftp/Nursing_1961-1962
lsdi2/ftp/Nursing_1960-1961
lsdi2/ftp/Oxford_1961-1962
lsdi2/ftp/Theology_News_1941
lsdi2/ftp/Theology_News_1941
lsdi2/ftp/Theology_News_1945-1(v31no.2)
lsdi2/ftp/Theology_News_no.31_v.14_1945

**Comment by jcrompton42** [comment]
checking on my script and retransferring, by lsdi2/ftp/Theology_News_v.31_no.14_1945/ do you mean actually lsdi2/ftp/Theology_News_v.31_no.14_1945 or are we missing some files?
