### ISSUE TITLE
Transfer last batch of Oxford Spokesman volumes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1818]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Oxford_Spokesman/Spokesman_19930303
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19930402
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19930426
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19930921
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19931016
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19931115
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19931130
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19940207
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19940415
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19940426
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19940929
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19941014
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19941027
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19941202

**Comment by jcrompton42** [comment]
Transferred
