### ISSUE TITLE
Re-transfer large batch of Yellowbacks to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1821]
Hi Beth, these directories are all Yellowbacks that were supposed to be transferred to EFS during phase 1 migration for the repository. I'm not sure what happened, but the files we need to ingest these volumes are not there. Many, if not all, of these directories do exist on EFS, but they only contain thumbnails, PDFs, and XML files, and I figured it would be easier to just completely overwrite all of these with the appropriate directories from Isilon rather than trying to keep the PDFs on EFS in place.

Let me know if you have any questions about this or if it doesn't make sense.

Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm03030652-2179/ocm03030652
lsdi/diesel/lts_new/ocm15529551-1898/ocm15529551
lsdi/diesel/lts_new/ocm10491454-1366
lsdi/diesel/lts_new/ocm28398003-1770
lsdi/diesel/lts_new/ocn262828093-2258/ocn262828093
lsdi/diesel/lts_new/ocm22609230-2257/ocm22609230
lsdi/diesel/lts_new/ocm13655689-2267/ocm13655689
lsdi/diesel/lts_new/ocm02777215-1722/ocm02777215
lsdi/diesel/lts_new/ocm12768387-2699
lsdi/diesel/lts_new/ocm04297720-1628/ocm04297720
lsdi/diesel/lts_new/ocm04278193-1602/ocm04278193
lsdi/diesel/lts_new/ocm04307980-1646/ocm04307980
lsdi/diesel/lts_new/ocm50734430-1913/ocm50734430
lsdi/diesel/lts_new/ocm29690004-1878/ocm29690004
lsdi/diesel/lts_new/ocm06684523-2005/ocm06684523
lsdi/diesel/lts_new/ocm22578472-1583
lsdi/diesel/lts_new/ocm62262589-2297
lsdi/diesel/lts_new/ocm10491582-1415
lsdi/diesel/lts_new/ocm04340519-1976/ocm04340519
lsdi/diesel/lts_new/ocm22592655-1981/ocm22592655
lsdi/diesel/lts_new/ocm02731321-1731/ocm02731321
lsdi/diesel/lts_new/ocm18066398-1730/ocm18066398
lsdi/diesel/lts_new/ocm05922290-1895/ocm05922290
lsdi/diesel/lts_new/ocm04315168-1714/ocm04315168
lsdi/diesel/lts_new/ocm10282155-1404
lsdi/diesel/lts_new/ocn391334732-2425/ocn391334732
lsdi/diesel/lts_new/ocm22578539-1590/ocm22578539
lsdi/diesel/lts_new/ocn437993173-2845
lsdi/diesel/lts_new/ocm06738792-1904/ocm06738792
lsdi/diesel/lts_new/ocm10282193-1528
lsdi/diesel/lts_new/ocm24179453-1412
lsdi/diesel/lts_new/ocm21013337-1405
lsdi/diesel/lts_new/ocm12758183-2245/ocm12758183
lsdi/diesel/lts_new/ocm15094358-1910/ocm15094358
lsdi2/ocm03610053-2106/ocm03610053
lsdi/diesel/lts_new/ocm22589520-1686/ocm22589520
lsdi/diesel/lts_new/ocm15578741-2440/ocm15578741
lsdi/diesel/lts_new/ocm04172434-1936/ocm04172434
lsdi/diesel/lts_new/ocm10491495-1535
lsdi/diesel/lts_new/ocm12100841-2182/ocm12100841
lsdi/diesel/lts_new/ocm04300980-1632/ocm04300980
lsdi/diesel/lts_new/ocm09945565-1892
lsdi2/ocm04449998-2990/ocm04449998
lsdi/diesel/lts_new/ocm06933575-2364/ocm06933575
lsdi/diesel/lts_new/ocm12758216-2254/ocm12758216
lsdi/diesel/lts_new/ocm10792920-1859/ocm10792920
lsdi/diesel/lts_new/ocm10620854-1760/ocm10620854
lsdi/diesel/lts_new/ocn262463863-1240/ocn262463863
lsdi/diesel/lts_new/ocm10892466-1901
lsdi/diesel/lts_new/ocm08720057-2031/ocm08720057/IMAGES
lsdi/diesel/lts_new/ocm24149806-2046/ocm24149806
lsdi/diesel/lts_new/ocm08045010-2129/ocm08045010
lsdi/diesel/lts_new/ocm15585156-1896/ocm15585156
lsdi/diesel/lts_new/ocm08521306-1592/ocm08521306
lsdi/diesel/lts_new/ocm04315224-1717/ocm04315224
lsdi/diesel/lts_new/ocm10260579-1398
lsdi/diesel/lts_new/ocm10491560-1365
lsdi/diesel/lts_new/ocm04294424-1619/ocm04294424
lsdi/diesel/lts_new/ocm04294415-1618/ocm04294415
lsdi/diesel/lts_new/ocm04311903-1661/ocm04311903
lsdi/diesel/lts_new/ocm04311972-1695
lsdi/diesel/lts_new/ocm04047372-2935
lsdi/diesel/lts_new/ocn170931999-2532/ocn170931999
lsdi/diesel/lts_new/ocm22612785-2251_RAW/ocm22612785
lsdi/diesel/lts_new/ocm24181021-2246/ocm24181021
lsdi/diesel/lts_new/ocm10620981-1606/ocm10620981
lsdi/diesel/lts_new/ocm04294326-1614/ocm04294326
lsdi/diesel/lts_new/ocm04311941-1664/ocm04311941
lsdi/diesel/lts_new/ocm10491482-1530
lsdi/diesel/lts_new/ocm10282147-1520
lsdi/diesel/lts_new/ocm11360691-2655
lsdi/diesel/lts_new/ocm10491530-1542
lsdi/diesel/lts_new/ocm04294283-1612/ocm04294283
lsdi/diesel/lts_new/ocm22578376-1572
lsdi/diesel/lts_new/ocm10892350-1902/ocm10892350
lsdi/diesel/lts_new/ocm04294375-1616/ocm04294375
lsdi/diesel/lts_new/ocm04278299-1604/ocm04278299
lsdi/diesel/lts_new/ocm15736606-2671
lsdi/diesel/lts_new/ocm04311920-1662/ocm04311920
lsdi/diesel/lts_new/ocm04307958-1645/ocm04307958
lsdi/diesel/lts_new/ocm13974506-2685
lsdi/diesel/lts_new/ocn190939723-1504
lsdi/diesel/lts_new/ocm04301011-1637/ocm04301011
lsdi/diesel/lts_new/ocm05044229-1593/ocm05044229
lsdi/diesel/lts_new/ocn437345880-2837
lsdi/diesel/lts_new/ocm12378089-1909/ocm12378089
lsdi/diesel/lts_new/ocm06805994-2261/ocm06805994
lsdi/diesel/lts_new/ocm22578415-1582
lsdi/diesel/lts_new/ocm10329035-1544
lsdi/diesel/lts_new/ocm11296882-2006/ocm11296882
lsdi/diesel/lts_new/ocm10491544-1497
lsdi/diesel/lts_new/ocm12091645-2243/ocm12091645
lsdi/diesel/lts_new/ocm22503402-1894/ocm22503402
lsdi/diesel/lts_new/ocm04301030-1638/ocm04301030
lsdi/diesel/lts_new/ocm11654478-2093/ocm11654478
lsdi/diesel/lts_new/ocm13655621-2656
lsdi/diesel/lts_new/ocm04294344-1615/ocm04294344
lsdi/diesel/lts_new/ocm15289227-1915/ocm15289227
lsdi/diesel/lts_new/ocm22589411-1719/ocm22589411
lsdi/diesel/lts_new/ocm02975897-1498
lsdi/diesel/lts_new/ocm06821868-1588/ocm06821868
lsdi/diesel/lts_new/ocm22578462-1591/ocm22578462
lsdi/diesel/lts_new/ocm38954517-1912/ocm38954517
lsdi/diesel/lts_new/ocm04282590-1601/ocm04282590
lsdi/diesel/lts_new/ocm22578429-1581
lsdi/diesel/lts_new/ocm04803862-1908/ocm04803862
lsdi2/ocn168389493-5598/ocn168389493
lsdi/diesel/lts_new/ocm04307932-1641/ocm04307932
lsdi/diesel/lts_new/ocm24166716-2081/ocm24166716
lsdi/diesel/lts_new/ocm12920402-1911/ocm12920402
lsdi/diesel/lts_new/ocm10321144-1529
lsdi/diesel/lts_new/ocm06933530-1653/ocm06933530
lsdi/diesel/lts_new/ocm15538640-2434/ocm15538640
lsdi/diesel/lts_new/ocm11296867-1914/ocm11296867
lsdi/diesel/lts_new/ocm04329454-1973/ocm04329454
lsdi/diesel/lts_new/ocm04315248-1718/ocm04315248
lsdi/diesel/lts_new/ocm10321074-1457
lsdi/diesel/lts_new/ocn268677048-1425
lsdi/diesel/lts_new/ocm02880038-1399
lsdi/diesel/lts_new/ocm10892334-2209/ocm10892334
lsdi/diesel/lts_new/ocm04416518-1357
lsdi/diesel/lts_new/ocm11864212-2259/ocm11864212
lsdi/diesel/lts_new/ocm04315104-1697/ocm04315104
lsdi/diesel/lts_new/ocm10329041-1505
lsdi/diesel/lts_new/ocm15041698-2421/ocm15041698
lsdi2/ocm01929512-2986/ocm01929512
lsdi/diesel/lts_new/ocm04294304-1613/ocm04294304
lsdi/diesel/lts_new/ocm22607964-2171/ocm22607964
lsdi/diesel/lts_new/ocm53080222-1721/ocm53080222
lsdi/diesel/lts_new/ocm82685488-1828/ocm82685488
lsdi/diesel/lts_new/ocm10329027-1549
lsdi/diesel/lts_new/ocm04315209-1716/ocm04315209
lsdi/diesel/lts_new/ocm04311990-1696
lsdi/diesel/lts_new/ocm13293698-1551
lsdi/diesel/lts_new/ocm11864306-2180/ocm11864306
lsdi/diesel/lts_new/ocm10620997-1651/ocm10620997
lsdi/diesel/lts_new/ocm10329024-1557
lsdi/diesel/lts_new/ocm10491431-1558
lsdi/diesel/lts_new/ocm04301050-1640/ocm04301050
lsdi/diesel/lts_new/ocm03676038-2008/ocm03676038
lsdi/diesel/lts_new/ocm48991130-1503
lsdi/diesel/lts_new/ocm22578352-1559
lsdi/diesel/lts_new/ocn223624509-1897/ocn223624509
lsdi/diesel/lts_new/ocm04428175-1934/ocm04428175
lsdi/diesel/lts_new/ocm03508352-1513
lsdi/diesel/lts_new/ocm04312022-1663/ocm04312022
lsdi/diesel/lts_new/ocm22594790-2754
lsdi/diesel/lts_new/ocm21096070-1782/ocm21096070
lsdi/diesel/lts_new/ocm04308009-1647/ocm04308009
lsdi/diesel/lts_new/ocm10491470-1548
lsdi/diesel/lts_new/ocm10491564-1397
lsdi/diesel/lts_new/ocm04404550-1935/ocm04404550
lsdi/diesel/lts_new/ocm04297691-1622/ocm04297691
lsdi2/ocn299780938-1807/ocn299780938
lsdi/diesel/lts_new/ocm04311881-1660/ocm04311881
lsdi/diesel/lts_new/ocm36072417-2507/ocm36072417
lsdi/diesel/lts_new/ocm04315144-1699/ocm04315144
lsdi/diesel/lts_new/ocm24166596-1900/ocm24166596
lsdi/diesel/lts_new/ocm10321151-1458
lsdi/diesel/lts_new/ocm24181300-2250/ocm24181300
lsdi/diesel/lts_new/ocn154282904-1918/ocn154282904
lsdi/diesel/lts_new/ocm07336328-1589/ocm07336328
lsdi/diesel/lts_new/ocm04315190-1715/ocm04315190
lsdi/diesel/lts_new/ocm15553153-2314
lsdi/diesel/lts_new/ocm10987607-1519
lsdi/diesel/lts_new/ocm06072389-1518
lsdi/diesel/lts_new/ocm04315123-1698/ocm04315123
lsdi/diesel/lts_new/ocn166275783-2459/ocn166275783
lsdi/diesel/lts_new/ocm04278257-1603/ocm04278257
lsdi/diesel/lts_new/ocm04301127-1639/ocm04301127
lsdi/diesel/lts_new/ocm10891921-2260/ocm10891921
lsdi/diesel/lts_new/ocm22578282-1413
lsdi/diesel/lts_new/ocm22592495-1899/ocm22592495
lsdi/diesel/lts_new/ocm04297644-1620/ocm04297644
lsdi/diesel/lts_new/ocm04843129-2134/ocm04843129
lsdi/diesel/lts_new/ocm36175187-2252/ocm36175187
lsdi/diesel/lts_new/ocm04297674-1621/ocm04297674
lsdi/diesel/lts_new/ocm04297736-1629/ocm04297736
lsdi/diesel/lts_new/ocm06738761-2181/ocm06738761
lsdi/diesel/lts_new/ocn163948712-1906/ocn163948712
lsdi/diesel/lts_new/ocm22039366-1939/ocm22039366
lsdi/diesel/lts_new/ocn145747328-1723/ocn145747328
lsdi/diesel/lts_new/ocm04288236-1605/ocm04288236
lsdi/diesel/lts_new/ocm50989462-1916/ocm50989462
lsdi/diesel/lts_new/ocm10742871-1890
lsdi/diesel/lts_new/ocm27688895-1907/ocm27688895
lsdi/diesel/lts_new/ocm24179587-1461

**Comment by jcrompton42** [comment]
Transferred. I think what happened previously is that many of these directories contain symbolic links, which rclone ignores by default.  I changed my script to follow links so ideally this won't happen in future.

**Comment by jcrompton42** [comment]
Transferred. I think what happened previously is that many of these directories contain symbolic links, which rclone ignores by default.  I changed my script to follow links so ideally this won't happen in future.
