### ISSUE TITLE
Transfer yet another batch of Oxford Spokesman files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1823]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Oxford_Spokesman/Spokesman_19900421
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19910318
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19910422
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19911009
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19920211
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19920300
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19920500
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19921005
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19921102
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19921201
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19930203

**Comment by jcrompton42** [comment]
transferred
