### ISSUE TITLE
Cantaloupe: enable support for rendering JP2 images in IIIF; test PDFBox processor

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1827]
**JP2 Support**
We have noticed that for some books which only contain JP2 files (JPEG 2000) for their page images, these images do not render correctly. They are valid files which download file directly from Curate, however. 

Examples (most works in the [Medical Heritage Imprints](https://digital.library.emory.edu/catalog/279v15dvtn-cor) collection)
https://digital.library.emory.edu/catalog/088qbzkhqt-cor

Additional notes:
I found a [reference in Samvera slack ](https://samvera.slack.com/archives/C0F4P3FFF/p1561656850040400?thread_ts=1561643422.039100&cid=C0F4P3FFF) about specifying an alternate processor for JP2s in Cantaloupe's properties file.  I am not sure what we have currently set.  

Here are notes about which processors support which file formats (not sure which version of Cantaloupe we are running):
https://cantaloupe-project.github.io/manual/4.1/processors.html#Format%20Support

**PDF Support**
If we do some testing with specific image processors, we should also try the [PDFBox processor](https://cantaloupe-project.github.io/manual/4.1/processors.html#PdfBoxProcessor) to see what support can be enabled for PDF files, too.

[Related presentation on using PDFBox with Cantaloupe](https://www.youtube.com/watch?v=kVVqiy_vURI)

**Comment by jcrompton42** [comment]
@eporter23 
I have added the imagemagickprocessor for jp2 files in arch, and have tested by adding a jp2 image at https://digital-arch.library.emory.edu/catalog/7612ngf1xx-cor. 

I have also made this change in cantaloupe test, please do some testing @eporter23 and confirm all is well

**Comment by jcrompton42** [comment]
@eporter23 I think the one in arch is just slow and timing out :( Kathryn confirmed it worked earlier though.  Coordinating with kathryn to find a time to push the change to prod

I did some experimenting with pdfbox in arch, but after talking to Collin, I believe you are correct about pdf and IIIF manifests. So if you want that work done, I would open a separate ticket for a developer.
