### ISSUE TITLE
Transfer Robert Paine Papers files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1843]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Theology_Pitts/P-MSS0404

**Comment by jcrompton42** [comment]
transferred
