### ISSUE TITLE
Transfer batch of catalogs, 2022-08-08

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1858]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

If any of the directories in this list already exist in EFS, please do not write over them and please let me know which ones they are (I don't expect any to be there already but these catalogs are kind of messy so who knows).

lsdi2/ftp/Citizenship_1931
lsdi2/ftp/Citizenship_1932
lsdi2/ftp/College_1950
lsdi2/ftp/College_1951
lsdi2/ftp/College_1952
lsdi2/ftp/College_1953
lsdi2/ftp/College_1954
lsdi2/ftp/College_1955
lsdi2/ftp/College_1956
lsdi2/ftp/College_1957
lsdi2/ftp/College_1958
lsdi2/ftp/College_1959
lsdi2/ftp/College_1959_2
lsdi2/ftp/Current_economic_1937
lsdi2/ftp/Dentistry_1953
lsdi2/ftp/Dentistry_1954
lsdi2/ftp/Dentistry_1955
lsdi2/ftp/Dentistry_1956
lsdi2/ftp/Dentistry_1957
lsdi2/ftp/Dentistry_1959
lsdi2/ftp/Federal_constitution_1936
lsdi2/ftp/General_1930
lsdi2/ftp/General_1931
lsdi2/ftp/General_1932
lsdi2/ftp/General_1933
lsdi2/ftp/General_1934
lsdi2/ftp/General_1935
lsdi2/ftp/General_1936
lsdi2/ftp/General_1937
lsdi2/ftp/General_1938
lsdi2/ftp/General_1939
lsdi2/ftp/GSAS_1939
lsdi2/ftp/GSAS_1949
lsdi2/ftp/GSAS_1950
lsdi2/ftp/GSAS_1951
lsdi2/ftp/GSAS_1952
lsdi2/ftp/GSAS_1953
lsdi2/ftp/GSAS_1954
lsdi2/ftp/GSAS_1955
lsdi2/ftp/GSAS_1956
lsdi2/ftp/GSAS_1957
lsdi2/ftp/GSAS_1958
lsdi2/ftp/GSAS_1959
lsdi2/ftp/Handbook_1932
lsdi2/ftp/Medicine_1930
lsdi2/ftp/Medicine_1931
lsdi2/ftp/Medicine_1932
lsdi2/ftp/Medicine_1934
lsdi2/ftp/Medicine_1935
lsdi2/ftp/Medicine_1936
lsdi2/ftp/Medicine_1937
lsdi2/ftp/Medicine_1938
lsdi2/ftp/Medicine_1939
lsdi2/ftp/Medicine_1946
lsdi2/ftp/Medicine_1950
lsdi2/ftp/Medicine_1951
lsdi2/ftp/Medicine_1952
lsdi2/ftp/Medicine_1953
lsdi2/ftp/Medicine_1954
lsdi2/ftp/Medicine_1955
lsdi2/ftp/Medicine_1956
lsdi2/ftp/Medicine_1957
lsdi2/ftp/Medicine_1958
lsdi2/ftp/Medicine_1959
lsdi2/ftp/Medicine_1995-1996
lsdi2/ftp/New_Deal_1934
lsdi2/ftp/Oxford_1933
lsdi2/ftp/Oxford_1934
lsdi2/ftp/Oxford_1971-1972
lsdi2/ftp/Political_problems_1935
lsdi2/ftp/Problems_1930
lsdi2/ftp/Problems_South_1935
lsdi2/ftp/Public_opinion_1933
lsdi2/ftp/Publications_1950
lsdi2/ftp/Register_1950
lsdi2/ftp/Register_1951
lsdi2/ftp/Register_1952
lsdi2/ftp/Register_1953
lsdi2/ftp/Register_1955
lsdi2/ftp/Register_1957
lsdi2/ftp/Register_1959
lsdi2/tesseract/EUACatalogs/Rollins/Rollins_2000-2001
lsdi2/ftp/Summer_1930
lsdi2/ftp/Summer_1931
lsdi2/ftp/Summer_1932
lsdi2/ftp/Summer_1935-2
lsdi2/ftp/Summer_School_Bulletin_1999
lsdi2/ftp/Theology_1930
lsdi2/ftp/Theology_1931
lsdi2/ftp/Theology_1932
lsdi2/ftp/Theology_1933
lsdi2/ftp/Theology_1934
lsdi2/ftp/Theology_1935
lsdi2/ftp/Theology_1936
lsdi2/ftp/Theology_1939-2
lsdi2/ftp/Theology_1950
lsdi2/ftp/Theology_1951
lsdi2/ftp/Theology_1952
lsdi2/ftp/Theology_1954
lsdi2/ftp/Theology_1955
lsdi2/ftp/Theology_1956
lsdi2/ftp/Theology_1956
lsdi2/ftp/Theology_1957
lsdi2/ftp/Theology_1958
lsdi2/ftp/Theology_1959

**Comment by jcrompton42** [comment]
transferred
