### ISSUE TITLE
Add new users to Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1859]
Please add Avery to the `repository_manager` group in Curate.

Please add Ayoub and Kaeln as admin level users also.

See [this wiki doc for details](https://wiki.emory.edu/display/DLPP/DLP+Middleware+Common+Tasks).

**Comment by eporter23** [comment]
@alexBLR just found out that Ayoub does not have a Curate account either. I'm adding to this ticket to include him (notes above).

**Comment by eporter23** [comment]
Also adding @kbowaterskelly to the ticket details since he doesn't have an account either.

**Comment by alexBLR** [comment]
@eporter23 , @kbowaterskelly , @abelemlih done

**Comment by eporter23** [comment]
Thanks @alexBLR - does this need a deploy to show up?

**Comment by eporter23** [comment]
@alexBLR never mind, I see them in there now. Thanks!
