### ISSUE TITLE
Add an EBS Fileshare 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#186]
- [x] Create the EBS file system (encrypted  or un-encrypted)
- [x] Attach to a VM 
- [x] Create linux XFS file system
- [x] Modify /etc/fstab file system will auto mount after restart

**Comment by mprefer** [comment]
Filesystem created is unencrypted. Can recreate is as encrypt if the team desires.
Currently volume is unattached to 'curate.library.emory.edu' to save mone.
