### ISSUE TITLE
Transfer batch 2 of Samuel Ajayi Crowther books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1871]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/000015066246
lsdi2/tesseract/Crowther/010003078625
lsdi2/tesseract/Crowther/300000108012
lsdi2/tesseract/Crowther/300000131012
lsdi2/tesseract/Crowther/300000407778
lsdi2/tesseract/Crowther/300000468118
dmfiles/Libraries/Theology_Pitts/P-S005/B018/F006/I001

**Comment by jcrompton42** [comment]
transferred
