### ISSUE TITLE
Transfer Civil War OP boxes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1886]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP2
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP3
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP4
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP5
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP6
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP7
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP8
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP9
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP10
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP11
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP12
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP13
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP14
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP15
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP16
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP17
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP18
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP19
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP20
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP21
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP22
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP23
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP24
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP25
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP26
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP27
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP28
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP29
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP30
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP31
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP32
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP33
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP34
dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP35

**Comment by jcrompton42** [comment]
/opt/dmfiles/MARBL/Manuscripts/MSS_0020_CivilWar/OP30 does not exist on our ISILON drive. Everything else has been transferred.
