### ISSUE TITLE
Test UCLA ansible solr scripts for solr cloud 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#189]
- [x] Test script to see if they can create solr cloud cluster 
- [x] Research solr cloud ansible modules

**Comment by tmiles2** [comment]
Based on standup it sounds like this one should be open as well @SolomonHD

**Comment by SolomonHD** [comment]
Was able to modify my fork of UCLA Solr to include a section for solr cloud. Combined with a new zookeeper role these will implement solr cloud.
