### ISSUE TITLE
Test Emory IP with ELB

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#191]
- [x] Test routing between 172.x and ELB DNS
- [x] Configure F5 to allow traffic to 172.x address

**Comment by SolomonHD** [comment]
This is going to be a little more complicated than we originally though. The "Emory IP" isn't going to be useful for our purposed. After a call with Paul Petersen and Alan white we need to:
- [ ] Service now request for linking f5 sources to cor-f5 ELB
- [ ] Service now request for generate public DMZ VIP and linking that to cor-f5 ELB
- [ ] Service now request to open the VIP to general internet (this may require some sort of security scan(
