### ISSUE TITLE
Team consult: loading large sets of fixity check results into Fedora

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1914]
While we now have the ability to bulk-load AWS fixity check results into Fedora, we want to consult with the team to anticipate if loading large quantities of these will cause performance issues in our environment. 

Our most recent fixity checks included 600,000 files (x2).
Our previous AWS fixity checks included ~500,000 files (x2).

**Comment by bwatson78** [comment]
I don't foresee us having performance problems. My rationale behind that is that we're not touching the containing CurateGenericWork in this process. We are only persisting to individual FileSets once with each line of the CSV and that process is happening iteratively. Multiple FileSets won't be persisting at the same time.

**Comment by bwatson78** [comment]
@rotated8 and @abelemlih Do you wanna take a look and voice your opinions?

**Comment by rotated8** [comment]
@bwatson78 Does updating a fileset trigger a work or collection to update? I think there was a feature where they'd recalculate their size under certain circumstances.

**Comment by rotated8** [comment]
@eporter23 When we loaded our last fixity check- was that done all at once, or batched? I don't remember that having issues.

**Comment by eporter23** [comment]
@rotated8 we haven't attempted to load a full set of production results into Fedora yet. We've done small test loads in arch only at this point. We don't want to load small batches in production because then we'll have to keep track of which ones have had it loaded, etc.

**Comment by eporter23** [comment]
Some other factors I should mention - the latest CSV file from AWS for prod copy 1 is ~125MB and ~750K rows. Would this need to be split into smaller files for our rake task?

**Comment by rotated8** [comment]
@bwatson78 It sounds like the rake task isn't idempotent. If we ran it twice with the same data, we'd get two fixity entries instead of only one. Is that right? If so, what would it take to make it idempotent?

@eporter23 Is there a metric we can use to assess impact? Is it responsiveness of Curate frontend, average time to load new material, something else?

**Comment by bwatson78** [comment]
@rotated8 There are no checks in place to identify duplicates already in the system. I can create a method to check for, I guess, the SHA1. That always changes with each Fixity Event, right?

**Comment by bwatson78** [comment]
@rotated8 As far as whether a FS save! kicks off a Work persistence, I'm checking that now.

**Comment by rotated8** [comment]
@bwatson78 I would have thought the SHA1 would be the same- that's the hash the file returned during the fixity check right? Do we have a timestamp for the check? I'd expect that to be unique, but I'm pretty well removed from how that all works.

**Comment by bwatson78** [comment]
@rotated8 Oops, you're right. So I'll need to check the SHA1 to id the FileSet and the Fixity's Event Start for duplicates. My next task to jump on?

**Comment by rotated8** [comment]
👍 Works for me

**Comment by bwatson78** [comment]
@rotated8 I played FileSetBehavior hopscotch and had Tamsin chime in with their knowledge. Saving a FileSet doesn't impact the containing Work.

**Comment by eporter23** [comment]
@bwatson78 I tested the fixity check revisions by generating a small set of results for 25 FileSets in test, loading them, and then reloading them. No duplicate entries. Looks good!

**Comment by eporter23** [comment]
Closing this and will make a new ticket to do some larger scale loads of fixity results in prod.
