### ISSUE TITLE
Transfer Yun Ch'i-Ho files 

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1925]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B001
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B002
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B003
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B004
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B005
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B006
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B007
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B008
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B017
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B019
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B020
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B021
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/OP

**Comment by jcrompton42** [comment]
transferred
