### ISSUE TITLE
Research CloudWatch Metrics

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#193]
Reworking this ticket for CloudWatch metrics. 

Scrum team has decided on proceeding with CloudWatch for logging purposes. Cloudwatch also includes a wide array of resource monitoring. This ticket will research which measurements we need. [This is a good resource](https://docs.aws.amazon.com/en_en/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html#linux-metrics-enabled-by-CloudWatch-agent) for measurements

- [x] Research which measurements and metrics will be best for our EC2
- [x] Capture metrics in yaml file for implementing with ansible role

**Comment by eporter23** [comment]
@SolomonHD I will confirm if this is in DCE's scope of work to provide

**Comment by SolomonHD** [comment]
After some thinking I believe this ticket will need to:

- [ ] Create role that will manage cloudwatch groups
- [ ] Also this role should install the cloudwatch log forwarder on the ec2s themselves
- [ ] The role should also assign the ec2 to the appropriate cloudwatch group

**Comment by SolomonHD** [comment]
I found a really detailed ansible role at https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent
I'm going to experiment with using this.

**Comment by tmiles2** [comment]
@mprefer Is there any progress on this issue?

**Comment by mprefer** [comment]
All metrics available to CloudWatch from the CloudWatch Agent on EC2. List of desired metrics to follow, with option to alter based on usefulness of metric(s):

https://docs.aws.amazon.com/en_en/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html#linux-metrics-enabled-by-CloudWatch-agent

**Comment by mprefer** [comment]
Initial list of metrics to capture (subject to change):

cpu_time_active
cpu_time_idle
cpu_time_iowait
cpu_time_system
cpu_time_user
cpu_usage_active
disk_free
disk_inodes_free
disk_inodes_total
disk_inodes_used
disk_total
disk_used
disk_used_percent
diskio_iops_in_progress
diskio_reads
diskio_read_bytes
diskio_read_time
diskio_writes
diskio_write_bytes
diskio_write_time
mem_active
mem_available
mem_available_percent
mem_buffered
mem_cached
mem_free
mem_total
mem_used
mem_used_percent
net_bytes_recv
net_bytes_sent
net_drop_in
net_drop_out
net_err_in
net_err_out
net_packets_sent
net_packets_recv
processes_blocked
processes_dead
processes_paging
processes_running
processes_sleeping
processes_stopped
processes_total
processes_zombies
swap_free
swap_used
swap_used_percent

**Comment by mprefer** [comment]
Will have to research the metrics available for non-EC2 elements in the environment, such as RDS and ELB, etc.

**Comment by tmiles2** [comment]
@mprefer Do we need to research the metrics on non-EC2 elements before Solomon take the next steps and closes out this issue?

**Comment by mprefer** [comment]
No. We can proceed with establishing metrics in CW without those other non-EC2 services. Those can be created at any time and should not prevent moving forward with the current metrics list.

**Comment by SolomonHD** [comment]
The CloudWatch Metrics have been turned on for all DLP instances.

![Metrics are under DLP_Metrics](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/7df2c98b-8973-407a-aef9-4ce902b23271)

![Search metrics by hostname](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/f068cb10-5d33-4b4f-924a-cbbb243c555f)
