### ISSUE TITLE
Bulkrax: FileSets not fully attached in Curate (but are related to works in Fedora)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1936]
Work
81937pvmqc-cor

FileSets not displaying with work in Curate in its Items list or in the File Manager:
378tb2rbzw-cor
24298sf7wz-cor
122v41nsb0-cor
491fj6q5hg-cor

When I [view the work in Fedora](https://fedora-cor-test.library.emory.edu/fcrepo/rest/prod/81/93/7p/vm/81937pvmqc-cor), these FileSets are shown as children of the work.

Reindexing the work does not resolve the issue.
Sidekiq also shows these 4 ids with FileSetAttachedJob failures - retries automatically fail.

**Comment by bwatson78** [comment]
I've incorporated changes to fix this behavior in #1938. My goal was to see if it was possible to associate FSs outside of the ingest process, and I found that I could. That led me to moving the association processing to the end of the ingest sequence, and those changes are now in Curate Test.

**Comment by eporter23** [comment]
Major revisions to the fileset attachment process have been very successful in the last few imports - no errors so far.
