### ISSUE TITLE
Bulkrax: preferred image logic should be applied when thumbs are generated

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1944]
When testing an image import in Bulkrax, I noticed that in some cases the preferred image logic is not being applied when the thumbnail is generated.

When an image-based Fileset has a preservation master file (original scan with color bars on the edges) and an intermediate file (cropped and straightened), the intermediate file should be used for the thumbnail. See more notes in prior tickets including #717.

Running a Regenerate Derivative job, however, does not correct this problem. 

Correctly processed example:
https://curate-test.library.emory.edu/concern/parent/699n2z354t-cor/file_sets/313zs7h4f2-cor

![Screen Shot 2022-09-01 at 12.36.07 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c29752a5-fdce-4a7c-98b1-b985f604de9b)

Incorrect example:
https://curate-test.library.emory.edu/concern/file_sets/146qz612vf-cor?locale=en

![Screen Shot 2022-09-01 at 12.35.27 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/42fc499c-a801-4f36-9a1b-9c75a18b28b4)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1948

**Comment by eporter23** [comment]
working well now, thanks!
