### ISSUE TITLE
Transfer Emory Unit Collection files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1949]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/Health_Sciences/HS-S015_USArmy_GenHosp_43rd

**Comment by jcrompton42** [comment]
@kmichaelis dir '/opt/dmfiles/MARBL/Manuscripts/Health_Sciences' does not seem to exist. Am I looking in the wrong place? Does Kyle still need to upload it?

**Comment by kmichaelis** [comment]
Oops, twas a cut-and-paste error! Here is the correct path:

**Comment by jcrompton42** [comment]
I do copy pastas all the time! transferred.
