### ISSUE TITLE
Fileset association fails: dedup key contains "-cor"

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1955]
Sometimes our deduplication key values have to be constructed and they use the collection identifier plus a numeric suffix. 

In this import, the dedup key for the work contained "-cor". The filesets were all created, but the fileset attachment job failed as noted below. 

The work was created and does have the correct dedup key. 
 
![Screen Shot 2022-09-08 at 2.01.59 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a818b51e-9a9c-4a46-abf5-f83d48739ae1)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1956
