### ISSUE TITLE
Bulkrax: support ingest of files from EFS/S3

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1960]
In our Bulkrax prototype, we are currently using the upload files from a Zip file option. For this ticket, we should investigate options to ingest files stored on EFS or S3. 

Zizia currently allows us to read files from EFS paths for import, so we may want to investigate how that is configured. We should also investigate what options Bulkrax supports currently for remote files. 

We could move files from EFS to a new S3 location if that is easier for Bulkrax to access.

While the ZIP method works successfully for small book imports, it will not work for others, including image ingests and large book ingests, which typically are greater than 5GB: 

- A recent book large book was 11GB when zipped. 
- A recent small image ingest batch was 7 GB.    

The current process requires downloading files from EFS, zipping them, and then reuploading them. For very large ingests, this can take hours and has not yet been successfully completed.

**Comment by bwatson78** [comment]
According to this [Bulkrax documentation][https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#method-2], uploading files for FileSets, specifically, is only possible when the files are in the folder as the CSV in the application. This means passing a link to the file wherever it is permanently/temporarily housed will not work. What will work is to create a Bulkrax importer without initiating an import and uploading the files to the associated folder referenced in the importer's show page (Parser Fields > `import_file_path`). The importation can then be kicked off after all of the files are in the `files` folder on the application.

**Comment by eporter23** [comment]
@bwatson78 have you been able to test this locally? If so and it was successful, I will close this ticket and write up a new one to plot out implementation.

**Comment by bwatson78** [comment]
Have confirmed it works locally.

Procedure: 
1. CSV is the only file uploaded, and choose "Create"
2. Identify folder on server to work with by expanding `Parser Fields` and noting the `import_file_path`.
3. On server, locate the folder that matches from above, and create the directoy 'files' inside of it.
4. Place every file listed in the CSV to be imported into `files`.
5. Press `Edit` on the import show page and click the 'Edit and Import` option.
6. All Jobs should kick off.
