### ISSUE TITLE
Transfer Emory Photo/Video collection files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1965]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Archives/EUA_0267_PhotoVideo

**Comment by jcrompton42** [comment]
transferred
