### ISSUE TITLE
Transfer various Black Student Activism collection files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1978]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Archives/EUA_0015_SGA
dmfiles/MARBL/Archives/EUA_0027_Ward
dmfiles/MARBL/Archives/EUA_0076_PresSubject
dmfiles/MARBL/Archives/EUA_0062_President

**Comment by jcrompton42** [comment]
transferred.
