### ISSUE TITLE
AWS fixity events job with 1000 entries fails to initiate in production

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1979]
We have previously loaded small batches (less than 100 entries) of AWS fixity check data into Fedora/SOLR in the arch and test environments. 

A recent test of loading 1000 fixity events on 9/20/22 using the Background Jobs UI in production resulted in a confirmation message that the job was sent to the queue. No jobs ever appeared in sidekiq, however.

To confirm: were there any errors with this attempt?  There were no enqueued, busy, or failed jobs reported in sidekiq and no updates appeared on the respective FileSet pages. 

![Screen Shot 2022-09-20 at 9.56.22 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/214d6736-0073-4a60-9483-e5cc948115e8)

**Comment by bwatson78** [comment]
Findings: The job enqueued on 9/20 at 13:55:25, started at the same time and took only 44 ms to complete.

**Comment by bwatson78** [comment]
I'd like to see the CSV to spot check it locally.

**Comment by eporter23** [comment]
@bwatson78 thanks for the investigation which revealed we hadn't finished automating the reformatting of the CSVs. I'll add a new ticket to work with Beth on.
