### ISSUE TITLE
Transfer Kessler books batch 12 files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1980]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/EMU79827
lsdi2/tesseract/Kessler/EMU79814
lsdi2/tesseract/Kessler/300000169491
lsdi2/tesseract/Kessler/300000218117
lsdi2/tesseract/Kessler/EMU79987
lsdi2/tesseract/Kessler/EMU79885
lsdi2/tesseract/Kessler/300000211048
lsdi2/tesseract/Kessler/EMU80035
lsdi2/tesseract/Kessler/EMU79831
lsdi2/tesseract/Kessler/EMU80137
lsdi2/tesseract/Kessler/EMU79826
lsdi2/tesseract/Kessler/000015281152
lsdi2/tesseract/Kessler/EMU79738
lsdi2/tesseract/Kessler/EMU80145
lsdi2/tesseract/Kessler/EMU79943
lsdi2/tesseract/Kessler/300000422297
lsdi2/tesseract/Kessler/558910-10

**Comment by jcrompton42** [comment]
transferred.
