### ISSUE TITLE
Update preprocessors to output Bulkrax-formatted CSVs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1984]
In order to use Bulkrax efficiently in production, we should update our preprocessor scripts to be able to generate the CSV structure required by Bulkrax. 

Ideally the preprocessors should allow user could output either Zizia or Bulkrax formatting.

In terms of prioritization, we should work on the book preprocessor(s) first.

Draft requirements:

- [Samples of Bulkrax importer CSVs for different preprocessor outputs](https://docs.google.com/spreadsheets/d/1lkn3dfe5jxKpQx8EAIZSr-nzsexbxHRD0kb9Vvberrw/edit#gid=0)
- [Summary notes for changes needed for each preprocessor](https://docs.google.com/document/d/1iXSQzc6Yb1GX1Nq_bY1hjZA2UpkG3sURxaRBCTdic94/edit#heading=h.rx47ybz892l9)
- [Preprocessor UI in Curate](https://docs.google.com/drawings/d/1wKsUvTawZe9B9R3GxIbR-u3pYjofQcD8XHuq7wSuY1M/edit)

**Comment by eporter23** [comment]
@kmichaelis a workflow note for later: we'll need to start adding the source_collection_id to the unprocessed CSV so it gets added to the parent column for Bulkrax. If I recall correctly we've been adding it to the processed CSV?

**Comment by bwatson78** [comment]
PRs made:
https://github.com/emory-libraries/dlp-curate/pull/2004
https://github.com/emory-libraries/dlp-curate/pull/2005
https://github.com/emory-libraries/dlp-curate/pull/2007
https://github.com/emory-libraries/dlp-curate/pull/2008
https://github.com/emory-libraries/dlp-curate/pull/2009

**Comment by eporter23** [comment]
@bwatson78 I've tested the basic Kirtas, LIMB and Langmuir outputs and they look great. I will coordinate testing DAMS output and some of the other features with @kmichaelis when she's back next week.

**Comment by eporter23** [comment]
@bwatson78 Kathryn did some testing and we found an issue where if you select the extra volume-level text file option, the label that gets generated is incorrect. For a volume-level txt file, the label/title should be "Transcript for Volume" but it's outputting "PDF for Volume". ![Screen Shot 2022-11-01 at 9.57.27 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/bc839511-943b-4855-994b-b1ba2edd598e)

**Comment by eporter23** [comment]
We're also looking at another possible issue where in Zizia outputs the PDF filename that gets generated may be incorrect - I'll report back once we have a better picture of what may be happening.

**Comment by eporter23** [comment]
@bwatson78 - @kmichaelis and I talked about the above comment and we think there may be a third variant to the digitization outputs that recently got implemented. We'll consider that a separate enhancement/issue for later. So for now the only thing to fix is the label/title for volume level .txt files noted above.

**Comment by bwatson78** [comment]
@eporter23 and @kmichaelis Thanks for the bug detail. Circling back to the issue now.
