### ISSUE TITLE
Process for copying files from EFS to curate's /imports folder for Bulkrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1985]
With our new Bulkrax import process, we need a way to ingest files directly from a server location instead of having to download them from EFS, create a zip file locally, and upload the zip file up to Curate.

Example path for an uploaded Zip file: `imports/62_20220926184518_109/Archive 8.zip`

Bulkrax unpacks the zip file within the individual importer's folder (e.g. `62_20220926184518_109` from the above example). Files for the ingest need to be stored in a subdirectory called "files" with a flat structure (no subdirectories).
![Screen Shot 2022-09-27 at 1.53.12 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/2fbf827a-ada3-4005-9068-2b5eae5f3e63)

Ideal process:

- Kathryn/Emily creates a new Bulkrax importer using the upload ZIP process and upload a CSV file only.
- Kathryn/Emily copies the server path for the newly uploaded CSV importer.
- Kathryn/Emily can initiate a process to  _copy_ (not move/delete) files from a given EFS path to the specific Curate's /imports subfolder
- The files can be copied such that any subdirectories are stripped out, retaining only a flat directory of all files needed.
- Kathryn/Emily can verify that the files have been copied to the correct location.
- A cleanup job can be established that periodically clears out older importers' files to preserve space on Curate's storage [to discuss: if this can be done on a schedule or better done manually]
- Copied files remain in EFS so that Kathryn/Emily can transfer them to Glacier when ready.

**Comment by jcrompton42** [comment]
@eporter23 can you give me an example of a file on EFS that would need to be copied? Just want to make sure I am looking in the right place for the directories.

**Comment by jcrompton42** [comment]
so @eporter23 does the directory in /imports need to have that prefix_timestamp form or does it just need to be something you can get to copy?

**Comment by eporter23** [comment]
We'd need to copy the path exactly as it's been generated in Bulkrax/Curate. Happy to chat if this doesn't clarify!

**Comment by jcrompton42** [comment]
Ok, updated, please test using:

awx job_templates launch copy-for-import --monitor -f human --extra_vars "{host: $ENV, efs_dir_name: Collections/xysz, imports_dir_name: 'prefix_morenumbers' }" 

Note that the prefix_morenumbers part does need those single quotes ' ' around it.

**Comment by eporter23** [comment]
@kmichaelis here's a reference example which led to a successful Bulkrax import! `awx job_templates launch copy-for-import --monitor -f human --extra_vars "{host: test, efs_dir_name: Collections/lsdi2/ocn246310029-5939/ocn246310029/Output/, imports_dir_name: '63_20221018183859' }"`

**Comment by jcrompton42** [comment]
closing now that @eporter23 has confirmed a successful import
