### ISSUE TITLE
Overwrite current B019 Yun Chi Ho files with new versions

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1986]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

This will require overwriting the files that currently exist in the B019 folder, please do so.

dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B019

**Comment by jcrompton42** [comment]
transferred
