### ISSUE TITLE
Transfer AHAM files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#1988]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja001
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja002
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja003
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja004
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja005
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja006
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja007
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja008
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja009
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja010
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja011

**Comment by jcrompton42** [comment]
transferred
