### ISSUE TITLE
Dashboard > Collections > Collection Type filter shows duplicate entries

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1993]
We saw this in prior upgrade testing but I am noting it as having recurred in 3.4.2. When you attempt to filter by Collection Type, you will see multiple entries for the same type as shown below:

![Screen Shot 2022-10-05 at 9.47.12 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/6b9e6685-edff-4e99-99b3-d25d5f1a9780)

Was there a migration utility that we had to run to fix this?

**Comment by bwatson78** [comment]
Checking for rake task.

**Comment by bwatson78** [comment]
This was fixed by running `hyrax:collections:update_collection_type_global_ids` rake task.
