### ISSUE TITLE
Collection Show Page includes large display of thumbnail in addition to the banner

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#1994]
When viewing the Public View of an individual collection, the thumbnail displays at enormous size below the banner image. Previously, we did not see the thumbnail in this view. 

Preferred display would be to not show the thumbnail in this view since we already have the banner.

Example in arch/3.4.2:
https://curate-arch.library.emory.edu/collections/105s7h44j3-cor?locale=en
![Screen Shot 2022-10-05 at 9.50.30 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/561d5587-ee4f-40ee-80b2-b3942a9cefc6)

Example in prod:
https://curate.library.emory.edu/collections/706g1jwsv6-cor?locale=en

![Screen Shot 2022-10-05 at 9.52.24 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/09904d18-6f5f-4647-a55e-86f7e845d0db)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1995

**Comment by eporter23** [comment]
Thanks for the fix!
