### ISSUE TITLE
Prevent duplicate manifest regeneration jobs being added to queue

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2002]
Our customized manifest regeneration job can be triggered by either a Curate user or a Lux user viewing a work. 

This can occur if:

- A work does not yet have a manifest generated
- A change has been made to the work such as updating certain metadata fields used in the manifest and the manifest has not yet been regenerated

When running ingests, Curate users often need to check the work as it is being ingested to see if FileSets are being attached and/or the work has been successfully created. This can trigger multiple unwanted manifest regenerations which hogs Fedora's resources.

Additionally, if a user in Curate is viewing the work while the manifest is regenerating, and clicks through the paginated Items can trigger an additional regeneration of the manifest. For example, if open the work and it starts generating the manifest, and then you click to Page 2 of the Items attached to the work, a second request gets queued.

At times we have seen 5-6 of the same manifest being regenerated in sidekiq. 

Is there a way to detect if a manifest is already being regenerated in order to stop sending duplicate requests to sidekiq?

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/dlp-curate/pull/2006

**Comment by eporter23** [comment]
@abelemlih I just triggered a duplicate manifest persistencejob on a work in Curate arch by doing the following: open a work that does not have a manifest generated. This triggered the first job to produce the initial manifest. With the work view page still open, I then went from page 1 to Page 4 of the items list for that work. This triggered the job to run a second time. 

![Screen Shot 2022-10-18 at 12.36.38 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/eba9ba2b-49a5-40e3-b887-25df149fd596) 

![Screen Shot 2022-10-18 at 12.36.38 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/85f3baef-15ce-4bb6-b5f0-c57161de568d)

**Comment by abelemlih** [comment]
@eporter23 I created a new PR to address the issues raised above: https://github.com/emory-libraries/dlp-curate/pull/2010. Please let me know if you have any questions!

**Comment by eporter23** [comment]
@abelemlih I just tested this again on a work in arch with no existing manifest, and the duplicate jobs are still being triggered if I navigate within the Items list for the work: ![Screen Shot 2022-10-20 at 9.30.30 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/00bd29dc-5da8-4d12-8a32-47045079796f)

**Comment by eporter23** [comment]
@abelemlih I guess I should confirm if this has been deployed yet? It was marked as closed and I re-opened it.

**Comment by eporter23** [comment]
@abelemlih I've tested this on multiple works now and it's performing as hoped. Thanks!
