### ISSUE TITLE
Add basic full text search prototype

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/dlp-curate#2012]
- Add a Solr field to store full text of a document
- Add full text to the fields used to render search results

**Comment by abelemlih** [comment]
@eporter23 here is an example of a full text data fileset with all the requirements we discussed: https://curate-test.library.emory.edu/concern/parent/293gxd25fd-cor/file_sets/358bg79czb-cor

Let me know if you have any questions/recommendations!

**Comment by eporter23** [comment]
Looks great @abelemlih ! I went ahead and manually made sure it was characterized like we talked about last week and all looks fine.
