### ISSUE TITLE
Transfer Kessler books batch 13 files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2014]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/571278-10
lsdi2/tesseract/Kessler/571279-10
lsdi2/tesseract/Kessler/571280-10
lsdi2/tesseract/Kessler/571281-10
lsdi2/tesseract/Kessler/300000197741
lsdi2/tesseract/Kessler/300000458285

**Comment by jcrompton42** [comment]
transferred
