### ISSUE TITLE
SPIKE:  What to do about Webpacker?

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#2031]
Rails no longer uses webpacker and has moved on to... something else.

- [x] Is there a consensus in the Rails community on what to move to?
- [x] Is there a consensus in the Samvera and Blacklight communities on what to move to?
- [x] Are there minimum version limits for Blacklight, Hyrax, or Rails we need to meet before moving?
- [x] What resources are available to learn about the new solution?
- [x] Are there examples of others making the same transition?
- [x] Are there any institutions who we may want to talk to about their transition to the new thing?

**Comment by bwatson78** [comment]
Q: Is there a consensus in the Rails community on what to move to?

A: Yes, officially, the rails community recommends to switch to [`jsbundling-rails`](https://github.com/rails/jsbundling-rails/) if currently using Webpacker. They provide a [switching guide](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md) on the Webpacker's Github page.

**Comment by bwatson78** [comment]
@rotated8 If you want more detail about what I've found, please add another comment.

**Comment by eporter23** [comment]
Closing this since no comments since November.
