### ISSUE TITLE
Collection banner images are missing in Curate after latest deploy

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2037]
In re-testing parts of the regression test plan with the latest version deployed to Curate (test and arch), the banner images previously assigned to selected collections are no longer visible, and editing the collection shows no banner image uploaded. Collections in the test environment that should have banners already assigned include:

https://curate-test.library.emory.edu/collections/320sqv9s4v-cor?locale=en
https://curate-test.library.emory.edu/collections/5053ffbg7n-cor?locale=en
https://curate-test.library.emory.edu/collections/914nk98sfv-cor?locale=en
https://curate-test.library.emory.edu/collections/706g1jwsv6-cor?locale=en
https://curate-test.library.emory.edu/collections/815p8cz8wv-cor?locale=en

They do seem to display in Lux, however!

**Comment by bwatson78** [comment]
It seems that the saved storage locations for the banners may have been corrupted. 
![Screen Shot 2022-11-18 at 12.26.48 PM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/74913767-0265-4ec3-83be-47d7c9710aa0)
The only banner that I see within the application is for 730bvq83nz-cor, which populates. 

Now looking into where Lux is pulling the images.

**Comment by bwatson78** [comment]
The banners for Digital Test are actually missing. You may have been clicking through the front page Featured Collections, that point to Lux Production.

**Comment by bwatson78** [comment]
There seems to be some issue with the `mnt` locations the banners are supposed to be stored in. Reaching out to Middleware to see if they can track down what happened there.

**Comment by eporter23** [comment]
Banner images in arch are loading as expected, so this seems to impact the test environment only.

**Comment by eporter23** [comment]
@jcrompton42 researched this and determined that they had been manually deleted at some point but we don't have timestamps on the actions. This does not seem to have occurred as part of a any scripted activity.

**Comment by eporter23** [comment]
We suspect the banners may have been manually deleted while diagnosing a previous Hyrax upgrade in which banner objects were changed and ours were no longer compatible.
