### ISSUE TITLE
Collection show pages do not re-sort 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2040]
**Describe the bug**
When viewing a collection in either the Dashboard or Public views, the Sort By options for viewing the list of works no longer appear to work after our recent Hyrax 3.4.x upgrades.

**To Reproduce**
1. Go to Dashboard > Collections and view a collection that has a range of works deposited on different dates e.g. [Rose Test Collection](https://curate-test.library.emory.edu/collections/139x0k6dts-cor?utf8=✓&sort=system_create_dtsi+asc&per_page=10&locale=en) or [Regression Test Collection](https://curate-test.library.emory.edu/dashboard/collections/7375tb2rnd-cor?utf8=✓&sort=system_create_dtsi+asc&per_page=10&locale=en). 
2. Click on Sort By to change it from Relevance to Date Uploaded descending
3. Observe that the list of works has not changed
4. Click on Sort By > Date Uploaded to change it to ascending
5. Observe that the list of works has not changed

**Expected behavior**

In production, if you sort works by Date Uploaded ascending or descending, the list of works changes to reflect those options.

![Screen Shot 2022-11-21 at 11.09.41 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/57486149-76de-4e70-b10e-1451631dc9e8)

![Screen Shot 2022-11-21 at 11.09.56 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/fdf04559-dec0-49b5-b94c-9a8972b4eb2e)

**Screenshots**

In Curate test, sorting by Date Uploaded ascending and descending does not change the results shown. 

![Screen Shot 2022-11-21 at 11.12.11 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/27a06e6f-8561-489b-aae6-703653093b68)

![Screen Shot 2022-11-21 at 11.12.11 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1ed502ff-26f6-4ab6-89ac-629b8d8174c2)

**Comment by bwatson78** [comment]
This is a known bug with an [open ticket](https://github.com/samvera/hyrax/issues/5905) in Hyrax' github.

**Comment by bwatson78** [comment]
I've created a PR request in Hyrax to address this issue: https://github.com/samvera/hyrax/pull/5920. I've also incorporated the changes into Curate as an override, which should be removed as soon as Hyrax reviewers approve of the changes and hopefully backport the fix into our version.

**Comment by eporter23** [comment]
@bwatson78 looks great!
