### ISSUE TITLE
Transfer North GA Methodist Journals batch 5 files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2044]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/NGaMethJrnls/000015264593_1905
lsdi2/tesseract/NGaMethJrnls/000015264593_1906
lsdi2/tesseract/NGaMethJrnls/000015264593_1907
lsdi2/tesseract/NGaMethJrnls/000015264593_1908
lsdi2/tesseract/NGaMethJrnls/000015264593_1909
lsdi2/tesseract/NGaMethJrnls/000015264601_1929
lsdi2/tesseract/NGaMethJrnls/300000170510_1900
lsdi2/tesseract/NGaMethJrnls/300000170510_1901
lsdi2/tesseract/NGaMethJrnls/300000170510_1902
lsdi2/tesseract/NGaMethJrnls/300000170510_1903
lsdi2/tesseract/NGaMethJrnls/300000170510_1904
lsdi2/tesseract/NGaMethJrnls/300000170523

**Comment by jcrompton42** [comment]
transferred

**Comment by kmichaelis** [comment]
@jcrompton42 I don't see these folders on EFS, can you please double check?

**Comment by jcrompton42** [comment]
@kmichaelis AARGH, I left out slash so they ended up on the wrong folder on efs, fixed, you should see them now.

**Comment by kmichaelis** [comment]
Thanks!
