### ISSUE TITLE
Transfer Emory Unit files and one catalog

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2054]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Health_Sciences/HS-S015_USArmy_GenHosp_43rd/B001/F006

dmfiles/Libraries/Health_Sciences/HS-S015_USArmy_GenHosp_43rd/B001/F007 (A few files have been added since originally transferred)

dmfiles/Libraries/Health_Sciences/HS-S015_USArmy_GenHosp_43rd/B001/F010 (A few files have been added since originally transferred)

dmfiles/Libraries/Health_Sciences/HS-S015_USArmy_GenHosp_43rd/B001/F011 (A few files have been added since originally transferred)

lsdi2/ftp/Medicine_1965-1966 (only TXT files were transferred to EFS)

**Comment by jcrompton42** [comment]
transferred.
