### ISSUE TITLE
Manually uploaded filesets show "Not Yet Characterized"

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2062]
**Describe the bug**
When using the Create/Edit work form to create filesets, the majority of uploaded filesets show no characterization data, though the characterization event shows in the Preservation Events.  

**To Reproduce**
1. Go to a test work, or create a new work
2. Click on the Files tab of the work form
3. Create a fileset
4. Wait for the fileset to be created and then view the fileset page
5. Note that the fileset says "not yet characterized" and no thumbnail is generated

Clicking on regenerate derivate typically resolves this problem, but it occurs at a very high rate so we should identify the underlying cause. To recreate this error I [created a new test work ](https://curate-test.library.emory.edu/concern/parent/3009w0vtdw-cor/file_sets/344pk0p2z8-cor) and added 5 FileSets manually. 4/5 show the "not yet characterized" message.

![Screen Shot 2022-12-09 at 1.28.01 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a2175bb0-8f2d-4908-860a-4ceba5e4b970)
**Expected behavior**

When a new fileset is added, the appropriate jobs and indexing occur so that characterization data is shown and a thumbnail is generated. This should occur automatically the majority of the time (not the minority of the time).

**Screenshots**

See above.

**Additional context**

We notice this also seems to happen related to the new filesets created for the full text data files generated in the full text prototype process.

**Comment by bwatson78** [comment]
FYI: We announce Characterizations as a "Success" right after the process is run, not checking whether it was truly characterized. I'm going to check what way the view checks for "Not Yet Characterized" to put that in place for our PreservationEvents.

**Comment by bwatson78** [comment]
Preliminary Findings: The FileSets attached to the work above just needed to be reindexed to reflect the Characterization. I am moving forward with altering our Characterization steps so that we reined the FileSet right after we characterize it and verify that the typical characterization values are populated before passing that to the PreservationEvents.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/2119

**Comment by eporter23** [comment]
@bwatson78 this is in 2.7, right? I created this work with manually uploaded filesets in curate test, but I'm still seeing the issue. https://curate-test.library.emory.edu/concern/curate_generic_works/11615dv4c2-cor?locale=en

**Comment by eporter23** [comment]
Disregard the above, I see it's only on arch right now.

**Comment by eporter23** [comment]
Created some filesets manually on this work in arch with 2.7.0. Same issue is persisting. https://curate-arch.library.emory.edu/concern/curate_generic_works/699n2z34xp-cor?locale=en

**Comment by bwatson78** [comment]
Well, lovely, back to the drawing board.

**Comment by eporter23** [comment]
The latest fix is working really well. Tested on [this work](https://curate-arch.library.emory.edu/concern/curate_generic_works/631cjsxkvx-cor?locale=en) with 3 manually uploaded filesets. Note for posterity: when a user manually uploads a fileset, they need to wait to see it attach and then can go to the View Fileset page, then click refresh. These screenshots were taken within a minute of each other (pre and post refresh). ![Screen Shot 2023-03-03 at 4.32.27 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9b2ec579-ce93-4a48-bdc4-0f3884410e25) 
![Screen Shot 2023-03-03 at 4.32.37 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/2278f4d3-23ad-4422-916e-7168b3ba0080)

**Comment by eporter23** [comment]
Works great in production as well.
