### ISSUE TITLE
Simplify/automate process to cancel busy jobs in sidekiq

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2064]
When we occasionally need to stop an unwanted process that has entered the Busy queue in sidekiq, the team often encounters difficulty doing so.

After a recent incident on 12/12/22 we discussed in Slack creating a ruby command line rake task that can be run when needed.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/2115

**Comment by bwatson78** [comment]
This is in v2.8.0, which is live in Test and Arch at this moment. 

To run this task, use the command `RAILS_ENV=production bundle exec rake curate:set_busy_jobs_to_cancel job_ids=<- a string of SideKiq job ids separated by a space " " ->`. 

That won't automatically cancel the Jobs. The next step is to restart the environment's SideKiq.
Stop: `bundle exec sidekiqctl stop <- location of SideKiq's pid -> 0`
Start: `bundle exec sidekiq -d`

When the SideKiq instance starts back up, it will check for unfinished jobs, see that the ones you marked for cancellation shouldn't be restarted and flush them--hopefully.
