### ISSUE TITLE
Update Curate users/groups

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2065]
User account cleanups needed as of Dec 2022:

Please create as new users and add to rose_viewer group:

- [x] rdetzle
- [x] kgmorr2
- [x] cfluke2

Please remove these users and remove from rose_viewer group:

- [x] eshoem2
- [x] kchason
- [x] lrowe8
- [x] ntwemlo
- [x] squigle
- [x] tthom70
- [x] vpate68

Please remove these users and remove from any groups:

- [x] adeese2
- [x] Devanshu Matlawala (dmatlaw)
- [x] Maxwell Benjamin Kadel (mkadel)
- [x] mlanie3
- [x] mtkowal
- [x] rkadel2

**Comment by bwatson78** [comment]
Completed all environments.

**Comment by eporter23** [comment]
Looks good @bwatson78! Note to self: we should make these consistent across all environments (using prod as our benchmark) at some point. Looks like we have slightly different user bases in the 3 environments but this isn't essential to fix right now.
