### ISSUE TITLE
Transfer batch of catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2066]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

If any of these folders already exist on EFS, please overwrite existing folders with new ones.

lsdi2/ftp/emorybulletin/010001131466-v3-no11
lsdi2/ftp/emorybulletin/010001131456-v15-no10
lsdi2/ftp/emorybulletin/010001131470-Announcements
lsdi2/ftp/emorybulletin/010001131468-Announcements
lsdi2/ftp/emorybulletin/010001131460-English
lsdi2/ftp/emorybulletin/010001131463-Trustees
lsdi2/ftp/emorybulletin/010001131461-Bulletin
lsdi2/ftp/emorybulletin/010001131460-Bulletin
lsdi2/ftp/emorybulletin/010001131459-Bulletin
lsdi2/ftp/emorybulletin/010001131458-v13-no2
lsdi2/ftp/emorybulletin/010001131457-v14-no1
lsdi2/ftp/emorybulletin/010001131466-v4-no1
lsdi2/ftp/emorybulletin/010001131470-theology
lsdi2/ftp/emorybulletin/010001131468-Theology
lsdi2/ftp/emorybulletin/010001131466-v3-no5
lsdi2/ftp/emorybulletin/010001131466-v4-no4
lsdi2/ftp/emorybulletin/010001131465-1920-Theology
lsdi2/ftp/emorybulletin/010001131463-Theology
lsdi2/ftp/emorybulletin/010001131462-Theology
lsdi2/ftp/emorybulletin/010001131461-Theology
lsdi2/ftp/emorybulletin/010001131460-Theology-Suppl
lsdi2/ftp/emorybulletin/010001131459-Theology
lsdi2/ftp/emorybulletin/010001131458-v13-no7
lsdi2/ftp/emorybulletin/010001131457-v14-no4
lsdi2/ftp/emorybulletin/010001131456-v15-no5
lsdi2/ftp/emorybulletin/010001131455-v16-no6
lsdi2/ftp/emorybulletin/010001131455-Theology-Summer
lsdi2/ftp/emorybulletin/010001131460-Theology
lsdi2/ftp/emorybulletin/010001131459-Theology-Summer
lsdi2/ftp/Business_1931
lsdi2/ftp/Business_1937
lsdi2/ftp/Business_1938
lsdi2/ftp/Business_1939
lsdi2/ftp/Business_1950
lsdi2/ftp/Business_1951
lsdi2/ftp/Business_1952
lsdi2/ftp/Business_1953
lsdi2/ftp/Business_1954
lsdi2/ftp/Business_1955-1
lsdi2/ftp/Business_1955-2
lsdi2/ftp/Business_1956
lsdi2/ftp/Business_1957
lsdi2/ftp/Business_1958
lsdi2/ftp/Business_1959
lsdi2/ftp/Business_BBA_1987-1988
lsdi2/ftp/Medicine_1970-1971
lsdi2/ftp/Theology_1945
lsdi2/ftp/Theology_1953
lsdi2/ftp/Theology_1982-1983
lsdi2/ftp/emorybulletin/010001131466-Charter-Deeds
lsdi2/ftp/emorybulletin/010001131460-Religion
lsdi2/ftp/emorybulletin/010001131462-Correspondence
lsdi2/ftp/emorybulletin/010001131458-v12-no7
lsdi2/ftp/emorybulletin/010001131466-v4-no2
lsdi2/ftp/emorybulletin/010001131458-v13-no8
lsdi2/ftp/emorybulletin/010001131456-Valdosta
lsdi2/ftp/emorybulletin/010001131457-Valdosta
lsdi2/ftp/emorybulletin/010001131465-1920-Summer
lsdi2/ftp/emorybulletin/010001131464-Summer
lsdi2/ftp/emorybulletin/010001131465-1919-Summer
lsdi2/ftp/emorybulletin/010001131463-Summer
lsdi2/ftp/emorybulletin/010001131462-Summer
lsdi2/ftp/emorybulletin/010001131461-Summer
lsdi2/ftp/emorybulletin/010001131460-Summer
lsdi2/ftp/emorybulletin/010001131459-Summer
lsdi2/ftp/emorybulletin/010001131458-v13-no5
lsdi2/ftp/emorybulletin/010001131457-v14-no3
lsdi2/ftp/emorybulletin/010001131456-v15-no3
lsdi2/ftp/emorybulletin/010001131458-v13-no5-Suppl
lsdi2/ftp/emorybulletin/010001131468-Academy
lsdi2/ftp/emorybulletin/010001131466-v3-no10
lsdi2/ftp/emorybulletin/010001131466-Academy-v2
lsdi2/ftp/emorybulletin/010001131466-Academy-v3
lsdi2/ftp/emorybulletin/010001131465-1919-Academy
lsdi2/ftp/emorybulletin/010001131465-1920-Academy
lsdi2/ftp/emorybulletin/010001131462-Academy
lsdi2/ftp/emorybulletin/010001131463-Academy
lsdi2/ftp/emorybulletin/010001131461-Academy
lsdi2/ftp/emorybulletin/010001131460-Academy
lsdi2/ftp/emorybulletin/010001131465-1919-Catalogue
lsdi2/ftp/emorybulletin/010001131465-1920-Catalogue
lsdi2/ftp/emorybulletin/010001131464-Catalogue
lsdi2/ftp/emorybulletin/010001131463-Catalogue
lsdi2/ftp/emorybulletin/010001131462-Catalogue
lsdi2/ftp/emorybulletin/010001131461-Catalogue
lsdi2/ftp/emorybulletin/010001131460-Catalogue
lsdi2/ftp/emorybulletin/010001131459-Catalogue
lsdi2/ftp/emorybulletin/010001131458-v13-no3
lsdi2/ftp/emorybulletin/010001131457-v14-no2
lsdi2/ftp/emorybulletin/010001131456-v15-no2
lsdi2/ftp/emorybulletin/010001131455-v16-no2
lsdi2/ftp/General_1930
lsdi2/ftp/emorybulletin/010001131459-Extension-Fall25
lsdi2/ftp/emorybulletin/010001131459-Extension-Fall26
lsdi2/ftp/emorybulletin/010001131458-v13-no9
lsdi2/ftp/emorybulletin/010001131457-v14-no7
lsdi2/ftp/emorybulletin/010001131456-v15-no12
lsdi2/ftp/emorybulletin/010001131459-Extension-Spr26
lsdi2/ftp/emorybulletin/010001131457-v14-Supp.2
lsdi2/ftp/emorybulletin/010001131456-v15-no4-Suppl
lsdi2/ftp/emorybulletin/010001131457-v14-no10
lsdi2/ftp/emorybulletin/010001131456-v15-no1
lsdi2/ftp/emorybulletin/010001131466-v3-no3
lsdi2/ftp/010001334825
lsdi2/ftp/emorybulletin/010001131468-Law
lsdi2/ftp/emorybulletin/010001131468-Law-Supplement
lsdi2/ftp/emorybulletin/010001131466-v3-no2
lsdi2/ftp/emorybulletin/010001131464-Law
lsdi2/ftp/emorybulletin/010001131463-Law
lsdi2/ftp/emorybulletin/010001131462-Law
lsdi2/ftp/emorybulletin/010001131461-Law
lsdi2/ftp/emorybulletin/010001131460-Law
lsdi2/ftp/emorybulletin/010001131459-Law
lsdi2/ftp/emorybulletin/010001131458-v13-no6
lsdi2/ftp/emorybulletin/010001131457-v14-no6
lsdi2/ftp/emorybulletin/010001131456-v15-no7
lsdi2/ftp/emorybulletin/010001131455-v16-no5
lsdi2/ftp/emorybulletin/010001131458-Library
lsdi2/ftp/emorybulletin/010001131460-Modern-Freedom
lsdi2/ftp/emorybulletin/010001131466-v3-no8
lsdi2/ftp/emorybulletin/010001131466-v3-no9
lsdi2/ftp/emorybulletin/010001131456-v15-no4
lsdi2/ftp/emorybulletin/010001131466-v3-no1
lsdi2/ftp/emorybulletin/010001131461-Honors
lsdi2/ftp/emorybulletin/010001131466-Educational-Comm
lsdi2/ftp/Business_1930
lsdi2/ftp/emorybulletin/010001131470-College
lsdi2/ftp/emorybulletin/010001131468-College
lsdi2/ftp/emorybulletin/010001131466-v3-no4
lsdi2/ftp/emorybulletin/010001131466-v4-no3
lsdi2/ftp/emorybulletin/010001131470-Medicine
lsdi2/ftp/emorybulletin/010001131466-v3-no6
lsdi2/ftp/emorybulletin/010001131466-v4-no5
lsdi2/ftp/emorybulletin/010001131464-Medicine
lsdi2/ftp/emorybulletin/010001131463-Medicine
lsdi2/ftp/emorybulletin/010001131462-Medicine
lsdi2/ftp/emorybulletin/010001131461-Medicine
lsdi2/ftp/emorybulletin/010001131460-Medicine
lsdi2/ftp/emorybulletin/010001131459-Medicine
lsdi2/ftp/emorybulletin/010001131458-v13-no4
lsdi2/ftp/emorybulletin/010001131457-v14-no5
lsdi2/ftp/emorybulletin/010001131456-v15-no6
lsdi2/ftp/emorybulletin/010001131455-v16-no8
lsdi2/ftp/emorybulletin/010001131456-v15-no8
lsdi2/ftp/Theology_1996-1997
lsdi2/ftp/Theology_1997-1998
lsdi2/ftp/emorybulletin/010001131466-v3-no12
lsdi2/ftp/emorybulletin/010001131460-Christ
lsdi2/ftp/emorybulletin/010001131460-Libraries-History
lsdi2/ftp/emorybulletin/010001131468-Opening
lsdi2/ftp/emorybulletin/010001131468-Wealth
lsdi2/ftp/emorybulletin/010001131456-v15-no9

**Comment by jcrompton42** [comment]
transferred
