### ISSUE TITLE
Bulkrax enhancements for production use

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2067]
This epic identifies several user-interface related enhancements for the Bulkrax interface to assist with user needs.

## Story
_As a Library Staff Depositor, I want to streamline the Bulkrax selection interface, so that I can more precisely select assets for importing and exporting_

**For the importer:**

- [x] The default sort of the top level importers list should be sorted to the date (and timestamp) of when the importer was created or validated. Currently it seems to default to alphabetical. While it is possible to re-sort by clicking on Last Run, this must be clicked several times and then does not appear to sort by timestamp. When navigating away and back to the importers list, a user must then re-sort once again.
- [x] Add a filter/view option to only show importers whose Status are not yet Complete. This helps depositors quickly get to importers that need to be run.

**Comment by bwatson78** [comment]
PR #2083 made for task 2.

**Comment by eporter23** [comment]
@bwatson78 this works very well! I am wondering how much effort it would take to make the filter controls more readable? The sort options are much smaller than the other controls, and the Status label is truncated. 

Chrome:

![Chrome Filters.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/58436970-d513-4b66-97b0-a5a83b03da25)

Safari:

![Safari filters.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7f6028ba-c7da-4ecd-86e3-51f52664e1b9)

Could we resize the elements to display more like this? I set a width on the container of 40% and adjusted the height of the sort buttons to match the next and previous arrows. 

![Filters resized.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/13f73453-9382-4c9c-aded-445cadb6b499)![Chrome Filters.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/1b2207c7-f89a-4b12-ae1e-244ce8a206b4)

**Comment by bwatson78** [comment]
On it.

**Comment by bwatson78** [comment]
PR made: #2089

**Comment by eporter23** [comment]
Looks great @bwatson78 !
