### ISSUE TITLE
Add Google Analytics tracking code to Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2094]
We created an account, but it was never added to Curate's markup.

As part of the Google Analytics 4 transition, we can add the new GA4 account ID.

G-TJW5N4RJNY

![Screen Shot 2023-01-19 at 3.38.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/761b3d94-4828-4eb9-b1c4-941c57b05630)

Prior ticket for adding Google Analytics to Lux:
https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-lux/189

**Comment by bwatson78** [comment]
PR made: #2100

**Comment by eporter23** [comment]
I'm seeing the script tag now, but the ID is missing: ![Screen Shot 2023-02-09 at 12.26.46 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/8ea5b50d-42aa-41a5-887c-cba3a8f3a43f)
