### ISSUE TITLE
Transfer 3 catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2098]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/emorybulletin/010001131455-v16-no7
lsdi2/ftp/emorybulletin/010001131455-v16-no9
lsdi2/ftp/emorybulletin/010001131455-v16-no10

**Comment by jcrompton42** [comment]
transferred
