### ISSUE TITLE
Transfer books from the William Scott collection

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2101]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

*If any of these folders do not exist, please let me know which ones. Thanks!

lsdi2/ftp/010001341673
lsdi2/ftp/010001334293
lsdi2/ftp/010001341674
lsdi2/ftp/000011820613
lsdi2/ftp/010001334505
lsdi2/ftp/010001334291
lsdi2/ftp/010001334727
lsdi2/ftp/010001334190
lsdi2/ftp/010001349531
lsdi2/ftp/010001334193
lsdi2/ftp/010001334014
lsdi2/ftp/010001334015
lsdi2/ftp/010001334535
lsdi2/ftp/010000125103
lsdi2/ftp/010001334104
lsdi2/ftp/010001334257
lsdi2/ftp/010001334192
lsdi2/ftp/010001334013
lsdi2/ftp/010001334396
lsdi2/ftp/010001334189
lsdi2/ftp/10002350160
lsdi2/ftp/010001334465
lsdi2/ftp/010001334256
lsdi2/ftp/010001334511
lsdi2/ftp/010001334534
lsdi2/ftp/010001334049
lsdi2/ftp/010001334050
lsdi2/ftp/010001334292
lsdi2/ftp/010001334102
lsdi2/ftp/010001334360
lsdi2/ftp/010001334361
lsdi2/ftp/010001334255
lsdi2/ftp/010001334315
lsdi2/ftp/010001334314
lsdi2/ftp/010001334280
lsdi2/ftp/010001334279
lsdi2/ftp/010001278358
lsdi2/ftp/010000709818
lsdi2/ftp/010002718358
lsdi2/ftp/010001334281
lsdi2/ftp/010001334316
lsdi2/ftp/010000709271
lsdi2/ftp/010001334478
lsdi2/ftp/010001334191
lsdi2/ftp/010001334481
lsdi2/ftp/010001334480
lsdi2/ftp/010001334479
lsdi2/ftp/010001334101
lsdi2/ftp/000011818867
lsdi2/ftp/010001334512

**Comment by jcrompton42** [comment]
Transferred all but the following 6 folders which do not exist:
lsdi2/ftp/010001334534
lsdi2/ftp/010001334292
lsdi2/ftp/010001334255 
lsdi2/ftp/010001334279 
lsdi2/ftp/010001334191 
lsdi2/ftp/010001334479
