### ISSUE TITLE
Transfer born digital catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2108]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/BDCatalogs/ECAS_2013-2014
lsdi2/tesseract/BDCatalogs/ECAS_2014-2015
lsdi2/tesseract/BDCatalogs/ECAS_2015-2016
lsdi2/tesseract/BDCatalogs/ECAS_2016-2017
lsdi2/tesseract/BDCatalogs/ECAS_2017-2018
lsdi2/tesseract/BDCatalogs/ECAS_2018-2019
lsdi2/tesseract/BDCatalogs/ECAS_2019-2020
lsdi2/tesseract/BDCatalogs/ECAS_2020-2021
lsdi2/tesseract/BDCatalogs/ECAS_2021-2022
lsdi2/tesseract/BDCatalogs/ECAS_2022-2023
lsdi2/tesseract/BDCatalogs/OXF_2014-2015
lsdi2/tesseract/BDCatalogs/OXF_2015-2016
lsdi2/tesseract/BDCatalogs/OXF_2016-2017
lsdi2/tesseract/BDCatalogs/OXF_2017-2018
lsdi2/tesseract/BDCatalogs/OXF_2018-2019
lsdi2/tesseract/BDCatalogs/OXF_2019-2020
lsdi2/tesseract/BDCatalogs/OXF_2020-2021
lsdi2/tesseract/BDCatalogs/OXF_2021-2022
lsdi2/tesseract/BDCatalogs/OXF_2022-2023
lsdi2/tesseract/BDCatalogs/RSPH_2016-2017
lsdi2/tesseract/BDCatalogs/RSPH_2017-2018
lsdi2/tesseract/BDCatalogs/RSPH_2018-2019
lsdi2/tesseract/BDCatalogs/RSPH_2019-2020
lsdi2/tesseract/BDCatalogs/RSPH_2020-2021
lsdi2/tesseract/BDCatalogs/RSPH_2021-2022
lsdi2/tesseract/BDCatalogs/RSPH_2022-2023
lsdi2/tesseract/BDCatalogs/THEO_2014-2015
lsdi2/tesseract/BDCatalogs/THEO_2015-2016
lsdi2/tesseract/BDCatalogs/THEO_2016-2017
lsdi2/tesseract/BDCatalogs/THEO_2017-2018
lsdi2/tesseract/BDCatalogs/THEO_2018-2019
lsdi2/tesseract/BDCatalogs/THEO_2019-2020
lsdi2/tesseract/BDCatalogs/THEO_2021-2022
lsdi2/tesseract/BDCatalogs/THEO_2022-2023

**Comment by jcrompton42** [comment]
transferred.
