### ISSUE TITLE
Re-transfer catalog

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2109]
I tried to ingest the catalog with this filepath:

lsdi2/ftp/emorybulletin/010001131460-Theology-Suppl

and discovered that while the folders for each file format exist on EFS, none of them actually contain files. Can you please re-transfer those files from the same path on /opt?

**Comment by jcrompton42** [comment]
Did some spot checks and this was true for several of the folders from that ticket. Retransferred all of them. Looking better now.
