### ISSUE TITLE
Transfer Emory Lawyer batch 2 files to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2138]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/EmoryLawyer/L-026_B009_F001
lsdi2/tesseract/EmoryLawyer/L-026_B009_F002
lsdi2/tesseract/EmoryLawyer/L-026_B009_F003
lsdi2/tesseract/EmoryLawyer/L-026_B009_F004
lsdi2/tesseract/EmoryLawyer/L-026_B009_F005
lsdi2/tesseract/EmoryLawyer/L-026_B009_F006
lsdi2/tesseract/EmoryLawyer/L-026_B009_F007
lsdi2/tesseract/EmoryLawyer/L-026_B009_F008
lsdi2/tesseract/EmoryLawyer/L-026_B009_F009
lsdi2/tesseract/EmoryLawyer/L-026_B009_F010
lsdi2/tesseract/EmoryLawyer/L-026_B009_F011
lsdi2/tesseract/EmoryLawyer/L-026_B009_F012
lsdi2/tesseract/EmoryLawyer/L-026_B010_F001
lsdi2/tesseract/EmoryLawyer/L-026_B010_F002
lsdi2/tesseract/EmoryLawyer/L-026_B010_F003
lsdi2/tesseract/EmoryLawyer/L-026_B010_F004
lsdi2/tesseract/EmoryLawyer/L-026_B010_F005
lsdi2/tesseract/EmoryLawyer/L-026_B010_F006
lsdi2/tesseract/EmoryLawyer/L-026_B010_F007
lsdi2/tesseract/EmoryLawyer/L-026_B010_F008
lsdi2/tesseract/EmoryLawyer/L-026_B010_F009
lsdi2/tesseract/EmoryLawyer/L-026_B010_F010
lsdi2/tesseract/EmoryLawyer/L-026_B010_F011

**Comment by jcrompton42** [comment]
transferred.
