### ISSUE TITLE
Transfer another Kessler batch

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2140]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/300000218037
lsdi2/tesseract/Kessler/300000458539
lsdi2/tesseract/Kessler/300000082606
lsdi2/tesseract/Kessler/300000206017
lsdi2/tesseract/Kessler/300000218191
lsdi2/tesseract/Kessler/300000082616
lsdi2/tesseract/Kessler/300000218194
lsdi2/tesseract/Kessler/000015285833
lsdi2/tesseract/Kessler/300000218101
lsdi2/tesseract/Kessler/300000281640
lsdi2/tesseract/Kessler/300000218113
lsdi2/tesseract/Kessler/300000155474
lsdi2/tesseract/Kessler/300000242321
lsdi2/tesseract/Kessler/300000281189
lsdi2/tesseract/Kessler/300000458953
lsdi2/tesseract/Kessler/000015149569
lsdi2/tesseract/Kessler/300000112685
lsdi2/tesseract/Kessler/000015274915
lsdi2/tesseract/Kessler/000015274917
lsdi2/tesseract/Kessler/300000218048
lsdi2/tesseract/Kessler/300000089730
lsdi2/tesseract/Kessler/300000218198
lsdi2/tesseract/Kessler/300000197963
lsdi2/tesseract/Kessler/300000290032
lsdi2/tesseract/Kessler/300000218255
lsdi2/tesseract/Kessler/300000218096
lsdi2/tesseract/Kessler/300000218153
lsdi2/tesseract/Kessler/300000218215
lsdi2/tesseract/Kessler/300000218254
lsdi2/tesseract/Kessler/300000218256

**Comment by jcrompton42** [comment]
transferred
