### ISSUE TITLE
Transfer Views of Rome books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2145]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/000011287308
lsdi2/ftp/000020265295
lsdi2/ftp/010000125183
lsdi2/ftp/010000154212
lsdi2/ftp/010000211961
lsdi2/ftp/010000215606
lsdi2/ftp/010000351768
lsdi2/ftp/010000426397
lsdi2/tesseract/ViewsOfRome/010001023892
lsdi2/ftp/010001059216
lsdi2/ftp/010001102857
lsdi2/tesseract/ViewsOfRome/010001133889
lsdi2/ftp/010001171586
lsdi2/ftp/010001224383
lsdi2/ftp/010001275193
lsdi2/ftp/010001275677
lsdi2/ftp/010001275678
lsdi2/ftp/010001275679
lsdi2/ftp/010001278310
lsdi2/ftp/010001278661
lsdi2/tesseract/ViewsOfRome/010001278878
lsdi2/ftp/010001334059
lsdi2/ftp/010001338920
lsdi2/ftp/010001349625
lsdi2/ftp/010001355776
lsdi2/ftp/010002405871
lsdi2/ftp/010002405872
lsdi2/ftp/010002405873
lsdi2/ftp/010002408932
lsdi2/ftp/010002408933
lsdi2/ftp/010002408934
lsdi2/ftp/010002426372
lsdi2/ftp/010002426372
lsdi2/ftp/010002426412
lsdi2/ftp/010002426413
lsdi2/tesseract/ViewsOfRome/010002586000
lsdi2/ftp/010002588343
lsdi2/ftp/010002630940
lsdi2/ftp/010002632180
lsdi2/tesseract/ViewsOfRome/010002713656
lsdi2/ftp/010002718615
lsdi2/ftp/010002990692
lsdi2/ftp/010002990710
lsdi2/ftp/010003050501
lsdi2/ftp/010003050994
lsdi2/ftp/010003065174
lsdi2/ftp/010003065175
lsdi2/ftp/010003065187
lsdi2/ftp/010003065188
lsdi2/ftp/010003065351
lsdi2/tesseract/ViewsOfRome/010003196432
lsdi2/tesseract/ViewsOfRome/300000049365
lsdi2/tesseract/ViewsOfRome/300000202053
lsdi2/tesseract/ViewsOfRome/300000202456
lsdi2/tesseract/ViewsOfRome/300000413252

**Comment by jcrompton42** [comment]
transferred except for 
 /opt/lsdi2/ftp/010001275678
/opt/lsdi2/ftp/010001275679 

neither of which exist.
