### ISSUE TITLE
Transfer more registrar catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2149]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/BDCatalogs/GBS_2014-2015
lsdi2/tesseract/BDCatalogs/GBS_2015-2016
lsdi2/tesseract/BDCatalogs/GBS_2016-2017
lsdi2/tesseract/BDCatalogs/GBS_2017-2018
lsdi2/tesseract/BDCatalogs/LGS_2017-2018

**Comment by jcrompton42** [comment]
transferred
