### ISSUE TITLE
Transfer another batch of John and Charles Wesley books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2151]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Wesley/000015004364
lsdi2/tesseract/Wesley/000015004677
lsdi2/tesseract/Wesley/000020088148
lsdi2/tesseract/Wesley/300000111106
lsdi2/tesseract/Wesley/300000220486
lsdi2/tesseract/Wesley/300000510568
lsdi2/tesseract/Wesley/300000510997

**Comment by jcrompton42** [comment]
transferred
