### ISSUE TITLE
Transfer Inman Park Association Records

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2152]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/IPA/1972/HR_1972-01
lsdi2/tesseract/IPA/1972/HR_1972-04
lsdi2/tesseract/IPA/1973/IPA_1973-01
lsdi2/tesseract/IPA/1973/IPA_1973-03
lsdi2/tesseract/IPA/1973/IPA_1973-04
lsdi2/tesseract/IPA/1973/IPA_1973-05
lsdi2/tesseract/IPA/1973/IPA_1973-06
lsdi2/tesseract/IPA/1974/IPA_1974-04
lsdi2/tesseract/IPA/1974/IPA_1974-05
lsdi2/tesseract/IPA/1974/IPA_1974-06
lsdi2/tesseract/IPA/1974/IPA_1974-07
lsdi2/tesseract/IPA/1974/IPA_1974-09
lsdi2/tesseract/IPA/1974/IPA_1974-10
lsdi2/tesseract/IPA/1974/IPA_1974-11
lsdi2/tesseract/IPA/1974/IPA_1974-12
lsdi2/tesseract/IPA/1975/IPA_1975-01
lsdi2/tesseract/IPA/1975/IPA_1975-02
lsdi2/tesseract/IPA/1975/IPA_1975-03
lsdi2/tesseract/IPA/1975/IPA_1975-04
lsdi2/tesseract/IPA/1975/IPA_1975-05
lsdi2/tesseract/IPA/1975/IPA_1975-06
lsdi2/tesseract/IPA/1975/IPA_1975-07
lsdi2/tesseract/IPA/1975/IPA_1975-09
lsdi2/tesseract/IPA/1975/IPA_1975-10
lsdi2/tesseract/IPA/1975/IPA_1975-11
lsdi2/tesseract/IPA/1975/IPA_1975-12
lsdi2/tesseract/IPA/1976/IPA_1976-01
lsdi2/tesseract/IPA/1976/IPA_1976-02
lsdi2/tesseract/IPA/1976/IPA_1976-03
lsdi2/tesseract/IPA/1976/IPA_1976-04
lsdi2/tesseract/IPA/1976/IPA_1976-05
lsdi2/tesseract/IPA/1976/IPA_1976-06
lsdi2/tesseract/IPA/1976/IPA_1976-07
lsdi2/tesseract/IPA/1976/IPA_1976-09
lsdi2/tesseract/IPA/1976/IPA_1976-10
lsdi2/tesseract/IPA/1976/IPA_1976-11
lsdi2/tesseract/IPA/1976/IPA_1976-12
lsdi2/tesseract/IPA/1977/IPA_1977-01
lsdi2/tesseract/IPA/1977/IPA_1977-02
lsdi2/tesseract/IPA/1977/IPA_1977-03
lsdi2/tesseract/IPA/1977/IPA_1977-04
lsdi2/tesseract/IPA/1977/IPA_1977-05
lsdi2/tesseract/IPA/1977/IPA_1977-09
lsdi2/tesseract/IPA/1977/IPA_1977-10
lsdi2/tesseract/IPA/1978/IPA_1978-02
lsdi2/tesseract/IPA/1978/IPA_1978-03
lsdi2/tesseract/IPA/1978/IPA_1978-04
lsdi2/tesseract/IPA/1978/IPA_1978-05
lsdi2/tesseract/IPA/1978/IPA_1978-06
lsdi2/tesseract/IPA/1978/IPA_1978-09
lsdi2/tesseract/IPA/1978/IPA_1978-10
lsdi2/tesseract/IPA/1978/IPA_1978-11
lsdi2/tesseract/IPA/1979/IPA_1979-01
lsdi2/tesseract/IPA/1979/IPA_1979-02
lsdi2/tesseract/IPA/1979/IPA_1979-03
lsdi2/tesseract/IPA/1979/IPA_1979-04
lsdi2/tesseract/IPA/1979/IPA_1979-05
lsdi2/tesseract/IPA/1979/IPA_1979-06
lsdi2/tesseract/IPA/1979/IPA_1979-07
lsdi2/tesseract/IPA/1979/IPA_1979-08
lsdi2/tesseract/IPA/1979/IPA_1979-09
lsdi2/tesseract/IPA/1979/IPA_1979-10
lsdi2/tesseract/IPA/1979/IPA_1979-11
lsdi2/tesseract/IPA/1979/IPA_1979-12
lsdi2/tesseract/IPA/1980/IPA_1980-01
lsdi2/tesseract/IPA/1980/IPA_1980-02
lsdi2/tesseract/IPA/1980/IPA_1980-03
lsdi2/tesseract/IPA/1980/IPA_1980-04
lsdi2/tesseract/IPA/1980/IPA_1980-05
lsdi2/tesseract/IPA/1980/IPA_1980-06
lsdi2/tesseract/IPA/1980/IPA_1980-07
lsdi2/tesseract/IPA/1980/IPA_1980-08
lsdi2/tesseract/IPA/1980/IPA_1980-09
lsdi2/tesseract/IPA/1980/IPA_1980-10
lsdi2/tesseract/IPA/1980/IPA_1980-11
lsdi2/tesseract/IPA/1980/IPA_1980-12
lsdi2/tesseract/IPA/1981/IPA_1981-01
lsdi2/tesseract/IPA/1981/IPA_1981-02
lsdi2/tesseract/IPA/1981/IPA_1981-03
lsdi2/tesseract/IPA/1981/IPA_1981-04
lsdi2/tesseract/IPA/1981/IPA_1981-05
lsdi2/tesseract/IPA/1981/IPA_1981-06
lsdi2/tesseract/IPA/1981/IPA_1981-07
lsdi2/tesseract/IPA/1981/IPA_1981-08
lsdi2/tesseract/IPA/1981/IPA_1981-09
lsdi2/tesseract/IPA/1981/IPA_1981-10
lsdi2/tesseract/IPA/1981/IPA_1981-11
lsdi2/tesseract/IPA/1981/IPA_1981-12
lsdi2/tesseract/IPA/1982/IPA_1982-01
lsdi2/tesseract/IPA/1982/IPA_1982-02
lsdi2/tesseract/IPA/1982/IPA_1982-03
lsdi2/tesseract/IPA/1982/IPA_1982-04
lsdi2/tesseract/IPA/1982/IPA_1982-05
lsdi2/tesseract/IPA/1982/IPA_1982-06
lsdi2/tesseract/IPA/1982/IPA_1982-07
lsdi2/tesseract/IPA/1982/IPA_1982-08
lsdi2/tesseract/IPA/1982/IPA_1982-09
lsdi2/tesseract/IPA/1982/IPA_1982-10
lsdi2/tesseract/IPA/1982/IPA_1982-11
lsdi2/tesseract/IPA/1982/IPA_1982-12
lsdi2/tesseract/IPA/1983/IPA_1983-01
lsdi2/tesseract/IPA/1983/IPA_1983-02
lsdi2/tesseract/IPA/1983/IPA_1983-03
lsdi2/tesseract/IPA/1983/IPA_1983-04
lsdi2/tesseract/IPA/1983/IPA_1983-05
lsdi2/tesseract/IPA/1983/IPA_1983-06
lsdi2/tesseract/IPA/1983/IPA_1983-07
lsdi2/tesseract/IPA/1983/IPA_1983-08
lsdi2/tesseract/IPA/1983/IPA_1983-09
lsdi2/tesseract/IPA/1983/IPA_1983-10
lsdi2/tesseract/IPA/1983/IPA_1983-11
lsdi2/tesseract/IPA/1983/IPA_1983-12
lsdi2/tesseract/IPA/1984/IPA_1984-01
lsdi2/tesseract/IPA/1984/IPA_1984-02
lsdi2/tesseract/IPA/1984/IPA_1984-03
lsdi2/tesseract/IPA/1984/IPA_1984-04
lsdi2/tesseract/IPA/1984/IPA_1984-05
lsdi2/tesseract/IPA/1984/IPA_1984-06
lsdi2/tesseract/IPA/1984/IPA_1984-07
lsdi2/tesseract/IPA/1984/IPA_1984-08
lsdi2/tesseract/IPA/1984/IPA_1984-09
lsdi2/tesseract/IPA/1984/IPA_1984-10
lsdi2/tesseract/IPA/1984/IPA_1984-11
lsdi2/tesseract/IPA/1984/IPA_1984-12
lsdi2/tesseract/IPA/1985/IPA_1985-01
lsdi2/tesseract/IPA/1985/IPA_1985-02
lsdi2/tesseract/IPA/1985/IPA_1985-03
lsdi2/tesseract/IPA/1985/IPA_1985-04
lsdi2/tesseract/IPA/1985/IPA_1985-05
lsdi2/tesseract/IPA/1985/IPA_1985-06
lsdi2/tesseract/IPA/1985/IPA_1985-07
lsdi2/tesseract/IPA/1985/IPA_1985-08
lsdi2/tesseract/IPA/1985/IPA_1985-09
lsdi2/tesseract/IPA/1985/IPA_1985-10
lsdi2/tesseract/IPA/1985/IPA_1985-11
lsdi2/tesseract/IPA/1985/IPA_1985-12
lsdi2/tesseract/IPA/1986/IPA_1986-01
lsdi2/tesseract/IPA/1986/IPA_1986-02
lsdi2/tesseract/IPA/1986/IPA_1986-03
lsdi2/tesseract/IPA/1986/IPA_1986-04
lsdi2/tesseract/IPA/1986/IPA_1986-05
lsdi2/tesseract/IPA/1986/IPA_1986-06
lsdi2/tesseract/IPA/1986/IPA_1986-07
lsdi2/tesseract/IPA/1986/IPA_1986-08
lsdi2/tesseract/IPA/1986/IPA_1986-09
lsdi2/tesseract/IPA/1986/IPA_1986-10
lsdi2/tesseract/IPA/1986/IPA_1986-11
lsdi2/tesseract/IPA/1986/IPA_1986-12
lsdi2/tesseract/IPA/1987/IPA_1987-01
lsdi2/tesseract/IPA/1987/IPA_1987-02
lsdi2/tesseract/IPA/1987/IPA_1987-03
lsdi2/tesseract/IPA/1987/IPA_1987-04
lsdi2/tesseract/IPA/1987/IPA_1987-05
lsdi2/tesseract/IPA/1987/IPA_1987-06
lsdi2/tesseract/IPA/1987/IPA_1987-07
lsdi2/tesseract/IPA/1987/IPA_1987-08
lsdi2/tesseract/IPA/1987/IPA_1987-09
lsdi2/tesseract/IPA/1987/IPA_1987-10
lsdi2/tesseract/IPA/1987/IPA_1987-11
lsdi2/tesseract/IPA/1987/IPA_1987-12
lsdi2/tesseract/IPA/1988/IPA_1988-01
lsdi2/tesseract/IPA/1988/IPA_1988-02
lsdi2/tesseract/IPA/1988/IPA_1988-03
lsdi2/tesseract/IPA/1988/IPA_1988-04
lsdi2/tesseract/IPA/1988/IPA_1988-05
lsdi2/tesseract/IPA/1988/IPA_1988-06
lsdi2/tesseract/IPA/1988/IPA_1988-07
lsdi2/tesseract/IPA/1988/IPA_1988-08
lsdi2/tesseract/IPA/1988/IPA_1988-09
lsdi2/tesseract/IPA/1988/IPA_1988-10
lsdi2/tesseract/IPA/1988/IPA_1988-11
lsdi2/tesseract/IPA/1988/IPA_1988-12
lsdi2/tesseract/IPA/1989/IPA_1989-01
lsdi2/tesseract/IPA/1989/IPA_1989-02
lsdi2/tesseract/IPA/1989/IPA_1989-03
lsdi2/tesseract/IPA/1989/IPA_1989-04
lsdi2/tesseract/IPA/1989/IPA_1989-05
lsdi2/tesseract/IPA/1989/IPA_1989-06
lsdi2/tesseract/IPA/1989/IPA_1989-07
lsdi2/tesseract/IPA/1989/IPA_1989-08
lsdi2/tesseract/IPA/1989/IPA_1989-09
lsdi2/tesseract/IPA/1989/IPA_1989-10
lsdi2/tesseract/IPA/1989/IPA_1989-11
lsdi2/tesseract/IPA/1989/IPA_1989-12
lsdi2/tesseract/IPA/1990/IPA_1990-01
lsdi2/tesseract/IPA/1990/IPA_1990-02
lsdi2/tesseract/IPA/1990/IPA_1990-03
lsdi2/tesseract/IPA/1990/IPA_1990-04
lsdi2/tesseract/IPA/1990/IPA_1990-05
lsdi2/tesseract/IPA/1990/IPA_1990-06
lsdi2/tesseract/IPA/1990/IPA_1990-07
lsdi2/tesseract/IPA/1990/IPA_1990-08
lsdi2/tesseract/IPA/1990/IPA_1990-10
lsdi2/tesseract/IPA/1990/IPA_1990-11
lsdi2/tesseract/IPA/1990/IPA_1990-12
lsdi2/tesseract/IPA/1991/IPA_1991-01
lsdi2/tesseract/IPA/1991/IPA_1991-02
lsdi2/tesseract/IPA/1991/IPA_1991-03
lsdi2/tesseract/IPA/1991/IPA_1991-04
lsdi2/tesseract/IPA/1991/IPA_1991-05
lsdi2/tesseract/IPA/1991/IPA_1991-06
lsdi2/tesseract/IPA/1991/IPA_1991-07
lsdi2/tesseract/IPA/1991/IPA_1991-08
lsdi2/tesseract/IPA/1991/IPA_1991-09
lsdi2/tesseract/IPA/1991/IPA_1991-11
lsdi2/tesseract/IPA/1991/IPA_1991-12
lsdi2/tesseract/IPA/1992/IPA_1992-01
lsdi2/tesseract/IPA/1992/IPA_1992-02
lsdi2/tesseract/IPA/1992/IPA_1992-03
lsdi2/tesseract/IPA/1992/IPA_1992-04
lsdi2/tesseract/IPA/1992/IPA_1992-05
lsdi2/tesseract/IPA/1992/IPA_1992-07
lsdi2/tesseract/IPA/1992/IPA_1992-08
lsdi2/tesseract/IPA/1992/IPA_1992-09
lsdi2/tesseract/IPA/1992/IPA_1992-11
lsdi2/tesseract/IPA/1992/IPA_1992-12
lsdi2/tesseract/IPA/1994/IPA_1994-01
lsdi2/tesseract/IPA/1994/IPA_1994-02
lsdi2/tesseract/IPA/1994/IPA_1994-03
lsdi2/tesseract/IPA/1994/IPA_1994-04
lsdi2/tesseract/IPA/1994/IPA_1994-05
lsdi2/tesseract/IPA/1994/IPA_1994-06
lsdi2/tesseract/IPA/1994/IPA_1994-07
lsdi2/tesseract/IPA/1994/IPA_1994-08
lsdi2/tesseract/IPA/1994/IPA_1994-09
lsdi2/tesseract/IPA/1994/IPA_1994-10
lsdi2/tesseract/IPA/1994/IPA_1994-11
lsdi2/tesseract/IPA/1994/IPA_1994-12
lsdi2/tesseract/IPA/1995/IPA_1995-01
lsdi2/tesseract/IPA/1995/IPA_1995-02
lsdi2/tesseract/IPA/1995/IPA_1995-03
lsdi2/tesseract/IPA/1995/IPA_1995-04
lsdi2/tesseract/IPA/1995/IPA_1995-05
lsdi2/tesseract/IPA/1995/IPA_1995-06
lsdi2/tesseract/IPA/1995/IPA_1995-07
lsdi2/tesseract/IPA/1995/IPA_1995-08
lsdi2/tesseract/IPA/1995/IPA_1995-09
lsdi2/tesseract/IPA/1995/IPA_1995-10
lsdi2/tesseract/IPA/1995/IPA_1995-11
lsdi2/tesseract/IPA/1995/IPA_1995-12
lsdi2/tesseract/IPA/1996/IPA_1996-01
lsdi2/tesseract/IPA/1996/IPA_1996-02
lsdi2/tesseract/IPA/1996/IPA_1996-03
lsdi2/tesseract/IPA/1996/IPA_1996-04
lsdi2/tesseract/IPA/1996/IPA_1996-05
lsdi2/tesseract/IPA/1996/IPA_1996-06
lsdi2/tesseract/IPA/1996/IPA_1996-07
lsdi2/tesseract/IPA/1996/IPA_1996-08
lsdi2/tesseract/IPA/1996/IPA_1996-09
lsdi2/tesseract/IPA/1996/IPA_1996-10
lsdi2/tesseract/IPA/1996/IPA_1996-11
lsdi2/tesseract/IPA/1996/IPA_1996-12
lsdi2/tesseract/IPA/1997/IPA_1997-01
lsdi2/tesseract/IPA/1997/IPA_1997-02
lsdi2/tesseract/IPA/1997/IPA_1997-03
lsdi2/tesseract/IPA/1997/IPA_1997-04
lsdi2/tesseract/IPA/1997/IPA_1997-05
lsdi2/tesseract/IPA/1997/IPA_1997-06
lsdi2/tesseract/IPA/1997/IPA_1997-07
lsdi2/tesseract/IPA/1997/IPA_1997-08
lsdi2/tesseract/IPA/1997/IPA_1997-09
lsdi2/tesseract/IPA/1997/IPA_1997-10
lsdi2/tesseract/IPA/1997/IPA_1997-11
lsdi2/tesseract/IPA/1997/IPA_1997-12
lsdi2/tesseract/IPA/1998/IPA_1998-01
lsdi2/tesseract/IPA/1998/IPA_1998-02
lsdi2/tesseract/IPA/1998/IPA_1998-03
lsdi2/tesseract/IPA/1998/IPA_1998-04
lsdi2/tesseract/IPA/1998/IPA_1998-05
lsdi2/tesseract/IPA/1998/IPA_1998-06
lsdi2/tesseract/IPA/1998/IPA_1998-07
lsdi2/tesseract/IPA/1998/IPA_1998-08
lsdi2/tesseract/IPA/1998/IPA_1998-09
lsdi2/tesseract/IPA/1998/IPA_1998-10
lsdi2/tesseract/IPA/1998/IPA_1998-11
lsdi2/tesseract/IPA/1998/IPA_1998-12
lsdi2/tesseract/IPA/1999/IPA_1999-02
lsdi2/tesseract/IPA/1999/IPA_1999-03
lsdi2/tesseract/IPA/1999/IPA_1999-04
lsdi2/tesseract/IPA/1999/IPA_1999-05
lsdi2/tesseract/IPA/1999/IPA_1999-06
lsdi2/tesseract/IPA/1999/IPA_1999-07
lsdi2/tesseract/IPA/1999/IPA_1999-08
lsdi2/tesseract/IPA/1999/IPA_1999-09
lsdi2/tesseract/IPA/1999/IPA_1999-10
lsdi2/tesseract/IPA/1999/IPA_1999-11
lsdi2/tesseract/IPA/1999/IPA_1999-12

**Comment by jcrompton42** [comment]
transferred
