### ISSUE TITLE
Transfer straggler Theology catalog

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2153]
Please copy all files from the [Theology 2020-2021](https://emory-my.sharepoint.com/personal/kmicha3_emory_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Frmetz%5Femory%5Fedu%2FDocuments%2FAdmin%2FPersonal%20Meeting%20Notes%20and%20Agendas%2FLisa%2C%20Rosalyn%2FDLP%20Operationalizing%2FCatalogs%20from%20registrar%2FTHEO2013%2D2023%2FTHEO%202020%2D2021%20Catalog&listurl=%2Fpersonal%2Frmetz%5Femory%5Fedu%2FDocuments&remoteItem=%7B%22mp%22%3A%7B%22webAbsoluteUrl%22%3A%22https%3A%2F%2Femory%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fkmicha3%5Femory%5Fedu%22%2C%22listFullUrl%22%3A%22https%3A%2F%2Femory%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fkmicha3%5Femory%5Fedu%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Fkmicha3%5Femory%5Fedu%2FDocuments%2FDLP%20Operationalizing%22%7D%2C%22rsi%22%3A%7B%22listFullUrl%22%3A%22https%3A%2F%2Femory%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Frmetz%5Femory%5Fedu%2FDocuments%22%2C%22rootFolder%22%3A%22%2Fpersonal%2Frmetz%5Femory%5Fedu%2FDocuments%2FAdmin%2FPersonal%20Meeting%20Notes%20and%20Agendas%2FLisa%2C%20Rosalyn%2FDLP%20Operationalizing%2FCatalogs%20from%20registrar%2FTHEO2013%2D2023%2FTHEO%202020%2D2021%20Catalog%22%2C%22webAbsoluteUrl%22%3A%22https%3A%2F%2Femory%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Frmetz%5Femory%5Fedu%22%7D%7D&view=0) folder in OneDrive to the following location on EFS:

lsdi2/tesseract/BDCatalogs

**Comment by jcrompton42** [comment]
@kmichaelis please grant permissions to jcrompt@emory.edu so that I can download this?

**Comment by jcrompton42** [comment]
hmm, @kmichaelis I still don't seem to have access?

**Comment by kmichaelis** [comment]
@jcrompton42 try again?

**Comment by jcrompton42** [comment]
got it! Files are transferred and at /mnt/efs/Collections/lsdi2/tesseract/BDCatalogs/THEO_2021-2022

**Comment by kmichaelis** [comment]
@jcrompton42 can you please double check the transferred files? The missing volume is for 2020-2021 but it looks like the ones that got transferred were for 2021-2022.

**Comment by kmichaelis** [comment]
Thanks!
