### ISSUE TITLE
Transfer last two registrar catalogs

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2157]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/BDCatalogs/LAW_Catalog_2013-2016
lsdi2/tesseract/BDCatalogs/SOM_2016-2017

**Comment by jcrompton42** [comment]
transferred
