### ISSUE TITLE
Transfer batch of Inman Park Assn Records

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2158]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/IPA/2001/IPA_2001-01
lsdi2/tesseract/IPA/2001/IPA_2001-02
lsdi2/tesseract/IPA/2001/IPA_2001-03
lsdi2/tesseract/IPA/2001/IPA_2001-04
lsdi2/tesseract/IPA/2001/IPA_2001-05
lsdi2/tesseract/IPA/2001/IPA_2001-06
lsdi2/tesseract/IPA/2001/IPA_2001-07
lsdi2/tesseract/IPA/2001/IPA_2001-08
lsdi2/tesseract/IPA/2001/IPA_2001-09
lsdi2/tesseract/IPA/2001/IPA_2001-10
lsdi2/tesseract/IPA/2001/IPA_2001-11
lsdi2/tesseract/IPA/2001/IPA_2001-12
lsdi2/tesseract/IPA/2002/IPA_2002-01
lsdi2/tesseract/IPA/2002/IPA_2002-02
lsdi2/tesseract/IPA/2002/IPA_2002-03
lsdi2/tesseract/IPA/2002/IPA_2002-04
lsdi2/tesseract/IPA/2002/IPA_2002-05
lsdi2/tesseract/IPA/2002/IPA_2002-06
lsdi2/tesseract/IPA/2002/IPA_2002-07
lsdi2/tesseract/IPA/2002/IPA_2002-08
lsdi2/tesseract/IPA/2002/IPA_2002-09
lsdi2/tesseract/IPA/2002/IPA_2002-10
lsdi2/tesseract/IPA/2002/IPA_2002-11
lsdi2/tesseract/IPA/2002/IPA_2002-12

**Comment by jcrompton42** [comment]
transferred
