### ISSUE TITLE
Retransfer individual volumes on top level of EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2161]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ocm04851455-5902
lsdi2/ocm11268010-5911
lsdi2/ocm43320630-5808
lsdi2/ocm47850318-5845
lsdi2/ocm45047945-5907
lsdi2/ocm11556687-5770
lsdi2/ocn246420972-5976
lsdi2/ocn246420972-5971
lsdi2/ocn246420972-5977
lsdi2/ocm14857369-5868
lsdi2/ocm14510359-5880
lsdi2/ocm38841356-5821
lsdi2/ocm62523189-5956
lsdi2/ocm14847773-5848
lsdi2/ocm53357467-6000
lsdi2/ocm19991842-5823_LIMB
lsdi2/ocm22224931-5846
lsdi2/ocm01835504-5779
lsdi2/ocm10793686-5872
lsdi2/ocn246428979-5955
lsdi2/ocm09720595-5866
lsdi2/ocm14332780-5928
lsdi2/ocm01397307-5836
lsdi2/ocm01397307-5835
lsdi2/ocm05687852-5871
lsdi2/ocm05272240-5931
lsdi2/ocn191237963-5999
lsdi2/ocn228701664-5978
lsdi2/ocm29164142-5865
lsdi2/ocm05397553-5833
lsdi2/ocm05397553-5832
lsdi2/ocm01802583-5912
lsdi2/ocm56935783-5964
lsdi2/ocm14775197-5839
lsdi2/ocm03452328-5863
lsdi2/ocm03452328-5862
lsdi2/ocm03452328-5860
lsdi2/ocm03452328-5859
lsdi2/ocm03452328-5858
lsdi2/ocm08746526-5851
lsdi2/ocm12870408-5797
lsdi2/ocm19948347-5870
lsdi2/ocm17983907-5822
lsdi2/ocm13168026-5782
lsdi2/ocm11266759-5882
lsdi2/ocm00772592-5809
lsdi2/ocm17783591-5800
lsdi2/ocm00332063-5901
lsdi2/ocm00332063-5900
lsdi2/ocm08466375-5820
lsdi2/ocm04896348-5769
lsdi2/ocm63355548-5954
lsdi2/ocn219743021-5778
lsdi2/ocm09727538-5812
lsdi2/ocm09727538-5816
lsdi2/ocm02623570-5925
lsdi2/ocm11515810-5849
lsdi2/ocm14853444-5986
lsdi2/ocm14853444-5984
lsdi2/ocm46646151-5897
lsdi2/ocm34725085-5941
lsdi2/ocm34725085-5944
lsdi2/ocm34725085-5943
lsdi2/ocm29168014-5965
lsdi2/ocm02713411-5992
lsdi2/ocm14317145-5843
lsdi2/ocm13658605-5927
lsdi2/ocm29168014-5966
lsdi2/ocm09432766-5771
lsdi2/ocm04801644-5817
lsdi2/ocm08834313-5801
lsdi2/ocm14447536-5781
lsdi2/ocn246320351-5894
lsdi2/ocm01492776-5947
lsdi2/ocm03385643-5847
lsdi2/ocm18662183-5998
lsdi2/ocm29155559-5795
lsdi2/ocm14844348-5768
lsdi2/ocm14828160-5989
lsdi2/ocm22341461-5837
lsdi2/ocm16006308-5853
lsdi2/ocm06269324-5819
lsdi2/ocn181697129-5757
lsdi2/ocn181697129-5761
lsdi2/ocm06912269-5968
lsdi2/ocm06912269-5969
lsdi2/ocn230978969-5930
lsdi2/ocm02713411-5993
lsdi2/ocm14760948-5909
lsdi2/ocm04975012-5838
lsdi2/ocm02547092-5850
lsdi2/ocn246325378-5908
lsdi2/ocm02698627-5775
lsdi2/ocm11876301-5898
lsdi2/ocm46967816-5923
lsdi2/ocm08156419-5869
lsdi2/ocn182849391-5806
lsdi2/ocm42958941-5972
lsdi2/ocm03964358-5776
lsdi2/ocm39744321-5884
lsdi2/ocm32514357-5997
lsdi2/ocm11204995-5924
lsdi2/ocm06897391-5810
lsdi2/ocm39625883-5773
lsdi2/ocm05116704-5952
lsdi2/ocm07842057-5913
lsdi2/ocm07842057-5910
lsdi2/ocn191239593-5879
lsdi2/ocm05514904-5844
lsdi2/ocm08685105-5996
lsdi2/ocm08291955-5994
lsdi2/ocm03219193-5774
lsdi2/ocm29169030-5811
lsdi2/ocm05116704-5949
lsdi2/ocm05116704-5950
lsdi2/ocm05116704-5951
lsdi2/ocm08433758-5852
lsdi2/ocm09021242-5798
lsdi2/ocm09727242-5963
lsdi2/ocm28184376-5881
lsdi2/ocm04989856-5934
lsdi2/ocm04989856-5936
lsdi2/ocm14847373-5756
lsdi2/ocm35127344-5818
lsdi2/ocm03279597-5921
lsdi2/ocm07409023-5983
lsdi2/ocm27606361-5985
lsdi2/ocn191063024-5807
lsdi2/ocm07409023-5975
lsdi2/ocm12997336-5926
lsdi2/ocm07409023-5973
lsdi2/ocm04989856-5935

**Comment by jcrompton42** [comment]
retransferred
