### ISSUE TITLE
Retransfer 3 Southeast Asia Online Archive books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2162]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/300000433992
lsdi2/ftp/010001182833
lsdi2/ftp/300000434000

**Comment by jcrompton42** [comment]
retransferred
