### ISSUE TITLE
Retransfer volumes to EFS for Glacier transfer

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2164]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/emorybulletin/010001131455-v16-no8
lsdi2/ftp/emorybulletin/010001131455-v16-no2
lsdi2/tesseract/BDCatalogs/ECAS_2022-2023
lsdi2/tesseract/BDCatalogs/ECAS_2017-2018
lsdi2/tesseract/BDCatalogs/ECAS_2016-2017
lsdi2/tesseract/BDCatalogs/ECAS_2015-2016
lsdi2/tesseract/BDCatalogs/ECAS_2014-2015
lsdi2/tesseract/BDCatalogs/ECAS_2013-2014
lsdi2/tesseract/BDCatalogs/GBS_2018-2019
lsdi2/tesseract/BDCatalogs/GBS_2019-2020
lsdi2/tesseract/BDCatalogs/GBS_2020-2021
lsdi2/tesseract/BDCatalogs/GBS_2021-2022
lsdi2/tesseract/BDCatalogs/GBS_2022-2023
lsdi2/tesseract/BDCatalogs/LAW_catalog_2021-2022
lsdi2/tesseract/BDCatalogs/LAW_handbook_2016-2018
lsdi2/tesseract/BDCatalogs/LAW_handbook_2018-2019
lsdi2/tesseract/BDCatalogs/LAW_handbook_2019-2020
lsdi2/tesseract/BDCatalogs/LAW_handbook_2020-2021
lsdi2/tesseract/BDCatalogs/LAW_handbook_2021-2022
lsdi2/tesseract/BDCatalogs/LAW_handbook_2022-2023
lsdi2/tesseract/BDCatalogs/LGS_2018-2019
lsdi2/tesseract/BDCatalogs/LGS_2019-2020
lsdi2/tesseract/BDCatalogs/LGS_2020-2021
lsdi2/tesseract/BDCatalogs/LGS_2021-2022
lsdi2/tesseract/BDCatalogs/LGS_2022-2023
lsdi2/tesseract/BDCatalogs/NUR_2013-2014
lsdi2/tesseract/BDCatalogs/NUR_2014-2015
lsdi2/tesseract/BDCatalogs/NUR_2015-2016
lsdi2/tesseract/BDCatalogs/NUR_2016-2017
lsdi2/tesseract/BDCatalogs/NUR_2017-2018
lsdi2/tesseract/BDCatalogs/NUR_2018-2019
lsdi2/tesseract/BDCatalogs/NUR_2019-2020
lsdi2/tesseract/BDCatalogs/NUR_2020-2021
lsdi2/tesseract/BDCatalogs/NUR_2021-2022
lsdi2/tesseract/BDCatalogs/NUR_2022-2023
lsdi2/tesseract/BDCatalogs/SOM_2014-2015
lsdi2/tesseract/BDCatalogs/SOM_2015-2016
lsdi2/tesseract/BDCatalogs/SOM_2017-2018
lsdi2/tesseract/BDCatalogs/SOM_2018-2019
lsdi2/tesseract/BDCatalogs/SOM_2019-2020
lsdi2/tesseract/BDCatalogs/SOM_2020-2021
lsdi2/tesseract/BDCatalogs/SOM_2021-2022
lsdi2/tesseract/BDCatalogs/SOM_2022-2023
lsdi2/tesseract/BDCatalogs/GBS_2014-2015
lsdi2/tesseract/BDCatalogs/GBS_2015-2016
lsdi2/tesseract/BDCatalogs/GBS_2016-2017
lsdi2/tesseract/BDCatalogs/GBS_2017-2018
lsdi2/tesseract/BDCatalogs/LGS_2017-2018
lsdi2/tesseract/BDCatalogs/SOM_2016-2017
lsdi2/tesseract/BDCatalogs/THEO_2020-2021
lsdi2/ftp/010001355776
lsdi2/ftp/010001338920
lsdi2/ftp/010003050994
lsdi2/ftp/010002588343
lsdi2/tesseract/ViewsOfRome/010002586000
lsdi2/ftp/010001334059
lsdi2/ftp/010002632180
lsdi2/ftp/010001275193
lsdi2/ftp/000020265295
lsdi2/ftp/010003050501
lsdi2/ftp/010002408932
lsdi2/ftp/010003065351
lsdi2/ftp/010002990692
lsdi2/ftp/010002718615
lsdi2/ftp/010003065188
lsdi2/ftp/010000211961
lsdi2/ftp/010001224383
lsdi2/ftp/010002426412

**Comment by jcrompton42** [comment]
retransferred
