### ISSUE TITLE
Retransfer Yellowbacks to EFS for ingest (batch 1)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2166]
Please retransfer the following from Isilon to /mnt/efs/Collections

lsdi/diesel/lts_new/ocm03392924-2177
lsdi/diesel/lts_new/ocm04282590-1601
lsdi/diesel/lts_new/ocm04301011-1637
lsdi/diesel/lts_new/ocm04311972-1695
lsdi/diesel/lts_new/ocm04321409-1922
lsdi/diesel/lts_new/ocm04416518-1357
lsdi/diesel/lts_new/ocm06342616-2071
lsdi/diesel/lts_new/ocm06747693-2551
lsdi/diesel/lts_new/ocm06793239-2139
lsdi/diesel/lts_new/ocm06821814-1791
lsdi/diesel/lts_new/ocm10755829-1810
lsdi/diesel/lts_new/ocm10757356-1830
lsdi/diesel/lts_new/ocm10892439-2235
lsdi/diesel/lts_new/ocm11657162-2852
lsdi/diesel/lts_new/ocm11864160-3062
lsdi/diesel/lts_new/ocm11864350-2175
lsdi/diesel/lts_new/ocm12091609-2218
lsdi/diesel/lts_new/ocm13407907-2700
lsdi/diesel/lts_new/ocm13537958-2743
lsdi/diesel/lts_new/ocm15041641-3014
lsdi/diesel/lts_new/ocm15057375-2544
lsdi/diesel/lts_new/ocm15372050-2310
lsdi/diesel/lts_new/ocm15580642-2870
lsdi/diesel/lts_new/ocm15585830-2856
lsdi/diesel/lts_new/ocm15645454-2024
lsdi/diesel/lts_new/ocm20062530-2037
lsdi/diesel/lts_new/ocm22592649-1853
lsdi/diesel/lts_new/ocm22597061-2801
lsdi/diesel/lts_new/ocm22603345-2168
lsdi/diesel/lts_new/ocm22609151-2237
lsdi/diesel/lts_new/ocm22613177-2428
lsdi/diesel/lts_new/ocm22617303-2595
lsdi/diesel/lts_new/ocm22622934-2383
lsdi/diesel/lts_new/ocm22623020-2647
lsdi/diesel/lts_new/ocm24166988-1875
lsdi/diesel/lts_new/ocm24181021-2246
lsdi/diesel/lts_new/ocm27818130-1950
lsdi/diesel/lts_new/ocm36072533-2501
lsdi/diesel/lts_new/ocm36072545-2406
lsdi/diesel/lts_new/ocm48991130-1503
lsdi/diesel/lts_new/ocn154282904-1918
lsdi/diesel/lts_new/ocn164865607-2503
lsdi/diesel/lts_new/ocn166408601-2479
lsdi/diesel/lts_new/ocn223259332-2919
lsdi/diesel/lts_new/ocn268677048-1425
lsdi/diesel/lts_new/ocn276877886-2575
lsdi/diesel/lts_new/ocn361572296-2270
lsdi2/ocm03610053-2106
lsdi2/ocm04449922-2982
lsdi2/ocm04449998-2990

**Comment by jcrompton42** [comment]
retransferred
