### ISSUE TITLE
Retransfer African American Imprints to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2167]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/africanamerican/010002588072
lsdi2/ftp/010000426223
lsdi2/ftp/010001216005
lsdi2/ftp/africanamerican/010002588310
lsdi2/ftp/10002350199
lsdi2/ftp/10002354563
lsdi2/ftp/010001023135
lsdi2/ftp/010001216053
lsdi2/ftp/010002406705
lsdi2/ftp/010002588624
lsdi2/ftp/010002634169
lsdi2/ftp/010001295646
lsdi2/ftp/africanamerican/010002631887
lsdi2/ftp/010000894826
lsdi2/ftp/010000158237
lsdi2/ftp/010000154057
lsdi2/ftp/010000426788
lsdi2/ftp/010002405684
lsdi2/ftp/010001225938
lsdi2/ftp/010002483592
lsdi2/ftp/010001224202
lsdi2/ftp/africanamerican/010002588661
lsdi2/ftp/010001217018
lsdi2/ftp/africanamerican/010002643597
lsdi2/ftp/africanamerican/010002643593
lsdi2/ftp/africanamerican/010002643598
lsdi2/ftp/africanamerican/010002482204
lsdi2/ftp/10002335905
lsdi2/ftp/10002361042
lsdi2/ftp/010002405952
lsdi2/ftp/10002354672
lsdi2/ftp/010000667892
lsdi2/ftp/africanamerican/010002588806
lsdi2/ftp/010002426554
lsdi2/ftp/010002483110
lsdi2/ftp/010000709381
lsdi2/ftp/010002405756
lsdi2/ftp/010002405748
lsdi2/ftp/010002588564
lsdi2/ftp/010002588527
lsdi2/ftp/010002588526
lsdi2/ftp/10002354380
lsdi2/ftp/010001278365
lsdi2/ftp/africanamerican/010002588547
lsdi2/ftp/010000878678
lsdi2/ftp/africanamerican/010002585983
lsdi2/ftp/010002588525
lsdi2/ftp/010000158003
lsdi2/ftp/africanamerican/010002588862
lsdi2/ftp/010002643738
lsdi2/ftp/010002643737
lsdi2/ftp/010000878954
lsdi2/ftp/010002588606
lsdi2/ftp/000011339549
lsdi2/ftp/010002428913
lsdi2/ftp/010001225946
lsdi2/ftp/010001353377
lsdi2/ftp/010002643710
lsdi2/ftp/010001275068
lsdi2/ftp/010000709092
lsdi2/ftp/010001059810
lsdi2/ftp/010002406363
lsdi2/ftp/010000426913
lsdi2/ftp/010000663565
lsdi2/ftp/010001349257
lsdi2/ftp/010002643921
lsdi2/ftp/10002350200
lsdi2/ftp/010001295647
lsdi2/ftp/africanamerican/000011606677
lsdi2/ftp/010002632461
lsdi2/ftp/010000878643
lsdi2/ftp/000011050380
lsdi2/ftp/010002630923
lsdi2/ftp/000011115833
lsdi2/ftp/010000878159
lsdi2/ftp/010002408871
lsdi2/ftp/africanamerican/010002643732
lsdi2/ftp/010001102087
lsdi2/ftp/010001036369
lsdi2/ftp/010000344118
lsdi2/ftp/010001059820
lsdi2/ftp/010001217210
lsdi2/ftp/010000426979
lsdi2/ftp/010002482200
lsdi2/ftp/010000158312
lsdi2/ftp/010002588740
lsdi2/ftp/010001217322
lsdi2/ftp/010001216911
lsdi2/ftp/010000663873
lsdi2/ftp/africanamerican/010002588887
lsdi2/ftp/010002588837
lsdi2/ftp/010001128257
lsdi2/ftp/010001349255
lsdi2/ftp/010002588741
lsdi2/ftp/010000663181
lsdi2/ftp/010002632269
lsdi2/ftp/010000663182
lsdi2/ftp/000011703407
lsdi2/ftp/010002588682
lsdi2/ftp/africanamerican/010002588561
lsdi2/ftp/africanamerican/010002588962
lsdi2/ftp/africanamerican/010002588524
lsdi2/ftp/010001355833
lsdi2/ftp/010001059595
lsdi2/ftp/010002483595
lsdi2/ftp/africanamerican/010002588603
lsdi2/ftp/010002406443
lsdi2/ftp/010001349284
lsdi2/ftp/010002587117
lsdi2/ftp/010001275454
lsdi2/ftp/010000709618
lsdi2/ftp/10002331722
lsdi2/ftp/010002585954
lsdi2/ftp/010001275055
lsdi2/ftp/africanamerican/010002631888
lsdi2/ftp/010001353748
lsdi2/ftp/africanamerican/010002588805
lsdi2/ftp/010002702160
lsdi2/ftp/010001171687
lsdi2/ftp/010002588720
lsdi2/ftp/010001059149
lsdi2/ftp/010001023521
lsdi2/ftp/010000125198
lsdi2/ftp/010001023439
lsdi2/ftp/africanamerican/010002632495
lsdi2/ftp/010002408942
lsdi2/ftp/africanamerican/010002588753
lsdi2/ftp/010000878575
lsdi2/ftp/010001353574
lsdi2/ftp/10002350164
lsdi2/ftp/africanamerican/010002643953
lsdi2/ftp/010002588729
lsdi2/ftp/africanamerican/010002588939
lsdi2/ftp/010000709255
lsdi2/ftp/010000344268
lsdi2/ftp/010001036331
lsdi2/ftp/010001349531
lsdi2/ftp/010001355465
lsdi2/ftp/010002406445
lsdi2/ftp/010001216064
lsdi2/ftp/010000351741
lsdi2/ftp/010001355449
lsdi2/ftp/010001355146
lsdi2/ftp/010000709155
lsdi2/ftp/010001036430
lsdi2/ftp/010000427966
lsdi2/ftp/010000878213
lsdi2/ftp/010001059575
lsdi2/ftp/africanamerican/010002588182
lsdi2/ftp/africanamerican/010002632462
lsdi2/ftp/010002485562
lsdi2/ftp/010002408442
lsdi2/ftp/africanamerican/010002588836
lsdi2/ftp/010000158356
lsdi2/ftp/010000427895
lsdi2/ftp/10002350120
lsdi2/ftp/010002408528
lsdi2/ftp/africanamerican/010002588893
lsdi2/ftp/010000709366
lsdi2/ftp/010000427453
lsdi2/ftp/010001355834
lsdi2/ftp/010000354402
lsdi2/ftp/010001355835
lsdi2/ftp/010002630190
lsdi2/ftp/010000344163
lsdi2/ftp/10002361941
lsdi2/ftp/010002701006
lsdi2/ftp/010000154037
lsdi2/ftp/10002331965
lsdi2/ftp/10002331699
lsdi2/ftp/010002483597
lsdi2/ftp/africanamerican/010002588546
lsdi2/ftp/010000354151
lsdi2/ftp/010002632272
lsdi2/ftp/africanamerican/010002588728
lsdi2/ftp/010000158558
lsdi2/ftp/africanamerican/010002588866
lsdi2/ftp/010002718161
lsdi2/ftp/010001345311
lsdi2/ftp/10002335928
lsdi2/ftp/africanamerican/010002588940
lsdi2/ftp/010001224829
lsdi2/ftp/africanamerican/010002585956
lsdi2/ftp/africanamerican/010002588604
lsdi2/ftp/010002643782
lsdi2/ftp/010000426915
lsdi2/ftp/010000427059
lsdi2/ftp/10002335332
lsdi2/ftp/010001022860
lsdi2/ftp/000011960684
lsdi2/ftp/10002350622
lsdi2/ftp/010000878697
lsdi2/ftp/010002588024
lsdi2/ftp/africanamerican/010002588726
lsdi2/ftp/010002585987
lsdi2/ftp/000011224691
lsdi2/ftp/010000330411
lsdi2/ftp/010000709159
lsdi2/ftp/010001355147
lsdi2/ftp/010000427090
lsdi2/ftp/010002718468
lsdi2/ftp/010002585614
lsdi2/ftp/000011015865
lsdi2/ftp/010001154054
lsdi2/ftp/010001059200
lsdi2/ftp/010000427456
lsdi2/ftp/010002588605
lsdi2/ftp/010001059828
lsdi2/ftp/010001349207
lsdi2/ftp/10002350644
lsdi2/ftp/010002630874
lsdi2/ftp/010001355136
lsdi2/ftp/010002643865
lsdi2/ftp/10002331914
lsdi2/ftp/010002643870
lsdi2/ftp/010002643869
lsdi2/ftp/010002643868
lsdi2/ftp/010002643712
lsdi2/ftp/010002643778
lsdi2/ftp/010000154039
lsdi2/ftp/010001295568
lsdi2/ftp/africanamerican/010002482203
lsdi2/ftp/africanamerican/010002643596
lsdi2/ftp/010002631939
lsdi2/ftp/africanamerican/010002631889
lsdi2/ftp/africanamerican/010002643813
lsdi2/ftp/010001132965
lsdi2/ftp/010001349228
lsdi2/ftp/010001355021
lsdi2/ftp/africanamerican/010002643777
lsdi2/ftp/010000427443
lsdi2/ftp/010002588885
lsdi2/ftp/010000709506
lsdi2/ftp/africanamerican/010002588025
lsdi2/ftp/10002335907
lsdi2/ftp/000011776117
lsdi2/ftp/010002631940
lsdi2/ftp/10002331269
lsdi2/ftp/africanamerican/010001355555
lsdi2/ftp/africanamerican/010000878070
lsdi2/ftp/africanamerican/010002585933
lsdi2/ftp/africanamerican/010000709875
lsdi2/ftp/africanamerican/010001355564
lsdi2/ftp/africanamerican/010002426597
lsdi2/ftp/africanamerican/010000426340
lsdi2/ftp/africanamerican/010002483582
lsdi2/ftp/africanamerican/010002426349
lsdi2/ftp/africanamerican/010002426670
lsdi2/ftp/africanamerican/010000878092
lsdi2/ftp/africanamerican/010002426647
lsdi2/ftp/africanamerican/010000158226
lsdi2/ftp/africanamerican/010001355302
lsdi2/ftp/africanamerican/010002426698
lsdi2/ftp/africanamerican/010002426834
lsdi2/ftp/africanamerican/010000158200
lsdi2/ftp/africanamerican/010002426551
lsdi2/ftp/africanamerican/010002428567
lsdi2/ftp/africanamerican/010002426672
lsdi2/ftp/africanamerican/010000878739
lsdi2/ftp/africanamerican/010002483583
lsdi2/ftp/africanamerican/010002426570
lsdi2/ftp/africanamerican/010002585872
lsdi2/ftp/africanamerican/010002406369
lsdi2/ftp/africanamerican/010000878148
lsdi2/ftp/africanamerican/010000212007
lsdi2/ftp/africanamerican/010002426553
lsdi2/ftp/africanamerican/010002428511
lsdi2/ftp/africanamerican/010000426590
lsdi2/ftp/africanamerican/010002426650
lsdi2/ftp/africanamerican/010002426833
lsdi2/ftp/africanamerican/010002426734
lsdi2/ftp/africanamerican/010001059052
lsdi2/ftp/africanamerican/010002483596
lsdi2/ftp/africanamerican/010002426572
lsdi2/ftp/africanamerican/010002483594
lsdi2/ftp/africanamerican/010001059624
lsdi2/ftp/africanamerican/010001214303
lsdi2/ftp/africanamerican/010002426573

**Comment by jcrompton42** [comment]
retransferred
