### ISSUE TITLE
Re-transfer Views of Rome volumes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2175]
Please retransfer these Views of Rome volumes from /opt/lsdi2 to their previous location on EFS:

lsdi2/ftp/010000215606
lsdi2/ftp/010001102857
lsdi2/ftp/000011287308
lsdi2/ftp/010000154212
lsdi2/ftp/010001275677
lsdi2/ftp/010001278310
lsdi2/ftp/010001278661
lsdi2/ftp/010001059216
lsdi2/ftp/010001171586
lsdi2/ftp/010002990710
lsdi2/ftp/010003065187
lsdi2/ftp/010003065175
lsdi2/ftp/010003065174
lsdi2/ftp/010001349625
lsdi2/ftp/010002630940
lsdi2/ftp/010002426413
lsdi2/ftp/010002405873
lsdi2/ftp/010002405872
lsdi2/ftp/010002405871
lsdi2/ftp/010002408934
lsdi2/ftp/010002408933
lsdi2/ftp/010000125183
lsdi2/ftp/010000426397
lsdi2/ftp/010000351768
lsdi2/ftp/010002426372
lsdi2/ftp/010002426372

**Comment by jcrompton42** [comment]
retransferred
