### ISSUE TITLE
Retransfer set of Yellowbacks for Glacier (cont'd)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2177]
I found another set of paths that are ingested, but need to be retransferred from Isilon to EFS so we can move the files to Glacier:

lsdi/diesel/lts_new/ocm06583544-2004/ocm06583544/Output/*
lsdi/diesel/lts_new/ocm06583598-2398/ocm06583598/Output/*
lsdi/diesel/lts_new/ocm06647235-2760/Output/*
lsdi/diesel/lts_new/ocm06647257-2278/ocm06647257/Output/*
lsdi/diesel/lts_new/ocm06647379-2554/ocm06647379/Output/*
lsdi/diesel/lts_new/ocm06647395-2038/ocm06647395/Output/*
lsdi/diesel/lts_new/ocm06652035-2497/ocm06652035/Output/*
lsdi/diesel/lts_new/ocm06652070-2426/ocm06652070/Output/*
lsdi/diesel/lts_new/ocm06652133-2718/Output/*

**Comment by eporter23** [comment]
@jcrompton42 not urgent, but when you have a little time can you please retransfer these to EFS?

**Comment by jcrompton42** [comment]
retransferred
