### ISSUE TITLE
EFS retransfer for Glacier: yellow backs from CSV batch 20

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2180]
The following Yellowbacks have been ingested but need re-transfer from Isilon to EFS:

lsdi/diesel/lts_new/ocm06655617-2051/ocm06655617/
lsdi/diesel/lts_new/ocm06655557-2039/ocm06655557/
lsdi/diesel/lts_new/ocm06671188-2670/
lsdi/diesel/lts_new/ocm06671163-2674/
lsdi/diesel/lts_new/ocm06671191-2676/
lsdi/diesel/lts_new/ocm06671173-2677/
lsdi/diesel/lts_new/ocm06671194-2678/
lsdi/diesel/lts_new/ocm06671132-2683/
lsdi/diesel/lts_new/ocm06671127-2684/
lsdi/diesel/lts_new/ocm06652158-2953/

NOTE: apologies in advance, but a prior ticket in which I requested a lot of Yellowbacks to be re-transferred had incorrect paths. I am working on cleaning this up gradually.

**Comment by jcrompton42** [comment]
retransferred
