### ISSUE TITLE
Transfer another batch of Wesley books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2182]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Wesley/0020076838
lsdi2/tesseract/Wesley/300000089789
lsdi2/tesseract/Wesley/300000089790
lsdi2/tesseract/Wesley/300000089791
lsdi2/tesseract/Wesley/300000089792
lsdi2/tesseract/Wesley/300000089793
lsdi2/tesseract/Wesley/300000089795
lsdi2/tesseract/Wesley/300000089796
lsdi2/tesseract/Wesley/300000089797
lsdi2/tesseract/Wesley/300000089798
lsdi2/tesseract/Wesley/300000089799
lsdi2/tesseract/Wesley/300000089800
lsdi2/tesseract/Wesley/300000089801
lsdi2/tesseract/Wesley/300000089818
lsdi2/tesseract/Wesley/300000089819
lsdi2/tesseract/Wesley/300000089825
lsdi2/tesseract/Wesley/300000089899
lsdi2/tesseract/Wesley/300000089994
lsdi2/tesseract/Wesley/300000111799
lsdi2/tesseract/Wesley/300000123144

**Comment by jcrompton42** [comment]
transferred
