### ISSUE TITLE
Transfer another Views of Rome batch

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2184]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/ViewsOfRome/010000344160
lsdi2/tesseract/ViewsOfRome/010000344532
lsdi2/tesseract/ViewsOfRome/010000427057
lsdi2/tesseract/ViewsOfRome/010001216057
lsdi2/ocm04801157-5608/ocm04801157
lsdi2/ocm04801157-5610/ocm04801157
lsdi2/tesseract/ViewsOfRome/010001355945
lsdi2/tesseract/ViewsOfRome/10002354817
lsdi2/ftp/010002408932
lsdi2/tesseract/ViewsOfRome/010002585979
lsdi2/tesseract/ViewsOfRome/010002713657
lsdi2/tesseract/ViewsOfRome/010002713658
lsdi2/tesseract/ViewsOfRome/010002961556

**Comment by jcrompton42** [comment]
transferred
