### ISSUE TITLE
Transfer Emory Alumnus/Emory Magazine files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2187]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/EmoryMagazine/000011712335/192703
lsdi2/tesseract/EmoryMagazine/000011712335/192705
lsdi2/tesseract/EmoryMagazine/000011712335/192707
lsdi2/tesseract/EmoryMagazine/000011712335/192709
lsdi2/tesseract/EmoryMagazine/000011712335/192711
lsdi2/tesseract/EmoryMagazine/000011712335/192801
lsdi2/tesseract/EmoryMagazine/000011712335/192803
lsdi2/tesseract/EmoryMagazine/000011712335/192805
lsdi2/tesseract/EmoryMagazine/000011712335/192807
lsdi2/tesseract/EmoryMagazine/000011712335/192809
lsdi2/tesseract/EmoryMagazine/000011712335/192811
lsdi2/tesseract/EmoryMagazine/000011712358/196501
lsdi2/tesseract/EmoryMagazine/000011712358/196503
lsdi2/tesseract/EmoryMagazine/000011712358/196505
lsdi2/tesseract/EmoryMagazine/000011712358/196507
lsdi2/tesseract/EmoryMagazine/000011712358/196509
lsdi2/tesseract/EmoryMagazine/000011712358/196511

**Comment by jcrompton42** [comment]
transferred
