### ISSUE TITLE
Implement Button on Works' Show Page to Start Full-Text Indexing

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-curate#2190]

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/2189

**Comment by bwatson78** [comment]
![Screenshot 2023-08-10 at 10.47.00 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/4e68f90e-3744-410e-b6aa-49a52732b04e)

**Comment by eporter23** [comment]
Looks great! I tested on 2 Kirtas and 2 LIMB outputs. 

https://curate-test.library.emory.edu/concern/curate_generic_works/706g1jwt5c-cor?locale=en
https://curate-test.library.emory.edu/concern/curate_generic_works/235gb5mkxg-cor?locale=en
https://curate-test.library.emory.edu/concern/curate_generic_works/453wstqk05-cor?locale=en 
https://curate-test.library.emory.edu/concern/curate_generic_works/4881jwsv0k-cor?locale=en
