### ISSUE TITLE
Bring Full-Text Search Result to Lux

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-curate#2191]
Replicate [Full-Text Search Highlight behavior](https://github.com/emory-libraries/dlp-curate/pull/2076) in Lux environments. Revise the existing search results label "Keyword matches" to "Full-text matches".

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/753

**Comment by eporter23** [comment]
@bwatson78 apologies for not specifying this before, but I'd like to adjust the color of the keyword match highlighting to use one of approved pattern library colors. Can you please adjust it to  `#E0F6DA`?

**Comment by eporter23** [comment]
Also, it would be good if a work is not indexed for full text and/or does not have any full text matches, that new field will not display in search results. I think that is the behavior I'm seeing in test, but wanted to confirm.

**Comment by bwatson78** [comment]
That is the behavior seen here in my local, as well.
![Screenshot 2023-08-17 at 7.39.41 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/6659ee10-21fa-417e-bf59-36de18576b47)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-lux/pull/754

**Comment by eporter23** [comment]
Looks great @bwatson78. Should be good for production if we can schedule that with Kathryn.
