### ISSUE TITLE
Transfer Emory Wheel files to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2195]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/docworks/emorywheel

**Comment by jcrompton42** [comment]
transferred. This was several terabytes! That's why it took so long to get this done.
