### ISSUE TITLE
Transfer more Wesley books

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2197]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Wesley/000015292540
lsdi2/tesseract/Wesley/000015292541
lsdi2/tesseract/Wesley/000015292542
lsdi2/tesseract/Wesley/000015292543
lsdi2/tesseract/Wesley/000015292544
lsdi2/tesseract/Wesley/000015292545
lsdi2/tesseract/Wesley/000015292546
lsdi2/tesseract/Wesley/000015292547
lsdi2/tesseract/Wesley/000015292548
lsdi2/tesseract/Wesley/000015292549
lsdi2/tesseract/Wesley/000015292891
lsdi2/tesseract/Wesley/000020106301
lsdi2/tesseract/Wesley/000020106303
lsdi2/tesseract/Wesley/300000001052
lsdi2/tesseract/Wesley/300000001053
lsdi2/tesseract/Wesley/300000001062

**Comment by jcrompton42** [comment]
transferred
