### ISSUE TITLE
Transfer AHAM boxes 70, 80, 82, 97

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2199]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja070
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja080
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja082
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja097

**Comment by jcrompton42** [comment]
transferred
