### ISSUE TITLE
Support different types of derivatives and access copies on multi-part objects

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#22]
## Story
As a Preservation Curator, I want to separate different types of derivatives and master files, so that archival masters, production masters, and access copies can all be stored as part of the same object but their purpose and usage can be easily determined

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Specifics vary relative to initial migration. Digitized images will have _ARCH and _PROD versions, one with color bar and one without. They may also have a Service File (lower resolution JPG). 

Digitized books will have TIFF files for pages, OCR for pages, character positioning data files for pages, and may also have a PDF file for the entire book or volume's pages. They may also have an OCR file for the entire volume.

Content filesets MUST include one and only one:
* Preservation Master File

FileSets MAY include one and only one of each of the following:
* Intermediate File (high resolution access copy)
* Service File (lower resolution/watermarked access copy)
* Thumbnail (as generated by Hyrax's ingest process)
* Extracted Text File (Plain text output or OCR data)
* Transcript File (plain text such as a transcript)

#### Links to Additional Information
[DLP CV Usage document](https://docs.google.com/document/d/1kVkpjVMK5-tmQGuH0hJuXTafI5Ba3B3RarkGCiOeEtY/edit#heading=h.ecswdm3gb10u)
[Emory AIP and FileSet outline](https://docs.google.com/spreadsheets/d/1tEZeuUm-l0RJ3KNP55feZnbTFykBrxekxFWdrn2f8Xc/edit#gid=403514438)
[PCDM Use Spec](https://pcdm.org/2015/05/12/use)
[Emory File Use to File Set Relationships](https://docs.google.com/document/d/1TMSOK0o-0ymRTjaa4ZJdf2rlqnA6CkU8UDvJYqSHVzk/edit)
[Emory AIP specification](https://wiki.service.emory.edu/display/DLPP/Archival+Information+Package+Recommendations)
[Emory AIP components diagram](https://docs.google.com/presentation/d/1FFlFKy6r-IN5K6AyRFLOraAyHFkTlJggnpymn7QaYZ8/edit#slide=id.p)

#### Checklist
- [ ] Item 1
- [ ] Item 2

#### Given/When/Then
* Given I am a Library Staff user ingesting compound objects with multiple types of derivatives or distinct access copies
* When I create or edit a complex object in the repository
* Then using the Hyrax interface/File Manager, I can navigate through an object's various file components and understand how a given file relates to the whole object package

**Comment by rotated8** [comment]
Should this be an epic?

**Comment by eporter23** [comment]
@rotated8 this should be an epic, but I'm guessing I didn't select that template when I created it and I can't seem to add it now (unless I recreate it).

**Comment by eporter23** [comment]
I was able to add the Epic label through the GitHub UI.

**Comment by eporter23** [comment]
Discussed at 3/18 sprint planning: I updated the acceptance criteria to add Service File as another possible file use need depending on Migration team work.

**Comment by eporter23** [comment]
Moving this to 0.3 because the fileSet relationships aren't yet assigned in 0.2 work.

**Comment by eporter23** [comment]
@rotated8 @alexBLR @devanshu-m after we talked about File Use today, I updated the acceptance criteria above to note the 1:1 relationship of a use to its parent File Set. I also looked back at the SIP mapping worksheet and removed the extra custom entry (Word Positioning Data). I  no longer think we will need that and we can just use standard PCDM use terms.

**Comment by eporter23** [comment]
Closing this as it overlaps with #127 and #119
