### ISSUE TITLE
Re-transfer several folders to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2201]
Please re-transfer these files to EFS from /opt. The files on /opt have been renamed and the ones on EFS need to be replaced with the ones that have the current, corrected filenames.

lsdi2/tesseract/IPA/2002
lsdi2/tesseract/IPA/2003
lsdi2/tesseract/IPA/2004
lsdi2/tesseract/IPA/2005

**Comment by jcrompton42** [comment]
transferred
