### ISSUE TITLE
Transfer more Inman Park files plz

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2203]
Please copy all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/IPA/1993
lsdi2/tesseract/IPA/2000

**Comment by jcrompton42** [comment]
transferred
