### ISSUE TITLE
Transfer Emblem Books files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2207]
Please copy all the following files in the following directories from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/emblembooks/010000790565
lsdi2/tesseract/emblembooks/010001218314
lsdi2/tesseract/emblembooks/010001275492
lsdi2/tesseract/emblembooks/010003196403
lsdi2/tesseract/emblembooks/300000143440
lsdi2/tesseract/emblembooks/300000158822
lsdi2/tesseract/emblembooks/300000197734
lsdi2/tesseract/emblembooks/300000250643
lsdi2/tesseract/emblembooks/300000281275
lsdi2/tesseract/emblembooks/300000281661
lsdi2/tesseract/emblembooks/300000281799
lsdi2/tesseract/emblembooks/300000363076
lsdi2/tesseract/emblembooks/300000458056
lsdi2/tesseract/emblembooks/300000458291

**Comment by jcrompton42** [comment]
@kmichaelis /opt/lsdi2/tesseract/emblembooks/010003196403 doesn't exist, the others are transferred. Thoughts?

**Comment by kmichaelis** [comment]
@jcrompton42 , the correct path should be /opt/lsdi2/tesseract/ViewsOfRome/010003196403. Please transfer files to the emblembooks directory. Thank you!

**Comment by jcrompton42** [comment]
found and transferred
