### ISSUE TITLE
Adjust ansible roles to preserve host keys between rebuilds

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#221]
Currently the host keys are lost whenever an ec2 is destroyed and rebuilt. We can set HostKeyChecking to False to get around this but that is not a good long term security practice. Developers have had problems connecting and deploying due to their SSH clients thinking the changed host key is due to a Man in the Middle attack.

- [ ] Modify the Ansible roles or create a new one to modify the host key with a value held in Ansible Vault
- [ ] Capture a host key for all websites in cor-cm
- [ ] Rebuild all hosts and test to make sure MITM message not longer comes up after a rebuild

**Comment by eporter23** [comment]
Discussed with team 7/29/20: this approach is no longer applicable.
