### ISSUE TITLE
Transfer handful of Spokesman issues 

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2212]
Please copy all the following files in the following directories from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Oxford_Spokesman/Spokesman_19671100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19671200
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19690131
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19721100
lsdi2/tesseract/Oxford_Spokesman/Spokesman_19791116

**Comment by jcrompton42** [comment]
transferred
