### ISSUE TITLE
Transfer AHAM boxes 93-96, 99, 101, 102

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2216]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja093
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja094
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja095
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja096
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja099
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja101
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja102

**Comment by jcrompton42** [comment]
transferred
