### ISSUE TITLE
Transfer batch of Emory Magazine issues

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2217]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193301
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193303
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193305
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193307
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193309
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193311
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193401
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193403
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193405
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193407
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193409
lsdi2/tesseract/EmoryMagazine/000011712338/000011712338_193411

**Comment by kmichaelis** [comment]
Lack of caffeine strikes again! The paths are indeed:

lsdi2/tesseract/EmoryMagazine/000011712338_193301
lsdi2/tesseract/EmoryMagazine/000011712338_193303
lsdi2/tesseract/EmoryMagazine/000011712338_193305
lsdi2/tesseract/EmoryMagazine/000011712338_193307
lsdi2/tesseract/EmoryMagazine/000011712338_193309
lsdi2/tesseract/EmoryMagazine/000011712338_193311
lsdi2/tesseract/EmoryMagazine/000011712338_193401
lsdi2/tesseract/EmoryMagazine/000011712338_193403
lsdi2/tesseract/EmoryMagazine/000011712338_193405
lsdi2/tesseract/EmoryMagazine/000011712338_193407
lsdi2/tesseract/EmoryMagazine/000011712338_193409
lsdi2/tesseract/EmoryMagazine/000011712338_193411

**Comment by jcrompton42** [comment]
I thought that would be the paths, but didn't want to assume. 

transferred.
