### ISSUE TITLE
Transfer batch of Campus Report issues

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2218]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/CampusReport/000011686012/1948-1949_Index
lsdi2/tesseract/CampusReport/000011686013/1949-1950_Index
lsdi2/tesseract/CampusReport/000011686015/1951-1952_Index
lsdi2/tesseract/CampusReport/000011686012/19481001
lsdi2/tesseract/CampusReport/000011686012/19481008
lsdi2/tesseract/CampusReport/000011686012/19481015
lsdi2/tesseract/CampusReport/000011686012/19481022
lsdi2/tesseract/CampusReport/000011686012/19481029
lsdi2/tesseract/CampusReport/000011686012/19481105
lsdi2/tesseract/CampusReport/000011686012/19481112
lsdi2/tesseract/CampusReport/000011686012/19481119
lsdi2/tesseract/CampusReport/000011686012/19481124
lsdi2/tesseract/CampusReport/000011686012/19481203
lsdi2/tesseract/CampusReport/000011686012/19481210
lsdi2/tesseract/CampusReport/000011686012/19481231
lsdi2/tesseract/CampusReport/000011686012/19490107
lsdi2/tesseract/CampusReport/000011686012/19490114
lsdi2/tesseract/CampusReport/000011686012/19490120
lsdi2/tesseract/CampusReport/000011686012/19490128
lsdi2/tesseract/CampusReport/000011686012/19490204
lsdi2/tesseract/CampusReport/000011686012/19490211
lsdi2/tesseract/CampusReport/000011686012/19490218
lsdi2/tesseract/CampusReport/000011686012/19490225
lsdi2/tesseract/CampusReport/000011686012/19490304
lsdi2/tesseract/CampusReport/000011686012/19490311
lsdi2/tesseract/CampusReport/000011686012/19490318
lsdi2/tesseract/CampusReport/000011686012/19490325
lsdi2/tesseract/CampusReport/000011686012/19490401
lsdi2/tesseract/CampusReport/000011686012/19490408
lsdi2/tesseract/CampusReport/000011686012/19490415
lsdi2/tesseract/CampusReport/000011686012/19490422
lsdi2/tesseract/CampusReport/000011686012/19490429
lsdi2/tesseract/CampusReport/000011686012/19490506
lsdi2/tesseract/CampusReport/000011686012/19490513
lsdi2/tesseract/CampusReport/000011686012/19490520
lsdi2/tesseract/CampusReport/000011686012/19490527
lsdi2/tesseract/CampusReport/000011686012/19490617
lsdi2/tesseract/CampusReport/000011686012/19490624
lsdi2/tesseract/CampusReport/000011686012/19490701
lsdi2/tesseract/CampusReport/000011686012/19490708
lsdi2/tesseract/CampusReport/000011686012/19490715
lsdi2/tesseract/CampusReport/000011686012/19490722
lsdi2/tesseract/CampusReport/000011686012/19490729
lsdi2/tesseract/CampusReport/000011686012/19490805
lsdi2/tesseract/CampusReport/000011686012/19490812
lsdi2/tesseract/CampusReport/000011686012/19490819
lsdi2/tesseract/CampusReport/000011686013/19490930
lsdi2/tesseract/CampusReport/000011686013/19491007
lsdi2/tesseract/CampusReport/000011686013/19491014
lsdi2/tesseract/CampusReport/000011686013/19491021
lsdi2/tesseract/CampusReport/000011686013/19491028
lsdi2/tesseract/CampusReport/000011686013/19491104
lsdi2/tesseract/CampusReport/000011686013/19491111
lsdi2/tesseract/CampusReport/000011686013/19491118
lsdi2/tesseract/CampusReport/000011686013/19491202
lsdi2/tesseract/CampusReport/000011686013/19491209
lsdi2/tesseract/CampusReport/000011686013/19500108
lsdi2/tesseract/CampusReport/000011686013/19500113
lsdi2/tesseract/CampusReport/000011686013/19500120
lsdi2/tesseract/CampusReport/000011686013/19500127
lsdi2/tesseract/CampusReport/000011686013/19500203
lsdi2/tesseract/CampusReport/000011686013/19500210
lsdi2/tesseract/CampusReport/000011686013/19500217
lsdi2/tesseract/CampusReport/000011686013/19500224
lsdi2/tesseract/CampusReport/000011686013/19500303
lsdi2/tesseract/CampusReport/000011686013/19500310
lsdi2/tesseract/CampusReport/000011686013/19500317
lsdi2/tesseract/CampusReport/000011686013/19500324
lsdi2/tesseract/CampusReport/000011686013/19500331
lsdi2/tesseract/CampusReport/000011686013/19500407
lsdi2/tesseract/CampusReport/000011686013/19500414
lsdi2/tesseract/CampusReport/000011686013/19500421
lsdi2/tesseract/CampusReport/000011686013/19500428
lsdi2/tesseract/CampusReport/000011686013/19500505
lsdi2/tesseract/CampusReport/000011686013/19500512
lsdi2/tesseract/CampusReport/000011686013/19500519
lsdi2/tesseract/CampusReport/000011686013/19500526
lsdi2/tesseract/CampusReport/000011686013/19500602
lsdi2/tesseract/CampusReport/000011686013/19500616
lsdi2/tesseract/CampusReport/000011686013/19500623
lsdi2/tesseract/CampusReport/000011686013/19500630
lsdi2/tesseract/CampusReport/000011686013/19500707
lsdi2/tesseract/CampusReport/000011686013/19500714
lsdi2/tesseract/CampusReport/000011686013/19500721
lsdi2/tesseract/CampusReport/000011686013/19500728
lsdi2/tesseract/CampusReport/000011686013/19500804
lsdi2/tesseract/CampusReport/000011686013/19500811
lsdi2/tesseract/CampusReport/000011686013/19500818
lsdi2/tesseract/CampusReport/000011686014/19500929
lsdi2/tesseract/CampusReport/000011686014/19501006
lsdi2/tesseract/CampusReport/000011686014/19501013
lsdi2/tesseract/CampusReport/000011686014/19501020
lsdi2/tesseract/CampusReport/000011686014/19501027
lsdi2/tesseract/CampusReport/000011686014/19501103
lsdi2/tesseract/CampusReport/000011686014/19501110
lsdi2/tesseract/CampusReport/000011686014/19501117
lsdi2/tesseract/CampusReport/000011686014/19501201
lsdi2/tesseract/CampusReport/000011686014/19501208
lsdi2/tesseract/CampusReport/000011686014/19510105
lsdi2/tesseract/CampusReport/000011686014/19510112
lsdi2/tesseract/CampusReport/000011686014/19510119
lsdi2/tesseract/CampusReport/000011686014/19510126
lsdi2/tesseract/CampusReport/000011686014/19510202
lsdi2/tesseract/CampusReport/000011686014/19510209
lsdi2/tesseract/CampusReport/000011686014/19510216
lsdi2/tesseract/CampusReport/000011686014/19510223
lsdi2/tesseract/CampusReport/000011686014/19510302
lsdi2/tesseract/CampusReport/000011686014/19510309
lsdi2/tesseract/CampusReport/000011686014/19510323
lsdi2/tesseract/CampusReport/000011686014/19510330
lsdi2/tesseract/CampusReport/000011686014/19510406
lsdi2/tesseract/CampusReport/000011686014/19510413
lsdi2/tesseract/CampusReport/000011686014/19510420
lsdi2/tesseract/CampusReport/000011686014/19510427
lsdi2/tesseract/CampusReport/000011686014/19510504
lsdi2/tesseract/CampusReport/000011686014/19510511
lsdi2/tesseract/CampusReport/000011686014/19510518
lsdi2/tesseract/CampusReport/000011686014/19510525
lsdi2/tesseract/CampusReport/000011686014/19510615
lsdi2/tesseract/CampusReport/000011686014/19510622
lsdi2/tesseract/CampusReport/000011686014/19510629
lsdi2/tesseract/CampusReport/000011686014/19510706
lsdi2/tesseract/CampusReport/000011686014/19510713
lsdi2/tesseract/CampusReport/000011686014/19510720
lsdi2/tesseract/CampusReport/000011686014/19510727
lsdi2/tesseract/CampusReport/000011686014/19510803
lsdi2/tesseract/CampusReport/000011686014/19510810
lsdi2/tesseract/CampusReport/000011686014/19510817
lsdi2/tesseract/CampusReport/000011686015/19510928
lsdi2/tesseract/CampusReport/000011686015/19511003
lsdi2/tesseract/CampusReport/000011686015/19511012
lsdi2/tesseract/CampusReport/000011686015/19511019
lsdi2/tesseract/CampusReport/000011686015/19511026
lsdi2/tesseract/CampusReport/000011686015/19511102
lsdi2/tesseract/CampusReport/000011686015/19511109
lsdi2/tesseract/CampusReport/000011686015/19511116
lsdi2/tesseract/CampusReport/000011686015/19511130
lsdi2/tesseract/CampusReport/000011686015/19511207
lsdi2/tesseract/CampusReport/000011686015/19511214
lsdi2/tesseract/CampusReport/000011686015/19520104
lsdi2/tesseract/CampusReport/000011686015/19520111
lsdi2/tesseract/CampusReport/000011686015/19520118
lsdi2/tesseract/CampusReport/000011686015/19520125
lsdi2/tesseract/CampusReport/000011686015/19520201
lsdi2/tesseract/CampusReport/000011686015/19520208
lsdi2/tesseract/CampusReport/000011686015/19520215
lsdi2/tesseract/CampusReport/000011686015/19520222
lsdi2/tesseract/CampusReport/000011686015/19520229
lsdi2/tesseract/CampusReport/000011686015/19520307
lsdi2/tesseract/CampusReport/000011686015/19520321
lsdi2/tesseract/CampusReport/000011686015/19520328
lsdi2/tesseract/CampusReport/000011686015/19520404
lsdi2/tesseract/CampusReport/000011686015/19520411
lsdi2/tesseract/CampusReport/000011686015/19520418
lsdi2/tesseract/CampusReport/000011686015/19520425
lsdi2/tesseract/CampusReport/000011686015/19520502
lsdi2/tesseract/CampusReport/000011686015/19520509
lsdi2/tesseract/CampusReport/000011686015/19520516
lsdi2/tesseract/CampusReport/000011686015/19520523
lsdi2/tesseract/CampusReport/000011686015/19520530
lsdi2/tesseract/CampusReport/000011686015/19520620
lsdi2/tesseract/CampusReport/000011686015/19520627
lsdi2/tesseract/CampusReport/000011686015/19520703
lsdi2/tesseract/CampusReport/000011686015/19520711
lsdi2/tesseract/CampusReport/000011686015/19520718
lsdi2/tesseract/CampusReport/000011686015/19520725
lsdi2/tesseract/CampusReport/000011686015/19520801
lsdi2/tesseract/CampusReport/000011686015/19520808
lsdi2/tesseract/CampusReport/000011686015/19520815
lsdi2/tesseract/CampusReport/000011686015/19520822
lsdi2/tesseract/CampusReport/000011686016/19520926
lsdi2/tesseract/CampusReport/000011686016/19521003
lsdi2/tesseract/CampusReport/000011686016/19521010
lsdi2/tesseract/CampusReport/000011686016/19521017
lsdi2/tesseract/CampusReport/000011686016/19521024
lsdi2/tesseract/CampusReport/000011686016/19521031
lsdi2/tesseract/CampusReport/000011686016/19521107
lsdi2/tesseract/CampusReport/000011686016/19521114
lsdi2/tesseract/CampusReport/000011686016/19521121
lsdi2/tesseract/CampusReport/000011686016/19521205
lsdi2/tesseract/CampusReport/000011686016/19521212
lsdi2/tesseract/CampusReport/000011686016/19530102
lsdi2/tesseract/CampusReport/000011686016/19530109
lsdi2/tesseract/CampusReport/000011686016/19530116
lsdi2/tesseract/CampusReport/000011686016/19530123
lsdi2/tesseract/CampusReport/000011686016/19530130
lsdi2/tesseract/CampusReport/000011686016/19530206
lsdi2/tesseract/CampusReport/000011686016/19530213
lsdi2/tesseract/CampusReport/000011686016/19530220
lsdi2/tesseract/CampusReport/000011686016/19530227
lsdi2/tesseract/CampusReport/000011686016/19530306
lsdi2/tesseract/CampusReport/000011686016/19530327
lsdi2/tesseract/CampusReport/000011686016/19530403
lsdi2/tesseract/CampusReport/000011686016/19530410
lsdi2/tesseract/CampusReport/000011686016/19530417
lsdi2/tesseract/CampusReport/000011686016/19530424
lsdi2/tesseract/CampusReport/000011686016/19530501
lsdi2/tesseract/CampusReport/000011686016/19530508
lsdi2/tesseract/CampusReport/000011686016/19530515
lsdi2/tesseract/CampusReport/000011686016/19530522
lsdi2/tesseract/CampusReport/000011686016/19530529
lsdi2/tesseract/CampusReport/000011686016/19530619
lsdi2/tesseract/CampusReport/000011686016/19530626
lsdi2/tesseract/CampusReport/000011686016/19530703
lsdi2/tesseract/CampusReport/000011686016/19530710
lsdi2/tesseract/CampusReport/000011686016/19530717
lsdi2/tesseract/CampusReport/000011686016/19530724
lsdi2/tesseract/CampusReport/000011686016/19530731
lsdi2/tesseract/CampusReport/000011686016/19530807
lsdi2/tesseract/CampusReport/000011686016/19530814

**Comment by jcrompton42** [comment]
transferred
