### ISSUE TITLE
Fix missing FileSet association for 4 FileSets to their work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#2222]
We are trying to fix an issue with a book volume where we discovered the first 4 FileSets on the work are showing a missing/incomplete association with their parent work. This is an issue we've had sometimes in Bulkrax and this is an early Bulkrax import. The FileSets show up from the Work page, but when viewed individually show the warning "The file is not currently available because its parent work has not yet completed the approval process".

Our attempts to manually recreate the Filesets errored out, possibly because the files already exist in Fedora/S3.

**Parent work:**
https://curate.library.emory.edu/concern/curate_generic_works/965v6wwr9b-cor?locale=en

**FileSets:**

PDF
https://curate.library.emory.edu/concern/parent/965v6wwr9b-cor/file_sets/829b5mkn7m-cor 

Transcript for Volume
https://curate.library.emory.edu/concern/parent/965v6wwr9b-cor/file_sets/320sqv9tjm-cor

OCR Output for Volume
https://curate.library.emory.edu/concern/parent/965v6wwr9b-cor/file_sets/6623bk3knh-cor

Page 1
https://curate.library.emory.edu/concern/parent/965v6wwr9b-cor/file_sets/593ttdz1nc-cor

**Comment by bwatson78** [comment]
@eporter23 I've been working with these FileSets from the command line and my findings are that these 4 Fedora objects are lacking `state` assignment. I'm going to confirm that in Fedora's UI, making sure that they match.

**Comment by bwatson78** [comment]
I've compared a bad FileSet (Page 1) to a good one (Page 2) and neither of them sport a state attribute. I think these need to be recreated.

**Comment by eporter23** [comment]
Updates on this - I have now deleted the original 4 FileSets and manually reattached them. This process required me to slightly modify each of the files in order to get them into S3 (so they had a different sha1 identifier for the S3 object name) . It appears that our S3 configuration will not allow us to replace an existing file if it has the exact same checksum.
