### ISSUE TITLE
Transfer batch of AHAM Libros

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2227]
Please transfer all the following files in the following OneDrive directory to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from the OneDrive subdirectory name.

e.g. 
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL091_L06
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL091_L07
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL093_L03

Please let me know if you have any questions. Thanks!

**Comment by jcrompton42** [comment]
Working on this, because I am working with home internet having to transfer files out of one drive and then on to efs takes a long time. Thanks for your patience!

**Comment by kmichaelis** [comment]
Hi @jcrompton42 , any updates on this ticket?

**Comment by jcrompton42** [comment]
I have about 5 folders left, so I should be finishing it up either today or Monday.

**Comment by jcrompton42** [comment]
Finally done!!
