### ISSUE TITLE
Transfer AHAM boxes 71, 73, 103 

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2231]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja071
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja073
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja103

**Comment by jcrompton42** [comment]
transferred
