### ISSUE TITLE
Transfer AHAM boxes 81 and 83

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2233]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja081
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja083

**Comment by jcrompton42** [comment]
transferred
