### ISSUE TITLE
Transfer final (I think) batch of Campus Report volumes

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2234]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/CampusReport/000011686017/19530928
lsdi2/tesseract/CampusReport/000011686017/19531005
lsdi2/tesseract/CampusReport/000011686017/19531012
lsdi2/tesseract/CampusReport/000011686017/19531019
lsdi2/tesseract/CampusReport/000011686017/19531026
lsdi2/tesseract/CampusReport/000011686017/19531102
lsdi2/tesseract/CampusReport/000011686017/19531109
lsdi2/tesseract/CampusReport/000011686017/19531116
lsdi2/tesseract/CampusReport/000011686017/19531123
lsdi2/tesseract/CampusReport/000011686017/19531207
lsdi2/tesseract/CampusReport/000011686017/19531214
lsdi2/tesseract/CampusReport/000011686017/19540111
lsdi2/tesseract/CampusReport/000011686017/19540118
lsdi2/tesseract/CampusReport/000011686017/19540125
lsdi2/tesseract/CampusReport/000011686017/19540201
lsdi2/tesseract/CampusReport/000011686017/19540208
lsdi2/tesseract/CampusReport/000011686017/19540215
lsdi2/tesseract/CampusReport/000011686017/19540222
lsdi2/tesseract/CampusReport/000011686017/19540301
lsdi2/tesseract/CampusReport/000011686017/19540308
lsdi2/tesseract/CampusReport/000011686017/19540322
lsdi2/tesseract/CampusReport/000011686017/19540329
lsdi2/tesseract/CampusReport/000011686017/19540405
lsdi2/tesseract/CampusReport/000011686017/19540412
lsdi2/tesseract/CampusReport/000011686017/19540419
lsdi2/tesseract/CampusReport/000011686017/19540426
lsdi2/tesseract/CampusReport/000011686017/19540503
lsdi2/tesseract/CampusReport/000011686017/19540510
lsdi2/tesseract/CampusReport/000011686017/19540517
lsdi2/tesseract/CampusReport/000011686017/19540524
lsdi2/tesseract/CampusReport/000011686017/19540531
lsdi2/tesseract/CampusReport/000011686017/19540614
lsdi2/tesseract/CampusReport/000011686017/19540621
lsdi2/tesseract/CampusReport/000011686017/19540628
lsdi2/tesseract/CampusReport/000011686017/19540705
lsdi2/tesseract/CampusReport/000011686017/19540712
lsdi2/tesseract/CampusReport/000011686017/19540719
lsdi2/tesseract/CampusReport/000011686017/19540726
lsdi2/tesseract/CampusReport/000011686017/19540802
lsdi2/tesseract/CampusReport/000011686017/19540809
lsdi2/tesseract/CampusReport/000011686018/19540920
lsdi2/tesseract/CampusReport/000011686018/19540927
lsdi2/tesseract/CampusReport/000011686018/19541004
lsdi2/tesseract/CampusReport/000011686018/19541011
lsdi2/tesseract/CampusReport/000011686018/19541018
lsdi2/tesseract/CampusReport/000011686018/19541025
lsdi2/tesseract/CampusReport/000011686018/19541101
lsdi2/tesseract/CampusReport/000011686018/19541108
lsdi2/tesseract/CampusReport/000011686018/19541115
lsdi2/tesseract/CampusReport/000011686018/19541122
lsdi2/tesseract/CampusReport/000011686018/19541206
lsdi2/tesseract/CampusReport/000011686018/19541213
lsdi2/tesseract/CampusReport/000011686018/19541220
lsdi2/tesseract/CampusReport/000011686018/19550110
lsdi2/tesseract/CampusReport/000011686018/19550117
lsdi2/tesseract/CampusReport/000011686018/19550124
lsdi2/tesseract/CampusReport/000011686018/19550131
lsdi2/tesseract/CampusReport/000011686018/19550207
lsdi2/tesseract/CampusReport/000011686018/19550214
lsdi2/tesseract/CampusReport/000011686018/19550221
lsdi2/tesseract/CampusReport/000011686018/19550228
lsdi2/tesseract/CampusReport/000011686018/19550307
lsdi2/tesseract/CampusReport/000011686018/19550321
lsdi2/tesseract/CampusReport/000011686018/19550328
lsdi2/tesseract/CampusReport/000011686018/19550404
lsdi2/tesseract/CampusReport/000011686018/19550411
lsdi2/tesseract/CampusReport/000011686018/19550418
lsdi2/tesseract/CampusReport/000011686018/19550425
lsdi2/tesseract/CampusReport/000011686018/19550502
lsdi2/tesseract/CampusReport/000011686018/19550509
lsdi2/tesseract/CampusReport/000011686018/19550516
lsdi2/tesseract/CampusReport/000011686018/19550523
lsdi2/tesseract/CampusReport/000011686018/19550530
lsdi2/tesseract/CampusReport/000011686018/19550613
lsdi2/tesseract/CampusReport/000011686018/19550620
lsdi2/tesseract/CampusReport/000011686018/19550627
lsdi2/tesseract/CampusReport/000011686018/19550704
lsdi2/tesseract/CampusReport/000011686018/19550711
lsdi2/tesseract/CampusReport/000011686018/19550718
lsdi2/tesseract/CampusReport/000011686018/19550725
lsdi2/tesseract/CampusReport/000011686018/19550801
lsdi2/tesseract/CampusReport/000011686018/19550808
lsdi2/tesseract/CampusReport/000011686018/19550815
lsdi2/tesseract/CampusReport/000011686019/19550912
lsdi2/tesseract/CampusReport/000011686019/19550919
lsdi2/tesseract/CampusReport/000011686019/19550926
lsdi2/tesseract/CampusReport/000011686019/19551003
lsdi2/tesseract/CampusReport/000011686019/19551010
lsdi2/tesseract/CampusReport/000011686019/19551017
lsdi2/tesseract/CampusReport/000011686019/19551024
lsdi2/tesseract/CampusReport/000011686019/19551031
lsdi2/tesseract/CampusReport/000011686019/19551107
lsdi2/tesseract/CampusReport/000011686019/19551114
lsdi2/tesseract/CampusReport/000011686019/19551121
lsdi2/tesseract/CampusReport/000011686019/19551128
lsdi2/tesseract/CampusReport/000011686019/19551205
lsdi2/tesseract/CampusReport/000011686019/19551212
lsdi2/tesseract/CampusReport/000011686019/19560102
lsdi2/tesseract/CampusReport/000011686019/19560109
lsdi2/tesseract/CampusReport/000011686019/19560116
lsdi2/tesseract/CampusReport/000011686019/19560123
lsdi2/tesseract/CampusReport/000011686019/19560131
lsdi2/tesseract/CampusReport/000011686019/19560206
lsdi2/tesseract/CampusReport/000011686019/19560213
lsdi2/tesseract/CampusReport/000011686019/19560220
lsdi2/tesseract/CampusReport/000011686019/19560227
lsdi2/tesseract/CampusReport/000011686019/19560305
lsdi2/tesseract/CampusReport/000011686019/19560312
lsdi2/tesseract/CampusReport/000011686019/19560326
lsdi2/tesseract/CampusReport/000011686019/19560402
lsdi2/tesseract/CampusReport/000011686019/19560409
lsdi2/tesseract/CampusReport/000011686019/19560416
lsdi2/tesseract/CampusReport/000011686019/19560423
lsdi2/tesseract/CampusReport/000011686019/19560430
lsdi2/tesseract/CampusReport/000011686019/19560507
lsdi2/tesseract/CampusReport/000011686019/19560514
lsdi2/tesseract/CampusReport/000011686019/19560521
lsdi2/tesseract/CampusReport/000011686019/19560528
lsdi2/tesseract/CampusReport/000011686019/19560604
lsdi2/tesseract/CampusReport/000011686019/19560618
lsdi2/tesseract/CampusReport/000011686019/19560625
lsdi2/tesseract/CampusReport/000011686019/19560702
lsdi2/tesseract/CampusReport/000011686019/19560709
lsdi2/tesseract/CampusReport/000011686019/19560716
lsdi2/tesseract/CampusReport/000011686019/19560723
lsdi2/tesseract/CampusReport/000011686019/19560730
lsdi2/tesseract/CampusReport/000011686019/19560806
lsdi2/tesseract/CampusReport/000011686019/19560813
lsdi2/tesseract/CampusReport/000011686019/19560910
lsdi2/tesseract/CampusReport/000011686019/19560917
lsdi2/tesseract/CampusReport/000011686020/19560925
lsdi2/tesseract/CampusReport/000011686020/19561001
lsdi2/tesseract/CampusReport/000011686020/19561008
lsdi2/tesseract/CampusReport/000011686020/19561015
lsdi2/tesseract/CampusReport/000011686020/19561022
lsdi2/tesseract/CampusReport/000011686020/19561029
lsdi2/tesseract/CampusReport/000011686020/19561105
lsdi2/tesseract/CampusReport/000011686020/19561112
lsdi2/tesseract/CampusReport/000011686020/19561119
lsdi2/tesseract/CampusReport/000011686020/19561126
lsdi2/tesseract/CampusReport/000011686020/19561203
lsdi2/tesseract/CampusReport/000011686020/19561210
lsdi2/tesseract/CampusReport/000011686020/19561231
lsdi2/tesseract/CampusReport/000011686020/19570107
lsdi2/tesseract/CampusReport/000011686020/19570114
lsdi2/tesseract/CampusReport/000011686020/19570121
lsdi2/tesseract/CampusReport/000011686020/19570128
lsdi2/tesseract/CampusReport/000011686020/19570204
lsdi2/tesseract/CampusReport/000011686020/19570211
lsdi2/tesseract/CampusReport/000011686020/19570218
lsdi2/tesseract/CampusReport/000011686020/19570225
lsdi2/tesseract/CampusReport/000011686020/19570304
lsdi2/tesseract/CampusReport/000011686020/19570311
lsdi2/tesseract/CampusReport/000011686020/19570325
lsdi2/tesseract/CampusReport/000011686020/19570401
lsdi2/tesseract/CampusReport/000011686020/19570408
lsdi2/tesseract/CampusReport/000011686020/19570415
lsdi2/tesseract/CampusReport/000011686020/19570422
lsdi2/tesseract/CampusReport/000011686020/19570429
lsdi2/tesseract/CampusReport/000011686020/19570506
lsdi2/tesseract/CampusReport/000011686020/19570513
lsdi2/tesseract/CampusReport/000011686020/19570520
lsdi2/tesseract/CampusReport/000011686020/19570527
lsdi2/tesseract/CampusReport/000011686020/19570603
lsdi2/tesseract/CampusReport/000011686020/19570617
lsdi2/tesseract/CampusReport/000011686020/19570624
lsdi2/tesseract/CampusReport/000011686020/19570701
lsdi2/tesseract/CampusReport/000011686020/19570708
lsdi2/tesseract/CampusReport/000011686020/19570715
lsdi2/tesseract/CampusReport/000011686020/19570722
lsdi2/tesseract/CampusReport/000011686020/19570729
lsdi2/tesseract/CampusReport/000011686020/19570805
lsdi2/tesseract/CampusReport/000011686020/19570812
lsdi2/tesseract/CampusReport/000011686020/19570819
lsdi2/tesseract/CampusReport/000011686020/19570909
lsdi2/tesseract/CampusReport/000011686020/19570916
lsdi2/tesseract/CampusReport/000011686020/19570923
lsdi2/tesseract/CampusReport/000011686020/19570930
lsdi2/tesseract/CampusReport/000011686021/19571007
lsdi2/tesseract/CampusReport/000011686021/19571014
lsdi2/tesseract/CampusReport/000011686021/19571021
lsdi2/tesseract/CampusReport/000011686021/19571028
lsdi2/tesseract/CampusReport/000011686021/19571104
lsdi2/tesseract/CampusReport/000011686021/19571111
lsdi2/tesseract/CampusReport/000011686021/19571118
lsdi2/tesseract/CampusReport/000011686021/19571125
lsdi2/tesseract/CampusReport/000011686021/19571209
lsdi2/tesseract/CampusReport/000011686021/19571216
lsdi2/tesseract/CampusReport/000011686021/19580106
lsdi2/tesseract/CampusReport/000011686021/19580113
lsdi2/tesseract/CampusReport/000011686021/19580120
lsdi2/tesseract/CampusReport/000011686021/19580127
lsdi2/tesseract/CampusReport/000011686021/19580203
lsdi2/tesseract/CampusReport/000011686021/19580210
lsdi2/tesseract/CampusReport/000011686021/19580217
lsdi2/tesseract/CampusReport/000011686021/19580224
lsdi2/tesseract/CampusReport/000011686021/19580303
lsdi2/tesseract/CampusReport/000011686021/19580310
lsdi2/tesseract/CampusReport/000011686021/19580324
lsdi2/tesseract/CampusReport/000011686021/19580331
lsdi2/tesseract/CampusReport/000011686021/19580407
lsdi2/tesseract/CampusReport/000011686021/19580414
lsdi2/tesseract/CampusReport/000011686021/19580421
lsdi2/tesseract/CampusReport/000011686021/19580428
lsdi2/tesseract/CampusReport/000011686021/19580505
lsdi2/tesseract/CampusReport/000011686021/19580512
lsdi2/tesseract/CampusReport/000011686021/19580519
lsdi2/tesseract/CampusReport/000011686021/19580526
lsdi2/tesseract/CampusReport/000011686021/19580616
lsdi2/tesseract/CampusReport/000011686021/19580623
lsdi2/tesseract/CampusReport/000011686021/19580630
lsdi2/tesseract/CampusReport/000011686021/19580706
lsdi2/tesseract/CampusReport/000011686021/19580714
lsdi2/tesseract/CampusReport/000011686021/19580721
lsdi2/tesseract/CampusReport/000011686021/19580728
lsdi2/tesseract/CampusReport/000011686021/19580804
lsdi2/tesseract/CampusReport/000011686021/19580811
lsdi2/tesseract/CampusReport/000011686022/19580915
lsdi2/tesseract/CampusReport/000011686022/19580922
lsdi2/tesseract/CampusReport/000011686022/19580929
lsdi2/tesseract/CampusReport/000011686022/19581006
lsdi2/tesseract/CampusReport/000011686022/19581013
lsdi2/tesseract/CampusReport/000011686022/19581020
lsdi2/tesseract/CampusReport/000011686022/19581027
lsdi2/tesseract/CampusReport/000011686022/19581103
lsdi2/tesseract/CampusReport/000011686022/19581110
lsdi2/tesseract/CampusReport/000011686022/19581117
lsdi2/tesseract/CampusReport/000011686022/19581124
lsdi2/tesseract/CampusReport/000011686022/19581208
lsdi2/tesseract/CampusReport/000011686022/19581215
lsdi2/tesseract/CampusReport/000011686022/19590105
lsdi2/tesseract/CampusReport/000011686022/19590112
lsdi2/tesseract/CampusReport/000011686022/19590119
lsdi2/tesseract/CampusReport/000011686022/19590126
lsdi2/tesseract/CampusReport/000011686022/19590202
lsdi2/tesseract/CampusReport/000011686022/19590209
lsdi2/tesseract/CampusReport/000011686022/19590216
lsdi2/tesseract/CampusReport/000011686022/19590223
lsdi2/tesseract/CampusReport/000011686022/19590302
lsdi2/tesseract/CampusReport/000011686022/19590309
lsdi2/tesseract/CampusReport/000011686022/19590323
lsdi2/tesseract/CampusReport/000011686022/19590330
lsdi2/tesseract/CampusReport/000011686022/19590406
lsdi2/tesseract/CampusReport/000011686022/19590413
lsdi2/tesseract/CampusReport/000011686022/19590420
lsdi2/tesseract/CampusReport/000011686022/19590427
lsdi2/tesseract/CampusReport/000011686022/19590504
lsdi2/tesseract/CampusReport/000011686022/19590511
lsdi2/tesseract/CampusReport/000011686022/19590518
lsdi2/tesseract/CampusReport/000011686022/19590525
lsdi2/tesseract/CampusReport/000011686022/19590601
lsdi2/tesseract/CampusReport/000011686022/19590615
lsdi2/tesseract/CampusReport/000011686022/19590622
lsdi2/tesseract/CampusReport/000011686022/19590629
lsdi2/tesseract/CampusReport/000011686022/19590706
lsdi2/tesseract/CampusReport/000011686022/19590713
lsdi2/tesseract/CampusReport/000011686022/19590720
lsdi2/tesseract/CampusReport/000011686022/19590727
lsdi2/tesseract/CampusReport/000011686022/19590803
lsdi2/tesseract/CampusReport/000011686022/19590810
lsdi2/tesseract/CampusReport/000011686022/19590817
lsdi2/tesseract/CampusReport/000011686023/19590921
lsdi2/tesseract/CampusReport/000011686023/19590928
lsdi2/tesseract/CampusReport/000011686023/19591005
lsdi2/tesseract/CampusReport/000011686023/19591012
lsdi2/tesseract/CampusReport/000011686023/19591019
lsdi2/tesseract/CampusReport/000011686023/19591026
lsdi2/tesseract/CampusReport/000011686023/19591102
lsdi2/tesseract/CampusReport/000011686023/19591109
lsdi2/tesseract/CampusReport/000011686023/19591116
lsdi2/tesseract/CampusReport/000011686023/19591123
lsdi2/tesseract/CampusReport/000011686023/19591207
lsdi2/tesseract/CampusReport/000011686023/19591214
lsdi2/tesseract/CampusReport/000011686023/19600104
lsdi2/tesseract/CampusReport/000011686023/19600111
lsdi2/tesseract/CampusReport/000011686023/19600118
lsdi2/tesseract/CampusReport/000011686023/19600125
lsdi2/tesseract/CampusReport/000011686023/19600201
lsdi2/tesseract/CampusReport/000011686023/19600208
lsdi2/tesseract/CampusReport/000011686023/19600215
lsdi2/tesseract/CampusReport/000011686023/19600222
lsdi2/tesseract/CampusReport/000011686023/19600229
lsdi2/tesseract/CampusReport/000011686023/19600307
lsdi2/tesseract/CampusReport/000011686023/19600321
lsdi2/tesseract/CampusReport/000011686023/19600328
lsdi2/tesseract/CampusReport/000011686023/19600404
lsdi2/tesseract/CampusReport/000011686023/19600411
lsdi2/tesseract/CampusReport/000011686023/19600418
lsdi2/tesseract/CampusReport/000011686023/19600425
lsdi2/tesseract/CampusReport/000011686023/19600502
lsdi2/tesseract/CampusReport/000011686023/19600509
lsdi2/tesseract/CampusReport/000011686023/19600516
lsdi2/tesseract/CampusReport/000011686023/19600523
lsdi2/tesseract/CampusReport/000011686023/19600530
lsdi2/tesseract/CampusReport/000011686023/19600613
lsdi2/tesseract/CampusReport/000011686023/19600620
lsdi2/tesseract/CampusReport/000011686023/19600627
lsdi2/tesseract/CampusReport/000011686023/19600704
lsdi2/tesseract/CampusReport/000011686023/19600711
lsdi2/tesseract/CampusReport/000011686023/19600718
lsdi2/tesseract/CampusReport/000011686023/19600725
lsdi2/tesseract/CampusReport/000011686023/19600801
lsdi2/tesseract/CampusReport/000011686023/19600808
lsdi2/tesseract/CampusReport/000011686024/19600916
lsdi2/tesseract/CampusReport/000011686024/19600926
lsdi2/tesseract/CampusReport/000011686024/19601010
lsdi2/tesseract/CampusReport/000011686024/19601017
lsdi2/tesseract/CampusReport/000011686024/19601024
lsdi2/tesseract/CampusReport/000011686024/19601031
lsdi2/tesseract/CampusReport/000011686024/19601107
lsdi2/tesseract/CampusReport/000011686024/19601114
lsdi2/tesseract/CampusReport/000011686024/19601121
lsdi2/tesseract/CampusReport/000011686024/19601128
lsdi2/tesseract/CampusReport/000011686024/19601205
lsdi2/tesseract/CampusReport/000011686024/19601212
lsdi2/tesseract/CampusReport/000011686024/19601219
lsdi2/tesseract/CampusReport/000011686024/19610103
lsdi2/tesseract/CampusReport/000011686024/19610109
lsdi2/tesseract/CampusReport/000011686024/19610116
lsdi2/tesseract/CampusReport/000011686024/19610123
lsdi2/tesseract/CampusReport/000011686024/19610130
lsdi2/tesseract/CampusReport/000011686024/19610206
lsdi2/tesseract/CampusReport/000011686024/19610213
lsdi2/tesseract/CampusReport/000011686024/19610220
lsdi2/tesseract/CampusReport/000011686024/19610227
lsdi2/tesseract/CampusReport/000011686024/19610306
lsdi2/tesseract/CampusReport/000011686024/19610313
lsdi2/tesseract/CampusReport/000011686024/19610320
lsdi2/tesseract/CampusReport/000011686024/19610327
lsdi2/tesseract/CampusReport/000011686024/19610403
lsdi2/tesseract/CampusReport/000011686024/19610410
lsdi2/tesseract/CampusReport/000011686024/19610417
lsdi2/tesseract/CampusReport/000011686024/19610424
lsdi2/tesseract/CampusReport/000011686024/19610501
lsdi2/tesseract/CampusReport/000011686024/19610508
lsdi2/tesseract/CampusReport/000011686024/19610515
lsdi2/tesseract/CampusReport/000011686024/19610522
lsdi2/tesseract/CampusReport/000011686024/19610529
lsdi2/tesseract/CampusReport/000011686024/19610612
lsdi2/tesseract/CampusReport/000011686024/19610619
lsdi2/tesseract/CampusReport/000011686024/19610626
lsdi2/tesseract/CampusReport/000011686024/19610703
lsdi2/tesseract/CampusReport/000011686024/19610710
lsdi2/tesseract/CampusReport/000011686024/19610717
lsdi2/tesseract/CampusReport/000011686024/19610724
lsdi2/tesseract/CampusReport/000011686024/19610731
lsdi2/tesseract/CampusReport/000011686024/19610807
lsdi2/tesseract/CampusReport/000011686025/19610918
lsdi2/tesseract/CampusReport/000011686025/19610925
lsdi2/tesseract/CampusReport/000011686025/19611002
lsdi2/tesseract/CampusReport/000011686025/19611009
lsdi2/tesseract/CampusReport/000011686025/19611016
lsdi2/tesseract/CampusReport/000011686025/19611023
lsdi2/tesseract/CampusReport/000011686025/19611030
lsdi2/tesseract/CampusReport/000011688406/19820510
lsdi2/tesseract/CampusReport/010000351841/19960226
lsdi2/tesseract/CampusReport/010000351841/19960610
lsdi2/tesseract/CampusReport/010000351841/19960624
lsdi2/tesseract/CampusReport/010000351842/19980420
lsdi2/tesseract/CampusReport/010000771666/20020218
lsdi2/tesseract/CampusReport/010001154007/20060117
lsdi2/tesseract/CampusReport/000011644340/20090824
lsdi2/tesseract/CampusReport/000011644340/20090831
lsdi2/tesseract/CampusReport/000011644340/20090914
lsdi2/tesseract/CampusReport/000011644340/20090928
lsdi2/tesseract/CampusReport/000011644340/20091019
lsdi2/tesseract/CampusReport/000011644340/20091102
lsdi2/tesseract/CampusReport/000011644340/20091116
lsdi2/tesseract/CampusReport/000011644340/20091207
lsdi2/tesseract/CampusReport/000011644340/20100125
lsdi2/tesseract/CampusReport/000011644340/20100208
lsdi2/tesseract/CampusReport/000011644340/20100222
lsdi2/tesseract/CampusReport/000011644340/20100315
lsdi2/tesseract/CampusReport/000011644340/20100329
lsdi2/tesseract/CampusReport/000011644340/20100412
lsdi2/tesseract/CampusReport/000011644340/20100426
lsdi2/tesseract/CampusReport/000011644340/20100517
lsdi2/tesseract/CampusReport/000011644340/20100607
lsdi2/tesseract/CampusReport/000011644340/20100621
lsdi2/tesseract/CampusReport/000011644340/20100706
lsdi2/tesseract/CampusReport/000011644340/20100719
lsdi2/tesseract/CampusReport/000011644340/20120514

**Comment by jcrompton42** [comment]
transferred
