### ISSUE TITLE
Transfer Emory Magazine files from OneDrive to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2236]
Please transfer all the following files in [this OneDrive directory](https://emory-my.sharepoint.com/personal/kmicha3_emory_edu/_layouts/15/onedrive.aspx?login_hint=kmicha3%40emory%2Eedu&id=%2Fpersonal%2Fkmicha3%5Femory%5Fedu%2FDocuments%2FMiscellaneous%20meetings%20and%20docs%2FEmory%20Magazine&view=0) to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure specified below:

lsdi2/tesseract/EmoryMagazine/EmoryMagazine_Autumn_2009
lsdi2/tesseract/EmoryMagazine/EmoryMagazine_Autumn_2010

etc.

**Comment by jcrompton42** [comment]
transferred
