### ISSUE TITLE
Re-copy William Scott Sr. and 2 Yellowback volumes' files to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2239]
The files for the William Scott Sr. Papers are no longer on EFS but also don't appear to be in Glacier. They need to be re-copied to EFS so I can move them to Glacier. 

Please re-transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_1082_Scott/B001
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/B002
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/B003
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV1
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV2_12037_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV3_12038_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV4_12039_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV5_12040_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV6_12041_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV7_12042_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV8_12043_William_Scott
dmfiles/MARBL/Manuscripts/MSS_1082_Scott/BV9_12044_Williams_Scott

There are also 2 Yellowback volumes that are ingested but no longer in EFS (to be transferred to Glacier):

lsdi2/ocm03043040-3067
lsdi/diesel/lts_new/ocm20814807-2881/

**Comment by jcrompton42** [comment]
transferred
