### ISSUE TITLE
Re-copy files from several collections to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2240]
Please re-transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/CherokeeBible/
lsdi2/tesseract/Crowther/300000329651/
dmfiles/Libraries/Health_Sciences/HS-S015_USArmy_GenHosp_43rd/
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B004
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B005
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B006
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B007
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B008
dmfiles/MARBL/Manuscripts/MSS_0754_Yun/B019
lsdi2/borndigital/EU_Catalogs/GSAS_2010-2011
lsdi2/borndigital/EU_Catalogs/Law_2014-2015

**Comment by jcrompton42** [comment]
transferred
