### ISSUE TITLE
Copy two South Asia Archives PDFs to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2241]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/300000434000/
lsdi2/ftp/300000433992/

**Comment by kmichaelis** [comment]
@jcrompton42 I looked and noticed that the PDFs being copied from the Isilon share have the same filename. Can you tell if they're two different PDFs, one with an incorrect name, or do they appear to be identical?

**Comment by jcrompton42** [comment]
Umm, I did a little spot checking and I can tell you things like the marc.xml contents are different, the pdf in the PDF subdirectories are different, and a few identically named (000001.xml eg) files between the folders do not contain the same info. That would indicate to me they are different but I am not sure if I am looking for something more specific?

**Comment by jcrompton42** [comment]
transferred folders and updated pdfs
