### ISSUE TITLE
Transfer batch 2 of AHAM Libros

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2242]
Please transfer all the following files in [this OneDrive directory](https://emory-my.sharepoint.com/personal/kmicha3_emory_edu/_layouts/15/onedrive.aspx?login_hint=kmicha3%40emory%2Eedu&isAscending=true&id=%2Fpersonal%2Fkmicha3%5Femory%5Fedu%2FDocuments%2FMiscellaneous%20meetings%20and%20docs%2FAHAM%20Libros%20to%20transfer&sortField=LinkFilename&view=0) (only the top level--exclude the subfolder titled "Transfer complete") to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from the OneDrive subdirectory name.

e.g.
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL091_L06
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL091_L07
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_CL093_L03

Please let me know if you have any questions. Thanks!

**Comment by jcrompton42** [comment]
approximately halfway through transferring

**Comment by jcrompton42** [comment]
transferred them all! Finally! Also my friends in Research IT have given me some ideas for a better way to do this so maybe the next batch will be a little faster.
