### ISSUE TITLE
Transfer batch of Yellowbacks to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2243]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm04294326-1614
lsdi/diesel/lts_new/ocm15645341-1795
lsdi/diesel/lts_new/ocm04329378-1966
lsdi/diesel/lts_new/ocm10891921-2260
lsdi/diesel/lts_new/ocm21086740-1885
lsdi/diesel/lts_new/ocm04329454-1973
lsdi/diesel/lts_new/ocm04321409-1922
lsdi/diesel/lts_new/ocm04311881-1660
lsdi/diesel/lts_new/ocm04315248-1718
lsdi/diesel/lts_new/ocm06342616-2071
lsdi/diesel/lts_new/ocm24179624-2072
lsdi/diesel/lts_new/ocm22578462-1591
lsdi/diesel/lts_new/ocm04340587-1990
lsdi/diesel/lts_new/ocm04428175-1934
lsdi/diesel/lts_new/ocm29690004-1878
lsdi/diesel/lts_new/ocm15154125-2401
lsdi/diesel/lts_new/ocm05922290-1895
lsdi/diesel/lts_new/ocm10620981-1606
lsdi/diesel/lts_new/ocn190928827-1788
lsdi/diesel/lts_new/ocm16618902-2017
lsdi/diesel/lts_new/ocn300311070-1833
lsdi/diesel/lts_new/ocm10491495-1535
lsdi/diesel/lts_new/ocm10491482-1530
lsdi/diesel/lts_new/ocm10491530-1542
lsdi/diesel/lts_new/ocm10491454-1366
lsdi/diesel/lts_new/ocm10491564-1397
lsdi/diesel/lts_new/ocm22592481-1831
lsdi/diesel/lts_new/ocm10621012-1543
lsdi/diesel/lts_new/ocm10491560-1365
lsdi/diesel/lts_new/ocm10321144-1529
lsdi/diesel/lts_new/ocm10620997-1651
lsdi/diesel/lts_new/ocm10742871-1890
lsdi/diesel/lts_new/ocm15099533-1808
lsdi/diesel/lts_new/ocm27818130-1950
lsdi/diesel/lts_new/ocm04315104-1697
lsdi/diesel/lts_new/ocm04329475-1974
lsdi/diesel/lts_new/ocm22592567-1951
lsdi/diesel/lts_new/ocm04294283-1612
lsdi/diesel/lts_new/ocm04340532-1987
lsdi/diesel/lts_new/ocm04282590-1601
lsdi/diesel/lts_new/ocm04340519-1976
lsdi/diesel/lts_new/ocm04297674-1621
lsdi/diesel/lts_new/ocm04288236-1605
lsdi/diesel/lts_new/ocm04307980-1646
lsdi/diesel/lts_new/ocm04307958-1645
lsdi/diesel/lts_new/ocm04329429-1972
lsdi/diesel/lts_new/ocm04344331-1882
lsdi/diesel/lts_new/ocm04404550-1935
lsdi/diesel/lts_new/ocm04278299-1604

**Comment by jcrompton42** [comment]
transferred
