### ISSUE TITLE
Transfer Gonne-Yeats box 4 and two fallout files in box 2

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2245]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/MARBL/Manuscripts/MSS_0930_Gonne-Yeats/B004
dmfiles/MARBL/Manuscripts/MSS_0930_Gonne-Yeats/B002/F047/ARCH/MSS0930_B002_F047_I001_P003_ARCH.tif
dmfiles/MARBL/Manuscripts/MSS_0930_Gonne-Yeats/B002/F047/PROD/MSS0930_B002_F047_I001_P003_PROD.tif

**Comment by jcrompton42** [comment]
transferred
