### ISSUE TITLE
Transfer batch of Views of Rome files

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2248]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/ViewsOfRome/000011902153
lsdi2/tesseract/ViewsOfRome/010002428141
lsdi2/tesseract/ViewsOfRome/010002631423
lsdi2/tesseract/ViewsOfRome/010002713660
lsdi2/tesseract/ViewsOfRome/010002713661
lsdi2/tesseract/ViewsOfRome/010002713663
lsdi2/tesseract/ViewsOfRome/010002713664
lsdi2/tesseract/ViewsOfRome/010002713665
lsdi2/tesseract/ViewsOfRome/010002713666
lsdi2/tesseract/ViewsOfRome/010002713667
lsdi2/tesseract/ViewsOfRome/010003065352
lsdi2/tesseract/ViewsOfRome/010003065353

**Comment by jcrompton42** [comment]
transferred
