### ISSUE TITLE
Transfer two straggler Views of Rome issues from OneDrive

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2249]
Please copy [these folders](https://emory-my.sharepoint.com/:f:/r/personal/kmicha3_emory_edu/Documents/Miscellaneous%20meetings%20and%20docs/Views%20of%20Rome%20stragglers?csf=1&web=1&e=ZrpzdR) from OneDrive to EFS. The filepaths should be:

lsdi2/tesseract/ViewsOfRome/010000426132
lsdi2/tesseract/ViewsOfRome/010001171587

**Comment by jcrompton42** [comment]
transferred
