### ISSUE TITLE
Rename ALTO files in the Boule Journal folder

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2252]
Please remove the characters "ALTO" from ALTO filenames in all subfolders in the Boule Journal folder on EFS:

lsdi2/docworks/boulejournal

Currently the filenames are structured like this:

BouleJournal_19250101_ALTO036.xml

I need them to look like this:

BouleJournal_19250101_036.xml

Thank you!

**Comment by jcrompton42** [comment]
renamed
