### ISSUE TITLE
Transfer small batch of African American Imprints

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2258]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/ftp/010001102103
lsdi2/ftp/africanamerican/010000667809
lsdi2/ftp/africanamerican/010000709375
lsdi2/ftp/africanamerican/010002588024
lsdi2/ftp/africanamerican/010000666968
lsdi2/ftp/10002350196

**Comment by jcrompton42** [comment]
transferred
