### ISSUE TITLE
Transfer 3 Kessler volumes to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2261]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/Kessler/000015280544
lsdi2/tesseract/Kessler/300000363541
lsdi2/tesseract/Kessler/EMU174867

**Comment by jcrompton42** [comment]
transferred
