### ISSUE TITLE
Re-transfer one Kessler volume to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2262]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location (directory already exists but is empty).

lsdi2/tesseract/Kessler/300000223701

**Comment by jcrompton42** [comment]
transferred
