### ISSUE TITLE
EFS storage content volume increasing without explanation

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2265]
A little over a week ago, I checked to see the amount of content that was on our EFS instance and it showed a total of 12.88 TB (the regular tier and the infrequent access tier combined). Today, it's showing that there is a little over 14 TB in EFS, although I haven't requested anything to be transferred to EFS in almost a month.

Emily has put a few OpenEmory test files on EFS, but only 154 KB worth. I just checked to make sure my most recent transfers from EFS to Glacier went through, and they appear to have been successful. Can you please investigate and see if there are any gremlins messing about on our EFS?

**Comment by jcrompton42** [comment]
This was me, transferring some files in an old ticket I had already done but not closed :( 
I deleted the new files and all should be well. No gremlins!
