### ISSUE TITLE
Transfer batch of Yellowbacks

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2266]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm10491454-1366
lsdi/diesel/lts_new/ocm06748821-1794
lsdi/diesel/lts_new/ocm10755737-1888
lsdi/diesel/lts_new/ocn420593196-2402/ocn420593196
lsdi/diesel/lts_new/ocm22578352-1559
lsdi2/ocn168389493-5598/ocn168389493
lsdi/diesel/lts_new/ocn190939723-1504
lsdi2/ocm10321134-1456/ocm10321134
lsdi/diesel/lts_new/ocm22590508-1745
lsdi/diesel/lts_new/ocm22590853-1814/ocm22590853
lsdi2/ocm10321038-1459
lsdi/diesel/lts_new/ocm10491582-1415
lsdi/diesel/lts_new/ocm38671171-2088/ocm38671171
lsdi/diesel/lts_new/ocm22581790-1799/ocm22581790
lsdi/diesel/lts_new/ocm10321074-1457
lsdi/diesel/lts_new/ocm06933530-1653/ocm06933530
lsdi/diesel/lts_new/ocm10621195-1805/ocm10621195
lsdi/diesel/lts_new/ocm05044204-1829/ocm05044204
lsdi/diesel/lts_new/ocm10757356-1830/ocm10757356
lsdi/diesel/lts_new/ocm10757373-2015/ocm10757373
lsdi/diesel/lts_new/ocm10755728-2016/ocm10755728
lsdi/diesel/lts_new/ocm28271022-1877/ocm28271022
lsdi/diesel/lts_new/ocm05044229-1593/ocm05044229
lsdi/diesel/lts_new/ocm22578415-1582
lsdi/diesel/lts_new/ocm10491544-1497
lsdi/diesel/lts_new/ocm10329035-1544
lsdi/diesel/lts_new/ocn145746759-1803
lsdi/diesel/lts_new/ocm10757382-1809/ocm10757382
lsdi2/ocm06938605-1802/ocm06938605
lsdi/diesel/lts_new/ocm22590649-1793/ocm22590649
lsdi/diesel/lts_new/ocm22592603-1869/ocm22592603
lsdi/diesel/lts_new/ocm31725325-1768
lsdi/diesel/lts_new/ocm38688696-1787
lsdi/diesel/lts_new/ocm10491470-1548
lsdi2/ocm02923645-1751
lsdi/diesel/lts_new/ocm22589596-1685/ocm22589596
lsdi/diesel/lts_new/ocm28398003-1770
lsdi/diesel/lts_new/ocn168336800-1358/ocn168336800

**Comment by jcrompton42** [comment]
transferred. I love yellowbacks!
