### ISSUE TITLE
Transfer more Yellowbacks

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2269]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm37669099-2492/ocm37669099
lsdi/diesel/lts_new/ocn166402644-2485/ocn166402644
lsdi/diesel/lts_new/ocm36072501-2509/ocm36072501
lsdi/diesel/lts_new/ocm38954517-1912/ocm38954517
lsdi/diesel/lts_new/ocm36072513-2502/ocm36072513
lsdi/diesel/lts_new/ocm36072525-2506/ocm36072525
lsdi/diesel/lts_new/ocm36072511-2475/ocm36072511
lsdi/diesel/lts_new/ocm36072530-2408/ocm36072530
lsdi/diesel/lts_new/ocm36072497-2410/ocm36072497
lsdi/diesel/lts_new/ocm36072495-2469/ocm36072495
lsdi/diesel/lts_new/ocm36072495-2470/ocm36072495
lsdi/diesel/lts_new/ocn165153386-2471/ocn165153386
lsdi/diesel/lts_new/ocn165153386-2472/ocn165153386
lsdi/diesel/lts_new/ocm36072518-2478/ocm36072518
lsdi/diesel/lts_new/ocm36072511-2476/ocm36072511
lsdi/diesel/lts_new/ocm11712748-2405/ocm11712748
lsdi/diesel/lts_new/ocn166408601-2479/ocn166408601
lsdi/diesel/lts_new/ocm13519831-2480/ocm13519831
lsdi/diesel/lts_new/ocn164865607-2503/ocn164865607
lsdi/diesel/lts_new/ocm36072553-2505/ocm36072553
lsdi/diesel/lts_new/ocm37669099-2491/ocm37669099
lsdi/diesel/lts_new/ocm36072473-2473/ocm36072473
lsdi/diesel/lts_new/ocm36072473-2474/ocm36072473
lsdi/diesel/lts_new/ocm10792935-1856/ocm10792935
lsdi/diesel/lts_new/ocm36072493-2461/ocm36072493
lsdi/diesel/lts_new/ocm22927132-2404/ocm22927132
lsdi/diesel/lts_new/ocn166352984-3033/ocn166352984
lsdi/diesel/lts_new/ocm20121300-2455/ocm20121300
lsdi/diesel/lts_new/ocm36072423-2482/ocm36072423
lsdi/diesel/lts_new/ocm36072417-2507/ocm36072417
lsdi/diesel/lts_new/ocm14997850-2481/ocm14997850
lsdi/diesel/lts_new/ocm06738792-1904/ocm06738792
lsdi/diesel/lts_new/ocm12378089-1909/ocm12378089
lsdi/diesel/lts_new/ocm10892334-2209/ocm10892334
lsdi/diesel/lts_new/ocm11258722-2489/ocm11258722
lsdi/diesel/lts_new/ocm27688895-1907/ocm27688895
lsdi2/ocm10892411-2330/ocm10892411
lsdi/diesel/lts_new/ocn123179270-2538/ocn123179270
lsdi/diesel/lts_new/ocm22039366-1939/ocm22039366
lsdi/diesel/lts_new/ocm36072417-2508/ocm36072417
lsdi/diesel/lts_new/ocn163947612-1917/ocn163947612
lsdi/diesel/lts_new/ocm10792986-1984/ocm10792986
lsdi/diesel/lts_new/ocm15567034-2958
lsdi/diesel/lts_new/ocm23244904-1938
lsdi/diesel/lts_new/ocn123179270-2537
lsdi/diesel/lts_new/ocn166275783-2460/ocn166275783
lsdi/diesel/lts_new/ocm36072540-2484/ocm36072540
lsdi/diesel/lts_new/ocm07393790-2477/ocm07393790
lsdi/diesel/lts_new/ocm36072545-2456/ocm36072545
lsdi/diesel/lts_new/ocm36072530-2409/ocm36072530
lsdi/diesel/lts_new/ocn166144255-3044
lsdi2/ocm14997853-2488/ocm14997853
lsdi2/ocm14997853-2487/ocm14997853
lsdi/diesel/lts_new/ocm14996872-2457
lsdi/diesel/lts_new/ocm36072533-2501
lsdi/diesel/lts_new/ocm10892471-2036/ocm10892471
lsdi/diesel/lts_new/ocm10891979-2070/ocm10891979
lsdi/diesel/lts_new/ocm36072545-2406/ocm36072545
lsdi/diesel/lts_new/ocm36072481-2490
lsdi/diesel/lts_new/ocn166435092-2454/ocn166435092
lsdi/diesel/lts_new/ocn166275783-2459/ocn166275783

**Comment by jcrompton42** [comment]
transferred
