### ISSUE TITLE
Transfer Board of Trustees batch 1

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2271]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi2/tesseract/EUA_0045_Trustees/BV1
lsdi2/tesseract/EUA_0046_Trustees/BV2
lsdi2/tesseract/EUA_0046_Trustees/BV3
lsdi2/tesseract/EUA_0046_Trustees/BV4
lsdi2/tesseract/EUA_0046_Trustees/BV5
lsdi2/tesseract/EUA_0046_Trustees/BV6

**Comment by jcrompton42** [comment]
transferred
