### ISSUE TITLE
Copy Chronicle of Higher Education files from OneDrive to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2272]
Please transfer all the following files in the following directory from [this OneDrive folder](https://emory-my.sharepoint.com/personal/kmicha3_emory_edu/_layouts/15/onedrive.aspx?login_hint=kmicha3%40emory%2Eedu&id=%2Fpersonal%2Fkmicha3%5Femory%5Fedu%2FDocuments%2FMiscellaneous%20meetings%20and%20docs%2FChronicle&view=0) to our AWS EFS mount. Transfer all files in each directory and create a directory on EFS with the structure:

/mnt/efs/Collections/lsdi2/Chronicle

**Comment by jcrompton42** [comment]
transferred
