### ISSUE TITLE
Transfer AHAM boxes 72, 74-79, 84-90

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2274]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja072
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja074
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja075
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja076
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja077
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja078
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja079
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja084
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja085
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja086
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja087
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja088
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja089
dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja090

**Comment by jcrompton42** [comment]
transferred
