### ISSUE TITLE
Copy PDF into AHAM EFS folder

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2275]
[Novo_c090e060.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dfc7448c9c772d98631f23fbaa5634c4831fbad/Novo_c090e060.pdf)

Please place a copy of the attached PDF into the following folder on EFS:

dmfiles/Libraries/Main_Woodruff/AHAM/Novo_Caja090/Novo_c090e060

**Comment by jcrompton42** [comment]
copied
