### ISSUE TITLE
Transfer another batch of Yellowbacks

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2276]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm15736606-2671
lsdi/diesel/lts_new/ocm11305386-2800
lsdi/diesel/lts_new/ocn307682718-2340
lsdi/diesel/lts_new/ocm22618442-2332
lsdi/diesel/lts_new/ocm13298911-2499
lsdi/diesel/lts_new/ocm13356911-2770
lsdi2/ocm06756859-2763
lsdi/diesel/lts_new/ocm21954262-2462
lsdi/diesel/lts_new/ocm24179874-2805
lsdi/diesel/lts_new/ocm22594643-2732
lsdi/diesel/lts_new/ocm15099351-2625
lsdi/diesel/lts_new/ocm02169810-2680
lsdi/diesel/lts_new/ocm24904363-2687
lsdi/diesel/lts_new/ocm02171638-2690
lsdi/diesel/lts_new/ocm22633663-2669
lsdi/diesel/lts_new/ocm02171467-2691
lsdi/diesel/lts_new/ocm02158661-2675
lsdi/diesel/lts_new/ocm02909952-2673
lsdi/diesel/lts_new/ocm22634256-2668
lsdi/diesel/lts_new/ocm22618557-2343
lsdi/diesel/lts_new/ocm12763238-2695
lsdi/diesel/lts_new/ocm15046542-2412
lsdi/diesel/lts_new/ocm13407907-2700
lsdi/diesel/lts_new/ocm13527399-2704
lsdi/diesel/lts_new/ocm22633880-2688
lsdi/diesel/lts_new/ocm22204868-2666
lsdi/diesel/lts_new/ocm15127640-2696
lsdi/diesel/lts_new/ocm22633761-2681
lsdi/diesel/lts_new/ocm22633916-2689
lsdi/diesel/lts_new/ocm15598490-2703
lsdi/diesel/lts_new/ocm13974506-2685
lsdi/diesel/lts_new/ocm02171664-2686
lsdi/diesel/lts_new/ocm62262589-2297
lsdi/diesel/lts_new/ocm11301083-2667
lsdi/diesel/lts_new/ocm22204767-2692
lsdi/diesel/lts_new/ocm22634002-2694
lsdi/diesel/lts_new/ocm36065742-2802
lsdi/diesel/lts_new/ocm22105139-2738
lsdi/diesel/lts_new/ocm04109835-2693
lsdi/diesel/lts_new/ocm13537958-2743
lsdi/diesel/lts_new/ocm03036944-2378
lsdi/diesel/lts_new/ocm52717129-2745
lsdi2/ocm04334623-2709
lsdi/diesel/lts_new/ocm22342289-2706
lsdi/diesel/lts_new/ocm05837262-2769
lsdi/diesel/lts_new/ocm06938370-2791
lsdi/diesel/lts_new/ocm15598559-2287
lsdi2/ocm04444792-2989
lsdi/diesel/lts_new/ocm22176718-2776
lsdi/diesel/lts_new/ocm15046551-2430
lsdi/diesel/lts_new/ocn129929299-2300
lsdi/diesel/lts_new/ocm15741030-2372
lsdi/diesel/lts_new/ocm11657209-2778
lsdi/diesel/lts_new/ocm15645442-2712
lsdi/diesel/lts_new/ocn217268073-2374
lsdi/diesel/lts_new/ocm08705262-2807
lsdi/diesel/lts_new/ocm22176718-3066
lsdi/diesel/lts_new/ocm11616310-2816
lsdi/diesel/lts_new/ocm13655446-2775
lsdi2/ocm06825933-2784
lsdi/diesel/lts_new/ocm15041698-2421
lsdi/diesel/lts_new/ocm24179908-2744
lsdi/diesel/lts_new/ocm13407890-2702
lsdi/diesel/lts_new/ocm09450819-2771
lsdi/diesel/lts_new/ocm05690904-2717
lsdi/diesel/lts_new/ocm15506256-2588
lsdi/diesel/lts_new/ocm24180402-2708
lsdi2/ocm05574566-2735
lsdi/diesel/lts_new/ocm16073481-2591
lsdi/diesel/lts_new/ocm06756928-2806
lsdi/diesel/lts_new/ocn310431969-2765
lsdi2/ocm06505885-2317
lsdi/diesel/lts_new/ocm21730311-2384
lsdi/diesel/lts_new/ocm02135789-2635
lsdi/diesel/lts_new/ocm06757038-2764
lsdi/diesel/lts_new/ocm11225805-2711
lsdi/diesel/lts_new/ocn187312877-2790
lsdi/diesel/lts_new/ocm22622962-2628
lsdi/diesel/lts_new/ocm15598507-2814
lsdi/diesel/lts_new/ocm13389778-2701
lsdi/diesel/lts_new/ocm15529638-2728
lsdi/diesel/lts_new/ocm15866621-2369
lsdi/diesel/lts_new/ocm22594424-2724
lsdi/diesel/lts_new/ocm24179707-2730
lsdi/diesel/lts_new/ocm13315353-2629
lsdi/diesel/lts_new/ocm22623020-2647
lsdi/diesel/lts_new/ocm15814782-2519
lsdi/diesel/lts_new/ocm22597061-2801
lsdi2/ocm05040011-2296
lsdi/diesel/lts_new/ocm22622890-2348
lsdi/diesel/lts_new/ocn187989625-2993
lsdi/diesel/lts_new/ocm13339889-2301
lsdi/diesel/lts_new/ocm15554707-2290
lsdi2/ocm01146882-2542
lsdi/diesel/lts_new/ocm03036846-2399
lsdi/diesel/lts_new/ocm57420208-3043
lsdi/diesel/lts_new/ocn422578895-2288
lsdi/diesel/lts_new/ocm15363206-2586
lsdi/diesel/lts_new/ocm52420904-2664
lsdi2/ocm04308983-2736
lsdi2/ocm03339111-3041
lsdi/diesel/lts_new/ocm22105442-2740
lsdi/diesel/lts_new/ocm11558691-2583
lsdi/diesel/lts_new/ocm22105142-2734
lsdi/diesel/lts_new/ocm22442260-2752
lsdi/diesel/lts_new/ocm15057387-2767
lsdi/diesel/lts_new/ocm22622974-2630
lsdi/diesel/lts_new/ocm09414504-2779
lsdi2/ocm04525438-2789
lsdi/diesel/lts_new/ocm15298482-2385
lsdi/diesel/lts_new/ocm22617449-2594
lsdi/diesel/lts-new/ocm36200326-2665

**Comment by jcrompton42** [comment]
Transferred all but the very last, lsdi/diesel/lts-new/ocm36200326-2665 does not exist. Further instructions?

**Comment by kmichaelis** [comment]
lts-new should be lts_new

**Comment by jcrompton42** [comment]
I could maybe have realized that from looking at any of the file paths above it. :headdesk:. All of these are transferred now.

**Comment by kmichaelis** [comment]
Thank you!
