### ISSUE TITLE
Build out Curate test environment in aws@emory account

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#228]
- [x] Build fedora-test in aws@emory account
- [x] Build util-test/solr environment in aws@emory account
- [x] Add security hardening from #241

**Comment by tmiles2** [comment]
@SolomonHD Can you provide and update on the IIIF server, time frame to complete?

**Comment by SolomonHD** [comment]
Removing IIIF references and making that into it's own ticket.
