### ISSUE TITLE
Transfer another batch of GA House and Senate Journals to EFS

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2282]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm06095504-3664
lsdi/diesel/lts_new/ocm13429979-4260
lsdi2/ftp/010000354603
lsdi2/ftp/010000667542
lsdi2/ftp/010001214317
lsdi2/ftp/010002426099
lsdi2/ftp/010002426100
lsdi2/ftp/010002426101
lsdi2/ftp/010002483453
lsdi2/ftp/010002483454
lsdi2/ftp/10002335799
lsdi2/ftp/10002335800
lsdi2/ftp/10002335805
lsdi2/ftp/Ga.House1880
lsdi2/ftp/Ga.House1881
lsdi2/ftp/Ga.House1891
lsdi2/ftp/southernimprints/10002350169
lsdi2/ftp/southernimprints/10002350171
lsdi2/ftp/southernimprints/10002350463
lsdi2/ftp/southernimprints/10002350464
lsdi2/ftp/southernimprints/10002350465
lsdi2/ftp/southernimprints/10002350466
lsdi2/ocm06095483-3561
lsdi2/ocm06095483-3566
lsdi2/ocm06095483-3570
lsdi2/ocm06095483-3571
lsdi2/ocm06095483-3576
lsdi2/ocm06095483-3580
lsdi2/ocm06095483-3582
lsdi2/ocm10472399-4244

**Comment by libah** [comment]
Files have been transferred.

**Comment by libah** [comment]
complete

**Comment by libah** [comment]
Files have been transferred.

**Comment by libah** [comment]
Files have been transferred.
