### ISSUE TITLE
Test Solr Cluster

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#229]
- [x] Test adding json data to solr, data should replicated through cluster
- [x] Test ingest job

**Comment by tmiles2** [comment]
@SolomonHD @mprefer Can you update this issue?

**Comment by SolomonHD** [comment]
There wasn't really an ingest job test but collin was able to deposit to curate.library and solr cloud is displaying the results. Appears to be working fine.
