### ISSUE TITLE
Re-transfer files for one Civil War Imprint (need to re-ingest)

### ISSUE THREAD

**Issue by kmichaelis** [emory-libraries/dlp-curate#2297]
Please transfer all the following files in the following directory from Isilon "library" volume to our AWS EFS mount. Transfer all files in each directory and create directories on EFS with the structure /mnt/efs/Collections/ + relative directory structure from original Isilon location.

lsdi/diesel/lts_new/ocm22538555-4017

**Comment by jcrompton42** [comment]
transferred
