### ISSUE TITLE
Support primary vs supplemental designations for content files and supplemental preservation files 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#23]
## Story
As a Preservation Curator, I want to accommodate Emory AIP categories (Content, Metadata, Supplemental Preservation Files) but also support derivative/master delineations within content files, so that we can accommodate primary/supplemental designations for content vs supplemental preservation files as well as delineating types of file usage 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Emory AIP specification delineates the following within a preservation object package:

Files are broken down into one of three top-level categories:
* Primary Content (displays to end users)
* Supplemental Content (displays to end users)
* Supplemental Preservation Files (display to Staff/Curate users only)

Metadata
* Actionable/indexed metadata such as Descriptive, Rights, Admin

Content files' binaries can be further broken out into derivative types (see [#22](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/22)):
* Preservation Master File
* Intermediate File (high resolution access copy)
* Service File (lower resolution/watermarked access copy)
* Thumbnail (as generated by ingest process)
* Extracted Text File
* Character Positioning Data
* Transcript File

Supplemental content files and supplemental preservation files are not anticipated to have multiple kinds of derivatives, only primary content files.

#### Links to Additional Information
[Simplified top-level category structure](https://docs.google.com/document/d/1dkRefUkf8gH-ofBQiECdmTBVUtYPfUvdm0BFOIOL7xc/edit)
[PCDM Use Spec](https://pcdm.org/2015/05/12/use)
[Emory AIP and FileSet outline](https://docs.google.com/spreadsheets/d/1tEZeuUm-l0RJ3KNP55feZnbTFykBrxekxFWdrn2f8Xc/edit#gid=403514438)
[Emory AIP specification](https://wiki.service.emory.edu/display/DLPP/Archival+Information+Package+Recommendations)
[Emory AIP components diagram](https://docs.google.com/presentation/d/1FFlFKy6r-IN5K6AyRFLOraAyHFkTlJggnpymn7QaYZ8/edit#slide=id.p)

#### Checklist
- [ ] Item 1
- [ ] Item 2

#### Given/When/Then
* Given I am an authorized user with ability to create an object and I have the ability to edit all of the object's components
* When I deposit a complex digitized or reformatted object (such as a digitized book or digitized image)
* Then I can deposit different types of file derivatives (such as a TIFF with color bars and the same image without them) as part of the ingest process and sort them into the appropriate AIP category so that they then become accessible to end users or staff

**Comment by rotated8** [comment]
In laevigata, this is facetable, but not searchable. Is this correct for curate as well? More broadly, how should this property be indexed?

**Comment by tmiles2** [comment]
@eporter23 Can this epic be closed?

**Comment by eporter23** [comment]
@rotated8 I see there's an open comment you posted a while back about indexing - do you still need a response on this?

**Comment by rotated8** [comment]
Only if you want it changed from what is mentioned above.

**Comment by eporter23** [comment]
I hadn't considered indexing needs for this. It might be of interest to be to run reports on later so indexing it could be useful. If indexing can be added later without too much trouble this can wait. If it is recommended to set it up now, let's go ahead and index it.

**Comment by tmiles2** [comment]
@rotated8 Any thoughts on Emily comments above? We need some feedback before closing out this epic.

**Comment by eporter23** [comment]
@rotated8 @tmiles2 I'm going to close the epic out, but make a note to revisit indexing needs in a different release if needed.
