### ISSUE TITLE
AWS at Emory Configuration 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#233]
The infrastructure strategies chosen by the Digital Library Program (DLP) project should address the repository’s needs around servers, storage and databases. In particular:

• Servers need to support multiple memory-intensive applications including Apache (or another web server), multiple Ruby on Rails apps (and the middleware connecting them to the web server), Solr, Fedora, Redis, Cantaloupe (or another IIIF server), Sidekiq (or another background job queuing system), etc.
• Storage concerns include the ability to expand past 200 Terabytes, in order to store all our current and planned collections, and to share files with the Rails applications, the background jobs server, and the IIIF server. 
• Database options must address the needs of the Rails applications and Fedora.

In addition to the servers and applications, the environment hosting the DLP applications should support the server and application configuration necessary to securely fulfill DLP’s primary functionality.

 **AWS at Emory Security Review:**
_We've been asked to complete two check points with the security team._
- During the initial build of the environments
- A review of the production environment

**Comment by SolomonHD** [comment]
Removing Lux from the Epic.
