### ISSUE TITLE
Build out ELB in the AWS at Emory account  

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#239]
- [x] Build ELB with proper routing to Solr and other instances
- [x] Test out the routing

**Comment by SolomonHD** [comment]
We finally got the F5 working with help from Sheldon Anderson and Paul Petersen.

We can now reach our vip which is dlp.aws.emory.edu (Must be on VPN to reach)

It routes to an instance behind the cor-f5 ELb.
