### ISSUE TITLE
Create service accounts for Fedora and Fedora test 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#240]
- [x] Create and name target buckets for Fedora data 
- [x] Generate the policies for respective service users   
- [x] Use VPCP console to request the service users 
- [ ] Test out the credentials once received

**Comment by SolomonHD** [comment]
Submitted two tickets for the creation of the two Fedora s3 user's the project requires. The incident numbers are:
INC03164874
INC03164868

Moving this ticket to blocked until we have the user credentials

**Comment by SolomonHD** [comment]
Received the two accounts from Paul Petersen

**Comment by tmiles2** [comment]
Closing out this issue to create a new issue for testing the service account with S3
