### ISSUE TITLE
Date Validation Epics - Testing Revisions

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#257]
Test outcomes against [date use cases and EDTF entries](https://docs.google.com/document/d/1A9hMl1ZNDbN2J4q77_6ixvq_wVW4gFJtxK-nnZKo5Tc/edit#) for epics #77 and #78 and #148, related to tickets #140 and #92:

Tested a variety of use cases on [this sample work](https://curate-test.library.emory.edu/concern/curate_generic_works/9k41zd48h?locale=en).

1. Date Created/Unknown entry
Form accepted X, XX, XXX, and XXXX. What are we requiring for a completely unknown date? The acceptance criteria is to require an entry is supplied here, but either A) store an unknown date in a machine readable way or B) allow the user to indicate the date is unknown, but not actually store any value.

![Screen Shot 2019-06-14 at 1.07.26 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0a1c32b9-4d14-4df5-befb-8c9a05b0c6a9)

2. Form accepts dates entered with less than 4 digits (should be at least YYYY)

![Screen Shot 2019-06-14 at 1.20.18 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/39be8ca4-f685-4c53-85bf-cf2eb3857320)

3. Data Collection Dates entered also get added to Subject - Time Periods
I entered two date ranges, followed by a 3-digit entry to try prompt validation. The form accepted the entry, but then displayed a copy of the date ranges entered in Subject - Time Periods along with a blank row under each of them where I'd added the bogus 3-digit entry.
![Screen Shot 2019-06-14 at 1.41.53 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/d14e87fc-b773-49e5-8868-750566a257f0)

4. Date issued, Copyright date, Scheduled rights review, Date digitized - form accepted a date range value, but technically this is supposed to be a single date only. Very low priority to revise.

5. Conference Dates, Data Collection Dates - form accepted single dates here, but were supposed to be date ranges. Also a very low priority to revise.

**Comment by eporter23** [comment]
@zo I think #4 and #5 probably don't need to be revised, because more flexibility is good in general, but just wanted to note those results in case it was significant.

**Comment by rotated8** [comment]
Talked to @eporter23, and for 1 we can add a before_save filter that takes an entry of any number of x-es and makes it 'XXXX'.

**Comment by eporter23** [comment]
Additional test notes on Date Created and Date Issued - they seem to be accepting arbitrary string values. ![Screen Shot 2019-06-19 at 11.27.37 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/df1487c7-4ae7-4eff-b5a4-cdf3927666a3)![Screen Shot 2019-06-19 at 11.27.51 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e0d6761a-b130-4c63-b405-2c43576755ca)![Screen Shot 2019-06-19 at 11.28.47 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/3b091013-8c61-4c02-ba2d-ce51e9c9d533)![Screen Shot 2019-06-19 at 11.29.33 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/9b389570-2f1e-4237-bd4e-71681ba7e4c2)
