### ISSUE TITLE
Establish hosting location (AWS/other)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#26]
Discussed at 12/12 release planning meeting for 0.1

This may involve producing a [Decision Document](https://emory.box.com/s/jm6vona6fda4vlmjlrzk78hat0rvdrqt)

**Comment by rotated8** [comment]
@tmiles2 I'm working on finishing the decision doc today.

**Comment by eporter23** [comment]
Update 2/13: @rosy1280 is revising based on updates from @tmiles2 on Emory at AWS timeline.

**Comment by eporter23** [comment]
Confirmed with @rosy1280 and @tmiles2 that we will aim to finalize this closer to our production launch, pending Security Review and ongoing Emory AWS projects. Changed release goal to 0.8.

**Comment by eporter23** [comment]
5/16/19: ART Review and Cloud Steering approved our recommendation to launch in AWS@Emory and move to the CIM environment long term.
