### ISSUE TITLE
Ability to add multiple filsets through the form

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#260]
- [x] Repeat `form_files` so that user can add multiple filesets through the form
- [x] Add field to every fileset for user to select if it is primary or supplementary
- [x] Edit job to save fileset primary/supplemental selection
- [x] Edit job test so that multiple filesets can be created each with multiple files
- [x] Add feature test for adding multiple filesets through the form

**Comment by tmiles2** [comment]
@devanshu-m do you have an estimate for this work?

**Comment by tmiles2** [comment]
@devanshu-m Or did we decide not to add one because of the remaining work?

**Comment by devanshu-m** [comment]
@tmiles2 I should hopefully have a PR in for this by Monday afternoon. I started working on it early this week.

**Comment by tmiles2** [comment]
@devanshu-m then can you put an estimation on how long it took you to complete the work? Here's the estimation description https://emory.app.box.com/notes/438779928854
