### ISSUE TITLE
Determine environments strategy (dev, QA, prod)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#27]
Discussed in release planning meeting 12/12 for 0.1

May result in a Decision Document, especially regarding dev environment

**Comment by rotated8** [comment]
Chart: https://www.lucidchart.com/invitations/accept/3e145326-5d57-40ed-8d51-0df802f3bcc1

Prod: 
![production](https://user-images.githubusercontent.com/638392/51559766-cf8f4200-1e50-11e9-8d93-186b6dce773f.png)

Test:
![qa](https://user-images.githubusercontent.com/638392/51559773-d61db980-1e50-11e9-9a84-e91d23665b0e.png)

**Comment by rotated8** [comment]
These charts exist in place of a decision doc.
