### ISSUE TITLE
Configure NOID for our identifier pattern 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#271]
See also epic #206 for where to store the metadata in the Curate metadata profile for Objects, Collections, File/FileSets.: the Primary Repository ID field.

**Comment by devanshu-m** [comment]
https://github.com/emory-libraries/dlp-curate/blob/master/config/initializers/hyrax.rb#L76

**Comment by rotated8** [comment]
This may require coordinating with Mark and Solomon, to ensure Fedora is emptied after this change.
