### ISSUE TITLE
Generate Blacklight skeleton app for Lux

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#272]
Current plan is to transfer digital.library to `aws@emory` account first, due to blacklight's relative simplicity vs hyrax, but our dlp-lux repo doesn't have an app in it yet. I believe if you follow the instructions here it will create a skeleton app. 

https://github.com/projectblacklight/blacklight/wiki/Quickstart

- [ ] Generate skeleton application and push it to dlp-lux

Optional: Add some Emory branding.

**Comment by eporter23** [comment]
@SolomonHD @nikdragovic for now, probably better to not try to brand it yet and just have the out of the box UI.
