### ISSUE TITLE
Provision servers

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#28]
Discussed in 12/12 release planning meeting for 0.1

**Comment by SolomonHD** [comment]
- [ ] Gain access to Lib/DCE AWS account
- [ ] Create AWS Access codes and secret key for Middleware
- [ ] Provision new Elastic IPs
- [ ] Build servers with EIPs

**Comment by tmiles2** [comment]
@mprefer Is this issue still blocked, if so how I don't think the environment is still a question.

**Comment by SolomonHD** [comment]
util-cor-test.library.emory.edu, curate-test.library.emory.edu, fedora-cor-test.library.emory.edu have all been created in ec2.
