### ISSUE TITLE
Investigate Logging Hyrax Events

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#281]
- [x] Work creation
- [x] Fileset creation
- [x] File persisted
- [ ] Characterization
- [ ] Virus check

**Comment by tmiles2** [comment]
Move this to the next sprint

**Comment by rotated8** [comment]
Work creation: after the create_work job is successful: https://github.com/samvera/hyrax/blob/master/app/jobs/create_work_job.rb#L21

Fileset creation: after the fileset is saved: https://github.com/emory-libraries/dlp-curate/blob/master/app/actors/hyrax/actors/file_set_actor.rb#L26

File persisted: in the attach_file_to_work job: https://github.com/emory-libraries/dlp-curate/blob/master/app/jobs/attach_files_to_work_job.rb#L55

Characterization: in the characterization job: https://github.com/samvera/hyrax/blob/master/app/jobs/characterize_job.rb#L12

Virus Check: after the checker service runs: https://github.com/samvera/hyrax/blob/addb09f382feb86ab32f937d1c41feaf8d7a1537/app/models/concerns/hyrax/virus_check.rb#L14
