### ISSUE TITLE
Technical Metadata Properties

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#282]
- [ ] Find where technical md lives and what the characterization job does
- [ ] Working with the Technical MD spec in the epic, add the fields to the File or FileSet model.

**Comment by tmiles2** [comment]
@devanshu-m What did you complete for this issue? I see it's closed but there are no details to associate with the completed work.

**Comment by devanshu-m** [comment]
@tmiles2 I submitted PR #299 for this which adds technical metadata to our schema and also changes original_file to preservation_master_file for characterization.
