### ISSUE TITLE
Technical Metadata Extraction

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#283]
Ensure the Characterization Job adds all the appropriate technical metadata to the File

**Comment by tmiles2** [comment]
@devanshu-m Who's testing this issue?

**Comment by devanshu-m** [comment]
I guess @eporter23 ? I can also do some tests.

**Comment by tmiles2** [comment]
Ok @devanshu-m 
@eporter23 please test if possible

**Comment by eporter23** [comment]
Preliminary testing for [images](https://docs.google.com/document/d/1YFlg5KGxjrzW1Fxjh4JgOEhHOb2OKy9tnd6H_iZB9Uo/edit?usp=sharing) and [text documents](https://docs.google.com/document/d/1B3FjPVNZlnhfFqx4yB4ClRHOz7CXkTLtbPvhywX99Iw/edit?usp=sharing) all look good.

**Comment by eporter23** [comment]
@devanshu-m looks great! There are a few properties that I have [flagged on this sheet](https://docs.google.com/spreadsheets/d/1csDcDnJdhB1VLlgJUU95DndXSeIP2j8yPMlErrsVVPw/edit#gid=1836172006) in yellow that I want to follow up on which I am not seeing in my test samples: PUID, file path, charset. There are a few other things I wanted to confirm also.

**Comment by eporter23** [comment]
I created a revision ticket for the one missing property which is PUID.
