### ISSUE TITLE
Install base Hyrax for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#29]
Discussed in 12/12 release planning meeting for 0.1

- [x] Determine how the 3.0 beta testers are installing the beta.
- [x] Generate a new Hyrax app (without a model) using their method.
- [x] Push to this repo
- [ ] Add Solomon's updates to the app

**Comment by tmiles2** [comment]
@devanshu-m Did you complete this work? I know we were looking to complete it today.

**Comment by devanshu-m** [comment]
@tmiles2 PR #46 is blocking completion. The PR is currently under review and changes were requested.

**Comment by tmiles2** [comment]
@devanshu-m ok I added it as a blocker
