### ISSUE TITLE
Create a larger file upload space 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#295]
Establish a large enough temp/scratch space for uploaded files, for both manual file uploads through the form and the for DCE's bulk ingest method.
Determine options
See #204 for acceptance criteria

**Comment by SolomonHD** [comment]
@rotated8 Is this referring to the UPLOAD_PATH env variable found in curate's dotenv?

**Comment by rotated8** [comment]
Yes, this ticket would add more space to the storage attached to that path.

**Comment by mprefer** [comment]
Increased root EBS file space from 14G to 50G on both curate and curate-test.
Created 'uploads' folder on the EFS mount, with a symbolic link such as:
/opt/uploads -> /mnt/efs/uploads.
This should cover any temporary space used and the final destination of uploaded files prior to processing and deposit into  S3.
