### ISSUE TITLE
Investigate Cleanup of UI Upload File Storage

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#296]
Establish a method to periodically purge the temp space to clear out storage used when users use the form to upload files.
This method can we a ruby call inside the app or a bash cron script

- [ ] Confirm which directories need to be purged with Collin
- [ ] Write bash script, or ruby call that purges target directories
- [ ] Persist script through rebuilds via Ansible

Determine if there is a configuration where uploads go: noting certain subdirectories only. Recommend there be an ongoing job that clears out things that are older than a month.
Make sure we don't delete uploads such as Collection banner images and derivative regenerations.

Update 8/26/20: we also need to confirm and approve the retention schedule drafted in ticket #1396.

**Comment by mprefer** [comment]
@rotated8 Can you supply the directories that will need periodic cleanup, and should there be any restrictions, such as age of file?

**Comment by tmiles2** [comment]
@eporter23 can you supply the directories that Mark P. needs since Collin is out?

**Comment by eporter23** [comment]
@tmiles2 unfortunately, no, I don't have those details

**Comment by eporter23** [comment]
Determine if there is a configuration where uploads go: noting certain subdirectories only. Recommend there be an ongoing job that clears out things that are older than a month. 
Make sure we don't delete uploads such as Collection banner images.

**Comment by eporter23** [comment]
Other considerations: ensure that any files needed for background jobs are available

**Comment by libdgg** [comment]
@rotated8 and @eporter23 can you review/respond to this and the idea to use the whenever gem for clean up.

**Comment by eporter23** [comment]
Closing this because Solomon created an AWX job that does some of this, prior to his leaving in Feb. It has been running without issues for about 6 months. We should create new tickets for anything that comes up in the future.
