### ISSUE TITLE
IIIF/Cantaloupe server build and integration

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#297]
- [x] Build out any IIIF server needed for curate in aws@emory
- [ ] Integrate into code of curate prod and test

**Comment by SolomonHD** [comment]
@rotated8 The servers have be built and they're at https://util-cor-test.library.emory.edu/cantaloupe/
and https://util-cor.library.emory.edu/cantaloupe/

**Comment by tmiles2** [comment]
@rotated8 are you going to do some testing on this, is that the next step?

**Comment by eporter23** [comment]
in 7/22 sprint planning we broke out a separate ticket for curate/code integration
