### ISSUE TITLE
Address monitoring and alerting on events 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#311]
*Task provided by Steve Collins

**Comment by eporter23** [comment]
@tmiles2 I spoke to Steve Collins today about possibly bringing this up in the queue given recent downtime issues

**Comment by tmiles2** [comment]
@eporter23 Sounds like a good idea, especially if we don't currently have measures in place.

**Comment by SolomonHD** [comment]
Closing an old ticket
