### ISSUE TITLE
View work page error when filesets attached

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#319]
As of testing on 7/19 and 7/22, the majority of filesets created and uploaded through the UI returns an error when trying to view a work. This may be related to epic #119 (Edit AIP/Filesets)

Was "Files and Filesets are not attached to works created through Curate UI" : Revised after retesting in Fedora navigating tree through ns006: hasMember instead of children: members. All works contain FileSets, and all FileSets appear to contain files.

**Comment by eporter23** [comment]
I looked at this in a little more detail with @devanshu-m this morning - I may have been looking in the wrong tree path in Fedora and wasn't getting to the FileSet child correctly. We will re-confirm if FileSets and Files are getting attached.

**Comment by eporter23** [comment]
@devanshu-m I retested all the prod links in Fedora. All works seem to have filesets which have files. I rescoped this ticket to focus on the view work error.

**Comment by rotated8** [comment]
After moving back to standalone Solr, and fixing upload/derivative/etc paths, this appears to be fixed, pending #355 getting merged.

**Comment by eporter23** [comment]
@rotated8 closing because I think this is fixed.
