### ISSUE TITLE
View FileSets from a Work or a Fileset Page

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#322]
See epic #119. The general goal is to see a listing of all the files assigned to a FileSet.

The mockup lists the FileSet's files - but we can also adjust this to show a listing of files from the view FileSet page instead of from the View Work page: https://curate.library.emory.edu/concern/parent/c534fn92g/file_sets/b2773v68h

[Mockup - see all attached files from View FileSet page](https://docs.google.com/drawings/d/1CXdEhXmj73Yt1xsd2h_aeQE-7EtLcVghztkTHv19Z8s/edit)

**Comment by tmiles2** [comment]
@devanshu-m Do you have an estimation for this work?

**Comment by eporter23** [comment]
@devanshu-m clarifying: this is new work related to #119, the ability to see the different files attached to each file set from the View Work page.

**Comment by devanshu-m** [comment]
Thank you @eporter23 

@tmiles2, I have put an estimate for the ticket
