### ISSUE TITLE
Add additional Files to a File Set

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#323]

**Comment by rotated8** [comment]
@eporter23 Is this for adding files while editing a fileset, or while editing a work?

**Comment by eporter23** [comment]
@rotated8 this is for while editing. (epic #119)

**Comment by eporter23** [comment]
I'm consolidating some duplicative and possibly confusing tickets for 119. I'm closing this one and rewriting a combined ticket for a UI to add/change/delete files from an existing fileset that has already been attached to a work.
