### ISSUE TITLE
Add or Change a Title/display label for an existing FileSet

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#328]

**Comment by eporter23** [comment]
Tested this by viewing an existing work, opening a File Set to edit it, and replacing the default the Title using the Hyrax basic Edit FileSets form.![Screen Shot 2019-08-12 at 9.26.13 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/78df12b6-51d6-4ea3-89fe-9e9ed3da19d7)
