### ISSUE TITLE
Add/Change/Delete Files from an existing FileSet

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#329]
For epic #119, we need a user interface to change files assigned to an existing FileSet after it is created.

#### Links to Additional Information
[Mockup for editing FileSets already attached to a work](https://docs.google.com/drawings/d/11wjr5PuMNjIArFCaXNoTbdPY1_r__XuEFv_Ezd3eWHQ/edit) 
[Hyrax - basic file management](https://samvera.github.io/edit-works-2.0.html#editing-a-work---file-manager)
[Hyrax - Edit File and File Manager Forms: Screenshots](https://docs.google.com/document/d/1acUwZMgG5RgWc6M2FA60Pyxb0dENXU4v4TLiv_Ja-0U/edit?usp=sharing)

#### Checklist

- [ ] Add another file to an existing FileSet
- [ ] Change/replace a file for a given File Use within an existing Set
- [ ] Delete a File from an existing Set
- [ ] Ensure that a Preservation Master file is still assigned
- [ ] If the Preservation Master file is changed, characterization should be re-run
- [ ] The FileSet's thumbnail should be updated relative to the prioritization of how thumbnails are generated - see ticket #411

**Comment by eporter23** [comment]
Closing this as a partial duplicate with #324.
