### ISSUE TITLE
Install background workers

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#33]
Discussed in 12/12 release planning meeting for 0.1

**Comment by SolomonHD** [comment]
- [ ] Install Redis on utility server
- [ ] Test Redis install

**Comment by SolomonHD** [comment]
We can't test Sidekiq until it's written into the code of the app. Let's put that in a separate ticket.

Same for evaluating elasticache, I'm going to make a separate ticket for that.

**Comment by SolomonHD** [comment]
Testing this ticket should simply be going to curate-test.library.emory.edu, the app needs redis to run.

**Comment by tmiles2** [comment]
@eporter23 @rotated8 Please see Solomon comments above
