### ISSUE TITLE
Delete a FileSet from a work (but at least one FileSet needs to exist)

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#331]
To test:

- [ ] Create a work with more than one fileset; select one of the FileSets and use one of Hyrax's standard "Delete" options to remove it
- [ ] Try to remove the remaining FileSet and see what occurs

**Comment by eporter23** [comment]
Curate allowed me to delete all three FileSets that were attached to this work. This was not what I was expecting. 

![Screen Shot 2019-08-13 at 4.32.18 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/294df235-8711-4c4e-aebe-dc9c73234214)

**Comment by eporter23** [comment]
@devanshu-m @rotated8 I've been testing this and it seems that Curate will let me delete all the FileSets from a work. Is this expected? The original requirement was that we had to have at least one FileSet for each work.

https://curate.library.emory.edu/concern/curate_generic_works/cor-416c2fqz69?locale=en

**Comment by devanshu-m** [comment]
@eporter23 We haven't worked on any deletion yet. Is this normal Hyrax behavior?

**Comment by eporter23** [comment]
I tested this in Nurax, and saw the same behavior.

**Comment by eporter23** [comment]
@devanshu-m @rotated8 @alexBLR I'm going to close this ticket out since it was mainly for testing, but it's something we can revisit later in development when we look at Delete activities.
