### ISSUE TITLE
Added DCE to our admins.yml file 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#336]
DCE is getting an error on Emory's test servers,“Could not authenticate you from Shibboleth because "you aren't authorized to use this application ( Mark,Bess, Jamie)

**Comment by mark-dce** [comment]
@mark-dce Can you check if you can login now?

**Comment by mark-dce** [comment]
Works great!

Need to confirm this works for everyone on the DCE side:

- [x] @mark-dce 
- [ ] @bess 
- [ ] @little9 
- [ ] @rachel-dce

**Comment by tmiles2** [comment]
@SolomonHD Can you add Rachel to the admin file, if you haven't done so. NetID is: RLYNN3

**Comment by SolomonHD** [comment]
Rachel's been added to curate and curate-test
