### ISSUE TITLE
TKI documentation 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#342]
- [x] How to install TKI 
- [x] How do we install Solomon TKI scripts
- [x] How to deploy 
- [x] Post a link to the documentation in this issue and in box

**Comment by tmiles2** [comment]
@SolomonHD is this ticket completed?

**Comment by SolomonHD** [comment]
https://wiki.service.emory.edu/display/DLPP/Install+TKI+Client+and+Connect+to+DLP+EC2s

**Comment by alexBLR** [comment]
worked for me @SolomonHD

**Comment by tmiles2** [comment]
@bess Tagging you in the ticket. I know you mentioned you wanted to test this process.

**Comment by bess** [comment]
I was able to get this working with @SolomonHD's help. Looks good!
