### ISSUE TITLE
Add additional FileSets to an existing work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#343]
Ability to add more FileSets to a work that has already been created (part of epic #119)

**Comment by eporter23** [comment]
@tmiles2 @devanshu-m @rotated8 I added this issue as one more aspect of epic #119 acceptance criteria (editing/managing FileSets)

**Comment by rotated8** [comment]
With the work show page running again, this works for me. I can visit the work edit page, go to the files tab, and add new filesets.

**Comment by eporter23** [comment]
Closing since we agreed the basic Hyrax functionality (albeit clunky) works for now.
