### ISSUE TITLE
Temporarily Replace Solr Cloud with a single Solr Instance

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#346]
- [x] Non-cloud Solr instance is available at solr-cor.library.emory.edu
- [x] Non-cloud Solr instance has dlp-curate's Solr config applied

**Comment by SolomonHD** [comment]
new instances have been built at util-cor.library.emory.edu and util-cor-test.library.emory.edu

cantaloupe has been moved to iiif-cor.library.emory.edu and iiif-cor-test.library.emory.edu

curate and curate-test have both been changed to point to util
