### ISSUE TITLE
Configure Solr Cloud shard leaders

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#347]
- [x] Solr Cloud always uses the same instance for each shard's leader. 
- [x] Deploy new configuration to solr-cor-test.library.emory.edu

**Comment by tmiles2** [comment]
@mprefer how's this ticket coming, is it completed?

**Comment by mprefer** [comment]
Deleted the replica leader in each shard, then added a new replica, forcing an election for a new leader. This was ineffectual.
Solomon is in process of rebuilding the SolrCloud with 1 shard, 3 replicas per advice from Michael Klein.
