### ISSUE TITLE
Preview selected metadata from View Work page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#356]
## Story
As a Library Staff Depositor or Metadata Specialist, I want to preview selected metadata fields from the View Work page for an object, so that I can quickly assess if key metadata has been populated or migrated for a work without having to edit it

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
(Requested to support DCE migration work) As we are starting to load data into Curate, we need to expand the Hyrax default set of fields that are displaying on the View Work page. 

During migration, we should display all fields temporarily until migration QA is complete. 

Long-term, some metadata should only be visible to those with Edit/Sharing permissions for the work (epic #19), which can be addressed in 0.5.

#### Links to Additional Information
[Mockup of field display](https://docs.google.com/drawings/d/1CZj7ucVW-2Nig3PH96EmxrOWwgOAQP81bzFqds425Ac/edit)
[Metadata Implementation - Objects](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589) - see the Displays To column, Curate Form Order column, and Display Label column

#### Checklist
- [x] Fields are displayed using the field labels identified for the create/edit form, followed by the field values (see the Curate Form Order column)

Deferred items (0.5 release) - see epic #462

* View work page does not display any fields that are categorized in the Displays To column as Staff Only
* View work page displays all fields that have been populated for a work which are categorized as Displays To: End Users and Staff
* [Filtered view of fields to add to View Work display](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=1722653369)

**Comment by eporter23** [comment]
@little9 Jamie, I removed the "To confirm" notes here and also indicated things that will be addressed in a later release, so that I can make a new epic for them later. Let me know if you have questions...

**Comment by eporter23** [comment]
I de-scoped some of the acceptance criteria to a later enhancement story, based on our joint sprint meeting 8/13/19.

**Comment by tmiles2** [comment]
@eporter23 Should this epic be captured in 0.4 on the release testing document?
