### ISSUE TITLE
Fedora S3 connection - confirm performance characteristics

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#357]
Note: A/I from the DCE Infrastructure meeting

**Comment by eporter23** [comment]
@tmiles2 @SolomonHD can we close this one? This goes back to July.

**Comment by tmiles2** [comment]
@eporter23 I think so but I'll let @SolomonHD confirm.

**Comment by eporter23** [comment]
Discussed with team 7/29/20 - marked as closed.
