### ISSUE TITLE
Investigate direct connection of Cantaloupe to S3 (vs. Http through fedora) for file access

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#358]
**ACCEPTANCE**
Give an image stored in S3 with a known identifier - e.g. `test_image.jpg` or `98310afc.tiff`
- [x] I can request that image via the standard cantaloupe [IIIF 2.1 Image API](https://iiif.io/api/image/2.1/) e.g.
    * https://imageserver.library.emory.edu/cantaloupe/iiif/2/test_image/full/full/0/default.png
    * https://imageserver.library.emory.edu/cantaloupe/iiif/2/98310afc/full/full/0/default.png
- [x] I can request different file formats using the `.png`, `.jpg`, `.tif` suffixes (per the [API format specification](https://iiif.io/api/image/2.1/#format))
- [x] I can scale the image to 15% of full size using the `pct:15` (per the [API size specification](https://iiif.io/api/image/2.1/#size))
- [x] Cantaloupe requests the file directly from S3 (i.e. not via a request through fedora)

**Comment by tmiles2** [comment]
Note: A/I from the DCE Infrastructure meeting

**Comment by SolomonHD** [comment]
Images in S3 Bucket

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/92af2a2e-0a84-419d-8f70-95639f736418)

**Comment by SolomonHD** [comment]
Links to images being server by Cantaloupe(Requires VPN):

https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/beauty-bloom-blue-67636.jpg/full/,100/0/default.png

https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/2020-supra-launchedition-01-1547310229.jpg/full/full/0/default.png

https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/MARBIBM.TIF/full/full/0/default.png

**Comment by SolomonHD** [comment]
Configurations Changed:
Mostly in cantaloupe.properties
```
source.static = S3Source
source.delegate = false
S3Source.endpoint = s3.us-west-1.amazonaws.com
S3Source.access_key_id = FEDORA USER ACCESS KEY
S3Source.secret_key = FEDORA USER SECRET KEY
S3Source.max_connections =
S3Source.lookup_strategy = BasicLookupStrategy
S3Source.BasicLookupStrategy.bucket.name = fedora-cor-test-binaries
S3Source.BasicLookupStrategy.path_prefix = Images/
```

**Comment by mark-dce** [comment]
Awesome!

I can do crazy things like this https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/MARBIBM.TIF/full/,500/90/gray.png
![image](https://user-images.githubusercontent.com/3064318/62897898-c9dc4980-bd19-11e9-8e5b-13e995c5d47f.png)
 
and this https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/beauty-bloom-blue-67636.jpg/pct:30,0,70,100/250,/45/default.png 
![image](https://user-images.githubusercontent.com/3064318/62898887-2fc9d080-bd1c-11e9-9b0b-ae3deee90096.png)
