### ISSUE TITLE
Establish Administrator user group for Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#36]
Discussed in 12/12 release planning meeting for 0.1

- [ ] Add Emily (eporter@emory.edu)
- [ ] Confirm additional members to add: Nik Dragovic, Alex Cooper, Cari Lovins, Collin Brittle

**Comment by devanshu-m** [comment]
These links might help for this ticket:

https://github.com/samvera/hyrax/wiki/Making-Admin-Users-in-Hyrax

https://github.com/samvera/hyrax/wiki/Setting-up-test-app-for-workflow

**Comment by rotated8** [comment]
Per discussion, beginning group will be Emily, Nik, Alex Cooper, Cari Lovens, and myself.

**Comment by eporter23** [comment]
2/4 - discussed using temporary account passwords/database authentication for now until we connect them to Shibboleth

**Comment by tmiles2** [comment]
Is @eporter23 testing this @devanshu-m?

**Comment by devanshu-m** [comment]
@tmiles2 No, I guess this ticket is more for the software engineering team to look at and comment for changes if necessary. PR is here: https://github.com/emory-libraries/dlp-curate/pull/73
