### ISSUE TITLE
Complete scrum team review of the security assessment 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#363]
Document can be found in Box https://emory.app.box.com/file/528500401683

**Comment by rotated8** [comment]
@tmiles2 We need to review this with Solomon and Mark. This affects them more than Software Engineering.

**Comment by mprefer** [comment]
Printed the security assessment form and will peruse it.

**Comment by tmiles2** [comment]
I've added a task in box for all AWS users to read the Rules of Behavior.

**Comment by tmiles2** [comment]
@mprefer I uploaded a new version of the document to box as the old one had several margin issues. I also incorporated your comments into the migration section. I've identified risks that have been reviewed and migrated with "completed". Anything your still looking into I noted that with "investigating" or "need to confirm". I'm going to setup some time for us to go over the document tomorrow.

**Comment by tmiles2** [comment]
I met with @mprefer today to review the security assessment document, identified risks that require further investigate into the remediation and documented work to implement others. All of those items are captured in issues: #607, #608, #609 and #610.
