### ISSUE TITLE
Add Rachel as Admin in AWS@Emory 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#364]

**Comment by tmiles2** [comment]
Rachel logged into her sponsored account and attempted to set up VPN access, but was denied access.

After logging in this message appears: 
Users must now register with the University Service Desk to gain access to the VPN. Please call 404-727-7777 for assistance.
Click here to continue…(then)
The session reference number:  b1311b35
Access was denied by the access policy. This may be due to a failure to meet access policy requirements.
If you are an administrator, please go to Access Policy >> Reports : All Sessions page and look up the session reference number displayed above.

**Comment by rotated8** [comment]
Added as an AWS admin

**Comment by tmiles2** [comment]
As of 8/1 Rachel can successfully log into the VPN and curate-test.
