### ISSUE TITLE
Configure Shibboleth for Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#37]
Discussed in 12/12 release planning meeting for 0.1

- [x] Install Shibb SP on Hyrax  app server
- [x] Configure and test for access to Shibb (Emory QA)

**Comment by tmiles2** [comment]
@alexBLR Here's the DLP Shib form that needs to be filled out https://emory.app.box.com/file/370020430760

**Comment by tmiles2** [comment]
@alexBLR Here's the link to the approved ETD Shib request form. https://emory.app.box.com/file/194318036392

Once the DLP form is completed, let me know and I'll submit it the LITS Identity Management - The process to get approval may take 2 weeks or less

**Comment by tmiles2** [comment]
- [ ] Install Shibb SP on Hyrax  app server 
- [ ] Configure and test for access to Shibb (Emory QA)

**Comment by eporter23** [comment]
Discussed on 2/4 that we need to do a separate submission for the Lux application, but there is potential for re-use between Curate and Lux.
