### ISSUE TITLE
Subject-geographic: QA vocab no longer loads for auto-completes 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#370]
**Describe the bug**

When populating objects in the last week or so, the Subject-Geographic field no longer loads the GeoNames vocabulary. Other vocabs from LC are working.
 

**To Reproduce**
1. Create a new work or edit an existing work
2. Click on the Additional Fields button to show all fields 
3. Scroll down to to Subject - Geographic
4. Begin slowly typing a common location such as "Atlanta"
5. No values are suggested while you are typing

**Expected behavior**
When I type three or more letters, a series of suggested terms appear in a drop box beneath the field.

**Screenshots**

![Screen Shot 2019-08-01 at 1.28.16 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/14567eab-11f4-4928-9ce9-002649d4ec1f)

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Safari
 - Version 12.1.1

**Additional context**
Timing-wise, I noticed this in our AWS@emory environment. When I did acceptance testing on controlled vocabs earlier, it was in our local AWS environment.

**Comment by rotated8** [comment]
The `GEONAMES_USERNAME` is missing from the .env.production file on prod. This has been fixed temporarily, but it should be added to that file in a more permanent manner.

**Comment by mprefer** [comment]
Missing configurations for lazy suggestions added to solrconfig.xml and uploaded to Zookeeper in the solr-test environment.
Tested to see if suggestion pop-up list displays and it does.

**Comment by eporter23** [comment]
@mprefer confirmed!
