### ISSUE TITLE
Create private repo for Curate metadata loads

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#375]
Requested by DCE: can we create a private repo in the Emory Libraries organization for managing CSVs and other data files for import? This might be useful for Alma data as well.

outcomes:
- [x] Created new private repo:
https://github.com/emory-libraries/cor-data-transfer
- [x] Added various Emory Libraries teams and DCE

**Comment by eporter23** [comment]
@bess @mark-dce updates on this: 

* Rosalyn re-requested our organization to be added to GitHub Education Program, but ETA unknown
* I also have permission to upgrade our current account and can do so next week if we are still waiting on our organization transfer

**Comment by tmiles2** [comment]
@eporter23 Should we moved this into blocked?

**Comment by eporter23** [comment]
@mark-dce @bess I set up a blank new private repo for us to use for metadata ingest files.

**Comment by mark-dce** [comment]
Yay 👍
