### ISSUE TITLE
CSV ingest template should use Curate-based columns

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#385]
This will greatly simplify the mapping and QA process. 

For CSV loading, should we focus on a legacy source agnostic loading template using CSV column names that align with Curate fields, as opposed to column names from our legacy sources? 

The DAMS-exported column names are long and cumbersome, but we don't have to use them...

**ACCEPTANCE CRITERIA**
- [x] CSV ingest template should use Curate-based columns (not DAMS etc.). I.e., each CSV header should match a fieldname in Hyrax.

**Comment by bess** [comment]
Question for @eporter23 : 

The spreadsheet I'm working with has several fields that it seems we want to combine in Hyrax, e.g., `legacy_identifier`. Our software assumes we'll only have one column with a given heading. I'm going to call these `legacy_identifier_1`, `legacy_identifier_2` etc in the spreadsheet, and then they'll all get put into the `legacy_identifier` field upon import. Does that sound like an acceptable solution?

**Comment by eporter23** [comment]
@bess thanks for asking that question, I was wondering how we might approach that! That sounds like a good solution. If possible, could we walk through the revised CSV template before the next migration sprint starts?
