### ISSUE TITLE
Test basic discovery of works within Emory Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#386]
- [x] As a Repository Administrator or other registered user, I can assign works to an Emory Collection and discover them by browsing My Collections or All Collections
- [x] Discover works that have been created in my Library’s Collection by searching against indexed metadata
- [x] Verify that appropriate Visibility controls function on Emory Collections at the Collection level

**Comment by tmiles2** [comment]
@eporter23  We closed out the related epic for this issue is the ticket still valid or is there some additional testing needed?
