### ISSUE TITLE
Decide where to store migrating metadata to be mapped to Preservation Workflows in preservation log

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#389]
Relates to Preservation Log epic #242.

For human-supplied notes and rights review context related to why an object has been ingested to the repository, should this be stored in work-level metadata/RDF, at least temporarily?

This will also potentially need to be edited at the work level as noted in [Preservation UI mockups](https://docs.google.com/drawings/d/1cIJ5W9qkeGhJkOnxOvi_5fTg_5YHwhUMJB8_Z_izWPY/edit).

If we use XML for the audit trail, where and how do we store data that is migrating in from spreadsheets for Phase 1 migrations?

**Comment by eporter23** [comment]
@rotated8 I am thinking it may be fastest to put the prep. workflow metadata (human entered notes and rights info) in Work-level metadata at least temporarily.

**Comment by tmiles2** [comment]
@eporter23 @rotated8 Does this issue still need to be open now that we have #475 open?

**Comment by eporter23** [comment]
@tmiles2 this is a separate question related to how we are mapping some of our metadata during the migration, because it doesn't have a destination just yet.

**Comment by tmiles2** [comment]
@eporter23  :+1
