### ISSUE TITLE
Investigate implementation strategy for editing FileSet display order

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#391]
This ticket was created during our joint sprint goals planning with DCE: 

Assign the overall display order for content, if there are multiple FileSets:
- Investigate implementation strategy for ordering

As an investigation, we need to assess what existing Hyrax UI options may exist for changing the display order of FileSets within a work. If we bulk-import a lot of pages in a book, and the pages don't display in the correct order, there needs to be a way for users to correct the order.

For example, the Hyrax File Manager allows users to drag and drop to change display order. If the native Hyrax UI does not work with our customized FileSets, what is the best approach for us to consider for implementation?

Related links:
[Knowledge Base: Hyrax File Manager](https://samvera.github.io/edit-works-2.0.html)

**Comment by devanshu-m** [comment]
@eporter23 can you please clarify what is required in this ticket? Could this be a ticket for @wulman16 to work on?

**Comment by eporter23** [comment]
See also this Hyrax bug for 3.x: https://github.com/samvera/hyrax/issues/4054

**Comment by eporter23** [comment]
close as duplicate for separate ticket
