### ISSUE TITLE
Configure Fedora to store deposited files in S3 and complete testing 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#395]
Additional note from 8/5 joint sprint planning meeting

**Comment by tmiles2** [comment]
@SolomonHD can you update this ticket: estimate, who's it assigned to, etc?

**Comment by SolomonHD** [comment]
@tmiles2 
I'm not sure what exactly this ticket is for. S3 Fedora is working in our environment.
There was talk of helping DCE setup something similar in their environment, I assume this ticket is for that?

**Comment by tmiles2** [comment]
@SolomonHD I'd followup with @eporter23 or @rotated8

**Comment by SolomonHD** [comment]
@tmiles2 This is a duplicate ticket. I'm closing it.
