### ISSUE TITLE
Implement one sample Curate user permission group for testing

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#396]
- [ ] Create a sample permission group which is not at the Administrator level
- [ ] Create a sample Collection
- [ ] Assign permission group to a test Collection [through the UI?]

Example group info below:

Group Name: Repository Managers
Collection-level Role: Manager
Users to add: Tiffany Miles (currently has access as Registered User level)

**Comment by tmiles2** [comment]
@devanshu-m  Can you add an estimate to this issue?

**Comment by eporter23** [comment]
@devanshu-m @tmiles2 I'm adding an estimate of 2 to this and closing it. This work was completed in part through the other group setup tickets, but also was some work done to get Tiffany added for testing on 9/27.
