### ISSUE TITLE
Preview images’ content in the Universal Viewer so that I can pan/zoom images 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#398]
Partial duplicate for #384

**Comment by little9** [comment]
Right now images are displaying in UV, but Book-like arrangements of files are only displaying the first image.

**Comment by eporter23** [comment]
@little9 I've done a little testing on this book object and it is mostly working with showing a paged view of TIFs (after I reset the various Hyrax representative media fields). It is giving me an authorization error after page 2 however:

https://curate.library.emory.edu/concern/curate_generic_works/ce7a6dfb-86fb-46a2-aeba-bf66352da95e?locale=en

**Comment by mark-dce** [comment]
We broke this out into separate tickets for Pan & Zoom (this ticket) and for texting access-level based resolution restrictions [491](https://app.zenhub.com/workspaces/dlp-curate-5bf484ae4b5806bc2bf6875b/issues/emory-libraries/dlp-curate/491).

It looks like pan & zoom were handled sufficiently by #384, so I'm closing this ticket.
