### ISSUE TITLE
Automate generation of Curate Collections and Admin Set

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#403]
Script the generation of the Default Admin Set and 3 migration collection entities

- [x] Generate Default Admin Set
- [x] Generate collections using Curate's "Library Collection" type  
- [x] Generate Langmuir collection and settings - [link to metadata spreadsheet](https://docs.google.com/spreadsheets/d/1fm0vLMzcIQEBUqzKUMqkJgcE3aMhJjfnzLc3OugKLsc)
- [x] Generate Yellowbacks collection and settings - [link to metadata spreadsheet](https://docs.google.com/spreadsheets/d/1eya1X2m2QoKH7WGsuyxP5RWYPnBwPDEGo9owLAZ79eY)
- [x] Generate Yearbooks collection and settings - [link to metadata spreadsheet](https://docs.google.com/spreadsheets/d/1Hi3ypdoeJ5IQTxOEis7UFZOHBSgx7AHVlImKAx2VShE)

**Comment by eporter23** [comment]
@bess @mark-dce some clarifications are needed on some of the 3 Collections metadata values and if we need a revised CSV template for that metadata to align with the work-level CSV approach we're taking. If you're already working on this, should I focus on making sure just the required metadata is in place for Langmuir, Yellowbacks, Yearbooks?

**Comment by eporter23** [comment]
@bess should we add acceptance criteria to the effect that long-term, Collections can be edited manually in the UI?
