### ISSUE TITLE
Align Curate field names/property names vs. Lux display labels to support migration development 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#407]
Identify strategies to reduce complexity if Lux display labels are significantly different than Curate filenames/model attribute names

**Comment by rotated8** [comment]
My proposal is to change the label to be "<property name> (<Lux label>)" for properties where this is an issue.

Looking at the [labels](https://github.com/emory-libraries/dlp-curate/blob/master/config/locales/hyrax.en.yml#L117), I see two that could easily qualify for this treatment:
- [holding_repository/Library](https://github.com/emory-libraries/dlp-curate/blob/master/config/locales/hyrax.en.yml#L123)
- [content_type/Format](https://github.com/emory-libraries/dlp-curate/blob/master/config/locales/hyrax.en.yml#L125)

@bess, @mark-dce What others would you add?

**Comment by mark-dce** [comment]
👍 for this solution in general.

Looking at [the metadata](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589), I still could see some confusion arise around the following fields (some of these might be more issues for @eporter23 to chime in on):


DLP Field | Display Label | Hyrax Field/Property | Comment 
-- | -- | -- | --
Role - Grant/Funding Agency | Grant/Funding Agency | :grant | would it be clearer an more consistent to use :grant_agency
Grant/Funding Information [Note] | Grant/Funding Information | :grant_information | if I don't know this attribute exists, I might see :grant and think it's the same thing
Rights Statement [Controlled] | Rights Statement - Controlled | :rights_statement | maybe :rights_statement_id
Rights Statement [Local/Free Text] | Rights Statement | :rights_statement_text
Restrictions on Access | Access Restrictions | :access_right | maybe :access_right_text ?
Legacy Identifier | Other Identifiers | :legacy_identifier | maybe make this plural :legacy_identiierrs
Legacy ARK | Legacy ARK ID  | :legacy_ark | I don't see a separate "ARK" field, but legacy suggests there should be one - also if it's legacy, wouldn't I just put it under Legacy
Primary Repository ID | Persistent URL | :primary_repository_ID | so this would be displayed "Primary Repository ID [Persistend URL]" ?

**Comment by eporter23** [comment]
@mark-dce @rotated8 I'm not sure how much time and effort it will be to rename the Hyrax Field/Property names, so I want to tread carefully, but some of these I have found confusing as well.

If we feel it's worth investing the time, my thoughts are:
+1 to _:grant_agency_ and _:grant_information_ 

with _:rights_statement_, I believe @rotated8 ran into a number of hard-coded Hyrax instances related to that name, so we opted to keep it as is

+1 to _legacy_identifiers_ (plural)

For :access_right, I'd prefer _:access_restriction_note_

For _:legacy_ark_, I requested that as a separate field in order to help us with ark redirects down the road. We are slowly transitioning from arks to our new repository ID scheme, but that is work to come.

For :primary_repository_ID, "Persistent URL" was requested as the Lux display label by stakeholders. If we make changes in the meantime, I'm okay with setting it back to "Primary Repository ID" for now, but we'll likely want to test that in the Lux UI context.

**Comment by eporter23** [comment]
@rotated8 @mark-dce I made one more pass on this (back in our [Metadata Implementation - Objects](https://docs.google.com/document/d/1X-vauRrOd3Pc5CyCzfGri25wU5OveyOr81hhUDH0GuY/edit) spreadsheet), with revised names in a new column. I'm including in some of what we discussed by phone regarding making repeatable property names plural in general. If you want to discuss again let me know but I'm good to move forward on it.

**Comment by mark-dce** [comment]
👍 to the changes.  & yes, I think a separate ticket to review collections and do the same kind of alignment makes sense.

**Comment by tmiles2** [comment]
@rotated8 should this ticket be in "in progress" based on the comments from our DCE check-in? "Is there anything remaining needed from DCE for Ticket 407- Field Names? Collin to submit PR for Bess & Mark to review"

**Comment by eporter23** [comment]
@rotated8 can you please touch base with @bess on the timing of this work, since it impacts the importer script?

**Comment by rotated8** [comment]
@tmiles2 Not yet. I'll move it to in progress when I start coding.
@eporter23 👍 My plan is to request a review from @bess for the PR, and tag you and @mark-dce in the PR comments.

**Comment by rotated8** [comment]
The PR #538 currently covers half this issue. It covers renaming the properties, but not rewriting the labels.
