### ISSUE TITLE
Identify criteria for which file to generate a thumbnail from or see in the Viewer

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#411]
Prioritize the following File Uses for displaying to the Viewer:
1. If a Service File has been generated automatically as part of a bulk ingest (may be stored separately from Curate preservation storage context/may not be associated with a Curate FileSet), use that Service File for IIIF delivery
2. If a Service File has been supplied and assigned to a Curate FileSet, use that file 
3. If an Intermediate File is assigned, use that file
4. If only a Preservation Master File is assigned, use that file

For generating Curate FileSet thumbnails, use the following:
1. If an Intermediate File is assigned, use that file
2. If only a Preservation Master File is assigned, use that file

**Comment by eporter23** [comment]
@rotated8 @mark-dce I wrote this up after our co-sprint goals meeting today; it may need further discussion.

**Comment by mark-dce** [comment]
I've written the corresponding implementation ticket here
**Display Preferred Image for filesets** #442
