### ISSUE TITLE
Configure Coveralls Reporting

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#413]
**ISSUE**
Coverage data is being generated during CircleCI builds, but we need to configure CircleCI properly in order to send that data to Coveralls.
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/3e5de2b1-3658-491e-831a-8ed130732e7b)

**ACCEPTANCE**
- [ ] Set the COVERALLS_REPO_TOKEN environment token in CircleCI [docs](https://docs.coveralls.io/supported-ci-services)
    - [ ] Go to https://coveralls.io/github/emory-libraries/dlp-curate/settings and look up the "Repo Token" (DCE doesn't have access to do this)
    - [ ] Go to https://circleci.com/gh/emory-libraries/dlp-curate/edit#env-vars and create a new environment variable with the name `COVERALLS_REPO_TOKEN` and the value you just looked up in Coveralls

**Comment by mark-dce** [comment]
It looks like we need to do some additional configuration since CircleCI is running tests in parallel https://docs.coveralls.io/parallel-build-webhook (i.e. the question mark in the above screenshot links to this setup document) 

I am seeing individual job data now: e.g. https://coveralls.io/jobs/51833326
![image.png](https://images.zenhubusercontent.com/5ca3b270500af570674ef5bc/284c5578-6622-4b53-a967-099511cc8748)

**Comment by mark-dce** [comment]
I've set the COVERALLS_PARALLEL environment variable in CircleCI environment variables (so we might see things work on the next build).

If that doesn't work, the hyrax repo seems to do this in the `.circleci/config.yml` file  https://github.com/samvera/hyrax/blob/v2.5.1/.circleci/config.yml#L142

**Comment by mark-dce** [comment]
Coverage is now being tracked at https://coveralls.io/github/emory-libraries/dlp-curate


<img width="745" alt="image" src="https://user-images.githubusercontent.com/3064318/62872541-56b7e080-bce3-11e9-871c-0b37e9892888.png">

**Comment by tmiles2** [comment]
@rotated8 This ticket is pending your final review before closing. See Marks comments above.

**Comment by rotated8** [comment]
👍
