### ISSUE TITLE
Shibboleth Form Submission

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/dlp-curate#42]
Submit a Shibboleth form with the initial set of parameters needed for Curate.

https://emory.app.box.com/file/370020430760

**Comment by tmiles2** [comment]
@rosy1280 Can you review the Shibboleth form and sign off once reviewed

**Comment by tmiles2** [comment]
@alexBLR here's the signed copy by Rosalyn. You will also need to sign the document 

https://emory.app.box.com/file/370020430760

**Comment by eporter23** [comment]
@tmiles2 @rotated8 can either of you submit this? We have all the signatures now.

**Comment by tmiles2** [comment]
@rotated8 I can do that today, if you like. FYI @eporter23

**Comment by rotated8** [comment]
@tmiles2 I'd appreciate that, thanks!
