### ISSUE TITLE
Investigate use of SOLR Cloud for Cor environment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#43]
@SolomonHD please update this ticket

**Comment by tmiles2** [comment]
@mprefer any progress on identifying when this work will be completed?

**Comment by mprefer** [comment]
Findings from SolrCloud investigation:
1) To have Solr highly available, at a minimum 2 EC2 instances required to distribute the indexes.
2) Three Zookeeper instances are required to maintain a quorum. Each Solr instance can run 
    Zookeeper and a third instance running any other Curate component may be used instead of 
    spinning up and paying for a dedicated Zookeeper instance.
3) SolrCloud has a feature called CDCR (Cross Data Center Replication) where index data can be 
    remain in sync across clusters. In our case, secondary cluster may be in a different AWS region.
    CDCR documentation ma be found here:
    http://lucene.apache.org/solr/guide/7_7/cross-data-center-replication-cdcr.html

**Comment by eporter23** [comment]
4/1/19: we will create another ticket for 0.8 if we are going to implement this
