### ISSUE TITLE
Easily set up default admin set for tests

### ISSUE THREAD

**Issue by RachelDCE** [emory-libraries/dlp-curate#431]
Make a spec helper before block that sets up default admin set, workflow, and anything else that needs to happen before something can successfully be ingested.

Something like this in the rails_helper:
```
  config.before(admin_set: true) do
     AdminSet.find_or_create
  end
```

This will prevent intermittent test failures where everything got cleaned out and now we're missing required admin sets, workflows, collection labels, etc.

**Comment by eporter23** [comment]
Discussed with team 7/29/20: this is resolved.
