### ISSUE TITLE
Show page metadata for Langmuir works

### ISSUE THREAD

**Issue by RachelDCE** [emory-libraries/dlp-curate#434]

**Comment by eporter23** [comment]
@little9 [looks great in our curate prod environment](https://curate.library.emory.edu/concern/curate_generic_works/e8f48e7b-f375-4c5e-b58f-0b9ff1df4d20?locale=en) - the acceptance criteria in #356 also specified a display order which follows the order of the form, however. Do we need a separate ticket for the display order? It is also a lower priority for me, however, but if it helps you all out we should do that as well.
