### ISSUE TITLE
Required fields should appear first on the edit form

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#439]
**ACCEPTANCE**
- [ ] Required fields are listed first on the work edit form
- [ ] Non-required fields are listed in a collapsible section of the form with the toggle label "More Fields"/"Fewer Fields"

**Comment by eporter23** [comment]
@mark-dce the display order and behavior of the edit form was approved by our local stakeholders - this isn't something we want to change.
