### ISSUE TITLE
Can't save work from the UI

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#440]
On https://curate-qa.curationexperts.com
Curate v0.3.3@b5c7c6eb6955e871c1ec14ecf847770490ea1534 updated on 11 August 2019

**STEPS TO REPRODUCE**
1. Login as administrator
2. Go to the works section of the dashboard
3. Click the "Add new work" button
4. Fill in all required metadata (so that "Describe your work" gets a green checkmark)
5. Click on the files tab
6. Choose a "Preservation Master File"
7. Click upload files (so that "Add files' gets a green checkmark)
8. I should now be able to save my work and cannot 

Additional steps: this appears to be related to date validation for Date Created **and for other required fields in the form**. If you enter an invalid date, skip a required text field, etc, and then go back and correct it with a valid entry, Save for the work is disabled until you manually click on another actionable form field.

**Comment by mark-dce** [comment]
NOTE: I notices this setting was turned on, so turned it off and retired creating a new work, but had the same problem

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/3064318/62840362-37776f80-bc5f-11e9-9a97-44240968344b.png">

**Comment by eporter23** [comment]
May be related to JS/date validation

**Comment by little9** [comment]
The JS validation for the date created in the form needs to be valid before the Save button is activated. It doesn't tell you if it isn't valid. 2001 or now is invalid 01/01/2001 is valid

**Comment by eporter23** [comment]
@mark-dce and I recreated this bug. If you type in an invalid date, and then correct it, and then try to save the work, saving is disabled. You can only re-enable saving if you click on another form field to activate it. We may want to adjust the validation behavior to stop when the user exits the form field.

**Comment by eporter23** [comment]
@mark-dce @zo just noted this behavior also occurs to some extent on all of our required form fields. If you bypass a required field, try to save, then go back and fill it in, you have to click on another field to re-enable the Savebutton.

**Comment by eporter23** [comment]
@mark-dce I'm going to remove this from the scope of 0.3 but let me know if/when you want to revisit.

**Comment by mark-dce** [comment]
@eporter23 I'd be OK if you wanted to go ahead and close this ticket and write a new ticket about how you'd like to see the Javascript validation behavior changed.  Writing a new ticket would give the opporunity to assign a more specific and meaningful title and to add more specific steps-to-reproduce and acceptance criteria.
