### ISSUE TITLE
Display Preferred Image for filesets

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#442]
**ACCEPTANCE**
- [x] Given a fileset with one or more files attached, display the following files in order of preference
    1. display the Service File
    2. if no Service File exists, display the Intermediate File
    3. if no Service or Intermediate File exists, display the Preservation Master
    4. if none of the above files exist, display the default hyrax work icon e.g.https://github.com/samvera/hyrax/blob/master/app/assets/images/work.png
- [x] Use the same preferred image when displaying thumbnails for the work in file lists or search results

**Comment by tmiles2** [comment]
@alexBLR Is this your issue, if so can you assign it to yourself and estimate the work?

**Comment by eporter23** [comment]
@alexBLR I have noted some [test revisions here](https://drive.google.com/file/d/1OpPju3au4vpPAM3YxSf5nXs1By9OSKFs/view?usp=sharing) - we may want to regroup on the requirements and if this needs more breakout of tickets.

**Comment by tmiles2** [comment]
@alexBLR are you moving this issue back in to progress to address the revisions or breaking it out into additional issues?

**Comment by eporter23** [comment]
See revision ticket #684. Will also create a new ticket for the View Work page behavior
