### ISSUE TITLE
Work Edit form needs to (show/edit) which fileset is used as reprenstative

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#443]
**ACCEPTANCE**
When a work has one or more filesets attached
- [ ] I can see which fileset is selected as the representative for the work
When a work has more than one fileset attached
- [ ] I can edit which fileset is used as the representative for the work in search results, collection listings, etc.

**Comment by eporter23** [comment]
@mark-dce I think this is closed: we confirmed that those Hyrax fields exist, but get moved into the hidden field group (this also seems to occur in vanilla Hyrax).

**Comment by eporter23** [comment]
I created an enhancement ticket to investigate later: #467
