### ISSUE TITLE
Adjust fieldname for Collections metadata: Related Material - Finding Aid

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#450]
In the Curate Collection-level metadata, https://docs.google.com/spreadsheets/d/17WLINPefxb0cQh2Jgx6H7XnUCDH8Ol1WlKaxtBAGW38/edit#gid=1472024349&range=9:9] was implemented with the fieldname _related_material_. Its intent is to store a URL which links to an online Finding Aid. 

This Collection-level fieldname should be adjusted to a distinct name to avoid confusion with the work-level field :related_material, because it has a more specific meaning and uses a distinct predicate.

Suggestion change this to _:finding_aid_link_

Relates to epic #75 and other Collection-related tickets: #403; #406; #387

**Comment by bess** [comment]
@eporter23 When I go to the spreadsheet for this field it says `[RDF predicate needed]`. We can't implement this until we have an RDF predicate. Note that it should not be the same RDF predicate that was used for the other `related_content` field, if you want to be able to distinguish them behind the scenes.

**Comment by bess** [comment]
Predicate should be `http://metadata.emory.edu/vocab/cor-terms#findingAid`
per @eporter23
