### ISSUE TITLE
Cannot change Collection Visibility (reverts to Private)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#455]
I noticed all the Collections I have manually created are set to Private, and I cannot change their Visibility setting - it immediately resets back to Private. This is occurring on all collections whether they were automatically installed or not.

Test location: Emory Prod

**To Reproduce**
1. As Administrator, go to curate prod > Dashboard > Collections
2. Click on a Collection which has Private visibility
3. Edit the Collection and go to its Discovery tab
4. Change the Collection's Visibility to Emory Network
5. You see a confirmation message saying the collection is updated, but then the visibility resets immeduately to Private

**Expected behavior**
After I change the visibility, the new visibility should be assigned.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bess** [comment]
I can confirm this bug.

**Comment by bess** [comment]
Fixed as of 0.3.8

**Comment by eporter23** [comment]
tested on 8/16 in curate prod - appears to be resolved.
