### ISSUE TITLE
"You do not have access to any collections" - unable to add a Work to a collection from View Work option

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#469]
In Curate prod, I created a new work, and then tried to add it to a Collection. As an Admin user, I would expect to have access to add works to all collections.

![Screen Shot 2019-08-13 at 5.19.47 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f72d7601-cf49-436a-a291-76ff2fd7c9fc)

![Screen Shot 2019-08-14 at 9.11.38 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/daa60c40-7795-4c47-9415-d1976dc9bd8d)

Not sure if we should add the Repository Administrators group explicitly to the Collections being generated by script?

![Screen Shot 2019-08-13 at 5.22.39 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/fb7752bb-ade9-49a8-98e4-a11a36efc00e)

**Comment by eporter23** [comment]
@bess if you have time can you take a look at this as part of your Collection related work?

**Comment by bess** [comment]
@eporter23  Can we take a look at this together? I am not able to replicate this behavior and I wonder if you're doing things differently from the way I'm doing them.

**Comment by bess** [comment]
Fixed as of 0.3.8

**Comment by eporter23** [comment]
I tested this by re-assigning sample works to each of the three collections - all worked.
