### ISSUE TITLE
Initiate and Schedule ART Review Approval

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#47]

**Comment by eporter23** [comment]
@tmiles2 created this one in 1/23 planning meeting - please refine as needed.

**Comment by tmiles2** [comment]
@eporter23 @rotated8 here's the link to our ART review template wiki page. https://wiki.service.emory.edu/display/cita/DLP%3A+Shared+Infrastructure%2C+Discovery%2C+and+Curation

**Comment by tmiles2** [comment]
@eporter23 @rotated8 I'm closing out this issue, I put a note in issue #152 (AWS at Emory configuration) to schedule the ART.
