### ISSUE TITLE
Dashboard filters show "translation missing:en.hyrax..."

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#470]
I've started seeing this in Curate prod when I go to the Dashboard to select a work or a Collection. Not sure if this is indicating anything serious, but:

![Screen Shot 2019-08-14 at 9.06.57 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f2cceb7f-5f7b-48ac-8207-16b0730fffc8)

**Comment by bess** [comment]
This is partially fixed as of 0.3.6:

![labels_fixed.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/2083d185-de54-4177-ae69-fc08540b80ba)

![labels_fixed_2.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/94d608ca-28c7-4a49-ba32-bcbc23f6a467)

**Comment by bess** [comment]
Fixed as of 0.3.7

**Comment by eporter23** [comment]
tested in curate prod - all clear!
