### ISSUE TITLE
Investigate if "cor-" prefix causes pair tree problems

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#474]
All of our assets will start to fall in one directory.

![Screen Shot 2019-08-15 at 12.02.19 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/a7b171c7-a4d3-4466-aee3-0ec32fb2fd49)

**Comment by bess** [comment]
@eporter23 This will definitely cause performance issues if steps aren't taken to distribute the pair tree.

**Comment by eporter23** [comment]
We've discussed this a few times and agree it will cause Fedora performance concerns. A separate ticket was written to mitigate this.
