### ISSUE TITLE
Test file transfers for Langmuir

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#475]
Discussed in standup:  start testing out file transfers for Langmuir collection. Consult with Kyle Fenton for more information about the NAS location and directory structure.

Here is a sample complete file path for a Langmuir image:
::nasn2dmz.cc.emory.edu:dmfiles:MARBL:Manuscripts:MSS_1218_Langmuir:ARCH:B038:MSS1218_B038_I038_P0001_ARCH.tif

[Additional notes from Kyle about NAS directories](https://docs.google.com/spreadsheets/d/1H-Bc4jNOnt8Mi-CWhHaRmYIr7c15tMRq9Ue3P5_U4io/edit#gid=392178988)

A full transfer for the image files should contain 45,641 TIFF files

- [x] Request access to NAS Directory
- [x] connect to NAS directory for DAMS: Langmuir collection
- [x] incorporate fixity checking as part of transfer (use rsync, MD5 or SHA1)*
- [x] record any fixity failures
- [x] record any transfer failures
- [x] transfer files to the existing EFS, mirroring directory structure of NAS.
- [x] Report on speed of working with EFS vs EBS.

This CSV is a partial list of the Langmuir files and includes a column called "Path" for the files to transfer: https://emory.app.box.com/file/501227444677

[Additional file list for "_PROD" versions of files](https://emory.box.com/s/6bw3z5i3i46ors0zi57lcoy3ff6gfhug)
*this is part of our acceptance criteria with stakeholders

**Comment by tmiles2** [comment]
@mprefer @SolomonHD Should this issue be in progress?

**Comment by tmiles2** [comment]
@mprefer @SolomonHD Can we get an update on issue?

**Comment by SolomonHD** [comment]
Mark has successfully attached the emory NFS mount to our VM of choice but we're having issues connecting to the AWS NFS mount. I requested a firewall exception today. We've also more or less ruled out using EBS because of storage sizing, the one mount that we have is 21TB and EBS tops out at 16TB

**Comment by tmiles2** [comment]
@SolomonHD typically how long does it take for the firewall exception request to go through?

**Comment by SolomonHD** [comment]
@tmiles2 The request is done. I mounted the EFS to libetdapprod1 last night and transferred about 80 GB worth of files

**Comment by SolomonHD** [comment]
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/0509f616-4510-493a-8b77-ba6dec77b34a)

**Comment by SolomonHD** [comment]
Langmir Collection uploaded:

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/5601b0b7-1cea-4f7a-8ca1-c543fecba5c7)
