### ISSUE TITLE
Collections duplicated in curate production

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#483]
**Describe the bug**
In Curate prod (curate.library.emory.edu) after the rebuild on 8/16, I am seeing duplicate instances of 

**To Reproduce**
1. Go to curate.library.emory and login as an Administrator
2. Click on Dashboard
3. Select Collections
4. See duplicate collections listed

**Expected behavior**
I should only see each collection once.

**Screenshots**
![Screen Shot 2019-08-18 at 12.49.13 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/f1f52c06-a55c-4829-9b55-01f2cb5517a2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bess** [comment]
@eporter23 I think this was an artifact of having had previous versions of these collections that weren't de-duplicating cleanly. I've deleted them and had them auto-re-create and now I only see one set, even after I deploy several times. I'm going to close this ticket and if you see it again we can re-open it.

**Comment by eporter23** [comment]
@bess I'll close it and keep an eye out for the next deploy on our end.
