### ISSUE TITLE
Add MD5 to hash values for files

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#484]
- [ ] Find MD5 in FITS output
Add MD5 to to File metadata
- - [ ] Add the MD5 to the digest_ssim or original_checksum_tesim for Solr
- - [ ] Add the MD5 to the appropriate place in Fedora as well

**Comment by devanshu-m** [comment]
https://github.com/samvera/hyrax/blob/83dc1ea89b7c512b8bd5b807809ca5f2da368434/app/indexers/hyrax/file_set_indexer.rb#L24

**Comment by devanshu-m** [comment]
https://github.com/samvera/hydra-works/blob/master/lib/hydra/works/characterization/fits_document.rb#L70

**Comment by devanshu-m** [comment]
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/file_set_fixity_check_service.rb

**Comment by devanshu-m** [comment]
https://bibwild.wordpress.com/2017/05/01/exploring-and-planning-with-sufiahyraxfedora-fixity-validation/

**Comment by eporter23** [comment]
Tested and closing, assuming that we see MD5 and SHA256 for Preservation Masters only, and we see SHA1 for all files even if they are not Preservation Masters.
