### ISSUE TITLE
Evaluate Logging Options

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#49]
- [x] Survey logging options
- [x] Compare relevant options
- [x] Recommend a course of action

**Comment by rotated8** [comment]
Tagging @eporter23 @tmiles2 for milestone suggestions. I don't think this needs to be done in this sprint, but it should be part of configuration, and ready before go-live.

**Comment by eporter23** [comment]
@rotated8 I think it fits well with 0.1 (overall target 3/1) but I've also been thinking we may need an additional "launch" related release. So if we can't finish that by 3/1 we could address in a wrap-up release.

**Comment by SolomonHD** [comment]
## Splunk Pros:

* Seems to be the best overall solution
* I have previous experience with it
* Seems simpler to setup than Greylog
* Emory may eventually offer Splunk as a service
* Many different deploy options
* Strong Documentation

## Splunk Cons:
* Expensive
* Very small free tier: 200mb/day, we'd go over that real quickly

#### Estimated Cost of Splunk Light at 5GB/day worth of log

__Monthly: $450 a month or $5400 for the year__
__Yearly: $4500__

__Splunk Cloud:  $810 monthly, $8100 yearly__

## Greylog Pros:

* Open Source
* Seems less expensive than Splunk
* There are a few ruby gems that target Greylog
* High free limit: 5GB/day, we could stay under that for a while

## Greylog Cons:
* Documentation is sparse
* Seems more complicated to set up than Splunk
* If we go over the free limit the entire logging shuts down
* The pricing structure is unclear

Estimated Cost for Greylog: $1500 a year? I think we could theoretically stay in the free tier for some time but LTDS eventually will need Enterprise support, etc.

**Comment by tmiles2** [comment]
@eporter23 @rotated8  I've moved this issue to the "to accept" column so Collin can ask any additional question or determine if Solomon's information meets the needs to close this out.

**Comment by eporter23** [comment]
Still in progress 4/15 - costs are predicted to be less than Splunk

**Comment by mprefer** [comment]
## ELK Stack:

ElasticSearch, Logstash, Filebeat, and Kibana are all open source and free.
ElasticSearch, Logstash, and Kibana can all run from a single AWS instance. Only Filebeat needs installation as an agent on machines that produce log files.
There are several Beat packages available to monitor and collect data on various aspects of a running system.
Cost is based on the size of the instance and the amount of traffic.
