### ISSUE TITLE
Preview Image content in the Universal Viewer so that I verify file quality related to access controls for images.

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#491]
**ACCEPTANCE**
Given a public hi-res image
- [ ] I have an option to download the full image
Given a public low-res image
- [ ] I have an option to download a reduced resolution version of the image
Given a public view-only image
- [ ] I am not provided any download options
- [ ] Using the IIIF endpoint, I can only request a reduced resolution version of the image

**Comment by eporter23** [comment]
Moving this to a later release to parallel Lux work development

**Comment by eporter23** [comment]
Closing this ticket, as it has been broken out further into tickets on both Curate and Lux boards.
