### ISSUE TITLE
View Work does not display all populated metadata fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#519]
When testing the first Langmuir load, I noticed the View Work page does not appear to display all populated fields. Having all the populated fields display is needed for QA of migrated data. There are about 14 fields which aren't displaying when populated, some of which are required.

I created a test object in Curate-test which has a value in every field from the form/model:
https://curate-test.library.emory.edu/concern/curate_generic_works/cor-276f1vhhnj?locale=en

[Comparison of form fields vs. display output](https://docs.google.com/spreadsheets/d/1cTTrtqWZRGHTjY8ZP2GvJokUl6IkxxscXj8aTg2D5P4/edit#gid=0)

**Comment by tmiles2** [comment]
@wulman16 can you provide an estimation for this work?

**Comment by eporter23** [comment]
Looks good! There is one field remaining (Persistent URL/primary_repository_id) but we'll handle that in a separate ticket.
