### ISSUE TITLE
CSS broken on Curate-test

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#52]
**Describe the bug**
CSS is not rendering on curate-test

**To Reproduce**
Go to curate-test.library.emory.edu

**Expected behavior**
Website rendering normally

**Comment by rotated8** [comment]
@SolomonHD changed the role order for deploy, and that fixed the problem.

**Comment by SolomonHD** [comment]
It was a MIME type issue, the role order I was calling overwrote the apache MIME type, this caused apache to render the js and css as just text.
