### ISSUE TITLE
Add Will to Envs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#521]
Software Engineering has a new hire who needs to be added to test, prod and any other envs moving forward

**Comment by SolomonHD** [comment]
@rotated8 @wulman16 
Please put Will's netID and github user in this ticket.
Also Will needs an SSH key associated with his github account.

**Comment by rotated8** [comment]
@wulman16 When you've added an SSH key, please let Solomon know.

**Comment by SolomonHD** [comment]
I've added Will as an auditor on the aws@emory account and also added his keys to the deploy user's authoried_keys file. He should be able to login now.
@wulman16 The test is your ability to login to curate and curate-test
