### ISSUE TITLE
Enable cross-region replication in S3

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#524]
As part of our AWS@Emory configuration, we should make sure we have cross-region replication enabled so that we have 2 copies of files for preservation requirements for our version 1 of Cor

Relates to epic #205 for Preservation Storage 

- [x] Research s3 cross replication
- [x] Enable s3 cross replication for fedora-cor bucket

**Comment by SolomonHD** [comment]
Enabling cross replication will require Versioning to be enabled. Will discuss during standup

**Comment by SolomonHD** [comment]
Bucket versioning and cross replication have been enabled for fedora-cor-binaries bucket and fedora-cor-test-binaries bucket.

fedora-cor replicates to backup-fedora-cor-binaries while fedora-test replicates to backup-fedora-cor-test-binaries

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/2ceb6106-9524-4c8d-86b6-2f4575170c7f)

**Comment by SolomonHD** [comment]
To test I copied a new file to fedora-cor and within about 5 minutes it was replicated to the backup bucket.
