### ISSUE TITLE
Display Preservation Workflow Fields

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/dlp-curate#527]

**Comment by eporter23** [comment]
@alexBLR you may have seen these already, but I think these may be the most relevant ideas I had for UI options so far. 

[Creating workflow metadata on a brand new work -- assigning Workflow Metadata](https://docs.google.com/drawings/d/1gFGxIw7JQwbGYHKVcST2CudadnRSJx_RpoMA5EN1TZU/edit?usp=sharing) (Accession or Ingest only)

[View-Only display of existing Workflow Metadata on a work](https://docs.google.com/drawings/d/1H7hNhV2qqLrPsC603EYnHv1xDl9ab96oa-kztTxP5cU/edit)

[Editing an existing Work - assigning Workflow Metadata](https://docs.google.com/drawings/d/1jWdnwqkxiRl8_ZyYWMaXBYfhP89qDPhjn-VTAoQu4DY/edit) : editing still somewhat TBD in terms of when that would be allowed, and who could see these options. Providing here just for examples of something we may need later in 0.5.

**Comment by tmiles2** [comment]
@alexBLR Can you get the screenshot of the work completed by lunch so we can close out testing this issue?

**Comment by alexBLR** [comment]
![Screen Shot 2019-10-04 at 4.12.09 PM.png](https://images.zenhubusercontent.com/5c488275c10ae96cd915967b/19f9446d-2ea7-4a36-9340-3b0a27ebd563)

**Comment by eporter23** [comment]
@alexBLR thanks, this looks good!If there were two workflows populated, such as one set of entries for Accessioning and one set of entries for Ingest, would they simply repeat?  I may want to tweak the display later but this is really helpful to confirm all the fields exist.
