### ISSUE TITLE
Get sample Yellowback books from filesystem

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#531]
For DCE to test ideas for structural metadata, we need to collect samples of Yellowback book objects which have multiple volumes or copies.

nfs://nasn2ac-nfs.cc.emory.edu:/ifs/emoryndb2/n2nfs/library/repl/lsdi

FULL SET - [base directory paths for all volumes to be migrated](https://emory.box.com/s/3ergcgqksla0mf8pfonjz6mbiht32ui5)

SAMPLES - directory paths

- [x] Sample 1: The slaves of Paris 
* v.1
    * Directory: /lsdi/diesel/lts_new/ocn171043761-2529
* v.2
    * Directory: /lsdi/diesel/lts_new/ocn171043761-2530

- [x] Sample 2: Mrs Brown at the sea-side
* c.1
    * Directory path: /lsdi/diesel/lts_new/ocm15736606-2671
* c.2
    * Directory path: /lsdi/diesel/lts_new/ocm15736606-2672

- [x] Sample 3: The coral pin
* v.1
    * Directory path: /lsdi/diesel/lts_new/ocn165153386-2471
* v.2
    * Directory path: /lsdi/diesel/lts_new/ocn165153386-2472

Checklist:
- [ ] Connect to share nfs://nasn2ac-nfs.cc.emory.edu:/ifs/emoryndb2/n2nfs/library/repl/lsdi
- [x] Generate a list of files in the directory and subfolders
- [x] Copy the files and their directory structure to our ingest staging space

**Comment by SolomonHD** [comment]
I've created a ticket for granting access from libetdapprod1 to this NFS mount:
[Link](https://emory.service-now.com/nav_to.do?uri=%2Fsc_task.do%3Fsys_id%3Daae6f1271bafb3c0a8441f4ead4bcb78%26sysparm_record_target%3Dtask%26sysparm_record_row%3D1%26sysparm_record_rows%3D101%26sysparm_record_list%3Dopened_by%253Djavascript%253Ags.getUserID%2528%2529%255Esys_class_name%2521%253Dsc_request%255Esys_class_name%2521%253Dsc_req_item%255EORDERBYDESCsys_created_on)

**Comment by mprefer** [comment]
File path for Yellowback files on the Curate server:

/mnt/efs/Collections/Yellowbacks/lsdi
/mnt/efs/Collections/Yellowbacks/lsdi2

**Comment by tmiles2** [comment]
@SolomonHD @mprefer Can I get an estimation for this issue?

**Comment by tmiles2** [comment]
Can you provide the size of the copy was @mprefer

**Comment by mprefer** [comment]
I made an error in my file list. 
Am currently determining the size of all the files required to verify that it's 1.2 million files @ ~300GB.

**Comment by eporter23** [comment]
@mprefer if you copy up everything in those specified directories it may be ~1.4 million files ~330 GB. There are some files that we won't need for migration, but I'm sure it will be easier not to try to weed them out.

**Comment by mprefer** [comment]
@eporter23 My numbers are a bit off from yours.
I found 328,790,111,688 (~ 330GB), but my file count was 3,094,140 which is much higher than ~1.4 million. Can this be correct?

**Comment by eporter23** [comment]
@mprefer I'll check with Kyle to see what may be going on there. I know there are extraneous files in those directories that we won't ingest, but I don't know if it would account for doubling the expected count.

**Comment by eporter23** [comment]
@mprefer Kyle noted "if the overall size is close to expected, but the file counts are doubled, it's probably because every image has a corresponding thumbnail file, which won't form part of the ingested object."

**Comment by mprefer** [comment]
@eporter23 So I can exclude the thumbnails ?

**Comment by mprefer** [comment]
Yellowbacks file transfer begun 4:17PM 09/06/19.

**Comment by mprefer** [comment]
Killed the rsyncs that were running since 09/06/19.
Started 2 rclone sessions, 1 for LSDI, 1 for LSDI2.

LSDI startup:
![rclone_lsdi-2.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/0593fb9a-a40a-4490-aeb6-ef7c9327a9f5)

LSDI2 startup:
![rclone_lsdi2-2.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/d512278b-d22c-4e2c-9d9a-e01c179f47a9)

**Comment by mprefer** [comment]
The LSDI2 rclone session completed. All the files had already been transferred to the destination on the EFS volume, The rclone session validated the MD5 checksums between the source and destination with no errors.

![rclone_lsdi2-complete.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/32cbd1ef-eb1e-484f-ae43-c68a0a85a0c1)

The LSDI session is still running at 12:35AM 09/10/19. 201,648 files transferred thus far, currently rclone is validating MD5 checksums of files that rsync had copied.

**Comment by tmiles2** [comment]
Thanks @mprefer for the update. @SolomonHD @mprefer Can we document on the Wiki the process you used that was successful, what wasn't and why? I think it will be useful as we do more migrations in the future. We can add an issue for documenting the process in our next sprint if it will impede on your time to complete other priorities remaining in the sprint.
