### ISSUE TITLE
Curate test reset/wipe for migrations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#541]
We need to switch over to treating production as a true production environment and no longer use it for testing.

- [x] DB is cleared out
- [x] Solr is cleared out
- [x] Fedora is cleared out
- [x] Redis is cleared out
- [x] tmp space is empty
- [x] S3 bucket is empty
- [x] Redeploy application (to regenerate 5 Phase 1 Collection entities are regenerated and all production permission groups/roles are assigned) 
- [x] Clearing out derivatives from efs mount share drive (/mnt/test_efs)

**Comment by mprefer** [comment]
Solomon and I reset Curate test to a pristine condition using manual methods.
