### ISSUE TITLE
Add Oxford users to Curate product for Phase 1 Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#549]
Repeats work from Rose users ticket. 

Group users when adding them. Use the process like we have in place for the Admin YAML file.
See the [worksheet: Groups and Users tab](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=1791455727) for epic #275.

- [x] YAML file for each Oxford user group: Oxford Managers, Oxford Viewers, Oxford Depositors
- [x] Add users to each YAML file
- [x] Setup rake task to create group if missing, and add users to the group

**Comment by tmiles2** [comment]
@eporter23 Who completed this work?

**Comment by eporter23** [comment]
@tmiles2 I thought Devanshu had already done this as part of prior work, but maybe I misunderstood.

**Comment by eporter23** [comment]
@devanshu-m @devanshu-m I see the Oxford groups here: https://curate-test.library.emory.edu/roles so I assuming this ticket is complete?

**Comment by devanshu-m** [comment]
@eporter23 I guess? We discussed putting both tickets in to test since the work is complete.

**Comment by eporter23** [comment]
As far as I can tell, this is done, in that the users exist and are in the right groups.
