### ISSUE TITLE
Initiate Security Review for Curate application

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#55]
Complete and submit the initial security review forms for Curate. We may not get approvals by 3/1 but we will get in the queue.

[KB Reference Information from Tiffany](https://emory.box.com/s/mjg9lw6qiony9lzcthl6cu95pz029rf1)

- [x] Complete questionnaire (CB)
- [x] Submit SN ticket (TM)

**Comment by tmiles2** [comment]
[ ] Complete questionnaire (CB) 
[ ] Submit SN ticket (TM)

**Comment by tmiles2** [comment]
- [ ] Complete questionnaire (CB)
- [ ] Submit SN ticket (TM)
