### ISSUE TITLE
Add new Health Sciences users to Curate product for Phase 1 Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#552]
Repeats work from Rose, Oxford users ticket.

Group users when adding them. Use the process like we have in place for the Admin YAML file.
See the worksheet: Groups and Users tab for epic #275.

- [x] YAML file for each Health Sciences user group: Health Sciences Managers, Health Sciences Viewers, Health Sciences Depositors
- [x] Add users to each YAML file
- [x] Setup rake task to create group if missing, and add users to the group

**Comment by tmiles2** [comment]
@eporter23 Same here, do you know who completed this work?

**Comment by eporter23** [comment]
@devanshu-m I see the Health Sciences groups here: https://curate-test.library.emory.edu/roles so I assuming this ticket is complete?

**Comment by devanshu-m** [comment]
@eporter23 I guess? The requirement was to have those groups and users in those groups should exist?

**Comment by eporter23** [comment]
@devanshu-m yes, as far as I am concerned this is done. Closing!
