### ISSUE TITLE
Evaluate AWS ElastiCache

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#56]
ElastiCache is an alternative to Redis that some Samverians are using. 

- [x] Install ElastiCache on a server in AWS
- [x] See if ElastiCache is compatible with DLP Curate

**Comment by mprefer** [comment]
Successfull test connections to ElistiCache Redis instance with:
1) redis-cli
2) Python
3) Ruby
4) Sidekiq
