### ISSUE TITLE
Cancel the old (premised) DLP sandbox VM

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#562]

**Comment by mprefer** [comment]
Catalog request to decommission vmch-hydra-sb.library.emory.edu (aka hydrabox) submitted, work order # 20-00872.

**Comment by mprefer** [comment]
vmch-hydra-sb.library.emory.edu has been decommissioned and charges have been suspended.

Charges have been suspended as of 10/02/2019 and will be reflected in October billing.

**Comment by mprefer** [comment]
Placed SN request to retire Avamar backups on this VM.
Request number:  INC03239532.

Placed additional SN request to have DNS CNAME record 'hydrabox.library.emory.edu' that pointed to this VM.
Request number:  INC03239552
