### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#57]
Cantaloupe released a later version than what util-cor-test is using

- [x] Rebuild util-cor-test with latest version of cantaloupe 4.0.3
- [x] Test to make sure cantaloupe is still working after the upgrade/rebuild
- [x] Update other dependencies as needed

**Comment by rotated8** [comment]
@SolomonHD This ticket is a month old. Has it been completed?
