### ISSUE TITLE
Create Ansible Role to manage the Backup/Restoring of Curate/Fedora/S3

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#570]
Bess has contacted me about the need to backup and restore curate after the Langmuir Collection
Since our system utilizes multiple server architecture, RDS and S3 it's going to be more involved to backup all of this and restore it. The best way forward will be an ansible role to manage all of this.

- [x] Develop ansible role that will backup curate's mysql database
- [x] Role should also utilized fedora's backup tools

**Comment by SolomonHD** [comment]
So after some thinking about this:

My current idea is to develop a general ansible role that will do a mysqldump to s3. This role will shutdown a service that you specify, and bring it back up after the dump is completed.

This role will also handle import databases in a similar manner. We can then use this role to dump or import fedora, hyrax mysql databases.

For the S3, use the AWS Console to do a batch tagging operation. Then we can do a lifecycle policy
that deletes all objects in the bucket that do not have a specific tags.

**Comment by SolomonHD** [comment]
@rotated8 @bess 
The current ansible role will backup curate and fedora's database. By tomorrow I will be in a position to attempt importing. I would like some assistance testing this out.

**Comment by tmiles2** [comment]
@SolomonHD Sounds like this issue should be in "to test", it that correct? Also Collin is out this week did he or Bess have chance to test this work last week?

**Comment by SolomonHD** [comment]
I've tested some of this role's functionality. Backing up the fedora and curate mysql database and importing works. There still needs to be some development around backup and restoring efs volumes (for the thumbnails) and around fedora/s3 lifecycle policy. I can break that out into another ticket and close this one if you like @tmiles2
