### ISSUE TITLE
Refresh PDFs for Yellowbacks on AWS staging

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#572]
Kyle completed some compression/optimization work on Yellowbacks PDFs which will need to be re-transferred before final ingest.

Re-transfer files in the [PDF_Path column of the pull-list spreadsheet](https://emory.box.com/s/qq9n6e9swyozu3maly0wtwggybgztgln)

**Comment by eporter23** [comment]
Discussed on 9/23 - we can use the original file list to target PDFs if needed

**Comment by eporter23** [comment]
Removed pre-migrate label because it's unclear if Kyle will resume this work before November

**Comment by eporter23** [comment]
Removing from 0.4 because the PDF optimizations were not complete at this time.

**Comment by eporter23** [comment]
Kyle has optimized the Yellowbacks PDFs and removed the blank page 1, which means we should get better thumbnails.

**Comment by eporter23** [comment]
@mprefer @tmiles2 I just heard from Kyle that he optimized all the Yellowbacks PDFs. This wasn't in our sprint goals, but if it's possible to get this file transfer started, that would be great. I will also target this for the next sprint.

**Comment by mprefer** [comment]
Used 'rclone' to xfer the files listed in the spreadsheet from local on premise NFS storage to the EFS file system in the Curate environment.

Ran md5sum against the local on premise originals and the transferred file on EFS...all checksums match.
