### ISSUE TITLE
Create nested attributes for preservation events

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#574]
Nested class should be called PreservationEvent, and have three attributes:

- [ ] type
- [ ] timestamp
- [ ] notes

**Comment by eporter23** [comment]
@alexBLR here are additional properties that may be needed for Events. Let me know if you want to discuss or prioritize these. https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=497852377
