### ISSUE TITLE
Transfer Yearbooks files to Cor staging

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#576]
Yearbooks files are stored on lsdi or lsdi2 (same shares as Yellowbacks). [See this Box note.](https://emory.box.com/s/exgc00xe41foumogn2muuuucsk9r5q17)

- [x] [Base directory paths for Oxford Yearbooks](https://emory.box.com/s/h4b6tgleqdk66io0xyo8ehbme42uo70e)

- [x] [Base directory paths for Emory Yearbooks](https://emory.box.com/s/sm5p4oppskxh5qc3qgjqe5efbrj90ibx)

Expected file size to copy: 
292,570 MB Oxford Yearbooks
434,354 MB Emory Yearbooks
726.924 GB total

Estimated file counts:
27,293 Oxford Yearbooks
103,846 Emory Yearbooks
131,139 total*

*there may be additional files in the directories which are not needed for ingest, so the count could be higher

**Comment by eporter23** [comment]
@mprefer @SolomonHD here's the info for the Yearbooks file transfer. We can start this as soon as you're ready.

**Comment by eporter23** [comment]
@mprefer Kyle updated me today that the file size count may be higher than previously estimated. It may be more like 1,204 GB (including some files that we won't actually ingest).

**Comment by mprefer** [comment]
Oxford Yearbooks transfer begun:
09/13/2019 @ 13:53

Emory Yearbooks transfer begun:
09/13/2019 @ 15"56

**Comment by mprefer** [comment]
Oxford Yearbooks complete:
Number of files: 36,598
Size:                    349.527GB
Run time:               31H 9M

![oxford_yearbooks_files.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/a977e8c7-7190-4dba-9b74-a6b7d17412e7)

**Comment by mprefer** [comment]
Emory Yearbooks complete:
Number of files:  161,377
Size: 822.696GB
Run rime: 63H 2M

![emory_yearbooks_files.png](https://images.zenhubusercontent.com/5c12be5f7387c610cbb20714/67aac48c-e6cb-424c-9a2f-8075d8bd848f)

**Comment by mprefer** [comment]
Validated the checksums with the 'md5sum' command on the EFS mount and the local Isilon mount points. 100% valid.

**Comment by eporter23** [comment]
Thanks @mprefer !
