### ISSUE TITLE
Transfer Medical Artifacts collection files to Cor staging

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#577]
Medical Artifacts file paths:
https://emory.box.com/s/zjrv57zgmt6wam8sxmmmd3u6z5mrnosh

Estimated size: 36 GB
Estimated counts: 240 (tifs)

**Comment by mprefer** [comment]
CSV downloaded and massaged for 'rclone'.

'rclone' transfer started 10/02/2019 @ 4:47PM

**Comment by mprefer** [comment]
File transfer complete after 1 hour 42 minutes.

MD5 checks will begin 10/03/2019.

**Comment by mprefer** [comment]
MD5 checksums between source and destination 100% valid.
