### ISSUE TITLE
Transfer Kobe collection files to Cor staging

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#578]
Kobe file paths:

https://emory.box.com/s/w31g5ukbhm36p7903vb5ud6fgqj1hhgk

Estimated file size: 25 GB
Estimated file count: 195 (tifs)

**Comment by mprefer** [comment]
CSV file has been downloaded and massaged for 'rclone';

Started 'rclone' transfer 10/02/2019 @ 4:45PM

**Comment by mprefer** [comment]
File transfer complete after 1 hour 26 minutes.

MD5 checks will begin 10/03/2019.

**Comment by mprefer** [comment]
MD5 checksums between source and destination 100% valid.
