### ISSUE TITLE
Run characterizejob on pmf

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#580]
- [ ] Make sure only pmf is characterized and file metadata properties are not appended/overwritten with characterization results for different types of files

**Comment by devanshu-m** [comment]
@eporter23 Please test this when deployed.

**Comment by tmiles2** [comment]
@devanshu-m is there an estimate for this work?

**Comment by eporter23** [comment]
I tested a [work with multiple FileSets](https://curate-test.library.emory.edu/concern/curate_generic_works/cor-320sqv9s5b?locale=en) containing a PMF plus derivatives. As we wanted, the PMF gets the characterization and enriched metadata, and the derivative files get basic technical metadata only. 

Bonus: the Upload Files process seems faster now.
