### ISSUE TITLE
NOID minter error after ticket 575

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#603]
Relates to work done in #575:

Trying to create new works in curate 0.4.8 and curate-test 0.4.8 produces this error:

![Screen Shot 2019-09-23 at 11.53.29 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/7236b8c1-8ce0-4e2b-839d-e3d892bb0b6e)

**Comment by alexBLR** [comment]
Fixed with @devanshu-m
