### ISSUE TITLE
(R-04)Security assessment - remediation work: prohibit public sharing of EBS volumes

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#608]
Description of the risk identified by the security team: https://emory.app.box.com/file/528500401683

**(R-04) Configuration Management: EBS – Data Exposure:**  Users are able to set EBS volumes as public. These volumes can be easily seen and accessed by anyone with an AWS account. This is a similar risk to public S3 buckets, except in this case there is a master list of all public EBS volumes available for anyone to browse.
 
**Security Recommendation:** Configure EBS volumes to prohibit public sharing.

**Remaining work to do:** 
- [x] Confirm the EBS volume aren't being shared publicly
- [x] If the volumes aren't being shared publicly document the existing state ( document in wiki)

**Comment by tmiles2** [comment]
@mprefer Can you start with this ticket and provide an estimate for it as well?

**Comment by mprefer** [comment]
After a more in-depth reading of the AWS documentation on EC2/EBS, the lifecycle management concerns maintaining snapshots of EBS volumes. The documentation also states that LCM can be achieved with the AWS cli tools, which I will pursue since the LCM function is not available with out aws@emory account.

**Comment by mprefer** [comment]
Using the AWS Backup service to test lifecycle management of EBS snapshots.

**Comment by mprefer** [comment]
The description is a misnomer. EBS volumes cannot be made public; however, snapshots of EBS volumes may be created and set to public.
Presently we only have 1 snapshot, which is configured as private, and is a snapshot of a volume that is not even in use.
I think the criteria has been met.
