### ISSUE TITLE
(R-08)Security assessment - remediation work: Investigating the SSL connection from the client to the MySQL database

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#609]
Description of the risk identified by the security team: https://emory.app.box.com/file/528500401683

**(R-08) Configuration Management: RDS - Encryption of Data in Transit:** Communications to/from the database may not be appropriately encrypted. For ePHI workloads this violates the terms of the Amazon Business Associate Agreement. For all workloads containing sensitive information, lack of network encryption to/from the database can lead to the potential exposure or compromise of sensitive data while in transit over the network.
 
**Security Recommendation:** Connections to RDS MySQL databases must use transport encryption. For more information on enabling encrypted connections, see http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Remaining work to do:** Investigate the solution to configure the applications to use SSL for all connection to the database

**Comment by mprefer** [comment]
Steps to configure Fedora for RDS SSL:

1. Download AWS RDS root CA certificate: https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem
2. openssl x509 -outform der -in rds-ca-2019-root.pem -out rds-ca-2019-root.der
3. keytool -import -alias rds-root -keystore <clientkeystore> -file rds-ca-2019-root.der
4. keytool -list -v -keystore <clientkeystore>

Where clientkeystore = /usr/java/latest/jre/lib/security/cacerts

Add the following to the Java Service Wrapper configuration file:
wrapper.java.additional.106=-Djavax.net.ssl.trustStore=%JAVA_HOME%/lib/security/cacerts
wrapper.java.additional.107=-Djavax.net.ssl.trustStorePassword=changeit
where %JAVA_HOME% = /usr/java/latest/jre

Add following (in bold) to Fedora repository.json file (/etc/fedora/repository.json):
"connectionUrl":"jdbc:mysql://${fcrepo.mysql.host:localhost}:${fcrepo.mysql.port:3306}/dlpfedarc1?createDatabaseIfNotExist=true**_&useSSL=true_"**

**Comment by mprefer** [comment]
Moving to "To Test" so someone can poke around the application to make sure it does not break because of the changes for SSL RDS communication.

**Comment by eporter23** [comment]
@mprefer I did some browsing and made some minor application setting/appearance changes in arch, all seems fine.
