### ISSUE TITLE
Revise automated collection generation from CSV process 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#612]
Revise the automated collection re-generation process to include:

- [x] multiple collections in a single spreadsheet
- [x] collections can be manually edited by Curate users and manual edits are not lost on re-builds
- [x] collection IDs remain persistent if regenerated - and should we recreate them with the new NOID pattern?

- [x] This refactor should also take into account the amount of time collection creation/updates takes during deploys.

**Comment by rotated8** [comment]
@eporter23 With the collections permission check piece, what did you have in mind?

**Comment by eporter23** [comment]
@rotated8 that probably means to restore the custom permission groups assigned (like what Devanshu has been working on)

**Comment by tmiles2** [comment]
@devanshu-m @wulman16 Do you have an estimation for this issue?

**Comment by devanshu-m** [comment]
@tmiles2 updated

**Comment by tmiles2** [comment]
Thanks @devanshu-m

**Comment by eporter23** [comment]
Tested this on Langmuir, Yellowbacks, and Yearbooks. Created additional tickets for enhancing deduplication and including the other two collections.
