### ISSUE TITLE
Display all Technical Metadata on View FileSet page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#616]
Expand the display of Technical Metadata on the View FileSet page so that it includes all the metadata extracted by FITS for the Preservation Master File

[List of technical metadata fields which may be extracted](https://docs.google.com/spreadsheets/d/1csDcDnJdhB1VLlgJUU95DndXSeIP2j8yPMlErrsVVPw/edit#gid=1836172006)

**Comment by wulman16** [comment]
The work for this ticket is done except for the automated test. I've attempted mocking the characterization service response in the spec with little success. The next step would probably be to try mocking the Solr document itself. There are a couple of examples in the Hyrax spec, such as:
https://github.com/samvera/hyrax/blob/v3.0.0.pre.beta1/spec/views/hyrax/file_sets/show.html.erb_spec.rb
https://github.com/samvera/hyrax/blob/v3.0.0.pre.beta1/spec/presenters/hyrax/file_set_presenter_spec.rb

**Comment by eporter23** [comment]
@wulman16 looks good! I also observed that the extended technical metadata displays on new works created after the deployment, so I'm glad we got this in before migrations are underway.
