### ISSUE TITLE
Implement thumbnail generation fix

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#617]
Following the investigation ticket:

Thumbnails on local machines look fine, but curate-test and prod instances do not generate thumbs successfully.

- [x] update ImageMagick version on curate-test (seems to resolve issue)
- [x] update on curate prod

**Comment by mprefer** [comment]
Downloaded ImageMagick-7.0.8-66.x86_64.rpm and ImageMagick-libs-7.0.8-66.x86_64.rpm from the ImageMagick site and installed on curate-test.

**Comment by mprefer** [comment]
Downloaded ImageMagick-7.0.8-66.x86_64.rpm and ImageMagick-libs-7.0.8-66.x86_64.rpm from the ImageMagick site and installed on curate.

convert -version
Version: ImageMagick 7.0.8-66 Q16 x86_64 2019-09-21 https://imagemagick.org

**Comment by mprefer** [comment]
I'll look at the Ansible script to see if ImageMagick is installed from the yum repo and propose downloading the most current RPMs from the ImageMagick site.
