### ISSUE TITLE
Investigate Cantaloupe performance for high-res images

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#618]
If we continue to serve out high res TIF files, investigate ways to increase load time (can take 5-20 seconds to load an image in the viewer)

**Comment by eporter23** [comment]
The Medical Artifacts collection is also full of very high res images. https://curate-test.library.emory.edu/concern/curate_generic_works/cor-7375tb2rd1?locale=en

If you click on the share icon in the viewer toolbar, then click on the IIIF icon, you can get the IIIF manifest data for any object:

![Screen Shot 2019-10-08 at 12.04.17 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/898a1b62-6067-42c7-be4d-5069c3183245)

**Comment by mprefer** [comment]
Added this item to <Curate_root>/shared/.env.production:
IIIF_SERVER_URL=http://iiif-cor-test.library.emory.edu/cantaloupe

**Comment by mprefer** [comment]
Code from hyrax.rb initializer that checks the ENV variable for IIIF_SERVER_URL:

  # Enable IIIF image service. This is required to use the
  # IIIF viewer enabled show page
  #
  # If you have run the riiif generator, an embedded riiif service
  # will be used to deliver images via IIIF. If you have not, you will
  # need to configure the following other configuration values to work
  # with your image server:
  #
  #   * iiif_image_url_builder
  #   * iiif_info_url_builder
  #   * iiif_image_compliance_level_uri
  #   * iiif_image_size_default
  #
  # Default is false
  config.iiif_image_server = true

  # If we have an external IIIF server, use it for image requests; else, use riiif
  config.iiif_image_url_builder = lambda do |file_id, base_url, size|
    if ENV['IIIF_SERVER_URL'].present?
      iiif_url = ENV['IIIF_SERVER_URL'] + file_id.gsub('/', '%2F') + "/full/" + size + "/0/default.jpg"
      Rails.logger.debug "event: iiif_image_request: #{iiif_url}"
      iiif_url
    else
      Riiif::Engine.routes.url_helpers.image_url(file_id, host: base_url, size: size)
    end
  end

  # If we have an external IIIF server, use it for info.json; else, use riiif
  config.iiif_info_url_builder = lambda do |file_id, base_url|
    if ENV['IIIF_SERVER_URL'].present?
      ENV['IIIF_SERVER_URL'] + file_id.gsub('/', '%2F')
    else
      uri = Riiif::Engine.routes.url_helpers.info_url(file_id, host: base_url)
      uri.sub(%r{/info\.json\Z}, '')
    end
  end

**Comment by mprefer** [comment]
When using the provided URLs earlier in this ticket, Riiif is used for image rendering. However, drilling down via the UI to display an image, system is attempting to use Cantaloupe.
So I'm going to move this to in progress.

**Comment by tmiles2** [comment]
@mprefer Could you provide some details as to why the issue is back in the blocked column?

**Comment by mprefer** [comment]
Seems useless to even attempt to evaluate Cantaloupe performances until Cantaloupe is functioning properly

**Comment by eporter23** [comment]
removing pre-migrate label because our schedule requires that we move forward with data loads

**Comment by eporter23** [comment]
Moving into 0.5 release because we don't know how long this may take to complete relative to other 0.4 items

**Comment by eporter23** [comment]
As of 12/12, Cantaloupe is re-enabled on curate-test. Images in curate-test are taking an extremely long time to load (minutes, not seconds). I've been trying to load a Langmuir image for 5 minutes as I write this comment, and it is still a black screen in the Viewer.

**Comment by SolomonHD** [comment]
There's been substantial upgrades to cantaloupe, I've modified the playbook to include a new role which downloads ImageMagick and other processors, also the cantaloupe configuration has been updated to use these processors. Performance is much more consistent now, I still feel it's a little slow to get the image itself, may need to research best caching strategy or  change how the delegate script works

**Comment by eporter23** [comment]
@mprefer @SolomonHD when we next pick this up, can we look into some of the caching options? https://cantaloupe-project.github.io/manual/4.1/caching.html

**Comment by tmiles2** [comment]
@mprefer Can we get this closed out with your findings this morning?

**Comment by mprefer** [comment]
Ran numerous 'wget's with captured IIIF URLs directly to the Cantaloupe server across a VPN connection from my local system. All the wget file downloads were less than 1 second duration.
Using the UI to display the same images in the Universal Viewer were much slower.
I'm wondering if UV has any settings that can be tweaked that affect it's performance?
