### ISSUE TITLE
Request AWS Backup functionality for aws@emory account

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#621]
We need AWS Backup for snapshot and restore functionality of EFS mounts, this will be necessary for restoring thumbnails and derivatives to a certain point.

- [x] Initiate security review for AWS Backup
- [x] Reach out to security team for ETA on approval

**Comment by SolomonHD** [comment]
I've opened a ticket requesting this functionality be added to our aws@emory account.

[Link](https://emory.service-now.com/nav_to.do?uri=%2Fsc_task.do%3Fsys_id%3D450118541b94c890a8441f4ead4bcba5%26sysparm_record_target%3Dtask%26sysparm_record_row%3D2%26sysparm_record_rows%3D106%26sysparm_record_list%3Dopened_by%253Djavascript%253Ags.getUserID%2528%2529%255Esys_class_name%2521%253Dsc_request%255Esys_class_name%2521%253Dsc_req_item%255EORDERBYDESCsys_created_on)

**Comment by SolomonHD** [comment]
Here is the email I've recently received from Chris Dehner:

Solomon,

I don't think I need anything else at the moment.  AWS Backup is quite the spiders web as it connects with at least 5 different services.  It'll take Zach and me some time to identify risks, recommend rememdiations, and present it to the cloud working group for approval.  It'll take a little time as it has to pass through different levels of approval.

Regards,

Christopher M. Dehner, CISA
Senior Enterprise Information Security Risk & Compliance Specialist
Library and Information Technology Services: Enterprise Security
Emory University and Emory Healthcare
1784 N. Decatur Road NE, Suite 300
Atlanta, GA 30022
404-727-1431
cdehner@emory.edu

________________________________________
From: Hilliard, Solomon G. <solomon.hilliard@emory.edu>
Sent: Tuesday, October 8, 2019 11:22 AM
To: Dehner, Chris <christopher.michael.dehner@emory.edu>
Subject: Follow Up 
 
Hi Chris,
 
I’d like to follow up on adding AWS Backup to aws@emory. Is there any else you need from me?

**Comment by tmiles2** [comment]
Per Zach Cox: 
Currently the Backup service has been approved and is awaiting deployment for the next deployment window/cycle. Please stay tuned to the latest email updates from the AWS at Emory service team for the announcements!

**Comment by tmiles2** [comment]
Per Paul Petersen: 
We are planning to enable the AWS Backup service on Thursday, October 31st between 5-7pm.
