### ISSUE TITLE
Investigate ability to search by ID in Curate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#622]
Can we configure the Curate search to search by an item's NOID ID?

**Comment by rotated8** [comment]
How is the ID stored in Solr?
Can the ID field be added to Blacklight's search terms?

**Comment by eporter23** [comment]
@wulman16 this looks great. I've been testing against our NOID values and values in other_identifiers. For documentation and training purposes, can you tell me which fields have been included/added to the Curate search?

**Comment by wulman16** [comment]
@eporter23 I added only the NOID values to search, which will work for collections, filesets, and works.

**Comment by wulman16** [comment]
@eporter23 After looking into it further, it looks like essentially every metadata field is currently searchable. (In other words, the only reason we had to add NOID in the first place is that it's not stored as metadata.)

**Comment by eporter23** [comment]
@wulman16 @rotated8 does this mean every field that is configured as "stored_searchable" is searchable from the Curate searchbox?
