### ISSUE TITLE
Test backup and restoration process - test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#623]
- [ ] Copy one environment totally to another environment and replicating it
- [ ] Document the backup and restoration process on the WIKI 

As a first step, backup all components of -test

**Comment by eporter23** [comment]
Removing the pre-migrate label because we don't have time to complete this prior to migrations starting.

**Comment by tmiles2** [comment]
@SolomonHD Can I get an updated list of tasks to complete this work?

**Comment by SolomonHD** [comment]
I've begun the process on curate test. I've stopped httpd on curate test

Currently I've backed up:
- EFS mount via AWS Backup
- Curate database via ansible role
- Fedora database via ansible role
- Solr curate-collection via ansible role

Next step is backing up the s3 bucket itself, then I begin clearing out all items listed

**Comment by SolomonHD** [comment]
I successfully copied ~14000 objects from one S3 bucket to another last Friday. 

Two issues came up whilst I was experimenting with backup:

- S3 Batch Operations ansible role, it currently works on a basic level but it needs more fleshing out to be a truly automated role.

- Backing up Fedora may be more complicated than I thought, I tried dumping the mysql database of Fedora and importing it to another blank DB but it didn't work. There may be more steps to backing up an S3 backed Fedora, I will try to contact Michael Klein and see if he has any ideas about this.

**Comment by eporter23** [comment]
@SolomonHD @rotated8 @tmiles2 since we've been asked this week by the Lux team to stabilize the test environment for Lux testing and demos (instead of using -arch), and I'm trying to load more data in there, I am wondering if we should only focus on the backup portion of this ticket and not attempt a restore this week? We can regroup on how to approach the restoration steps in our sprint planning next week.

**Comment by eporter23** [comment]
For this sprint, we can close this ticket and create additional tickets to do further testing on a full restore.

**Comment by tmiles2** [comment]
@eporter23 Are there additional details we want to add to close out this ticket beyond the work that has moved to this ticket #1000?

**Comment by eporter23** [comment]
Thanks for the reminder @tmiles2. I also created #1007 to continue testing after #1000 is complete.

**Comment by eporter23** [comment]
Closing this (other tickets created to follow this work).
