### ISSUE TITLE
Cron job for fixity checking on a schedule

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#627]
This ticket should follow the software engineering ticket to create a rake task for fixity checking in bulk.

Create a cron job that kicks off the fixity check rake task

To be confirmed: how often this needs to run

**Comment by devanshu-m** [comment]
Investigation in #624

**Comment by eporter23** [comment]
May need to break this out; one for cron job (5/13) and one for rake task (8/13)

**Comment by devanshu-m** [comment]
Rake task: `RAILS_ENV=production rails curate:file_sets:fixity_check`

**Comment by rotated8** [comment]
Use bundler, so we're always using the gems from the Gemfile.lock: `RAILS_ENV=production bundle exec  rails curate:file_sets:fixity_check`

**Comment by tmiles2** [comment]
Cron job will run weekly; start the job on Friday nights
