### ISSUE TITLE
Log preservation events related to Characterization

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#631]
Characterization: in the characterization job: https://github.com/samvera/hyrax/blob/master/app/jobs/characterize_job.rb#L12

Characterization events:

Metadata extraction (files/FITS)
Format identification (files/FITS)
Validation (files/FITS)

**Comment by rotated8** [comment]
We will log this as one "event", since all these happen at the same time.

**Comment by rotated8** [comment]
Pseudocode is something like

```
Find work for this fileset
Create new preservation_event object
Fill it in
Attach it to the work and save it
```

**Comment by devanshu-m** [comment]
start before: https://github.com/samvera/hyrax/blob/i18n-3.0.0-beta1/app/jobs/characterize_job.rb#L12

end after: https://github.com/samvera/hyrax/blob/i18n-3.0.0-beta1/app/jobs/characterize_job.rb#L16

**Comment by eporter23** [comment]
@wulman16 more detailed example outputs for characterization related events here: https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#

**Comment by wulman16** [comment]
I'm revising my code to use the newly defined `create_preservation_event` method, which now takes in a hash: https://github.com/emory-libraries/dlp-curate/commit/b658061b5a054ae85938554bc30ae077f65f2575

**Comment by eporter23** [comment]
@wulman16 this looks good! I noted some hopefully minor revision requests in #737. I'll close this ticket to reflect the initial work being completed.
