### ISSUE TITLE
Log events related to File Attach Job

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#632]
When the File Attach Job occurs, log this event:

* Message digest calculation

File persisted: in the attach_file_to_work job: https://github.com/emory-libraries/dlp-curate/blob/master/app/jobs/attach_files_to_work_job.rb#L55

[Example outputs for message digest calculation](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#)

**Comment by devanshu-m** [comment]
Update: SE team will discuss where to log this event (on the file or fileset)

**Comment by devanshu-m** [comment]
Solutions to try:
1) Get parent (fileset) from file
2) Pass fileset.id

**Comment by devanshu-m** [comment]
Solution implemented:
* Getting file_set ID by slicing first 14 characters from object (file) ID
* Then, finding the file_set and passing that file_set to the create_preservation_event method along with event hash
