### ISSUE TITLE
Log events for Work Creation

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#635]
Work creation: after the create_work job is successful: https://github.com/samvera/hyrax/blob/master/app/jobs/create_work_job.rb#L21

Object Validation

**Comment by eporter23** [comment]
@devanshu-m I have not found any work-level events getting attached in Fedora for works I created since 11/5 when 0.4.24 was released. Has this one been deployed?

**Comment by devanshu-m** [comment]
@eporter23 It should be. Can you send me the link to the work?
