### ISSUE TITLE
Create Ansible role for backup and restoring solr

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#644]
- [x] Create Ansible role that exports Solr index data and configs from Zookeeper
- [x] Create compressed tarball of data and configs from Zookeeper and store in S3 bucket
- [x] Create Ansible role that can unarchive backup file and restore to Solr instance
- [ ] Complete testing in AWS 
- [x] Push to github

**Comment by tmiles2** [comment]
@mprefer Have you started this issue?

**Comment by tmiles2** [comment]
@mprefer Do you have an update on the progress of this work?

**Comment by mprefer** [comment]
Created bash scripts to extract index data from Solr and to post data to Solr.
Each is based on the host, port, and collection. Data is in CSV format.
Created ancillary utility scripts to perform various functions, but not critical the backup/restore process.
Created script to extract Solr configuration files from the Zookeeper "filesystem".
These need to be Ansiblized for automation purposes.

**Comment by mprefer** [comment]
Created Ansible scripts to perform the following tasks:
  1) Make certain cURL is installed for use in making REST API calls to Solr.
  2) Extract Solr index data in CSV format or via the REST API that backs up the binary index files. Both are 
  options and can both be utilized in a single backup.
  3) Compress a tarball of the all the files created in in step 2 and store in S3.
  4) Role to restore the backup files to local disk storage and restore to Solr, either with the CSV file or thru 
   the REST API of the binary index files.

Have tested with an on premise 2 node SolrCloud cluster. Testing in the Curate AWS environment to be performed.

This will be a subprocess of Solomon's full backup scenario.

**Comment by tmiles2** [comment]
Closing out this ticket and creating a new ticket for the remaining/outstanding work.
