### ISSUE TITLE
Create ansible role for s3 lifecycle tagging and delete by tag

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#646]
As part of the hyrax/fedora/solr backup and restore playbook that's being developed, we need an ansible role that will manage mass tagging and deleting objects from s3. Although there is an s3_lifecycle module I don't see the options needed for this role. Mostly likely this role will need to leverage the aws cli.

- [x] Create role that mass tags objects in s3
- [ ] The role should also delete objects in s3 that have or are lacking certain tags

**Comment by SolomonHD** [comment]
Update: I've created a role that will mass tag objects. It's at https://github.com/emory-libraries/emorylib_role_s3_batch_operations/branches

Right now the role will tag every object in a bucket. There is another batch operation for copying things from one bucket to another bucket (even in another region), which I believe will be useful but I'm having issues getting it to work.

The batch operation goes through but there is a very high failure rate of 96%.

**Comment by SolomonHD** [comment]
I'm also still working on the lifecycle role, this role will mass delete tagged objects in s3.

**Comment by SolomonHD** [comment]
The S3 error rate issue remains, Also we're running into what I believe is the same issue with mass ingest job into curate-test, it's giving us errors with 403 access denied there as well.

I've reached out to Cloud engineer Chris Riddle for help, he may be able to arrange a meeting with an AWS representative tomorrow.

**Comment by SolomonHD** [comment]
Update: S3 issues have been resolved, the roles lacked sufficient permissions to access object versions, increasing the permissions of the roles fixed the issue and we can now reliability use batch operations copy function.

**Comment by tmiles2** [comment]
@SolomonHD Can we get an update on this in ticket?
