### ISSUE TITLE
Populate Repository Manager group and add to all Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#655]
The [repository_manager](https://curate-test.library.emory.edu/roles/8/edit?locale=en) group is defined to provide Manager-level access to all collections in the repository.

- [x] Create all the [identified user accounts](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=1791455727&range=J:J) needed if they do not already exist in Curate (Doug Goans is missing; Doug should also be an Admin user)
- [x] Add the [specified users](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=1791455727&range=J:J) to the repository_manager group

**Comment by tmiles2** [comment]
@eporter23 Solomon will add Doug in the Admin file manually

**Comment by eporter23** [comment]
@SolomonHD @devanshu-m I still don't see Doug as a user in prod or test if I look in the UI. Can you all confirm?

**Comment by eporter23** [comment]
@devanshu-m The [Repository managers group](https://docs.google.com/spreadsheets/d/1vdercM6W3FZjHCjim0qyvPnlRo9tgbvY7XQ0SiDhx4o/edit#gid=1791455727&range=J:J) should include Alex Cooper, Cari Lovins, Doug Goans, Emily Porter. When I view it in the /roles UI I only see Kathryn Michaelis. Can you confirm what is in the yml file for this group?

**Comment by devanshu-m** [comment]
@eporter23 They have been added to the yml file. I guess @SolomonHD needs to rebuild servers for those changes to take place?

**Comment by SolomonHD** [comment]
I've manually added all the repository managers to the curates.
