### ISSUE TITLE
Collection metadata: change CSV de-duplicating to not use local_call_number

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#665]
Relates to work in #612. We need a reliable ID to de-duplicate collections against, but local_call_number is an optional field and formal/official call numbers have not been defined for some collections. Call number also displays to the public so we don't want to have fake info there.

Options:
* Add the de-duplication ID method DCE is adding for the importer tool for work-level metadata to Collection-level metadata - see #660
* Change the currently unused primary_repository_ID field to become other_identifiers as defined in work-level metadata

**Comment by wulman16** [comment]
We're implementing the first option, so each collection in the CSV will have a `deduplication_key` field.
