### ISSUE TITLE
Include Asian Artifacts, Medical Artifacts collections in CSV generation process

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#669]
Expands on work in ticket #612 to include the additional two collections. These were created manually in curate-test, but have the old NOID pattern. They do not yet exist in production.

[Asian Artifacts](https://curate-test.library.emory.edu/dashboard/collections/cor-1439zw3r2q?locale=en)

[Medical Artifacts](https://curate-test.library.emory.edu/dashboard/collections/cor-549g4f4qsm?locale=en)

Asian Artifacts participant roles
* Repository Manager
* Oxford Manager
* Oxford Depositor
* Oxford Viewer

Medical Artifacts participant roles
* Repository Manager
* Health Sciences Manager
* Health Sciences Depositor
* Health Sciences Viewer

**Comment by devanshu-m** [comment]
@eporter23 https://github.com/emory-libraries/dlp-curate/blob/master/config/collection_metadata/collections.csv

**Comment by eporter23** [comment]
@devanshu-m here's an [updated CSV:](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/curate-generate-tasks/collections.csv)

**Comment by devanshu-m** [comment]
Solution to implement:
* Overwrite existing csv for collections generations
* Make sure tests still pass and write additional tests if necessary
* Make sure duplication does not occur on production

**Comment by eporter23** [comment]
@devanshu-m closing this because we confirmed the work is complete, but please see #727 - the last rebuild of arch did not assign the group permissions to the collections.
