### ISSUE TITLE
Errors in Universal Viewer: images do not load

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#674]
When logged in as Admin and trying to view images in curate-test (from off campus, but connected by VPN) I am getting login errors in the Universal Viewer:

![Screen Shot 2019-10-11 at 2.35.47 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/0f57942e-1ac8-40ba-afee-7e24053cb164)

**Comment by wulman16** [comment]
I'm also seeing this error on curate-test, though I'm unable to reproduce it locally.

**Comment by eporter23** [comment]
Testing update: I was able to download the original TIF file in the UI, though the image still does not display in the viewer.

**Comment by tmiles2** [comment]
@mprefer do you have an update on this issue?

**Comment by mprefer** [comment]
S3 is returning a 404 (File not found) HTTP error. May need assistance in deciphering how Hyrax maps file names to internal names(?) when generating the URL for IIIF server.
Cantaloupe log entries can be found in Box at this URL:

https://emory.app.box.com/file/544367119341
