### ISSUE TITLE
Display Preferred Image on View Work Page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#681]
Further splits out the display of preferred image logic for the Universal Viewer and thumbnails on the View Work page.

- [x] Change manifest generation to use the preferred image from #942

See [mockup for View Work display](https://docs.google.com/drawings/d/1Hl01D-ITNFkDhdnlCNRRZrGCTYvrdzFCcASZ7Etg1rY/edit?usp=sharing)

See also:
Original ticket from DCE co-sprint: #411
FileSet work developed in #442

**Comment by eporter23** [comment]
This was closed but I haven't tested it yet, so I'm moving it back into Test. Has this work been deployed already?

**Comment by devanshu-m** [comment]
Yes, this should be deployed to all servers. @eporter23

**Comment by eporter23** [comment]
Unfortunately this doesn't appear to be working for me in arch, -test, or prod. For Langmuir images, I am still seeing the images with color bars (preservation master file) instead of the cropped image without color bars (intermediate file) which should be displaying in the UV.

**Comment by eporter23** [comment]
@alexBLR @devanshu-m can either of you send me a screenshot (or an ID for an ingested work) where this is working for you? When I look at Langmuir objects in our various environments I only see images with color bars in them in the UV.

**Comment by devanshu-m** [comment]
* Adds sha1 for the preferred_file in the image url so that UV can display the correct file. This new image url lives in the manifest.

**Comment by eporter23** [comment]
@devanshu-m now that the re-index of test has finished, I am seeing the preferred image on some works but not others - is this because some of the manifests are cached?
