### ISSUE TITLE
Run importer rake task for Yellowbacks 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#701]
Use [DCE's book importer rake task](https://wiki.service.emory.edu/pages/viewpage.action?pageId=161546595) to process:

- [ ] Determine if CSV needs to be split into batches

- [x] [Pull list CSV - LSDI items](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yellowbacks/yellowbacks_Curate_lsdi.csv)
- [x] [Pull list CSV - LSDI2 items](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yellowbacks/yellowbacks_lsdi2_Curate.csv)

- [x] [Alma records](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yellowbacks/alma-yellowbacks.xml)

- [x] Transfer the post-processed Yellowbacks CSV file(s) to https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/2019/processed/yellowbacks

Rake task syntax:
Run the rake task in the Kirtas mode. We can leave the repl parameter blank because we have re-transferred the Yellowback files. Example from DCE:

bundle exec rake curate:books csv=../cor-data-transfer/curate-ingests/2019/in_development/yellowbacks/yellowbacks_Curate_lsdi.csv xml=../cor-data-transfer/curate-ingests/2019/in_development/yellowbacks/alma-yellowbacks.xml repl="" map="kirtas"

**Comment by eporter23** [comment]
Note: we should confirm if DCE's documentation is still up to date because the book importer work is still being finalized.

**Comment by eporter23** [comment]
We need to add Troopers revenge to the Alma output

**Comment by devanshu-m** [comment]
This is currently blocked due to an error while running the rake task.

![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/2fe50d0c-5685-43a4-b81b-5352fc7189b1)

**Comment by eporter23** [comment]
@mark-dce since this is an xpath error, I assume it ties to the alma xml source. I wanted to confirm, does the pre-processor expect an exact 1:1 of alma records to works in the pull-list CSV? I'd recently split the Yellowbacks into two CSV files, but we're trying to use the same Alma xml file (which has _all_ the Yellowback records and is not split). Could this be causing the error that Devanshu noted above?

**Comment by devanshu-m** [comment]
The xml file is missing the `Alma MMSID` field which might be required here: https://github.com/emory-libraries/dlp-curate/blob/master/app/importers/yellowback_preprocessor.rb#L85

**Comment by devanshu-m** [comment]
Note: The `ALMA MMSID` field in the CSV might be the issue.

**Comment by mark-dce** [comment]
Yes, the preprocessor assumes that each item in the supplied csv will have a Valid MMSID that matches and entry in the supplied xml file.  If you think this is a situation that might re-occur, we can add some additional error logging; otherwise, correcting the input files to have a valid MMSID in the CSV that matches a corresponding record in the XML file should fix the problem.

**Comment by eporter23** [comment]
@mark-dce @devanshu-m the good news is - we discovered that the Alma ID value was getting undesirably auto-reformatted as a number with extra digits in the CSV file. We ran a small sample cleaning up those values and it ran just fine. I'll retrace through the CSV steps to see where this is happening.

**Comment by eporter23** [comment]
@devanshu-m I believe I have corrected the CSV files - refreshed versions are available at the links above

**Comment by mark-dce** [comment]
@eporter23 that's good to hear.  Let me know if it would still be helpful to have some additional error messaging to help identify if this every happens again in the future, or whether you think you'll be able to recognize this if it happens again without any additional coding.
