### ISSUE TITLE
Arch Fedora: Ldp::BadRequest: RDF Stream contains subject(s) not in the domain of this repository.

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#705]
When creating the default AdminSet in Arch, the task fails with the following error:

`Ldp::BadRequest: RDF Stream contains subject(s) (https://<arch-fedora-url>/fcrepo/rest/prod/ad/mi/n_/se/admin_set/default) not in the domain of this repository.`

Two search results turn up, the first is to a Fedora [development ticket](https://jira.duraspace.org/browse/FCREPO-2379), which seems unrelated, and the second to [an old email](https://groups.google.com/forum/#!topic/samvera-tech/1XE4lDv85HQ) to the Samvera tech listserv, which went unresolved.

The Fedora URL configured for curate on Arch is correct, pointing to the appropriate fedora instance, and the URL in the error corresponds to the correct instance, and appears well formed.

**Comment by rotated8** [comment]
This ticket will be resolved when you can run `RAILS_ENV=production bundle exec rails hyrax:default_admin_set:create` from the current release dir, and the command does not produce an error.

**Comment by SolomonHD** [comment]
I've seen this error before somewhere, I believe it's related to the s3 issues we've been having. I would have to search cloudwatch to confirm

**Comment by SolomonHD** [comment]
Issue was fixed by changing the FEDORA_URL environment variable from https:// to http://
The ELB is formatted correctly to route https to fedora-arch, something about hyrax isn't liking the https. I'll just leave it as http for now.
