### ISSUE TITLE
Test out AWS Backup Service Functionality

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#712]
AWS Backup will be enabled 10/31 at 7PM

- [x] Test out the EFS functionality of the service
- [x] Generate and mount a backup EFS volume on another EFS volume.

**Comment by SolomonHD** [comment]
AWS Backup service has been enabled on our aws@emory account

**Comment by tmiles2** [comment]
@SolomonHD What's the next steps to finish out the work, all the tasks are checked?
