### ISSUE TITLE
Test Fedora Compatibility with Versioning Enabled S3 Buckets

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#725]
Bess and I have discovered an bug when trying to import objects in an s3 versioning enabled bucket. The import job runs great the first time but throws 403 access denied errors when attempting to import the same objects again. Expected behavior is the the objects will be overwritten.

I suspect the issue is lack of sufficient permissions for the fedora users. It's possible that even with the right perms the fedora s3 adapter won't work properly with versioning enabled s3 buckets

- [x] Recreate curate-arch bucket with versioning disabled for testing
- [x] Submit tickets for the creation of another set of fedora users that have versioning related permissions
- [x] Test new fedora users against a versioning enabled bucket

**Comment by SolomonHD** [comment]
I've just submitted the tickets for the creation of the new fedora users.
Prod: INC03259098 
Test: INC03259104 
Arch: INC03259105

**Comment by SolomonHD** [comment]
We received our new set of fedora users and it appears to have resolved our 403 issue.

**Comment by tmiles2** [comment]
Pending follow up with Bess.
