### ISSUE TITLE
Add filename(s) to FileSet eventDetails

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#735]
For some events like Replication, there are multiple log entries attached to the FileSet. In other cases, the event is only happening on the Preservation Master File, but for posterity, it would be good to indicate that. It would be helpful for all FileSet-level events to show the filename for which the event is being logged.

This could be added to the event detail entry. Examples: 

Applicable events:
- [x] Virus Check
_Virus scan performed on Preservation Master file_
- [x] Replication or File Submission (if event is renamed)
_Filename.ext submitted for preservation storage_
- [x] Characterization
_Preservation Master file: Technical metadata extracted from file, format identified, and file validated_

**Comment by devanshu-m** [comment]
@eporter23 Virus checking, message digest calculation, and characterization only happen on the PMF for now. So, do we need filenames for them?
Also, for replication, I guess we need to discuss where the event actually happens.
This issue seems to be blocked/needs more information. Moving it to blocked for now.

**Comment by eporter23** [comment]
@devanshu-m I'll look at the eventDetails outputs for each of these. It could be that we add a generic "preservation master file" note, or it could also be something I handle through documentation and training.   I agree that we should discuss more about the Replication event in particular.

**Comment by eporter23** [comment]
@devanshu-m I added some eventDetail outputs. I decided not to add anything for Message Digest Calculation because that already has a lot of detail in it.

**Comment by devanshu-m** [comment]
@eporter23 
notes:
* Virus check will be completed with the virus-check event ticket (#731) since work for this event creation is currently blocked.
* Replication will be completed with the replication ticket (#736) since it requires revision related to where the event is created.

**Comment by eporter23** [comment]
Characterization looks great. I will test the other two in their respective tickets.
