### ISSUE TITLE
Test revision: Replication event log

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#736]
For the Replication event, please call the eventType simply "Replication" as noted in the [sample event outputs document](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.ybxs2aykd56b).

Current: 
ns010: eventType
Replication (FileSet created)

Requested:
ns010: eventType
Replication

Also, please see ticket #735 to add the individual filename to the Replication event so we know which event refers to which file in the Set, because multiple Replication events are being logged.

**Comment by eporter23** [comment]
@devanshu-m @rotated8 if we are not able to determine that a file has been persisted to S3, can we at least log an event for each file, including its filename, that indicates a file has been _submitted_ to Fedora? 

If so, perhaps we could re-label this event as "File Submission". If this seems like a better way to close out this ticket for now (true Replication is beyond the scope of v.1 anyway) I can produce an updated output sample.

**Comment by eporter23** [comment]
@devanshu-m  Here is an example of a [File Submission](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#) event if needed.

**Comment by devanshu-m** [comment]
@eporter23 screenshots in PR #781

**Comment by eporter23** [comment]
@devanshu-m looks good; I will close this for the completed work but please see #795 revision ticket to update the eventDetail text to match the revised event sample noted in the comments for this ticket, since this is no longer truly a replication event.
