### ISSUE TITLE
Ensure that ClamAV is working

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#741]
Currently the ansible scripts that build curate are installing ClamAV but we don't know if the service is working with hyrax or not

- [x] Check if curate is configured to use ClamAV
- [ ] Test to see if ClamAV will detect a virus signature (via false positive test)

**Comment by tmiles2** [comment]
@SolomonHD Is there an update on the progress of this, target completion date is tomorrow?

**Comment by SolomonHD** [comment]
Still haven't configured the new role yet; will experiment this afternoon

**Comment by SolomonHD** [comment]
Clamscan is enabled on curate-test

**Comment by SolomonHD** [comment]
Clamby is working on curate-arch. It let's non viruses through and detected the virus below. It may need some additional logic on what to do after a virus is detected.  

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/7f5a2160-e6b5-44f9-8e5e-cb82a6b11bb7)

**Comment by SolomonHD** [comment]
I believe my role in this ticket is over, ClamAV and freshclam are installed and ready to go on all curates. Devanshu and Collin as still working on virus detecting logic, transferring this ticket to them,
