### ISSUE TITLE
Proposed visibility label and text changes

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#751]
Emily - Do the following highlighted changes accurately reflect changes we should make to visibility labels?

| Current label | New Label | Text Description | 
|---|---|---|
| Public | Public | **_Public access with full resolution view & download_** |
| LowRes  | **_Public Low View_** | **_Public access with restricted resolution view-only_** | 
| Emory Network | **_Emory High Download_** | **_Emory users with full resolution view & download_** |
| Emory Low  |  **_Emory Low Download_** | **_Emory users with restricted resolution view & download_**  | 
| Rose High Resolution | **_Rose High View_**  | **_Rose Library reading room access only_**  | 
| Private | Private | **_Administrator and Owner access only_** |
| Embargo | Embargo | Set date for future release. |
| Lease | Lease | Set date for future reduced access. |

**BEFORE**
![image](https://user-images.githubusercontent.com/3064318/68713246-0874e080-0563-11ea-9ef1-a608ced4105c.png)

**AFTER**
![image](https://user-images.githubusercontent.com/3064318/68713856-576f4580-0564-11ea-9bc7-6dce0cd2d2e4.png)

**Comment by eporter23** [comment]
@mark-dce looks good!
