### ISSUE TITLE
Test revisions for work-level events (630, 635)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#767]
Validation - see [Event Testing Notes](https://docs.google.com/document/d/1VtVv33qBSVQFJOzr6YlieplOJD3N8WMvM-7NxtjVfZA/edit#heading=h.s57msgxj2u6a) and [Sample Events outputs](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.llukvaexhur)
- [x] Change eventType to be only "Validation"
- [x] Adjust eventDetails text to say "Submission package validated'

Metadata Extraction - see [Event Testing Notes](https://docs.google.com/document/d/1VtVv33qBSVQFJOzr6YlieplOJD3N8WMvM-7NxtjVfZA/edit#) and [Sample Events outputs](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.spblj8mdryl7) 
- [x] Original requirements were to indicate if metadata was extracted from an external source, such as by the bulk import process. If we cannot determine if the metadata was supplied by a bulk import process or by a form entry, we need to change the eventDetails output to be more generic, or we may need to omit this event for now and revisit it as an enhancement.

Policy Assignment - see [Event Testing Notes](https://docs.google.com/document/d/1VtVv33qBSVQFJOzr6YlieplOJD3N8WMvM-7NxtjVfZA/edit#heading=h.niiw1ia3ibge) and [Sample Events outputs](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.llukvaexhur) 
- [x] Record the specific Hyrax visibility setting assigned when the work was created in the eventDetails

**Comment by devanshu-m** [comment]
@eporter23 
notes:
* It might be difficult to figure out what created the work - ui or importer. Removing metadata extraction event.

**Comment by eporter23** [comment]
Policy assignment looks good (much more informative now). There is still one more minor change to address for the revised eventDetails text (removing the "Policy was assigned" part of the statement and only including the new text you have added). I'll write up another ticket but it is low priority.
