### ISSUE TITLE
Thumbnails do not generate for PDFs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#776]
For works whose primary and representative media is a PDF, thumbnails are not generated; we only see the default placeholder icon.

![Screen Shot 2019-11-19 at 12.30.24 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/16d37144-3dbd-493a-94d5-1d3b7e0bb0c2)

- [x] Install LibreOffice with GhostScript on Arch
- [x] Install on Prod
- [x] Install on Test

**Comment by eporter23** [comment]
Discussed in sprint planning: we need LibreOffice with GhostScript

**Comment by mprefer** [comment]
Installed 'LibreOffice' and 'ghostscript' yum packages from the 'base' yum repo on curate-arch & curate.

**Comment by mprefer** [comment]
I would assume this issue can be closed, yes?

**Comment by eporter23** [comment]
@mprefer I agree, closing now that we have them on all 3 environments.
