### ISSUE TITLE
Add Migration Team members to selected Manager-level groups

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#778]
Kyle Fenton and Simon O'Riordan currently have depositor-level permissions for multiple Collections, but need to be added to the following manager-level groups in order to perform QA testing (because they cannot see all the objects created by bulk-import):

- [x] Oxford Managers
- [x] Rose Managers
- [x] Health Sciences Managers

Additionally, we can remove the following users who no longer work at Emory:
- [x] Dorothy Waugh
- [x] Anita Vanucci

**Comment by devanshu-m** [comment]
Hi @eporter23, can you add the link to the CSV that had users UIDs?

**Comment by devanshu-m** [comment]
@SolomonHD ready to merge https://github.com/emory-libraries/cor-cm/pull/7

**Comment by SolomonHD** [comment]
This has been merged to cor-cm. Also I've rebuilt all the instances with this change so it should be working.

**Comment by SolomonHD** [comment]
@devanshu-m @eporter23 Are there any tests for this ticket or do I close?

**Comment by eporter23** [comment]
@SolomonHD @devanshu-m I've got a separate ticket to do any further testing with those users. I did check all the Curates and I see the user assignments updated as requested. Closing!
