### ISSUE TITLE
Fix Yellowback acceptance samples not matching expected naming conventions

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#785]
**ISSUE**
When running a test import, DCE discovered that 5 of the 27 sample Yellowbacks have unexpected prefixes in their filenames.  In the examples shown below, we would expect file to be named just `0001.tif`

```
./Yellowbacks/lsdi/diesel/lts_new/ocm10321058-1432/Output/ocm10321058-1432_0001.tif
./Yellowbacks/lsdi/diesel/lts_new/ocm04308068-1649/ocm04308068/Output/ocm04308068_0001.tif
./Yellowbacks/lsdi/diesel/lts_new/ocm04300958-1631/ocm04300958/Output/ocm04300958_001.tif
./Yellowbacks/lsdi/diesel/lts_new/ocn170931999-2532/ocn170931999/Output/_0001.tif
./Yellowbacks/lsdi/diesel/lts_new/ocm04300922-1630/ocm04300922/Output/ocm04300922_0001tif
```

See ticket #758 for addition background about file naming expectations.

**ACCEPTANCE**
Either
- [x] *PREFERRED* Update the file naming for the indicated volumes
OR
- [ ] Decide to remove those volumes from the acceptance sample

NOTE: renaming can be accomplished with a command like `rename 's/ocm\d+_//' *`

NOTE: this is a subset of work identified in #758

**Comment by mprefer** [comment]
Which environment are these in, PROD, TEST, or ARCH ?
Where in the filesystem are these "samples"?
Should ALL files meeting the error condition be renamed in the full Yellowback EFS file mount?

**Comment by SolomonHD** [comment]
@mprefer This is files on the "import_efs" mnt, which is reachable from prod, test or arch at /mnt/import_efs/Collections/Yellowbacks/...

**Comment by eporter23** [comment]
@mprefer @SolomonHD please note this is a subset of work identified in #758 which I was going to target for next sprint. We have a small QA sample identified that DCE wants to load on Monday, which is noted in this ticket. The other ticket identifies a larger set of filenames to adjust.

**Comment by mprefer** [comment]
The rename command on RHEL compatible distros does not accept regex expressions. Installed the yum package 'prename' which is a Perl script that does accept regex.

Moved the 5 files listed above. 2 of the files don't exist (lines 3 & 5 in above list)

**Comment by eporter23** [comment]
@mark-dce can you take a look?

**Comment by eporter23** [comment]
Closing this, noting that we will need to do larger tests on filenames and filepaths for all books; will open new tickets as needed to address.
