### ISSUE TITLE
Run preprocessor rake task on Emory University LIMB yearbooks

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#817]
Some of the Emory yearbooks were redigitized and use the LIMB output. Use [DCE's book importer rake task](https://wiki.service.emory.edu/pages/viewpage.action?pageId=161546595) to process:

- [ ] [Pull list CSV for Emory LIMB yearbooks](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/EU-Yearbooks-Curate-LIMB.csv)
- [ ] [Alma records for Yearbooks](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml)
 
Transfer the post-processed Emory LIMB Yearbooks CSV file to https://github.com/emory-libraries/cor-data-transfer/tree/master/curate-ingests/2019/processed/yearbooks

For this CSV, here is example syntax from DCE that should be applicable:

`bundle exec rake curate:books csv=../cor-data-transfer/curate-ingests/2019/in_development/yearbooks/EU-Yearbooks-Curate-LIMB.csv xml=../cor-data-transfer/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml repl="" map="limb"
`

**Comment by eporter23** [comment]
@devanshu-m here is another Yearbooks CSV that you can run the DCE rake task on, same process as #834

**Comment by bwatson78** [comment]
@eporter23 Please check file: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/yearbooks/EU-Yearbooks-Curate-LIMB-merged.csv

**Comment by bwatson78** [comment]
@eporter23 Second pass: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/yearbooks/EU-Yearbooks-Curate-LIMB-merged_second_pass.csv
