### ISSUE TITLE
Test-run of sample Preservation Workflow Metadata import from CSV

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#824]
Try a sample run of the rake task developed in #791. We will run this task after collections begin to be loaded.

The following [small sample CSV](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/langmuir/langmuir_batch_raketest-processed-working.csv) can be run in curate-test.

**Comment by eporter23** [comment]
Try testing a small sample from test. @devanshu-m notes that CSV needs to be uploaded to /config.

**Comment by eporter23** [comment]
@devanshu-m if you want to test your rake task, I linked a small sample that is already loaded in test.

**Comment by devanshu-m** [comment]
Notes:
Ran bulk-import rake task. Moving to test for @eporter23 to test sample works.

**Comment by eporter23** [comment]
@devanshu-m noted that the test file CSV headers needed to be fixed so that they consistently begin with workflow_ prefix (some are missing). This causes problems with import.
