### ISSUE TITLE
Review /Collections structure on file transfer EFS mount

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#833]
DCE has continued to identify file-related issues for books. In order to help troubleshoot filename and file path issues for the DCE book importer tool: 

- [ ] Grant eporter at least read access to the AWS /mnt/import_efs/Collections space
- [ ] Establish best practices for the directory structures within /Collections (ADR?)

Background info:
For Yearbooks and Yellowbacks, we supply the importer tool base file paths provided by Kyle. These are typically like
/lsdi2/ftp/050000084033
/lsdi/diesel/lts_new/ocm13015593-3048
/lsdi2/ocm04416480-2987

When files were transferred up to our AWS pre-ingest space, new folder levels were introduced which didn't exist in the original directory structure, causing files to not be found by the book importer which was working from the original relative paths noted in the spreadsheet.

New file paths in AWS:
**/Yearbooks/Oxford/**lsdi2/ftp/050000084033
**/Yearbooks/Emory/**lsdi/diesel/lts_new/ocm13015593-3048
**/Yellowbacks**/lsdi2/ocm04416480-2987

We should also consider DAMS-managed files, which all fall under a main root of 
//dmfiles (with a Library and collection hierarchy underneath) 

Decision - should we always retain the exact relative directory structure from the legacy source, or should we reorganize collections during file transfer?

* Retain original relative structure - harder to "scan" but requires no updates to CSV 
* Reorganize collections - requires confirmation with content specialists about which assets are in which collection folders and updating the file paths in the CSV

**Comment by rotated8** [comment]
I think this can avoid an ADR, only because I don't think it's an architecture change. We should document the best practices, though.

**Comment by eporter23** [comment]
Discussion outcome: as a best practice, we will copy all collections into the base /mnt/import_efs/Collections directory in AWS and not modify the legacy directory structure. File structures should typically begin as /mnt/import_efs/Collections/lsdi, /mnt/import_efs/Collections/lsdi2, /mnt/import_efs/Collections/dmfiles
