### ISSUE TITLE
Manual creation of second-copy of files in S3 region buckets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#838]
This ticket follows work in which we had to undo S3 versioning. We now need an interim step to create a second copy of our repository files.

Second copy S3 bucket should be in a different region than the first copy.

**Comment by eporter23** [comment]
@SolomonHD noted doing this first as a manual process and later as an automated process

**Comment by eporter23** [comment]
In release planning on 1/29/20 we discussed doing this after the data loads are completed

**Comment by eporter23** [comment]
@SolomonHD can we close this?

**Comment by SolomonHD** [comment]
Yes this copy has already happened.
