### ISSUE TITLE
Ensure Hyrax supports multi-part objects

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#84]
- [x] Test creating a work within a work
- [x] Test creating multiple filesets within a work
- [ ] Test adding multiple files within a fileset

**Comment by rotated8** [comment]
Can use the Hydra::PCDM `#members` relation (and other, similar methods) to set up and test this. Eventually we should have a feature test for this.

**Comment by tmiles2** [comment]
@alexBLR Did we close out this issue yesterday?
