### ISSUE TITLE
Book page thumbnails not generating properly

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#842]
This issue has reappeared after the wipe and restore of Curate test and prod. We had resolved this previously in ticket #617 (upgrading ImageMagick)

See screenshot below:
![Screen Shot 2019-12-11 at 12.26.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ebeb02e4-108c-497a-84e2-c7fc3a252311)

**Comment by rotated8** [comment]
@eporter23 Can you add a link to this object?

**Comment by eporter23** [comment]
@rotated8 https://curate-test.library.emory.edu/concern/curate_generic_works/986b2rbp0f-cor?locale=en is the work which I just started loading today 12/11/19. Here is [one example FileSet](https://curate-test.library.emory.edu/concern/parent/986b2rbp0f-cor/file_sets/5977sqv9sj-cor) (many look like this).

**Comment by SolomonHD** [comment]
This was due to an issue with a rebuild, I'm creating a new role that will properly handle ImageMagick and other image libraries

**Comment by SolomonHD** [comment]
I've created a new role with installs the later version of ImageMagick, it's baked into the hyrax playbook, this should not be an issue on future rebuilds.
