### ISSUE TITLE
Intermittent Test Failure: Admin setup

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#848]
Depending on when the following test runs in a randomized sequence, there may already be administrator users created.  The test checks for an absolute number of admins, but should probably be checking that the total number of admins changes by the expected number when the test is run (or you need to explicitly delete all admins before the test is run because other tests may create admins and not clean up after themselves)

  2) AdminSetup returns all admins
     Failure/Error: expect(w.admins.count).to eq 3
     
       expected: 3
            got: 4
     
       (compared using ==)
     # ./spec/lib/admin_setup_spec.rb:28:in `block (2 levels) in <top (required)>'

**Comment by eporter23** [comment]
Discussed with team 7/29/20: this is resolved.
