### ISSUE TITLE
Update Import preprocessor to handle books that start on page 0 instead of page 1

### ISSUE THREAD

**Issue by mark-dce** [emory-libraries/dlp-curate#851]
**STORY**
Some Emory yearbooks were digitized with the first image numbered starting at 0 instead of starting with image 1.  

**ACCEPTANCE**
- [ ] Update the preprocessor to accept a parameter indicating the starting image number
- [ ] Update the preprocessor rake task to accept the new parameter

**Comment by eporter23** [comment]
Closing this because we haven't had an opportunity to test it fully. I created another ticket to do so once we have identified all the zero based files in our book collections.
