### ISSUE TITLE
Preview CSV import: errors on supported fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#852]
Replicated in curate-test; curate-arch
Curate v0.5.1@2622d057c43f8d14fafbaae0a07943d098faa9be updated on 12 December 201

**Describe the bug**
When loading a CSV that has been either manually constructed or is a modified version of a rake-constructed CSV, the Preview CSV Import feature reports errors on fields that should be supported:
* deduplication_key
* abstract
* administrative_unit

HUNCH: the warning seems to occur on the first column header of the sheet. Book CSVs start with deduplication_key, and the import_template starts with abstract. This issue also seems related to how the CSV is encoded, when saving the CSV in Excel back to CSV.

**To Reproduce**
Try loading a [CSV saved as CSV with UTF-8 encoding](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/asian-artifacts/kobe-test-3.csv)
Try loading the [same CSV saved with no additional options](https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/asian-artifacts/kobe-test-3-plaincsv.csv)

**Expected behavior**
CSVs with UTF-8 encoding should be to be loaded, when generated using appropriate column headers and other required field validation is met - OR - we should clarify any encoding settings needed for CSVs.

**Screenshots**
Example where abstract is the first column order (CSV + UTF-8):
![Screen Shot 2019-12-13 at 12.01.26 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/730817ad-d607-451f-8cb9-f4a7a3b6e9d7)

Same data saved as CSV 
![Screen Shot 2019-12-13 at 12.11.05 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/3e06b43d-8738-49a6-a73e-fd9e9c368c28)

Moved administrative_unit to first column order - error reported on that field
![Screen Shot 2019-12-13 at 12.15.23 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ea3e8b9c-5dbb-4fd5-abe6-0dae99ccc465)

Strange characters in Langmuir rake processed output (imported as text into Excel)
![Screen Shot 2019-12-13 at 1.14.09 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c42d8844-0ff3-432b-885b-588ede549f11)

Langmuir rake processed output in Apple Numbers
![Screen Shot 2019-12-13 at 1.15.46 PM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b2d494dc-d1ae-413c-a236-8bef0db47eaf)

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser - Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mark-dce** [comment]
@eporter23 could you please post one or two of the modified files to box and link them here.  I'm concerned that Excel is adding hidden characters to the field names.  We've seen this in sample files modified in Excel before.

**Comment by eporter23** [comment]
Updated with links and some additional screenshots. I'll do some more testing after opening CSVs in OpenOffice or Apple Numbers to see if anything changes.

**Comment by eporter23** [comment]
@mark-dce I've switched to using OpenOffice when I need to modify any of the rake-processed CSVs. So far I have not encountered this error, so it does seem that Excel is the culprit. I'm not sure that there is a lot we can do about it, so Emory can factor this into its workflow. If you agree I will close this issue.

**Comment by mark-dce** [comment]
I like the OpenOffice solution.  Based on what you've found, we could also add code to look at the header fields and try to strip any non-printing characters at the beginning or end of the string before trying to match to the expected headers.

**Comment by mark-dce** [comment]
(sorry hit carriage return too soon) I don't think the extra development is worth the effort if you're willing to use OpenOffice -FWIW  I've been editing this type of CSV file using OpenOffice for over a year and have never seen this issue.

**Comment by eporter23** [comment]
I'm going to go ahead and close this, glad we confirmed what the issue was.
