### ISSUE TITLE
Preprocessor extensions for additional DAMS image collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#860]
Goal: expand the [Langmuir preprocessor](https://github.com/emory-libraries/dlp-curate/blob/0a50515828f401840decbff1977ce074e6e03538/app/importers/langmuir_preprocessor.rb) developed by DCE to support additional image collections' conventions. The Langmuir preprocessor expects certain patterns in its input file that do not always exist in other DAMS-managed collections.

For some DAMS-exported collections including the Kobe and Medical Artifacts collections, most of the Langmuir preprocessor functions will apply:

* The input file contains a list of all files and includes work-level metadata, and transforms them into work and fileset rows using a specified column as its deduplication key (Digital Object - Parent Identifier)
* Filenames will end with a part number (e.g. P001.tif) which sets the order of the filesets for display
* Work-level metadata is pulled from the first row of file-level entries (if duplicative metadata is entered for all files)

The following differences are noted which are not yet supported:
* There will always be preservation master files only. (Currently, the Langmuir preprocessor assumes there is always 1 master file and 1 intermediate file for each fileset it creates a row for).
* Filename strings do NOT include _ARCH, _PROD as is the case with Langmuir (_ARCH = master file; _PROD = intermediate file)
* FileSets should be labeled_ Image 1_, _Image 2_ etc using "Image" + their part number from the end of the filename. The Langmuir preprocessor already does this that if there are more than 2 image parts for a Work. Artifact objects always have at least one "part", and may have as many as 20 additional parts.

Note: these images were migrated without extending the preprocessor, but this required manual construction of the file manifest. We should plan for this development as soon as possible in order to handle additional collections queuing for ingest.

See also: [DAMS to Curate Metadata Mapping](https://docs.google.com/spreadsheets/d/1Mv78t-1HJNPFgBgN6eGt_sM0iumuBkFAFkRP7YhD1Dk/edit#gid=811514181)

**Example Files**

The Medical Artifacts and Asian Artifacts collections' ingest CSV were _manually_ reformatted using the original DAMS-exported CSV file. The examples below show the original spreadsheet and their eventual output. For small collections this manual process can suffice but ideally, this transformation could be automated by modifying the existing Langmuir preprocessor or by creating a new generic DAMS preprocessor.

Original DAMS export file:
https://emory.box.com/s/kd16420aq57jfyh4ev2meu4mpco2nebc

Manually transformed CSV for ingest:
https://emory.box.com/s/5e5r6t770fpngedqqdksh8k6ezqqgji1

**Comment by lovinscari** [comment]
Zo will let Cari know by COB today if completed today or move to next sprint. This was an add-on from additional sprint goal.

**Comment by eporter23** [comment]
Reviewed a test sample that Zo sent via slack. The output looks very good, with a few adjustments needed:

Metadata mappings:
need to map `Desc - Abstract` to Curate's `abstract`
need to map `other_identifiers` to Curate's `other_identifiers`

Fileset rows:
`fileset_label` for works with only 1 FileSet should be "Image 1" instead of "Front"

**Comment by eporter23** [comment]
Additional file for testing: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/asian-artifacts/Kobe-DAMS-Export.csv

**Comment by eporter23** [comment]
I'll go ahead and close this based on prior testing. Since it's a rake task, testing it in one environment vs. another should not be significant.
