### ISSUE TITLE
File permissions on single Kobe TIF (can't read)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#863]
When trying to run the importer on some Kobe files, I got an error in sidekiq noting that a specific file could not be read: OXKOBE_045_P0001.tif 

 I looked at the file in the EFS mount, and it shows

-rwxr-x--- 

whereas other files are -rw-r--r--

We need to reset the permissions on the file so it can be read for import.

**Comment by mprefer** [comment]
Changed perms on :
Collections/dmfiles/Libraries/Oxford_SpecColl/OX-MSS011/Output/OXKOBE_045_P0001.tif
to -rw-r--r--
