### ISSUE TITLE
Re-transfer Yellowbacks files

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#865]
Since we transferred these collections initially to our EFS mount, we've discovered a number of file management anomalies (files still needing to be renamed, incorrect content files, etc.). 

Kyle has continued to rename and correct file issues in our local environment, and at this point, it will be more efficient to re-transfer these files to AWS. 

Please retransfer the following using our prior method utilizing fixity checks:
- [x] [lsdi Yellowbacks](https://emory.box.com/s/t809h3dfyp1c9mlf11t687num9a5iaiu) (copy all files and directories noted in the Base Path column of the spreadsheet)
- [x] [lsdi2 Yellowbacks](https://emory.box.com/s/0kba1csro0658jhch8frybwp9wenzy8u) (copy all files and directories noted in the Base Path column of the spreadsheet)

Please copy the directories so that their EFS destination path is
- [x] /mnt/efs/Collections/lsdi/ (followed by the relative path in the spreadsheet)
- [x] /mnt/efs/Collections/lsdi2/ (followed by the relative path in the spreadsheet)
 
For now:
- [x] Retain the existing  /mnt/efs/Collections/Yellowbacks and  /mnt/efs/Collections/Yearbooks directories in AWS until migrations are done

Retransfer the appropriate files to /Collections preserving the original relative directory structure, which begins with either lsdi or lsdi2

**Comment by eporter23** [comment]
@mprefer @SolomonHD I'm queuing this up in case either of you have time to start this before the holidays. Please let me know if I can clarify any of this.

**Comment by mprefer** [comment]
All Yellowbacks transferred from local NFS storage to EFS storage @ AWS to the requested directories as specified above.

**Comment by eporter23** [comment]
Spot checked these and looks good. Thanks @mprefer
