### ISSUE TITLE
Poor quality book page thumbnails on Curate-test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#869]
While we had previously remediated this problem, book page thumbnails are poor quality again. We have achieved better quality on this in the past, has something changed? See also #842, #617

[Example object in test](https://curate-test.library.emory.edu/concern/curate_generic_works/7784j0zpcx-cor?locale=en)

![Screen Shot 2019-12-19 at 11.46.26 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/31fa3d0a-fc1b-4751-bb57-d168e2ada205)

![Screen Shot 2019-12-19 at 11.47.53 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/ffaf2d1c-b5b8-4942-95ac-207ccddb4261)

**Comment by SolomonHD** [comment]
@eporter23 I believe this issue was solved by the imagemagick roles I created, have you experienced this within the last couple of weeks?

**Comment by eporter23** [comment]
@SolomonHD I'm running a test load of books right now and will take a look as they get processed.

**Comment by eporter23** [comment]
Yellowbacks and Yearbooks loaded into test and arch during the week of 1/10/20 have thumbnails as expected. Closing this and will open a new issue if it recurs.
