### ISSUE TITLE
Enhance and test Ansible role for SOLR backup 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#876]
Continues work started in #644

**Comment by eporter23** [comment]
@SolomonHD @mprefer please revise and further break out as needed

**Comment by mightycollins** [comment]
Mark has it created via bash scripts.  Main task here is to anisbalize the script/process.

**Comment by mprefer** [comment]
Ansible scripts written and tested locally.
Need to test in AWS environment, so moving to "To Test" column.

**Comment by tmiles2** [comment]
@SolomonHD what's the latest progress on this ticket? I see that Mark last commented on moving it to test but now it's in progress column.

**Comment by tmiles2** [comment]
Remaining work - test in AWS

**Comment by SolomonHD** [comment]
Current ansible roles:
Restore: https://github.com/emory-libraries/emorylib_solr_cloud_restore_from_s3/tree/first-devel
Backup: https://github.com/emory-libraries/emorylib_solr_cloud_backup_to_s3/tree/first-devel

I'm putting some finishing touches on the Backup part.

**Comment by tmiles2** [comment]
@SolomonHD are the "finishing touches" based on the outcomes from testing that was done in AWS or is testing still pending?

**Comment by SolomonHD** [comment]
I've ran into some issues when testing with AWS. Mainly it's in how the backups were made, I was not using correct API call for that, I was using some sort of replication API instead of the correct "Collections" API. 

I'm going to put this back in progress until I have the issues ironed out.

**Comment by SolomonHD** [comment]
The two roles are in an acceptable state and I've tested them thoroughly, closing ticket.
