### ISSUE TITLE
Investigate increasing sidekicks workers to speed up bulk ingest rates

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#877]
We discussed increasing the number of sidekiq workers from 5 - 10. Solomon made some configuration changes but they do not appear to have increased in the application.

**Comment by SolomonHD** [comment]
The SIDEKIQ_WORKERS environment variable was not working; The value was being ignored and it was defaulting to the hard coded value of 5. I've merged a change to dlp-curate that will hard code a value of 25 for production environments.

**Comment by eporter23** [comment]
Closing based on current testing in all environments showing up to 25 threads

**Comment by SolomonHD** [comment]
There has been issues regarding Database Pool being insufficient with this increased Sidekiq threads, I've also increased the database pool to 50 to help alleviate this.
