### ISSUE TITLE
Pause fixity check cron job in production during data loads

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#878]
The cron job developed in #627 was running in production in December, but we want to temporarily pause it until we have loaded all the data so that Curate has more resources for ingest.

A new ticket will be written to re-enable the cron job in production once all data is loaded.

**Comment by mprefer** [comment]
Cron job for fixity check is currently disabled. Will enable when requested.

**Comment by eporter23** [comment]
I'll close this out @mprefer
