### ISSUE TITLE
Investigate file path errors on Yellowbacks samples

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#885]
See [notes here](https://docs.google.com/document/d/1UfLfDZc2D9US6McxEy2Ir0cqAI1R97keZ7pJapOfI6w/edit?folder=1wUMFAzkKMawUVFQAAuX7YKYsxMUE3BBX) - 5 out of 28 sample volumes reported files not found when trying to import.

When checking in the EFS mount, the directories exist, but the page-level content files (.tif, .pos, .txt) are missing. 

![Screen Shot 2020-01-09 at 9.47.54 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/b14a757b-6de2-499f-9af0-4d0ee674cb53)

This applies to the following identified so far:

Collections/lsdi/diesel/lts_new/ocm10321058-1432/Output
Collections/lsdi/diesel/lts_new/ocm04308068-1649/ocm04308068/Output
Collections/lsdi/diesel/lts_new/ocm04300958-1631/ocm04300958/Output
Collections/lsdi/diesel/lts_new/ocm04300922-1630/ocm04300922/Output
Collections/lsdi/diesel/lts_new/ocn170931999-2532/ocn170931999/Output

**Comment by eporter23** [comment]
To confirm - these may be the same volumes that we changed the directory structure on previously.

**Comment by mprefer** [comment]
Used 'rclone' to copy 2364 missing files out of a total 7787 total files based on the paths provided above.

**Comment by eporter23** [comment]
@mprefer I can now see all the files in the Output subdirectory - thanks! There may be a few more file transfer/copy requests coming related to file cleanup that Kyle has been doing but I'll write them up separately as I find them.
