### ISSUE TITLE
Fix re-ordering issue (implementation ticket for #856)

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#886]
This is the implementation ticket for #856
- [ ] Add param to permitted params list
- [ ] Improve test suite for curate_generic_work_form for permitted params and model attributes

**Comment by eporter23** [comment]
Closed after testing. File Manager ordering works on a very large book object. Tested both manual drag and drop and Sort Alphabetically options

**Comment by rotated8** [comment]
🎉
