### ISSUE TITLE
Investigate - Fixity checking options on second S3 bucket

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#887]
When we establish our second copy workflow, we will also need to perform fixity checking on the second copies.

Investigate if this is possible in S3 directly, because Curate/Fedora won't be able to access the second bucket.

Time boxed at 5 points

**Comment by eporter23** [comment]
Is this an option we can investigate? https://docs.aws.amazon.com/solutions/latest/serverless-fixity-for-digital-preservation-compliance/welcome.html

**Comment by SolomonHD** [comment]
I've read the link provided in the OG post and I've found the serverless example on github here:
https://github.com/awslabs/serverless-fixity-for-digital-preservation-compliance

I believe we'll be able to run this as a cloudformation stack. I am unsure about the cost, in the white paper they said the expected cost for a 10 TB bucket with 1000 objects, each 10 GB in size was $30.00 per month. Our situation is different we'll have about 60,000 objects around 100MB or less in size. What this means for the cost I don't know. We'll probably have to run it for a few days to estimate the cost.
