### ISSUE TITLE
Update Curate labels to reflect Lux labels

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#888]
The Lux UI implements some revised labels. We previously updated the labels in Curate, and should refresh these to match recent changes.

These labels should display consistently in the View Work, Edit and Create forms as well as the View, Edit, Create forms for Collections.

Current output:
curate_field_name (Display Label)
Example: holding_repository (Library)

Desired output:
Display Label (curate_field_name)
Example: Library (holding_repository)

[Full list of desired label outputs](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&range=AJ:AJ)

See the appropriate locale file.

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-18 at 11.46.19 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/c58d5aa4-ba94-4206-99f5-24e3194d70e5)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-18 at 11.48.15 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1de20394-c2b8-46aa-8944-ec75a103dded)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-18 at 11.49.48 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/841a905d-026a-41cd-bc5e-dda241b3bc98)

**Comment by bwatson78** [comment]
![Screen Shot 2020-06-18 at 11.53.23 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/b5c78e4d-a7ab-47a1-baab-1d043b712679)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1263

**Comment by eporter23** [comment]
Thanks - this should be ready for prod whenever appropriate.
