### ISSUE TITLE
Investigate creating further rake tasks to regenerate thumbs; re-characterize filesets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#894]
Look at modifying DCE's rake task to incorporate our preferred thumbnail logic

Add another rake task to re-characterize filesets

**Comment by eporter23** [comment]
@devanshu-m should we close this one as a duplicate?

**Comment by devanshu-m** [comment]
@eporter23 I guess?

**Comment by eporter23** [comment]
Closing as duplicate for a ticket already closed
