### ISSUE TITLE
Update RDS Certs

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#898]
Amazon post: https://aws.amazon.com/blogs/database/amazon-rds-customers-update-your-ssl-tls-certificates-by-february-5-2020/

**Comment by eporter23** [comment]
@rotated8 @SolomonHD @mprefer is this done already?

**Comment by rotated8** [comment]
The automatic service update should already have passed, right @SolomonHD? That would mean we're one env down, two to go.

**Comment by SolomonHD** [comment]
Yes the dev RDS has been updated, I'm going to schedule the prod RDS to update this Sunday.
