### ISSUE TITLE
SPIKE: Investigate Solr performance tuning

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#899]
- [ ] autocommit?
- [ ] autosoftcommit?
- [ ] time/docs/etc between commits?

**Comment by tmiles2** [comment]
@mprefer can I get an estimate on this ticket?

**Comment by mprefer** [comment]
Have read various sections of the official Solr reference guide and Solr High Performance, watched several YouTube videos on Solr performance, and various entries from a Google search.
Taken a default solrconfig.xml and copied pertinent performance entities to the Hyrax solrconfig.xml.
Most settings are set to the default values as a baseline, some obvious tweaks have been made.

Nothing has been implemented, as this was just an information gathering mission.
Will continue researching and testing during down periods.

**Comment by mprefer** [comment]
solrconfig.xml:

https://emory.box.com/s/uhiiyubbgdu66r1gjwyoi50yebf127to

**Comment by tmiles2** [comment]
@rotated8 Did you have a chance to review the link above?

**Comment by rotated8** [comment]
Not yet. I'll take a look this afternoon.
