### ISSUE TITLE
UV loads no files after changing representative media type

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#903]
For a work that contains both PDF and TIF versions of book pages, we may sometimes want to switch between offering the PDF or a deeper page-level zoom presentation of the object.

In Curate:
If a book is created with the representative media set to PDF, Hyrax displays only a thumbnail (no UV) when viewing the work.
If I edit the work and select a TIF page file, the UV appears, but loads no files.
https://curate-test.library.emory.edu/concern/curate_generic_works/4644qrfj7j-cor?locale=en

In Nurax, if I perform these steps, the View Work display changes successfully between showing a PDF thumbnail and the UV showing TIF files.
https://nurax-dev.curationexperts.com/concern/images/kk91fk644?locale=en

**Comment by tmiles2** [comment]
Linked to #910

**Comment by eporter23** [comment]
this appears to be resolved now with work done in #910
