### ISSUE TITLE
SPIKE: Investigate Virus-related ingest failure

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#907]
Emily's comments: After running Devanshu's rake task we saw that all but 2 of the "not fixed" issues in test were cause by false-positive virus scan failures which prevented files from being ingested. After running the rake task in prod we saw that all of the "not fixed" items also showed repeated virus scan events which prevented a fileset from getting fully created
- [ Rake task outcomes in test](https://docs.google.com/spreadsheets/d/17SWK-fVcwgAN4j7sOxzViPcEjLa-UuuJFtnyZLZSxP8/edit#gid=2006179059)
- [Rake task outcomes in prod](https://docs.google.com/spreadsheets/d/1UPIFJbxmBBwXz0Zfib2v4q6E22lp2ROWQFuCWrRe6PI/edit#gid=178429282)

**Comment by tmiles2** [comment]
First steps would be finding out if the files are in S3

**Comment by tmiles2** [comment]
@SolomonHD @mprefer you can click the link to test and prod outcomes to see the errors.

**Comment by SolomonHD** [comment]
@tmiles2 @rotated8  

The files in S3 are named after their MD5 hash, can you please add the MD5 hashes to the spreadsheets so we can lookup if they are in S3.

**Comment by mightycollins** [comment]
I haven't heard if ETD has these kinds of issues with their virus checking.  Can this be replicated in ETD?  Are the configurations between ETD and DLP different?

**Comment by rotated8** [comment]
@mightycollins ETD's configuration and operation is significantly different from Curate. Curate is ingesting thousands of files very quickly, which should never happen for ETDs.

**Comment by tmiles2** [comment]
Related #905

**Comment by eporter23** [comment]
@alexBLR these are the outcomes of the latest run of the fileset indexer rake task in Curate prod. The Filesets highlighted in yellow are still active and the first six show the repeated virus scan events which pass (but the preservation master file is not attached). https://docs.google.com/spreadsheets/d/1ybkJRJVdjrmSbHOvOppnkgHT0e8-TYF1xisof7cZHfU/edit#gid=178429282

**Comment by eporter23** [comment]
@alexBLR here are some additional examples of what seem to be false-positive viruses detected in the test environment: https://docs.google.com/spreadsheets/d/17SWK-fVcwgAN4j7sOxzViPcEjLa-UuuJFtnyZLZSxP8/edit#gid=2006179059

**Comment by rotated8** [comment]
Moving this to "To Merge", to reflect @alexBLR being done working on this, but it needing a final comment before it can close.

**Comment by devanshu-m** [comment]
Notes from investigation done by @alexBLR and I:

* You can create a file_set without a preservation_master_file through the console.
  * When attaching pmf and imf (for instance), the jobs might be running async (in parallel) so even if pmf does not attach, imf might, and the file_set should get created which might cause a file_set not having a pmf.
  * solution: checking for a pmf being present for a file_set before we start the file_set ingest process.

* Virus checking:
  * The scanner might be looking for the pmf in this directory: `opt/curate/uploaded/hyrax/uploaded_file/pmf` and finding the file correctly. So it runs the scanner on the file, but for some reason the file does not get attached to the file_set and hence not transferred to fedora/s3.

* Missing parent:
  * The file_set with issues in the prod csv all have a missing parent (orphaned) for some reason. However, the actual work does end up attaching the required file_sets after a few retries.
  * From @eporter23: The file_sets that have failed have tried attaching to the same work and failed after retries -- which are the file_sets in the csv.
