### ISSUE TITLE
SPIKE: Investigate File Download Performance 

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#909]

**Comment by eporter23** [comment]
@tmiles2 @rotated8 @devanshu-m can you all confirm details of this ticket?

**Comment by SolomonHD** [comment]
From our testing, the issue is the F5 load balancer(LB), normally curate goes through the F5 LB and fedora does not. We manipulated our /etc/hosts file to bypass the F5 for curate and all downloads we ran from curate worked fine, just like fedora.
