### ISSUE TITLE
Add admin MD to curate-generic worktype

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#91]
- [x] Add admin MD fields, following notes from #64
- [x] Test for presence of MD
- [x] Test number of accepted terms (multiple: true/false)
- [x] Test indexing in Solr (searchable, facetable, etc.)
- [x] Test for requirement (required, optional, etc.)

**Comment by eporter23** [comment]
@rotated8 @devanshu-m @alexBLR there is a field for System of Record ID (D20) in the Admin worksheet which is intended for future use such as importing metadata from another system such as Alma or ArchivesSpace. Should we add an additional related property to indicate which system the identifier refers to, or use some type of prefix in the value that is assigned to D20?

**Comment by rotated8** [comment]
After discussion, we're going to add prefixes as needed, and keep the info in one field.

**Comment by eporter23** [comment]
For example, "alma:990010478840302486" - alma is the system prefix and 990010478840302486 is the Alma MMSID (record ID)

**Comment by eporter23** [comment]
@rotated8 @alexBLR @devanshu-m checking on this - is this awaiting a PR to add the Admin metadata to the model? I won't be able to test until it's added.
