### ISSUE TITLE
IIIF Manifest caching

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#910]
- [x] Add logic to retrieve an already cached manifest
- [x] Add logic to create new manifest if not already created when work page is visited
- [x] Add rake task to create manifest and save them in cache

**Comment by SolomonHD** [comment]
@devanshu-m 
Where is this caching stored on the server? Is there an env variable that controls the path?

**Comment by devanshu-m** [comment]
@SolomonHD it is stored in the tmp folder in the application

**Comment by SolomonHD** [comment]
@devanshu-m Can we set an env var to control this? That will make for easy moving of cache data later. You can make the default the tmp folder if this env var is undefined.
