### ISSUE TITLE
SPIKE: Investigate monitoring and alerts on Events 

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/dlp-curate#912]
Related to #311 

- [ ] Schedule a meeting with DevOps (include Steve C.) to discuss the tools for monitoring alerts and what alerts are being monitored 

- [ ] Outline any gaps in monitoring and the solution to clear the gaps

**Comment by tmiles2** [comment]
@rotated8 Can you take the lead on this ticket, getting the meeting setup sometime this sprint (if possible). We could time box this at 3pts?

**Comment by mightycollins** [comment]
Will discuss with my team in tomorrow's team meeting.  Then we can have a broader discussion.

**Comment by mightycollins** [comment]
Here is what I have:
Story/Epic to establish monitoring of DLP infrastructure in a robust and agile method.  Using CloudWatch, we should be able to implement monitoring and event capturing in AWS.  These events dependent on severity should trigger notifications informing the team of potential issues.  Out of the box, CloudWatch captures information on most of the native services.  Establishing views of that information and triggers for notifications will be part of this Epic. I see this potentially being broken down into multiple steps.
1 - Event capturing for non-AWS native services.  
	Creation of custom monitoring scripts for middleware items like Fedora, SOLR, Cantaloupe, Apache, Certificates, etc.
	What is being montitored will be based on the middleware’s technology.  For example the Fedora, SOLR and Cantaloupe are all java based applications.  Things to monitor would include:
		Java daemon up or down
		Catalina.out log for “java out of heap” and other such errors
		ActiveMQ for queued messages (on premise Fedora get’s stuck)
2 - Adding monitoring scripts to playbooks for deployment with EC2 builds
3 - Implementing monitoring in ARCH
4 - Implement in Test
5 - Implement in Prod
6 - Once events are being captured and retained, we could start looking at triggering notifications on them.  This would include notifications for basic events like CPU usage as well as the custom events.  Alerts should reflect SLA and expected up time.
7 - Reporting or basic metric capturing with correlation to performance can be identified.

**Comment by tmiles2** [comment]
@rotated8 Can we get this closed out this morning?

**Comment by rotated8** [comment]
Tickets were created yesterday. Epic #956, then implementation tickets #950 to #957
