### ISSUE TITLE
Date digitized repeated in bulk imported books

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#915]
To confirm: are MARC date formats always consistent?

The Date Digitized field is repeated multiple times in book objects as shown below.

We also need to correct the date so that it is formatted in EDTF time, because it appears to cause problems with validation when you try to save the work using the work form. The field is not required, but it does show validation errors if you scroll down to view the field.

Ideas to resolve:

- [ ] Change Date Digitized mapping in the books pre-processor so that it pulls from the CSV and not Alma XML
- [ ] OR - temporarily remove Date Digitized in the books pre-processor and we add it manually to CSVs
- [x] OR - refine the logic in the pre-processor so that it only uses the first date, and trims that to a 4 digit year

![Screen Shot 2020-01-26 at 11.58.42 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/3b6df3a6-a489-4932-96a0-973e0eaa4f03)

**Comment by bwatson78** [comment]
@eporter23 Should a recurring process be written to check, across all documents, this field to see if it has redundant values, format the unique values into EDTF, persist the repetitive, unformatted values with the corrected values, and maybe reindex the object? 

Or, should we leave the Fedora object value as-is and just adjust how the solr indexing digests and formats the return field?

**Comment by bwatson78** [comment]
@eporter23 Can you also provide me an example object?

**Comment by eporter23** [comment]
@bwatson78 to your first question, Kathryn and I have been manually cleaning up the generated output in the CSVs prior to ingest and/or cleaning up the entries in the objects in Curate. So, there should not be a need to look for these on a recurring basis. So, the goal would be to adjust the output of this that comes out of the preprocessor scripts so we don't have to fix them manually. I'll look for a sample CSV that hasn't been fixed yet.

**Comment by eporter23** [comment]
Here's a small CSV generated by the preprocessor that contains the repeated entries in date_digitized: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/processed/yearbooks/Yearbooks-Oxf-1988-and-90.csv

Alma source XML file: https://github.com/emory-libraries/cor-data-transfer/blob/master/curate-ingests/2019/in_development/yearbooks/alma-yearbooks.xml 
See the 583, subfield c entries:
**<datafield ind1=" " ind2=" " tag="583">**
    <subfield code="a">digitized</subfield>
    **<subfield code="c">2010</subfield>**
    <subfield code="2">pda</subfield>
    <subfield code="5">GEU</subfield>
    <subfield code="x">public domain</subfield>
  </datafield>

**Comment by bwatson78** [comment]
@eporter23 My apologies. I was unaware (or forgot :-) ) that you had been cleaning up the entries. Would you say you have a preferred method from the 3 above, since I could do any of them?

**Comment by eporter23** [comment]
@bwatson78 of the three above, I'd prefer to the third option. I think at one point in a backlog refinement session some other ideas were floated about checking first to see if all the repeated dates were identical, and then only including unique ones, but those ideas weren't captured in the ticket while estimating. I think typically the dates _are_ identical for the most part. So, as a first pass, I think pulling the first date and then trimming it to YYYY would be good.

**Comment by eporter23** [comment]
Slightly more info: the MARC data format for 583 subfield c should reliably be formatted in a consistent pattern:

> $c - Time/date of action
> The date and time are recorded according to Representations of Dates and Times (ISO 8601). The date requires 8 numeric characters in the pattern yyyymmdd (4 for the year, 2 for the month, and 2 for the day). The time requires 8 numeric characters in the pattern hhmmss.f (2 for the hour, 2 for the minute, 2 for the second, and 2 for a decimal fraction of the second, including the decimal point). The 24-hour clock (00-23) is used.
> 583	0#$3plates$acondition reviewed$c20040915$lmutilated$2pda$5DLC
> 583	1#$awill microfilm$c2004$2pda$5ICU

Based on the above reference,

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-curate/pull/1381
No screenshots to provide.

**Comment by eporter23** [comment]
Tested by running the preprocessor again - good to go for prod.
