### ISSUE TITLE
Bulk imports fail because input CSV file cannot be found

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#916]
This problem started showing up on 1/24/20. The uploaded CSV file goes through the pre-check process, but then we start to see errors in Sidekiq. 

1) When trying to run imports, the import is slow to start and reports this error:

RuntimeError: Cannot find expected input file /opt/dlp-curate/releases/20200109213604/tmp/csv_uploads/langmuir_batch3-processed-B060-68.csv

2) This error then recurs while the batch is running, and it fails to complete.

This batch has failed to complete several times between 1/24 and 1/26.

**Comment by eporter23** [comment]
Notes from Solomon in Slack: 

o I notice that the csv uploads go to a local "release" folder of curate instead of a shared folder
10:46
Is that intended? Why aren't we using efs for that?
10:48
@emily I see the langmuir_batch3-processed-B060-68.csv file, but it's in a different release
10:48
/opt/dlp-curate/releases/20200116182450/tmp/csv_uploads/langmuir_batch3-processed-B060-68.csv
10:48
That's where the file is

solomonhd  10:51 AM
It's some sort of issue with deploys
10:51
It may be expecting the csv in a older deploy folder

solomonhd  10:58 AM
So the issue here is that csv_uploads and csv_uploads_cache are not linking to the share folder the way cache and sockets and pids all are (edited) So the app is getting confused about where stuff is
new messages

There's many places you could correct this but I think the easiest would be capistrano

11:02
append :linked_dirs, "log", "public/assets", "tmp/pids", "tmp/cache", "tmp/sockets", "config/emory/groups"
11:02
Just add tmp/csv_uploads and tmp/csv_uploads_cache to that line

**Comment by SolomonHD** [comment]
I'm going to create another branch in curate which links these folders properly.

**Comment by SolomonHD** [comment]
I've deployed a branch to curate-test which fixes the issue:
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/9a3c80d5-bf11-4b3e-a525-b17e50478a87)

**Comment by tmiles2** [comment]
- [ ] rebuild Arch 

- [ ] run small ingest 

- [ ] Deploy 

- [ ]  ingest again
