### ISSUE TITLE
Validate date metadata

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#92]
- [x] Identify date metadata from https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=514733824
- [x] Identify date formats from Solr
- [x] Implement date format validation on the curate-generic worktype
- [x] Test the format validation.
- [x] Test date storage in Solr

**Comment by eporter23** [comment]
Note: summary of data use cases here: https://wiki.service.emory.edu/pages/viewpage.action?pageId=119147632#Metadata/DataEntryFunctionalRequirements-DateEntries

Descriptive Dates:
* Date Created
* Date Issued/Published
* Conference Dates
* Data Collection (Start and End Dates)

Rights:
* Copyright Date
* Scheduled Rights Review Date

Admin:
* Date Digitized
