### ISSUE TITLE
Move Manifest Caching off EC2 Storage

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#923]
Currently, IIIF manifests are cached on EC2 storage, which will be destroyed when the EC2 is rebuilt. Instead, they should be cached in a permanent, non-release dependent, place.

Devops:
- [x] Where is this storage mounted?
- [x] Does the application have write access?

---

Software Engineering:
- [ ] Change the caching location to include the hostname of the server
- [ ] Change the caching location to the storage mount

**Comment by SolomonHD** [comment]
The efs mounts are different for each environment, e.g. Arch's is /mnt/arch_efs, prod's is /mnt/prod_efs.

The efs mounts are wide open and any user can write to them, the thumbnails are stored on efs.

I would suggest setting another environment variable for this or perhaps piggy-backing off an existing one.

**Comment by eporter23** [comment]
@SolomonHD @devanshu-m @rotated8 this is already done, right?
