### ISSUE TITLE
Temp DB_AUTH on prod (switch to shib)

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#93]
- [ ] set `DATABASE_AUTH` env variable as `false` on prod and in appropriate files
- [ ] modify admin setup to set default password only for dev and not on prod
- [ ] move admins from database to shib in `admins.yml` on prod

**Comment by eporter23** [comment]
Discussed with team 7/29/20: this work was implemented in other tickets which are closed.
