### ISSUE TITLE
Supply volume level PDFs, OCR data files to Lux users for download

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#936]
For digitized books, we ingest image files for each page, but also provide a PDF for the entire volume. Some volumes also provide an OCR data file for the whole volume. These files should be offered as downloadable files for Lux viewers.

In Hyrax, these additional files should be able to be selected in the _Rendering_ field, but this does not currently work in Curate.

![Screen Shot 2020-02-03 at 9.17.56 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/28b22d3d-2c15-4ee6-b4fd-7a3e53a851e4)

[Example showing PDF file available for download](http://wellcomelibrary.org/iiif/b18035723/manifest) in UV:

![Screen Shot 2020-02-03 at 9.27.10 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/347f4d97-1d70-44a2-bbf2-085066fd281e)

**Comment by tmiles2** [comment]
DLP- Lux/#271
