### ISSUE TITLE
Configure test server to use database authentication

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#94]
- [x] set `DATABASE_AUTH` env variable as `true` on test server
- [x] configure cap deploy to use `admins.yml` file under `config/emory` on test server instead of using the one that comes from github
- [x] specify admins in `admins.yml` file from ticket #36

**Comment by SolomonHD** [comment]
New branch add-admins-file has been created that links config/emory and also .env.production file has been changed on curate-test.

**Comment by tmiles2** [comment]
@SolomonHD @devanshu-m  What's the status on this issue?

**Comment by devanshu-m** [comment]
I guess this work was completed last week. But @SolomonHD might know better.
