### ISSUE TITLE
Use environment variable for IIIF Manifest Cache

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#948]
IIIF Manifest is something that @eporter23 wants to persist between ec2s, but currently it's a hard coded path to /tmp of the rails app. 

- [x] Replace the hard coded path with an environment variable called IIIF_MANIFEST_CACHE

**Comment by rotated8** [comment]
@SolomonHD I think you've mentioned the environment vars in Slack. Please add them to this ticket.

I think you mentioned there being more than one variable. Can you say why this is necessary?

**Comment by SolomonHD** [comment]
@rotated8 I'm not totally sure what you mean, I don't know much about manifest caching but I believe it's all in one file, so one env var that is a path to that file or directory should be sufficient.

**Comment by devanshu-m** [comment]
Notes:

* We are adding an env variable that will contain the path to the
directory where manifests get cached. Path example:
full/path/to/directory/

**Comment by SolomonHD** [comment]
IIIF_MANIFEST_CACHE has been added to all servers and to cor-cm

**Comment by devanshu-m** [comment]
Manifests are getting cached successfully. Closing this ticket.
