### ISSUE TITLE
Add documentation to cor-cm repo

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/dlp-curate#95]
General documentation for cor-cm ansible repo is needed
- [x] Create home page or wiki on base directory of repo
- [x] Create examples showing how to use scripts to build out servers

**Comment by rotated8** [comment]
@solo

**Comment by rotated8** [comment]
@SolomonHD This ticket is about a month old. Has it been completed?

**Comment by SolomonHD** [comment]
@rotated8  I'm starting on it today.

**Comment by SolomonHD** [comment]
This is blocked until dynamic inventory has be integrated into the main cor-cm repo

**Comment by tmiles2** [comment]
@SolomonHD is this work now unblocked?

**Comment by eporter23** [comment]
Still in progress 4/15
