### ISSUE TITLE
Solr Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#950]
Solr should have monitoring for:

- [x] Java low memory status (Low Heap)
- [x] Solr Cloud (jetty) up/down
- [x] Apache up/down
- [x] Zookeeper up/down
- [x] If a Solr cluster member is up/down, (potentially using Solr Cloud API)
- [x] EFS is mounted

---
- [ ] It should alert if one of the above conditions is met.

**Comment by libdgg** [comment]
UPDATE: Mark was busy trying to resolve non-DLP issues related to SSL Certificate Authority issues that affected multiple library applications. He can re-start work on this ticket as of 6/8/2020. The remaining work includes new areas (i.e. Cloudwatch) and Mark plans to reach out to Solomon with any questions he may run into. Right now the estimate is to complete by the end of this week (approx Friday 6/12/2020).

**Comment by tmiles2** [comment]
Blocked due to production issues with legacy apps

**Comment by SolomonHD** [comment]
Alerts will be moved to another ticket.
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/fe896a47-8002-4a6e-bcc9-df4e00caffd7)
