### ISSUE TITLE
Fedora Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#951]
Fedora should have monitoring for:

- [x] Java low memory status (Low Heap)
- [x] Tomcat up/down
- [x] Tomcat log errors via Java Service Wrapper
- [x] Apache up/down
- [ ] S3 access
---
- [ ] It should alert if one of the above conditions is met.

**Comment by SolomonHD** [comment]
Alerts will be moved to another ticket.
Need further research on a potential S3 access ticket, same as cantaloupe

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/ccd04676-7262-40dc-b7f1-7f5a9beb6943)
