### ISSUE TITLE
Cantaloupe Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#952]
Cantaloupe should have monitoring for:

- [x] Java low memory status (Low Heap)
- [x] Uptime (whether Cantaloupe is up or down.)
- [x] Apache up/down
- [x] Apache Threads

**Comment by SolomonHD** [comment]
Wrapper.conf logs should already be logged to cloudwatch, no need for a metric.  Removing Cantaloupe access as well until I can figure out a method to check for that. Alerts will be moved to another ticket.
