### ISSUE TITLE
Sidekiq Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#953]
Sidekiq should have monitoring for:

- [ ] Sidekiq daemon up/down
- [ ] One instance running
- [ ] Elasicache Redis up/down
---
- [ ] It should alert if one of the above conditions is met.

**Comment by SolomonHD** [comment]
Alerts are moving to another ticket, Also removing the Elasticache monitoring, 

It's an AWS service so already monitored, I may implement some sort of check_http check on it at a later date.

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/2006c277-7eca-4790-94db-5f65433a792f)
