### ISSUE TITLE
Application Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#954]
Apache should have monitoring for:

- [x] Uptime
- [x] Server Errors
- [x] EFS is mounted
---
- [ ] It should alert if one of the above conditions is met.

**Comment by mightycollins** [comment]
This story will be for the monitoring of the EC2s used for the application instances.  This includes Apache, passenger and Ruby on Rails processess.

**Comment by rotated8** [comment]
This applies to Curate and Lux EC2s. Apache process up or down, number of processes, and mod_passenger up or down

**Comment by SolomonHD** [comment]
Moving alerts to another ticket

**Comment by SolomonHD** [comment]
All application checks have been added to DLP_Metrics namespace
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/cae73f6b-de52-4821-9ba1-4366b11ff6f7)
