### ISSUE TITLE
AWS-Native Service Monitoring

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#955]
AWS-native services should have monitoring for:

- [x] Uptime
- [x] Appropriate usage statistics (CPU/Memory, etc.)
---
- [x] It should alert if one of the above conditions is met.

**Comment by eporter23** [comment]
@SolomonHD @mprefer is this ticket duplicative of the recent monitoring work? Can we close this?

**Comment by SolomonHD** [comment]
![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/cbb73b5d-8884-447f-a6f4-a8cae80028b0)

**Comment by SolomonHD** [comment]
I've added Elasticache specific metrics:

![image.png](https://images.zenhubusercontent.com/5c191329a896da5d83d69955/d76c6935-1e77-4e89-b8ac-f960b8816d6a)
