### ISSUE TITLE
Bug: Solr Reindexing Fails in Arch

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#963]
From @wulman16:

Running the Solr reindex rake task causes [Net::ReadTimeout Errors](https://app.honeybadger.io/projects/66999/faults/60510252)

The stacktrace suggests reading descendants from Fedora is the issue.
`[GEM_ROOT]/gems/active-fedora-11.5.4/lib/active_fedora/indexing/descendant_fetcher.rb:72`

Next step is to try reindexing a book alone on the console.

This ticket will be complete when the ReSolrizer job can complete successfully in -arch, -test, and prod.

**Comment by eporter23** [comment]
Example of a [very large book object in Curate-arch](https://curate-arch.library.emory.edu/concern/curate_generic_works/163stqjq41-cor?locale=en) - 506 pages

**Comment by tmiles2** [comment]
@rotated8 this ticket is blocking a ticket on the Lux board #273, how much work would it be to get this done so we can remove the blocker? 

@eporter23 FYI

**Comment by devanshu-m** [comment]
Notes:

* The rake task is trying to reach the immediate descendants for `rest/prod` in fedora (which has the hasParent field as the base_uri for fedora) but also looks at the child of that immediate descendant. For instance, it looks at the file_set (`rest/prod/broken_up_file_set_id/file_set_id`) but it also looks at the `files` child of the file_set (`rest/prod/file_set/files`). After this it won't go down any further. Same is the case with Hydra::AccessControls. It goes until the the grand-child level.
* The error originates when trying to create a graph (this graph is what I am assuming is the family tree): https://github.com/samvera/ldp/blob/master/lib/ldp/resource/rdf_source.rb#L29
https://github.com/samvera/ldp/blob/master/lib/ldp/resource/rdf_source.rb#L59
https://github.com/samvera/ldp/blob/master/lib/ldp/resource/rdf_source.rb#L72
* I am not sure why it times out. We have time out limit set to 2 hours as it says in the fedora config here: https://github.com/emory-libraries/dlp-curate/blob/master/config/fedora.yml#L16

**Comment by devanshu-m** [comment]
Notes:

* Currently, request to create a graph for descendants in fedora times
out. In this commit, we add request options when creating a Faraday
connection. This way we can specify timeout in seconds so that the
read request for graph finishes. This is added by default in ActiveFedora
12+ and this monkey patch can be removed once we upgrade AF. Refer:
samvera/active_fedora#1271
* This will solve the issue where ResolrizeJob used to timeout.
