### ISSUE TITLE
SPIKE: [Authenticate error on arch]

### ISSUE THREAD

**Issue by devanshu-m** [emory-libraries/dlp-curate#965]
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/e5775e44-a983-4667-a0bf-7531325a3fee)

Two reasons that could be causing this issue:
* Missing file in S3: Sometimes we get a 404 when we try to reach the image directly using the iiif url.
* Base URL for images in manifest is incorrect.

^ there could be more reasons for this happening. We need to find the root cause.

**Comment by tmiles2** [comment]
@rotated8  It looks like your PR fixed this issue can we close this or move it to test so Emily can address this?
![image.png](https://images.zenhubusercontent.com/5c07f3880498270a145dcf84/45a95716-9cfa-487c-9bea-0ccce2569cdf)

**Comment by rotated8** [comment]
@tmiles2 Yes, once we have signoff for what's in -test, I'm happy to move it to prod.
