### ISSUE TITLE
Rake Task for File Existance Verification

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#969]
Rake task should check if the SHAs for files in Fedora exist in S3.

**Comment by devanshu-m** [comment]
Notes:

* This rake task goes through all the files in all file_set in curate and checks their existence in their respective S3 bucket.
* There is a rake task that kicks off this job: `RAILS_ENV=*env* bundle exec rails curate:file_sets:check_binaries bucket=*s3-bucket-name* file_set=*optional*`
