### ISSUE TITLE
Display Persistent URL for Lux in Curate Works and Collections view pages

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#983]
When viewing Work pages and Collection pages in Curate, we should display the Persistent URL for these objects as it is generated for the Lux application.

This should display at the beginning of the metadata fields shown on the page.

View Work Page and View Collection Page

Display Label: **Persistent URL**
Display Value: **https://digital.library.emory.edu/purl/** + the cor ID for the object
Redirect notes: the base url https://digital.library.emory.edu/purl should redirect to https://digital.library.emory.edu/catalog in Lux. 

IIIF Manifest/More Information Pane

- Display as:
- **Persistent URL:**
- https://digital.library.emory.edu/purl/123xjdjd99kid-cor

**Comment by devanshu-m** [comment]
Notes for @eporter23 @nikdragovic :

* Adds the persistent url pattern to the work and collection show page in
curate and also adds this to the manfiest metadata to be displayed
in the more info tab in lux.
* Lux base_url is added through an env variable.

Curate work show page:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/97aeb5be-8c95-4439-8f2c-0a315fd08ca7)

Lux more info tab:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/e2cb304c-b0db-4cd7-85f9-b56feb2dc08d)

Curate collection show page:
![image.png](https://images.zenhubusercontent.com/5c12bc2dd3542818d52aa3a0/d21656e8-6ece-4f2b-b013-653be8631524)

**Comment by devanshu-m** [comment]
We need a new env variable set to the base url for lux servers. Env variable: ENV['LUX_BASE_URL']

Example: ENV['LUX_BASE_URL'] = "digital-test.library.emory.edu" for lux test and so on for arch and prod.

**Comment by eporter23** [comment]
@devanshu-m minor revision: can we display the fully qualified URL using **https://digital**.... etc and not just the domain?

**Comment by devanshu-m** [comment]
@eporter23 That will need to be added in the env variable. Example: ENV['LUX_BASE_URL'] = "**https://**digital-test.library.emory.edu"

@mprefer

**Comment by eporter23** [comment]
@devanshu-m @mprefer looks good! There is a problem with the HTML for the link however. Is this in the display side or the variable?

<a href="**http://https://**digital-test.library.emory.edu/purl/153jwstqk1-cor" target="_blank">https://digital-test.library.emory.edu/purl/153jwstqk1-cor</a>

**Comment by devanshu-m** [comment]
@eporter23 This is display side, can you put in a bug ticket?

**Comment by eporter23** [comment]
Closing and will create a new bug ticket.
