### ISSUE TITLE
Deliver "embed"/iframe sizes to UV/Lux

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#987]
The UV's "Share" button provides the ability to select from a set of preset sizes, which update an iframe tag that can be copied and pasted by users. We need to confirm that these options are supplied to the UV.

- [ ] Confirm any changes to the default presets from Lux requirements
- [ ] Confirm if these size options need to be provided in our manifest or another source (info.json)
- [ ] Deliver the size options via the appropriate data source

**Comment by devanshu-m** [comment]
Notes after talking to @nikdragovic :

* The embed/iframe size options are only for the iframe and do not change the dimensions of the images shown in UV for the work.
* I am still not sure if this can be controlled through curate or by the uv_config.

**Comment by eporter23** [comment]
I just confirmed with @nikdragovic and @devanshu-m that we will move forward with the default iframe sizes offered in the UV, so, no additional development will be needed at this time.
