### ISSUE TITLE
Can't create new work in UI in test - Ldp::Conflict in Hyrax::CurateGenericWorksController#create

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-curate#991]
I've tried three times this week to manually add a work in curate-test using the form in order to create a Parent Work for demo and testing. I keep running into the following error:

Note: I've been able to create a work manually in the form in -arch.

![Screen Shot 2020-02-14 at 9.12.24 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/be2ad0b4-a34e-49bd-8350-7ca586ee48a5)

**Comment by devanshu-m** [comment]
I ran this command: `[::Noid::Rails::Service.new.minter.mint, ::Noid::Rails::Service.new.minter.mint]` as suggested here: https://github.com/samvera/hyrax/issues/3128

This seems to have solved the issue for now. @eporter23 @rotated8

**Comment by devanshu-m** [comment]
More notes in #997
