### ISSUE TITLE
SPIKE: Dynamic Login Redirects

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-curate#996]
When a user logs in, they should be redirected to the page they were on, or attempting to access, when they started logging in. If no page can be identified, they should be redirected to the user dashboard.

This is time-boxed to one day.

It may be useful to start in our [callbacks controller](https://github.com/emory-libraries/dlp-curate/blob/master/app/controllers/omniauth_callbacks_controller.rb).

The edge case in Lux this fixes is when someone who is signed in to shibboleth, and has a Curate account, but is not signed into Curate tries to view a work in Lux, they request the work's manifest from Curate, and Curate appears to be signing the user in, which redirects to the dashboard page, rather than back to manifest page.

- [x] User is redirected to the previous page, when logging in.
- [x] User is redirected to the dashboard if a previous page is not available.

**Comment by devanshu-m** [comment]
Refer: https://github.com/emory-libraries/dlp-curate/pull/1004

**Comment by devanshu-m** [comment]
Notes:

* In the solution implemented, we redirect the user to omniauth request's origin
if it exists, else will redirect to the dashboard. Refer:
https://github.com/omniauth/omniauth/wiki/Saving-User-Location
